### ISSUE TITLE
[In-Person Event] Cloud Native Wasm Day North America

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#108]
# In-Person Event Submission

## Requirements

- Event Name: Cloud Native Wasm Day North America
- Link to the Event Website: https://events.linuxfoundation.org/cloud-native-wasm-day-north-america/
- Provide verification that you are an event organizer: I am on the CNCF events team and responsible for the D+I scholarships, activities, and applications such as this. The event lead is Elna Vogel 

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, disability, LGBTQIA+, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide an example of the Speaker Feedback page if available.
  - `A` https://www.cncf.io/wp-content/uploads/2021/06/WasmDay-2021_report-Final.pdf

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, disability, LGBTQIA+, etc.); and Details regarding a disability that we should be mindful of as we try to accommodate everyone for this event.
  - `Q` Provide an example of the Attendee Feedback page if available.
  - `A` https://www.cncf.io/wp-content/uploads/2021/06/WasmDay-2021_report-Final.pdf

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes the Code of Conduct will be posted on-site, on the virtual event platform, as well the event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/cloud-native-wasm-day-north-america/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` The scholarship program exists to support individuals who may not otherwise have the opportunity to attend in two categories: Diversity (in-person and virtual), Need-based (in-person and virtual).
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA+, women, persons of color, and/or persons with disabilities) who may not otherwise have the opportunity to attend. The need-based scholarship provides support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/cloud-native-wasm-day-north-america/attend/scholarships/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Due to local COVID-19 restrictions, we unfortunately cannot offer child care services at this event We can, however, provide a list of local childcare providers.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will be providing a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event and will be located onsite. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/cloud-native-wasm-day-north-america/attend/diversity-inclusion/

**Comment by spotz** [comment]
@Nebrethar All done and did it in the right section this time:)

**Comment by germonprez** [comment]
@Wendi-West thanks for the submission :)

Two questions on demographics

1) Is there a post-survey form that will be used to ask attendees/speakers about their inclusive experience at the event? 

2) With respect to the registration form, this is the same as my question from a different application. I see questions regarding 

- Race / Person of Color
- Disability
- Gender Identity

I don't see questions about sexual orientation as indicated in the description in this issue.

**Comment by Wendi-West** [comment]
@germonprez We don't currently have a post-survey form specifically regarding their inclusive experience. There are multiple surveys pre and post event about the event and experience overall. And we have a D+I Slack channel for discussions, questions and feedback. Additionally, when I saw the question about the feedback form on the application (it wasn't a question for the virtual events in May that I applied for) I asked our content team and they liked the idea and will be brining it up as something to possibly implement with future events. All speakers have direct contact with the content team and leader and reach out with questions, concerns and feedback. 

As for the registration form, you're correct. I made a mistake. The sexual orientation question used to be part of the registration questions, or was part of a template that we were working on having approved and it isn't incorporated in the general registration questions right now. I'm sorry for that mistake. However, the Diversity scholarship does ask that question.

Let me know if you have any other questions or concerns. Thanks!

**Comment by Nebrethar** [comment]
As for the KubeCon review, I am going to provide a preliminary badge here. @spotz @germonprez let me know if you need anything more for the review. Thank you!

@Wendi-West you are free anytime to accept the result or hold for further consideration. Thank you!

**Comment by germonprez** [comment]
Thanks @Wendi-West I really appreciate your thoughtful responses. Best of luck with the event!!

**Comment by Wendi-West** [comment]
You're all so delightful to work with. I greatly appreciate your time and dedication!!! And thank you for the badge, we accept!

**Comment by Nebrethar** [comment]
Great! You will see your badge in the main repository page shortly. Congratulations @Wendi-West on a Gold badge!
