### ISSUE TITLE
[In-Person Event] PromCon North America 2021

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#109]
# In-Person Event Submission

## Requirements

- Event Name: PromCon North America 2021
- Link to the Event Website: https://promcon.io/2021-losangeles/
- Provide verification that you are an event organizer: I am on the CNCF events team and responsible for the D+I scholarships, activities, and applications such as this. The event lead is Elna Vogel 

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, disability, LGBTQIA+, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide an example of the Speaker Feedback page if available.
  - `A` https://promcon.io/2021-losangeles/registration/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, disability, LGBTQIA+, etc.); and Details regarding a disability that we should be mindful of as we try to accommodate everyone for this event.
  - `Q` Provide an example of the Attendee Feedback page if available.
  - `A` https://promcon.io/2021-losangeles/registration/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes the Code of Conduct will be posted on-site, on the virtual event platform, as well the event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://promcon.io/2021-losangeles/diversity/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` The scholarship program exists to support individuals who may not otherwise have the opportunity to attend in two categories: Diversity (in-person and virtual), Need-based (in-person and virtual).
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA+, women, persons of color, and/or persons with disabilities) who may not otherwise have the opportunity to attend. The need-based scholarship provides support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://promcon.io/2021-losangeles/diversity/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Due to local COVID-19 restrictions, we unfortunately cannot offer child care services at this event We can, however, provide a list of local childcare providers.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will be providing a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event and will be located onsite. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by tetris4** [comment]
@Wendi-West thanks for applying! In the link provided for the registration page, I can't seem to find any statistics on speaker and attendees demographics. If I missed them, do let me know and I will update my evaluation.

**Comment by Nebrethar** [comment]
Pinging @Ruth-ikegah for review. Let me know if there's anything I can help with!

**Comment by Wendi-West** [comment]
@tetris4 They did not add the report in their website but it was posted on CNCF webpage:  https://www.cncf.io/reports/#annual-reports 

Here's the report for PromCon Online Europe 2020: https://www.cncf.io/wp-content/uploads/2021/06/promcon-2021-report-Final.pdf

**Comment by Ruth-ikegah** [comment]
> @tetris4
> 
> Here's the report for PromCon Online Europe 2020: https://www.cncf.io/wp-content/uploads/2021/06/promcon-2021-report-Final.pdf
> 
> PromCom did not Tadd the report directly on their website but it was posted on CNCF webpage: https://www.cncf.io/reports/#annual-reports

thanks for the link and thanks for applying again @Wendi-West ! I am done with my review @Nebrethar , sorry for the delay.

**Comment by Wendi-West** [comment]
Thank you everyone!!! Yes, @Nebrethar we accept the result and badge!!!

**Comment by Nebrethar** [comment]
Awesome! Thanks @Wendi-West for your application. I have added the event to the readme of this repository.
