### ISSUE TITLE
Feedback from a Mock Reviewer

### ISSUE THREAD

**Issue by germonprez** [badging/event-diversity-and-inclusion#11]
Hi @bistaastha and @Nebrethar 

Thanks for all of your work on this! Here are some preliminary comments: 

The applicant is the organizer of the event.
- I am not able to determine this from the information that is provided / requested 

For this: 
If any of the checks above are not met, or if the matter provided is insufficient, describe how.
Metric criteria (reference)
- Can you make the reference link open a new window/tab? 

I don't completely understand the first metric, second metric, third metric, and fourth metric sets. Could you provide more detail as I'm currently unsure how to check the appropriate box. 

The quantitative/qualitative headers when checking the metrics criteria are not clear. Why do you need these headings? I would suggest removing them.

**Comment by Nebrethar** [comment]
Thank you for the feedback @germonprez . We are taking these points into account for the next updates to /badging 😁 We will do our best to update this issue as we make changes

**Comment by xiaoya-Esther** [comment]
My feedback is mostly overlapped with @germonprez, 

> I am not able to determine whether the applicant is an organizer from the information that is provided/requested

- I think if it's obligatory that only an event organizer can apply for the badge, maybe proof should be requested in the applier PR template.


> - [ ] Ask applicant about the process if information is not openly available.

- I actually don't quite understand what this checkbox means, does the `applicant` here means applicant for the event or applicant for the badge?

- One little bug I found is the hyperlink in the very above of this PR conversation is not available, I think I know where it should have redirected but any invalid hyperlinks should be eliminated.

![image](https://user-images.githubusercontent.com/56542972/87801068-c59da200-c881-11ea-9294-eb09a0dde2b1.png)


- Using the names of "first set", "second set"...is not intuitive for me, I always forget the set level corresponds to which metrics, but the terms of local, regional, national, multinational that I found in Event Criteria is perfectly clear-sighted, I guess apply them in the checklist will be better(but this is just from my own perspective)

> In order to suggest the appropriate badge, fill out the field below with one of the Badge level names.

- Above is copied from the checklist, does this mean I need only to type down "pending" or "passing", or should I actually put the badge down there? When I was trying to perform the later, I found the badge link won't show normally in the checklist.

This just occurs to me that (if) a reviewer is not so familiar with markdown or HTML, he may be confused about how the badge should be issued, and a guideline for this is also necessary. But I guess the action of "issue the badge" is not yet detailed, so this is just an early thought.

But all in all, it's amazing to see how the workflow has grown, what you've done are really nice works.

**Comment by bistaastha** [comment]
Hi @germonprez and @xiaoya-Esther 
Thanks for your feedback, here are a bunch of thoughts this brought to my mind, and this is probably a good place as any to talk about them.

Starting with Matt G.'s feedback:

> * I am not able to determine this from the information that is provided / requested

I agree with @xiaoya-Esther on this one, although I am not entirely sure what proof an organizer can give (my guess right now that it would be the link to the Event website or their role within a particular organization associated with the Event). I hadn't considered this point while building the checklist, and this makes me wonder if Project Badging would also require similar proof.

> * Can you make the reference link open a new window/tab?

I looked around for this feature, and GitHub flavored Markdown doesn't support that :(

> The quantitative/qualitative headers when checking the metrics criteria are not clear. Why do you need these headings? I would suggest removing them.

They were initially there to logically divide the checklist, but I can see how it complicates things for reviewers.

---

Coming to @xiaoya-Esther's feedback:

> * I actually don't quite understand what this checkbox means, does the `applicant` here means applicant for the event or applicant for the badge?

Applicant in all cases refers to the person who opened the PR.

> * One little bug I found is the hyperlink in the very above of this PR conversation is not available, I think I know where it should have redirected but any invalid hyperlinks should be eliminated.

Thanks for noting this :) I'll fix it right away.

> * Using the names of "first set", "second set"...is not intuitive for me, I always forget the set level corresponds to which metrics, but the terms of local, regional, national, multinational that I found in Event Criteria is perfectly clear-sighted, I guess apply them in the checklist will be better(but this is just from my own perspective)

Noted, we'll try to either use geographical scales or new names for these sets (whichever is better) in the revised version.

> * Above is copied from the checklist, does this mean I need only to type down "pending" or "passing", or should I actually put the badge down there? When I was trying to perform the later, I found the badge link won't show normally in the checklist.

Here, you are supposed to put in only the name. I think adding an example would make this clearer.

> This just occurs to me that (if) a reviewer is not so familiar with markdown or HTML, he may be confused about how the badge should be issued, and a guideline for this is also necessary.

Suggesting the Badge to the actual Applicant commit is actually the work of someone who is in a moderator role, which would likely be someone who has more familiarity with GitHub.

----

Thanks again :)

**Comment by germonprez** [comment]
A few comments as a mock reviewer: 

The applicant is the organizer of the event.
- This seems hard to determine. Should you ask this of the applicant and have them provide a link to indicate that they are one of (perhaps many) event organizers. 

- It is not possible to determine this: Reviewing panel for selecting Event Speakers.

- I don't like how I can uncheck or check boxes that the applicant filled out.

**Comment by germonprez** [comment]
More comments. 

For something like Family Friendliness, there are several things that an event can provide. Is the bar simply to provide one (or more than one)?

**Comment by germonprez** [comment]
I actually think that you should remove the Reviewing panel for selecting Event Speakers question. I don't see it in the CHAOSS metric.

**Comment by Nebrethar** [comment]
Closing because this is old content, and now out-of-date
