### ISSUE TITLE
Discuss/consider adding accessibility options

### ISSUE THREAD

**Issue by mollydb** [badging/event-diversity-and-inclusion#122]
I think it would be great to add some questions about accessibility at events. Examples include:

* Live stream / remote access
* Captions
* Sign language interpreters
* Wheelchair access
* Quiet room

**Comment by ElizabethN** [comment]
@mollydb we have kind of a backlog on our DEI metrics (so many good ideas from the community!) but accessibility is extremely important to us. I've added it to our spreadsheet of metrics ideas and will work on this in the next few weeks. Thanks for your patience here and for keeping this issue open and top of mind for us!

**Comment by ElizabethN** [comment]
This is the metric that is up for public review prior to being released in April. This metric will be included in the next version of the DEI Badging initiative. We would love your input/feedback @mollydb or anyone with thoughts around accessibility: https://github.com/chaoss/wg-dei/blob/main/focus-areas/event-diversity/event-accessibility.md

Thank you! 🙏
