### ISSUE TITLE
"Diversity ticket allocation" is ambiguous

### ISSUE THREAD

**Issue by mollydb** [badging/event-diversity-and-inclusion#125]
I'm a little confused about what this means. Does this mean that there are tickets available at no-cost for "diversity" attendees or that there is a number of tickets, in general, allocated for "diversity" attendees?

For example, the event I'm reviewing right now has a Diversity Scholarship option for no-cost tickets, but not an option for "here is a pot of tickets set aside for people who fit some demographic requirements and who also want to pay for a ticket."

I guess the right question is: Are diversity tickets always free?

**Comment by Nebrethar** [comment]
Sorry this took me so long! I ran out of time (and gas) after finals week.

I added more metric info to each item in the application. I am going to work on the checklist side of things now.

**Comment by ElizabethN** [comment]
@Nebrethar sorry to ping you! Is this something we need to add to the next release? Or has it already been added?

**Comment by ElizabethN** [comment]
I believe this has been added into the checklist so I'm closing this issue. Thanks for bringing this up @mollydb!
