### ISSUE TITLE
[Virtual Event] PrestoCon 2021

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#126]
# Virtual Event Submission

## Requirements

- Event Name: PrestoCon
- Link to the Event Website: https://events.linuxfoundation.org/prestocon/ and https://events.linuxfoundation.org/prestocon/attend/diversity-inclusion/
- Provide verification that you are an event organizer: Rachel Braun - Meeting & Event Planner, Linux Foundation

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.) -No all-man programs or panels
  - `Q` Provide an example of the Speaker Feedback page if available.
  - `A` Not available at this time - speakers will receive a survey to submit feedback regarding the event, post-event. Question related to specifically to Diversity & Inclusion initiatives is: Diversity and Inclusion are vital to the future of our community and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.) -Geographic location
  - `Q` Provide an example of the Attendee Feedback page if available.
  - `A` Not available at this time - attendees will receive a survey to submit feedback regarding the event, post-event. Question related to specifically to Diversity & Inclusion initiatives is: Diversity and Inclusion are vital to the future of our community and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/prestocon/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` PrestoCon is a free event - there is no ticket fee. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A`  PrestoCon is a free event - there is no ticket fee. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`   PrestoCon is a free event - there is no ticket fee.

**Comment by Nebrethar** [comment]
@Gemarodri @Victorybrown Hello! I have removed Diversity Access Tickets from this application's checklists, just a heads up.

**Comment by Gemarodri** [comment]
Hi @RachelBraunLF, thanks for submitting the application!

Everything looks good, I only have a small question, where the participants would accept the code of conduct? During the registration?

**Comment by RachelBraunLF** [comment]
Hi @Gemarodri ! Yes, participants are required to accept the code of conduct during registration.

**Comment by Gemarodri** [comment]
Thanks @RachelBraunLF! 

@Nebrethar I'm done with the review

**Comment by Nebrethar** [comment]
Thanks @Gemarodri! That was quick!

Pinging for review @Victorybrown, let me know if you need anything 😄

**Comment by Victorybrown** [comment]
Hello, @Nebrethar I'll gt t it now.

**Comment by Victorybrown** [comment]
@Nebrethar I'm done with the review. @Gemarodri The speaker % is quite uneven, is this because of the submission or after the submission review. Are there more males applying for speaker roles than women?

**Comment by Nebrethar** [comment]
Great question @Victorybrown. I'm curious about the numbers too.

Nice work @RachelBraunLF, I am going to generate a badge for PrestoCon 2021. Let me know whether you accept the badge 🎉

**Comment by Gemarodri** [comment]
@Victorybrown, I'm assuming that that low % for women speakers is explained by a low amount of women applicants. I do not think this % will change after our review, but hopefully it will change for the next conference. 
 
Maybe @RachelBraunLF can have better insights about how why the % speakers in PrestoCon 2021 is uneven

**Comment by RachelBraunLF** [comment]
Hi @Nebrethar - thank you! I accept the badge. 

 @Gemarodri is correct in that the low percentage is explained by the low number of non-male applicants. Diversity and inclusion in speakers and attendees is incredibly important to the Presto Foundation, and we continue to encourage and seek out diverse speakers.

**Comment by Nebrethar** [comment]
@RachelBraunLF I will add PrestoCon 2021 to the list and you are free to use the badge. Keep doing what you are doing! 😁
