### ISSUE TITLE
[In-Person Event] FOSS Backstage

### ISSUE THREAD

**Issue by Max-Plain-Schwarz** [badging/event-diversity-and-inclusion#127]

**Comment by Max-Plain-Schwarz** [comment]
# In-Person Event Submission

## Requirements

- Event Name: FOSS Backstage
- Link to the Event Website: https://foss-backstage.de/
- Are you an organizer of this event? Yes

## Event Demographics

    - [x] This event commits to Event Diversity and Inclusion.
      - `Q` Detail the process for measuring Event Demographics.
      - `A` We have put together a demographic survey that we send to attendees when they purchase their tickets. We will also send the survey out after the event. You can see the survey here https://forms.gle/mPRK8u1C7c5vA9V36
      - `Q` Provide an example of an opt-out option on the Event registration page if available.
      - `A` See the survey here https://forms.gle/mPRK8u1C7c5vA9V36
      - `Q` Provide an example of a demographics text input box on the Event registration page if available.
      - `A` See the survey here https://forms.gle/mPRK8u1C7c5vA9V36

## Inclusive Experience at Event

  - [x] This event commits to the Code of Conduct at Event.
      - `Q` Provide an example of the Event Feedback page if available.
      - `A` You can find a cop of the feedback survey from 2021 here https://forms.gle/haLLZL23sLyrixdn7 - this will be updated for 2022 and sent out to attendees after the event.
      - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
      - `A` The results from the demographic survey were used to write the diversity report, which you can find here https://foss-backstage.de/diversity. The results of this survey have shown us areas that we intend to work in for future events such at the gender balance of speakers and attendees and the over representation of white participants and speakers. We intend to do this through outreach to user groups and promotion of our diversity tickets program.
      - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
      - `A` We will continue to to use the results from the survey to build better in person and online events.
      - `Q` Will the event platform be accessible to attendees and speakers after the event?
      - `A` All talks, online and offline, will be recorded and made available for everyone through our YouTube page here https://www.youtube.com/playlist?list=PLq-odUc2x7i-A0sOgr-5JJUs5wkgdiXuR

## Code of Conduct at Event

    - [x] This event commits to the Code of Conduct at Event.
      - `Q` Is the code of conduct posted at Event venue?
      - `A` Physical copies will be made abailable at the in person venue 
      - `Q` Provide a link for the Event Code of Conduct.
      - `A` https://foss-backstage.de/code-conduct

## Diversity Access Tickets

    - [x] This event commits to the Diversity Access Tickets.
      - `Q` How many different types of diversity access tickets are available for the event?
      - `A` Free diversity tickets are available for the onsite event and online only. Reduced price tickets are also available for pupils, students, trainees, people on social welfare, retirees and people with disabilities. 
      - `Q` What are the criteria for qualifying for a diversity access ticket?
      - `A` Diversity tickets that are available to people from underrepresented groups within the FOSS community. This includes, but is not limited to: women, people of colour, LGBTQIA people, disabled people, and people facing economic or social hardships. Tickets are freely available to anyone who feels they require one, we do not make any checks.
      - `Q` Provide a link to the page containing information about Diversity Access Tickets.
      - `A` https://foss-backstage.de/diversity 

## Family Friendliness

    - [x] This event commits to Family Friendliness.
      - `Q` Does the Event provide childcare facilities for its attendees and speakers?
      - `A` We are currently in talks with a childcare providers who are situated on the other side of the road to our venue. We hope to be able to promote their services to our attendees. 
      - `Q` What are the other ways that a family-friendly environment is being created in the Event?
      - `A` We hope that a hybrid event will allow more people to attend who cannot travel to Berlin due to childcare commitments.
      - `Q` Provide relevant links related to family friendliness at the Event.
      - `A`

**Comment by Nebrethar** [comment]
Hi @Max-Plain-Schwarz! Thanks for applying 😁 

You are the first person to apply through badging v3. Congratulations!

It looks like we ran into a formatting bug on the GitHub issue here. Do you mind if I fix the formatting on your application?

Also please feel free to mention any other errors you may have encountered in this process. Thanks!

**Comment by djmitche** [comment]
I'm sorry this has taken me a bit to get to -- I should have a chance this weekend!

**Comment by djmitche** [comment]
Looking good!  I didn't see information about accessibility in the website or the answers above, so I've left those un-checked.  Given more information, or if I've missed something, I'll be happy to revisit.

It also seems like the family-friendliness is still a work-in-progress, so I've left those un-checked as well.  Perhaps @Nebrethar can indicate whether the hybrid format is sufficient for family friendliness.

**Comment by djmitche** [comment]
(sorry, I missed the "Comment" button!)

**Comment by Nebrethar** [comment]
I will review and provide my feedback in a couple of hours 😁 Sorry it took me so long!

**Comment by Nebrethar** [comment]
The event will be accessible in the hybrid format, and you are in talks about getting it on-site. That's a tough one. Rather than let it help or hurt, I believe it's fair to take it out.

Reviewing team let me know if you object, but I will take it out for now.

@bistaastha @djmitche Let me know when your reviews are finished 😁

**Comment by bistaastha** [comment]
Hi @Nebrethar! I am done with my review.

**Comment by djmitche** [comment]
This is what remains for me:

> I didn't see information about accessibility in the website or the answers above, so I've left those un-checked. Given more information, or if I've missed something, I'll be happy to revisit.

**Comment by Nebrethar** [comment]
Thanks, @bistaastha @djmitche for your reviews and feedback!

I am going to generate a DEI badge, @Max-Plain-Schwarz, for FOSS Backstage 😁 Let me know if you would like to discuss further or if you accept the badge.

**Comment by djmitche** [comment]
Can we close this up?

**Comment by Nebrethar** [comment]
> Can we close this up?

Thank you for reaching out. I sent an email to the event team

**Comment by ElizabethN** [comment]
@Max-Plain-Schwarz :wave: Hi! Just checking to make sure you were ok with this badge. We'd love to issue it officially and close this issue for you. What do you think?

**Comment by ElizabethN** [comment]
@Max-Plain-Schwarz feel free to use the badge above. We can certainly re-open this issue if you'd like to discuss this more, but great job!
