### ISSUE TITLE
[In-Person Event] Cephalocon 2022

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#130]
# In-Person Event Submission

## Requirements

- Event Name: Cephalocon 2022
- Link to the Event Website: https://events.linuxfoundation.org/cephalocon/
- Are you an organizer of this event? Yes, Rachel Braun - Senior Event Planner, Linux Foundation

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete.   Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Specify dietary needs (if any.) Do you identify as a person of color? What gender do you identify with? How old are you? 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic-related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you. 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` Not available. 

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the Cephalocon ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` The virtual event platform for Cephalocon 2022 is to be determined, though a virtual registration option is available to all. Details will be provided on the platform soon. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/cephalocon/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Cephalocon offers one type of diversity access ticket - travel funding. Cephalocon utilizes a scholarship program to provide diversity access tickets to support individuals who may not otherwise have the opportunity to attend. If an applicant receives a travel funding scholarship, the scholarship includes a Coach airfare ticket, accommodation for the dates of the event plus one night prior to the event start date, ground transportation to/from the airport.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Cephalocon places an emphasis on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status. If an individual works for a company that has the ability to fund travel, we ask that they not apply to save scholarship funds for those who need it.   We ask applicants to provide a few key pieces of information on their application including their Company or Organization, whether they can receive funds from their organization, a brief description of the ways they are involved in technology and/or open source communities, and why they want to attend the conference.   We also ask if they belong to an underrepresented and/or marginalized group. This field is not required and is optional to include. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/cephalocon/attend/scholarships/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Due to local COVID-19 restrictions, we are unfortunately unable to offer child care services at this event. We can, however, provide a list of local childcare providers.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will provide a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event and will be located onsite. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/cephalocon/attend/diversity-inclusion/#onsite-resources

**Comment by tetris4** [comment]
Hi everyone! @RachelBraunLF the only thing not clear to me was regarding "Accessibility Requests - Attendees are able to inquire if accomodations are available and make suggestions for future accomodations at events.". Is this available for the event?

@Nebrethar if not, then I've completed my review =)

**Comment by tetris4** [comment]
Neat, thanks @RachelBraunLF !

@Nebrethar this is something that could be improved, so applicants can supply information on the Accessibility Requests criterion.

**Comment by Nebrethar** [comment]
Thank you for your reviews @Dhruv-Sachdev1313 @tetris4 😁 You continue to impress with your speed and attention to detail.

@tetris4 That's a great catch!
@RachelBraunLF I understand if you can not update the application right away 😄 You have done a great job of understanding feedback and working with it, so I'm hoping we will see it on the next iteration of the event.

I am going to generate a badge now. I will need @RachelBraunLF feedback on whether you accept the badge. Anyone can say something if the conversation is not over!

**Comment by RachelBraunLF** [comment]
Thanks @Nebrethar - I accept the badge!

Related to editing the application, I'm happy to make the update with the current information related to Cephalocon, however am wondering if the application be updated to provide a spot for this question to be asked/answered? I don't see anywhere within the application where this should be added.

**Comment by Nebrethar** [comment]
@RachelBraunLF I am so sorry, I had misunderstood the point you made there!

You are 100% right. I will add that question to the application today.

**Comment by Nebrethar** [comment]
I have implemented a fix for the missing question. Sorry about that!

Questions Added:
> How can attendees learn more about accessibility at the event?

> Does the event platform allow attendees to suggest future accomodations for the event?
