### ISSUE TITLE
[In-Person Event] cdCon 2022

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#131]
# In-Person Event Submission

## Requirements

- Event Name: cdCon 2022
- Link to the Event Website: https://events.linuxfoundation.org/cdcon/
- Are you an organizer of this event? Yes, Rachel Braun - Senior Event Planner, Linux Foundation

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete.   Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Specify dietary needs (if any.) Do you identify as a person of color? What gender do you identify with? How old are you? 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic-related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you. 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` Not available. 

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the Continuous Delivery Foundation ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Is the event team using feedback from previous event attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We include Onsite Resources available to our attendees on the event webpage: ​​https://events.linuxfoundation.org/cdcon/attend/diversity-inclusion/#onsite-resources - information includes, but is not limited to venue accessibility, wheelchair + medical equipment rental, communication stickers + interaction wristbands (specific to health + safety protocols and individual comfort levels). 
  - `Q` Does the event platform allow attendees to suggest future accommodations for the event?
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.  Additionally, during the registration process, we ask registrants if they have any accommodations requests we should be aware of. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` The virtual event platform for cdCon 2022 is TBD at this point, though information will be shared and made available to registrants soon. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/cdcon/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` cdCon offers one type of diversity access ticket - travel funding. cdCon utilizes a scholarship program to provide diversity access tickets to support individuals who may not otherwise have the opportunity to attend. If an applicant receives a travel funding scholarship, the scholarship includes a Coach airfare ticket, accommodation for the dates of the event plus one night prior to the event start date, ground transportation to/from the airport.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` cdCon places an emphasis on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status. If an individual works for a company that has the ability to fund travel, we ask that they not apply to save scholarship funds for those who need it.   We ask applicants to provide a few key pieces of information on their application including their Company or Organization, whether they can receive funds from their organization, a brief description of the ways they are involved in technology and/or open source communities, and why they want to attend the conference.   We also ask if they belong to an underrepresented and/or marginalized group. This field is not required and is optional to include. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/cdcon/attend/diversity-inclusion/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Due to local COVID-19 restrictions, we are unfortunately unable to offer child care services at this event. We can, however, provide a list of local childcare providers.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will provide a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event, and will be located onsite. 
  - `Q` Provide relevant links related to family-friendliness at the Event.
  - `A` https://events.linuxfoundation.org/cdcon/attend/diversity-inclusion/#onsite-resources

**Comment by Anita-ihuman** [comment]
@RachelBraunLF Thank you for applying for the CHAOSS DEI badging Initiative. 
My feedback:
-  I appreciate the effort put towards making the event website as detailed as expected. Particularly in the aspect of Diversity & Inclusion. 
- A little observation about the Demographics; it would be great to see the statistics from speaker and attendee demographics on the website in future events.

**Comment by djmitche** [comment]
This is fantastic, and it's clear you and the team have put a _lot_ of work into making this event accessible and developing speaker and attendee diversity!  I just have two questions:

 * You wrote "Not available" regarding a text input box for variable demographics.  I did not try to register to see what this meant, but my impression is that open-text entry is not available.  Is that correct?
 * The scholarships page doesn't mention how the allocation works.  I read this requirement as, at least, indicating to the applicant how they will learn if their attendance has been funded.  I assume there's a followup email, but that's not mentioned in the page, nor is an expect-to-hear-by date.

**Comment by RachelBraunLF** [comment]
Thank you @Anita-ihuman for your feedback! 

@djmitche - yes, the text input box for variable demographics is not available for this event. 
Regarding scholarships, the allocation will be decided upon by a review committee (members will be peer-reviewers and members of the CDF community.) There will be a specific budget line item to fund scholarship recipients. 

On the scholarship page, there is a funding application deadline, along with a date when all applicants will be notified by: 
A standard in-person ticket for cdCon 2022 will be included. 

"For questions, please contact travelfund@linuxfoundation.org.

Travel Funding Application Deadline: April 8, 2022 | All Applicants Notified By: April 15, 2022"

Please let me know if you have any other questions.
Thank you!

**Comment by djmitche** [comment]
> Travel Funding Application Deadline: April 8, 2022 | All Applicants Notified By: April 15, 2022"

Oh, how did I miss that?!

**Comment by RachelBraunLF** [comment]
@djmitche No worries!
Are there any outstanding questions you need me to answer?

**Comment by djmitche** [comment]
Nope -- I left "Text Input" un-selected since it's not the case.  I don't recall how to wrap up this review, though..

**Comment by djmitche** [comment]
@badging-bot help

**Comment by Nebrethar** [comment]
Thank you @RachelBraunLF @Anita-ihuman @djmitche !

I will hand this review off to @ElizabethN as I am on a break right now 😁 She can help get it closed up.

**Comment by djmitche** [comment]
@Nebrethar how should we finish this up?

**Comment by Nebrethar** [comment]
I can go ahead and close this up, actually. @RachelBraunLF, nice work! I will generate a badge level for you now :) Please let me know whether you accept the badge or want to continue the review 😁

**Comment by Nebrethar** [comment]
> @Nebrethar how should we finish this up?

Thanks for pinging me here @djmitche. Generally, the application is finished by a maintainer, primarily so you don't have to worry about it as a reviewer 😝 

I'll be sending out a message to all badging contributors soon, but a heads up: @ElizabethN is receiving the leadership of the Badging Initiative. I am going to be a reviewer (and some kind of advisor) as I finish up my schooling. 

BTW, I'm planning to stay involved for the years ahead 😁 and I read my emails!

**Comment by ElizabethN** [comment]
Thanks everyone! I think it's ok to close this, so I'm going to do that 😄 . If not, somebody give me a shout and we'll reopen.

**Comment by ElizabethN** [comment]
Haha, my bad. Sorry everyone! @RachelBraunLF are you ok with this badge, or would you like to continue the conversation?

**Comment by RachelBraunLF** [comment]
Hi @ElizabethN - I accept the badge! Thank you to all for the review!

**Comment by ElizabethN** [comment]
Awesome job @RachelBraunLF and team! Here are your badges! 🥳
