### ISSUE TITLE
[In-Person Event] Phony badge application for GSOC 2022 badging bot microtask by Ayush Tamra

### ISSUE THREAD

**Issue by ayushtamra** [badging/event-diversity-and-inclusion#135]
# In-Person Event Submission

## Requirements

- Event Name: Phony badge application for GSOC 2022 badging bot microtask by Ayush Tamra
- Link to the Event Website: https://github.com/badging/event-diversity-and-inclusion/issues/134
- Are you an organizer of this event? Yes, Ayush Tamra - Chaotic!

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Asking them demographic related questions which are completely optional
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic related questions are completely optional
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` Not available

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` https://example.com/event-feedback-form
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` The feedback is taken from the attendees, speakers and volunteers and shared with the core team to improve the DEI experience
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes they do
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` https://example.com/DEI/resources
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` yes it does
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` yes it does

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://example.com/Code-of-conduct

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` one type- travel tickets which are fully funded
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Funding applicants who are from underrepresented groups, and the applicants who are interested in attending but attending the event is not financially feasible for them
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://example.com/Diversity-Access-Tickets 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We are planning to organize subevents that family memebers including kids can participate example: games, subevents which include some learning and fun!
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://example.com/event/family

**Comment by ayushtamra** [comment]
Hello @ElizabethN , thanks for asking
Actually I took reference from the past applications, and then made an application out from it, I think the past applications like [this](https://github.com/badging/event-diversity-and-inclusion/issues/136) are acting as a great reference for explaining how the whole process works and on what basis reviewers are providing the feedback for the application. So it appears that I don't want feedback for now on this application but I will definitely inform you if I need to learn something more from it.

**Comment by ayushtamra** [comment]
Also I have a idea/question that as the new applicants are without any clarity how they can basically fill the application, and how they will get a feedback on it, so can we just add a link for the past applications on the [DEI badging page](https://chaoss.community/diversity-and-inclusion-badging/), tso that they can basically see it as a reference and can apply after that, a graphic video explaining the initiative and the process would also be helpful in the future if we can try working on it.

**Comment by ElizabethN** [comment]
@ayushtamra I know we chatted about this on Slack but we will be making a few updates to that form, and we can include your idea in the next release. I think it's a great one!
