### ISSUE TITLE
[In-Person Event] OpenJS World 2022

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#136]
# In-Person Event Submission

## Requirements
- Event Name: OpenJS World 2022
- Link to the Event Website: https://events.linuxfoundation.org/openjs-world/
- Are you an organizer of this event? Yes, Rachel Braun - Senior Event Planner, Linux Foundation

## Event Demographics
- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite, and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete.   Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Specify dietary needs (if any.) Do you identify as a person of color? What gender do you identify with? How old are you? 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic-related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you. 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` There is not a text input box on the event registration page. 

## Inclusive Experience at Event
    
- [X ] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We include Onsite Resources available to our attendees on the event webpage: ​​https://events.linuxfoundation.org/openjs-world/attend/diversity-inclusion/ - information includes, but is not limited to venue accessibility, wheelchair + medical equipment rental, communication stickers + interaction wristbands (specific to health + safety protocols and individual comfort levels). 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.  Additionally, during the registration process, we ask registrants if they have any accommodations requests we should be aware of. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` The virtual event platform for OpenJS World 2022 is to be determined, though a virtual registration option is available to all. Keynotes and other event recordings will be made available on the OpenJS Foundation YouTube channel. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/openjs-world/attend/code-of-conduct/ 

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` OpenJS World has a scholarship fund which offers travel funding to provide diversity access tickets to support individuals who may not otherwise have the opportunity to attend. If an applicant receives a travel funding scholarship, the scholarship includes: Coach airfare ticket, accommodation for the dates of the event plus one night prior to the event start date, ground transportation to/from the airport.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` OpenJS World places an emphasis on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status. If an individual works for a company that has the ability to fund travel, we ask that they not apply to save scholarship funds for those who need it.   We ask applicants to provide a few key pieces of information on their application including their Company or Organization, whether they can receive funds from their organization, a brief description of the ways they are involved in technology and/or open source communities, and why they want to attend the conference.   We also ask if they belong to an underrepresented and/or marginalized group. This field is not required, and is optional to include. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/openjs-world/attend/scholarships/ 

## Family Friendliness

- [X ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Does the Event provide childcare facilities for its attendees and speakers? Childcare will be provided on-site free of charge for vaccinated children. Attendees can RSVP for childcare here. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will provide a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event, and will be located onsite. 
  - `Q` Provide relevant links related to family-friendliness at the Event.
  - `A` https://events.linuxfoundation.org/openjs-world/attend/diversity-inclusion/#onsite-resources

**Comment by germonprez** [comment]
Thanks for the application @RachelBraunLF and I hope you are doing well :) 

This is an amazing application. A few questions that I couldn't find from the website but that I'm suspecting you have answers for. For the following, could you provide just a little insight as to how you are addressing these. For example, is there a post-event survey for speaker/attendee inclusivity? 

For session availability, I'm guessing this is provided as it has been for all the other LF events I've attended. 

Speaker Inclusivity - The Event requests feedback from speakers regarding Diversity & Inclusion.
Attendee Inclusivity - The Event requests feedback from attendees regarding Diversity & Inclusion.
Session Accessibility - Event attendees are able to access the event platform after the event

Thanks!
Matt

**Comment by RachelBraunLF** [comment]
Hi @germonprez - thanks for the feedback! Looking forward to the review.

**Comment by KafayahL** [comment]
Hi, @RachelBraunLF everything looks good, the only thing I couldn't find was the text box to input variable demographics such as Gender, Race, or Ethnicity. It gives you options to choose from or not but no text input. 
Other than that, I"m done with my review. 
Thank you.
Kafayah

**Comment by RachelBraunLF** [comment]
Hi @KafayahL - many thanks for your review! To address your question: there is not a text input option for variable demographics, as noted in the application. However, demographic information is 100% optional and is not required to proceed with registration. If an attendee should not want to provide this information, they are able to bypass this section. 

Please let me know if you have any more questions. Thank you!

**Comment by ElizabethN** [comment]
@RachelBraunLF thanks for the response!

**Comment by ElizabethN** [comment]
@RachelBraunLF Is this badge ok with you? Would you like to discuss anything further?

**Comment by RachelBraunLF** [comment]
Thanks @ElizabethN - I accept the badge - thank you!!

**Comment by ElizabethN** [comment]
@RachelBraunLF thank you so much! Here are your badges - keep up the amazing work!
