### ISSUE TITLE
[In-Person Event] Hyperledger Global Forum 2022

### ISSUE THREAD

**Issue by celiastampslf** [badging/event-diversity-and-inclusion#137]
# In-Person Event Submission

## Requirements

- Event Name: Hyperledger Global Forum 2022
- Link to the Event Website: https://events.linuxfoundation.org/hyperledger-global-forum/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite, and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete.   Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Specify dietary needs (if any.) Do you identify as a person of color? What gender do you identify with? How old are you?   Voluntary speaker demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals.Voluntary information requested includes:  -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, disability, LGBTQ, etc.)
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you. 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` Not currently available.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` Example:We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A`  Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We include Onsite Resources available to our attendees on the event webpage: ​​https://events.linuxfoundation.org/hyperledger-global-forum/attend/diversity-inclusion/#onsite-resources - information includes, but is not limited to venue accessibility, wheelchair + medical equipment rental, communication stickers + interaction wristbands (specific to health + safety protocols and individual comfort levels). 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.  Additionally, during the registration process, we ask registrants if they have any accommodations requests we should be aware of. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Event session recordings will be made publicly available on the Hyperleder Foundation's YouTube channel post-event.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/hyperledger-global-forum/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Hyperledger Global Forum offers one type of diversity access ticket - travel funding. Hyperledger Global Forum utilizes a scholarship program to provide diversity access tickets to support individuals who may not otherwise have the opportunity to attend. If an applicant receives a travel funding scholarship, the scholarship includes: Coach airfare ticket, accommodation for the dates of the event plus one night prior to the event start date, ground transportation to/from the airport.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Hyperledger Global Forum places an emphasis on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status. If an individual works for a company that has the ability to fund travel, we ask that they not apply to save scholarship funds for those who need it.   We ask applicants to provide a few key pieces of information on their application including their Company or Organization, whether they can receive funds from their organization, a brief description of the ways they are involved in technology and/or open source communities, and why they want to attend the conference.   We also ask if they belong to an underrepresented and/or marginalized group. This field is not required, and is optional to include. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/hyperledger-global-forum/attend/scholarships/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, complimentary onsite child care will be provided.  Information is not yet posted on the event website, but will be available soon.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will provide a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event, and will be located onsite. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/hyperledger-global-forum/attend/diversity-inclusion/#onsite-resources

**Comment by ElizabethN** [comment]
Pinging @Dhruv-Sachdev1313 and @Gemarodri to make sure y'all saw this :blush: Thank you!

**Comment by Gemarodri** [comment]
Hi @celiastampslf! Thanks for the submission. 

I have some questions for you. I hope you can help me understanding how the event is planning to do the following:
- Will be the survey sent also to speakers? (Note that the answer says "_it will be send to all attendees_", but it doesn't say anything about speakers)
- Are event attendees able to access the event platform after the event? How?

Another question that I have is related to the Code of Conduct:
- Why participants are not enforced to accept the Code of Conduct? According to the web, "_participants **are expected** to behave in accordance with professional standards, with both this Code of Conduct as well as their respective employer’s policies governing appropriate workplace behavior and applicable laws_". But they are not force to accept. Do you anticipate any problem with this? 

Best regards, 
Gema

**Comment by celiastampslf** [comment]
Hi @Gemarodri,
Thanks for the questions and I'm happy to provide insight:

- Will be the survey sent also to speakers? (Note that the answer says "it will be send to all attendees", but it doesn't say anything about speakers)
- A: Yes, speakers will also receive the post-event survey as an attendee of the event.

- Are event attendees able to access the event platform after the event? How?
- A: This event is in-person (with keynotes being live streamed for free) and all session recordings will be publicly available on YouTube after the event.  There is not a separate virtual platform.

- Why participants are not enforced to accept the Code of Conduct?
- A: Good catch!  Acceptance of the event's Code of Conduct is required in the registration process via our Terms & Conditions.  Here is a copy of the T&C verbiage with regards to the CoC:
_LINUX FOUNDATION EVENT CODE OF CONDUCT
The Linux Foundation & Hyperledger Foundation are dedicated to providing a harassment-free experience for participants at all of our events. Linux Foundation & Hyperledger Foundation events are working conferences intended for professional networking and collaboration in the Linux community. They exist to encourage the open exchange of ideas and expression and require an environment that recognizes the inherent worth of every person and group. While at Linux Foundation & Hyperledger Foundation events or related ancillary or social events, any participants, including speakers, attendees, volunteers, sponsors, exhibitors, booth staff and anyone else, should not engage in harassment in any form.

The expanded [Event Code of Conduct](https://events.linuxfoundation.org/hyperledger-global-forum/attend/code-of-conduct/) contains full details and examples, which cover behavior expectations, unacceptable behavior and consequences, as well as incident reporting and response protocol._

**Comment by Gemarodri** [comment]
Hi @celiastampslf thank you for the information. I have updated my review according to your responses.

@ElizabethN, I'm done with this review.

Thanks!

**Comment by Dhruv-Sachdev1313** [comment]
Hi @ElizabethN, I have updated some checkboxes based on @celiastampslf answers. Could you please generate the result again? Sorry for being late!!

**Comment by ElizabethN** [comment]
@Dhruv-Sachdev1313 oh, it's totally my fault for jumping ahead! Whoops!

**Comment by celiastampslf** [comment]
@ElizabethN @Gemarodri @Dhruv-Sachdev1313 Thank you all for reviewing our event and for the quick turnaround!  If we add any diversity-focused elements leading up to the event, should I update the information here for a possible higher score?
Either way, we'll get the Gold badge up on our website shortly.  Thanks again!

**Comment by ElizabethN** [comment]
@celiastampslf Oh, I realized I didn't actually answer your question! Yes- feel free to update anything that changes, just tag me in the comment and we will re-do the application. :+1:
