### ISSUE TITLE
[In-Person Event] OpenInfra Summit

### ISSUE THREAD

**Issue by allisonprice** [badging/event-diversity-and-inclusion#139]
# In-Person Event Submission

## Requirements

- Event Name: OpenInfra Summit
- Link to the Event Website: https://openinfra.dev/summit/
- Are you an organizer of this event? Yes 

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` The registration process for the OpenInfra Summit is quite extensive, both in recruiting speakers and attendees. We include several questions to ensure that we understand the demographics of our attendees and speakers. 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` We include "prefer not to say" when asked about gender. 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` We include "let me tell you" when asked about gender. 

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` https://www.surveymonkey.com/r/DenverSummitSurvey2019
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, we actively engage with the DEI activities at the Summit, including the Diversity & Inclusion lunch we host at every event and collect feedback on how we can make the event more inclusive. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, once we gather the feedback, we debrief to identify themes around barriers to participate in the event due to DEI challenges. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We have accessibility information on the Summit FAQ and are open to any questions at summit@openinfra.dev
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Yes, attendees can email summit@openinfra.dev with any suggestions / feedback for future events. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` The event is in-person, but we make all session videos available for free after the event on YouTube, as well as a China specific platform for global accessibility

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` The code of conduct is linked from the maps that are distributed throughout the venue. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://openinfra.dev/legal/code-of-conduct

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We offer a student/government/nonprofit discount to accommodate for a diversity of income level. We also host a Travel Support Program to support Community members that don't have the means to pay for flights/hotels in order to attend the events. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` We have forms for attendees to fill out, and Community supported committees to make approvals. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` Travel Support: https://openinfrafoundation.formstack.com/forms/TSP_Berlin2022; Discounted Registration application: https://openinfrafoundation.formstack.com/forms/berlin2022_summit_discounted_registration 

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by ElizabethN** [comment]
@allisonprice thanks so much for submitting your event!

**Comment by germonprez** [comment]
Hi @allisonprice. Thanks for the submission. I'll get to this review in the next day!

**Comment by djmitche** [comment]
I wasn't able to find a link to the CoC from the summit website.  I looked on the home page, in the bottom navigation banner, and in the FAQ.  I see the link above in this issue and will review it from there, and I appreciate that it will be posted at the event itself, but it should also be visible for people considering registering so that they can know what kind of conduct to expect & is expected of them.

Still looking at the other items :)

**Comment by germonprez** [comment]
@djmitche -- you can find the CoC about 2/3rds of the way down the page: https://openinfra.dev/summit in the Inclusive. Diverse. Open section

**Comment by djmitche** [comment]
Ah, indeed!  I'm not sure how I missed that.  I'm also missing accessibility information in the FAQ?  I promise I hit ctrl-f "acces" :)

**Comment by djmitche** [comment]
@ElizabethN I can't find information about diversity access tickets in [the reviewer guide](https://github.com/badging/diversity-and-inclusion/blob/master/reviewer-guide.md), to evaluate both the Travel Support Program and the ticket discounts.  I apologize for my apparent inability to find things on the Internet today!

**Comment by ElizabethN** [comment]
@djmitche I think this is a recent-ish addition to the checklist. Mostly we are just looking for efforts by the event organizers to lower the barrier to attendance by providing some method by which they provide tickets, scholarships, or financial aid for underrepresented groups in tech. Does that help clarify?

**Comment by germonprez** [comment]
Hi @allisonprice I have a few questions that would be great to talk about: 

1) The diversity access tickets really seem to be travel support for key open source members who don't have financial support. Could these tickets be expanded to included a broader set of people with an interest in the summit? I ask because there are times where people are not really able to have key positions in an open source project due to DEI-related factors. If being a key contributor is essential for travel support, this may limit the program. 

2) Regarding accessibility, I really only see comments regarding COVID. The hope with this set of checks is that the conference demonstrates one or more different forms of accessibility for people attending the conference. For example, this could include information about wheelchair accessibility or visually impaired accessibility. Is there information like this that could be shared on the website? 

Thanks so much! 
Matt

**Comment by djmitche** [comment]
>  Does that help clarify?

Thanks, yes, and with that information I agree with @germonprez - this is a travel stipend, but not "diversity access tickets".  I was also unable to find any accessibility information.

**Comment by ElizabethN** [comment]
@allisonprice is this badge acceptable to you? Would you like to discuss things further or make any changes to your event? We are happy to revise the badge based on changes or information that was previously missing.  Thanks so much!

**Comment by allisonprice** [comment]
Hi @ElizabethN sorry for the delay in response as I have been out of office. 

Yes, this badge is great! I definitely welcome advice / recommendations on how we can make our event more accessible and inclusive regardless of a badge change. If there is anything we should consider implementing, please let me know. 

What are the next steps to use the badge?

**Comment by ElizabethN** [comment]
Hi @allisonprice! 

>What are the next steps to use the badge?

In the next comment, I will generate the code for you to use which will display the badge on your website, repo, or anywhere you'd like to use it. 

>I definitely welcome advice / recommendations on how we can make our event more accessible and inclusive regardless of a badge change. If there is anything we should consider implementing, please let me know.

Some ideas for you:

_Accessibility_
- provide a way for attendees or speakers to request or ask about specific accommodations (for example, wheelchair access, closed captioning, dietary restrictions, etc)
- some ideas on what you can provide at the conference to help with accessibility can be found under "Implementation" and under the "References" section here: https://github.com/chaoss/wg-dei/blob/main/focus-areas/event-diversity/event-accessibility.md

_Family Friendliness_
- some ideas on what you can provide at the conference to make it more family-friendly can be found here under "Implementation" and under the "References" section here: https://github.com/chaoss/wg-dei/blob/main/focus-areas/event-diversity/family-friendly.md

_Diversity Access Tickets_
- it's great that you provide discounts for students! Other ways you can provide tickets or scholarships to traditionally underrepresented groups can be found under "References" here: https://github.com/chaoss/wg-dei/blob/main/focus-areas/event-diversity/diversity-access-tickets.md

Let us know how it goes! Thanks again for being awesome and for applying for a badge! :tada:
