### ISSUE TITLE
[In-Person Event] Open Source Summit North America 2022

### ISSUE THREAD

**Issue by cartislf** [badging/event-diversity-and-inclusion#142]
# In-Person Event Submission

## Requirements

- Event Name: Open Source Summit North America 2022
- Link to the Event Website: https://events.linuxfoundation.org/open-source-summit-north-america/
- Are you an organizer of this event? Yes, Sr. Event Planner

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Event demographics are captured using the registration form. All demographic questions are optional.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the attendee information page we provide a list of pronouns to chose from but also provide a space for text input if none of the options provided apply.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers  and attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's post-event survey was considered when planning 2022.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Under the Diversity and Inclusion page on the event website there is a section that speaks to venue accessibility.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, it will be made available at the conclusion of the event via YouTube to all at no charge. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the onsite Diversity & Inclusion resources flyer. This flyer has all DEI-related resources, as well as event team members they can contact should they need anything onsite.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/open-source-summit-north-america/attend/code-of-conduct/ 

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We offer 2 types of scholarships for this event, Diversity Registration Scholarships and Need-Based Registration Scholarships. There is no limit to the number of diversity or need-based registration scholarships that we offer for this event. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity Registration Scholarships - Applicants must be from a traditionally underrepresented and/or marginalized group in the technology and/or open source communities who are unable to attend without some financial assistance. Including, but not limited to: persons identifying as LGBTQIA+, women, persons of color, and/or persons with disabilities. Need-based Registration Scholarships - Individuals who apply should be active members of the open source community who are unable to attend for financial reasons and are unable to get funding from their companies.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/open-source-summit-north-america/attend/scholarships/#scholarships 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, we are offering complimentary onsite child care this year. Children (as well as professional child care providers) must be fully vaccinated to participate. Fully vaccinated is defined as two weeks (14 full days) after the final dose of a vaccine approved for emergency or full use by the WHO. Proof of vaccination will be required. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We offer our attendees a private nursing room that they can access throughout the event, gender-neutral restrooms, pronoun stickers, and have ADA-accessible transportation provided to any offsite venues. We are also offering Kid’s Day, a complimentary course designed for youth (ages 9-18) as an introduction to the fun and the magic of web design. Very little computer knowledge is required. The basics, typing, browsing the internet, and minor computer operation, are all your child needs to participate. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/open-source-summit-north-america/attend/diversity-inclusion/  https://events.linuxfoundation.org/open-source-summit-north-america/features/kids-day/

**Comment by ElizabethN** [comment]
Cc @Anita-ihuman just making sure you saw this :blush: Thanks Anita!

**Comment by Anita-ihuman** [comment]
@cartislf Thank you for applying for the CHAOSS DEI Badging Initiative. Do have a great event.

**Comment by cartislf** [comment]
Hi Anita, 
Thank you! Is our application still under review or Has the badge been awarded? Sorry if I missed that.

**Comment by ElizabethN** [comment]
@cartislf normally I would wait to have confirmation that this badge is ok, but you scored 100%! 🎉  I will go ahead and generate the badge ☺️ THANK YOU SO MUCH and have a wonderful event!
