### ISSUE TITLE
[In-Person Event] Linux Storage Filesystem / MM & BPF Summit 

### ISSUE THREAD

**Issue by cartislf** [badging/event-diversity-and-inclusion#143]
# In-Person Event Submission

## Requirements

- Event Name: Linux Storage Filesystem / MM & BPF Summit 
- Link to the Event Website: https://events.linuxfoundation.org/lsfmm/
- Are you an organizer of this event? Yes, Sr. Event Planner

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendees onsite to ensure they can enjoy the event to the fullest: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s). Do you identify as a person of color? What gender do you identify with? How old are you? (Please note, none of these questions are required, they are optional for attendees to fill out) 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` For the registration question, “What gender do you identify with?” attendees may answer “Other gender identity”.  On site at the event, pronoun stickers are provided for attendees which include a Fill-In option. 

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers and attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's post-event survey was considered when planning 2022.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Under the Diversity and Inclusion page on the event website there is a section that speaks to venue accessibility and all on-site resources.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We send out a post-event survey to all speakers where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` This is an invitation only event.  Sessions will be recorded and distributed to attendees for viewing.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the onsite Diversity & Inclusion resources flyer. This flyer has all DEI-related resources, as well as event team members they can contact should they need anything onsite.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/lsfmm/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` This is an invitation only event with complimentary registration.  Diversity access tickets are not available for this event however, the Linux Foundation does offer travel funding for attendees that could not afford to attend the event on their own.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` N/A for this event
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` N/A for this event 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, we are offering complimentary onsite child care this year. Children (as well as professional child care providers) must be fully vaccinated to participate. Fully vaccinated is defined as two weeks (14 full days) after the final dose of a vaccine approved for emergency or full use by the WHO. Proof of vaccination will be required. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We offer our attendees a private nursing room that they can access throughout the event, gender-neutral restrooms, pronoun stickers, and have ADA-accessible transportation provided to any offsite venues.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/lsfmm/attend/child-care/

**Comment by Victorybrown** [comment]
@KafayahL for the "Accessibility Request" metric, when we say accommodation, are we talking about housing? or accommodation based on acceptance of suggestions? 

Also "Diversity Access Tickets" for events like this, based solely on invitations, how do we measure it?

**Comment by KafayahL** [comment]
> 

Accessibility at in-person and virtual events focuses on the responsibility of organizers to be as inclusive as possible and to address and provide equal access to attendees. @Victorybrown 

We can measure it by checking on the event website to see if they have provided the option to request/apply for these tickets.

I hope that helps answer your question.

**Comment by KafayahL** [comment]
@cartislf thank you for your application,
@ElizabethN  I am done with my review!

**Comment by ElizabethN** [comment]
Great, thank you @KafayahL! @Victorybrown are you also finished?

**Comment by Victorybrown** [comment]
@ElizabethN Yes, I am.

**Comment by ElizabethN** [comment]
Ah, it's counting Aastha's blank review - let me delete and re-run.

**Comment by ElizabethN** [comment]
lol much better! @cartislf are you satisfied with this badge? Would you like to discuss, change, or clarify anything before we issue the badge?

**Comment by ElizabethN** [comment]
@cartislf there you go! Enjoy the event!!
