### ISSUE TITLE
[In-Person Event] Zephyr Developer Summit 2022

### ISSUE THREAD

**Issue by Naomi-Wash** [badging/event-diversity-and-inclusion#145]
## Requirements

- Event Name: Zephyr Developer Summit 2022
- Link to the Event Website: https://events.linuxfoundation.org/zephyr-developer-summit/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` On the registration form we have multiple questions that ask for D+I. At the beginning of the D+I section we have this language, "We want to encourage greater diversity within the open source community, and demographic information helps us achieve that goal. It is collected solely for the purpose of compiling, analyzing and disclosing aggregate statistics regarding participation in open source projects and communities (including attendance at our events), to help track progress towards meeting our commitment to diversity initiatives." Then some of the following questions are included: "Do you identify as a person of color?", "Do you identify as part of the LGBTQIA+ Community?", "What gender do you identify with?", "How old are you?". On the Call for Proposals, we include multiple questions to ensure our speakers are diverse. The language is as follows: Zephyr is committed to a diverse and inclusive community. The following question is asked in an effort to track our progress in increasing diversity at events and will remain confidential. What gender does the primary speaker identify with?* Is the primary speaker a person of color? Which racial/ethnic background(s) does the primary speaker identify with? (check all that apply) Aside from gender, if the co-speaker identifies with an underrepresented minority group in technology, please indicate that group below (ie race/ethnicity, dis/ability, LGBTQ etc). For panels, more than 2 speakers, we also don't allow panels with only men. On the website we also note that we do not accept all-male panels and we encourage speakers to take the Inclusive Speaker Orientation Course.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` Here is the language that is on the registration form: "Consent to provide demographics information for the purpose listed above is optional and purely voluntary, and is provided by selecting an option from the drop-down for the corresponding category. Demographic information is considered confidential and private. It will not be shared with others as part of your registration details, nor will it be used to subject you to adverse treatment. It will be used only in aggregate form for reporting information about diversity of participation in open source projects and communities, including reporting attendance totals at our events.     Should you choose to provide any demographic information, you may request removal of that information at any time by writing to privacy@linuxfoundation.org."
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the registration form is this question and answer choices: "What gender do you identify with?" Options: Prefer not to answer, Woman, Man, Other gender identity."

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` After every event, we send a post-event survey to all attendees that asks questions about their experiences. In that survey, we also have an open-ended section where they can tell us about any element of the event that we could do better on. Also, on our D&I page, we have language that specifically states "If you have ideas on how we can create a more inclusive event, please do not hesitate to let us know" with the contact information for the event manager.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, there was a post-event meeting and the event managers went over aspects to improve DEI at the in-person event this year. This included updating the registration form with more D+I questions and striving to have more diversity in speakers.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we always try to incorporate attendee feedback in surveys to improve future events.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We have a D+I page on the website and it lists on-site resources and it includes accessibility and wheelchair resources.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We send out a post-event survey that includes a section for virtual attendees who attended via a platform. There they are able to provide any feedback they have.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, the virtual platform is open 2 weeks post event. Also, all sessions will be recorded and added to the project YouTube channel post-event.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we will have a large sign that states out our Code of Conduct fully. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/zephyr-developer-summit/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` At this time we are not providing diversity access tickets, but it may be implemented in the coming weeks.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Due to budget restraints, we unfortunately cannot offer child care services at this event. We will, however, provide a list of local childcare providers to attendees if they email the events inbox. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` Nursing Room We will be providing a private nursing room to aid in the comfort and accessibility of our nursing attendees. The room will be available all days of the event and will be located onsite. For location information, please check with registration or information desk staff onsite.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by KafayahL** [comment]
@Dhruv-Sachdev1313, @tetris4 
Hi, Hope you are doing good.
I'm just checking in to make sure you got the notification for this. Please let me know if you have any questions or notify @ElizabethN when you are done with the review. 
Thank you.

**Comment by Naomi-Wash** [comment]
Hi Elizabeth,

I would just like to understand the parameters that made us only achieve a
silver badge. The only element that is missing for this event is the
diversity access tickets. If we were to have that element, would we have
reached gold?

Thank you for providing clarification.

Best,
-Naomi


--
*Naomi Washington*
Event Planner

<https://linuxfoundation.org/>

T: 1.913.426.3148 (Central Time)
E: ***@***.***

**Comment by ElizabethN** [comment]
>The only element that is missing for this event is the
diversity access tickets. If we were to have that element, would we have
reached gold?

Yes, that would push you into a gold level (>80%). There are a few options for you, though! We can issue you the silver badge now, and if you decide to implement something like this for this year, we can re-issue it. Or, if you are considering this already, we can wait to issue the badge until it's been implemented. Or, we can leave your badge at the Silver level, which is still pretty great, and something to be proud of! :blush: 

Let us know what you'd like to do @Naomi-Wash and thanks again for submitting your application!

**Comment by Naomi-Wash** [comment]
Thank you, Elizabeth; I appreciate options. If I were to have it issued
now, would I have to complete the entire process again if we add additional
elements or just message this email chain with the updates?

Best,
-Naomi


--
*Naomi Washington*
Event Planner

<https://linuxfoundation.org/>

T: 1.913.426.3148 (Central Time)
E: ***@***.***

**Comment by ElizabethN** [comment]
@Naomi-Wash oh, you wouldn't have to go through it all again - only let us know in this thread about any changes or updates. :+1:

**Comment by Naomi-Wash** [comment]
Perfect, thank you Elizabeth. I'll accept the silver badge now then.

Have a great week!
-Naomi


--
*Naomi Washington*
Event Planner

<https://linuxfoundation.org/>

T: 1.913.426.3148 (Central Time)
E: ***@***.***

**Comment by ElizabethN** [comment]
Awesome, @Naomi-Wash! Keep up the great work! :tada:
