### ISSUE TITLE
Automated updation of README.md with the reviewed applications

### ISSUE THREAD

**Issue by ayushtamra** [badging/event-diversity-and-inclusion#149]
**Description:**
After reviewing the applications the moderators of the repository have to manually add the applicant information in the README.md which could be automated.
Adding application information here:
![image](https://user-images.githubusercontent.com/64156683/164994311-32a1ad17-578f-4929-adc3-22e368229950.png)

**Potential solution:**
It can be worked by defining github actions or through the badging bot.
The badging bot can actually do this job after the /end review command.
Though I am not much confident right now how this can be done by badging-bot but I am sure to figure it out and implement it using one of the methods.

**Context:**
So I am working on the badging bot these days and on some new features we could use to make the process more automated, So I figured out this could be a very simple yet very time-saving feature for the community.
So I just wanted to take feedback from the community if this could be implemented. @ElizabethN @Nebrethar 

I would be happy to work on this feature :smile:

**Comment by ElizabethN** [comment]
I will defer to @nebrethar to comment on if it's implementable but from my standpoint it would be very helpful!

**Comment by ElizabethN** [comment]
This has been implemented, so I'm closing this issue. Thanks to all who worked on this! :heart:
