### ISSUE TITLE
[In-Person Event] Cloud Native Wasm Day Europe 2022

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#154]
# In-Person Event Submission

## Requirements

- Event Name: Cloud Native Wasm Day Europe 2022
- Link to the Event Website: https://events.linuxfoundation.org/cloud-native-wasm-day-europe/
- Are you an organizer of this event? I am an organizer with the CNCF Events Team, and manage the DEI activities. Lindsay Gendreau is the event lead for Cloud Native Wasm Day

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Demographic information is collected solely for the purpose of compiling, analyzing and disclosing aggregate statistics regarding diversity of attendance at our events, to help track progress towards meeting our commitment to diversity initiatives. Consent to provide demographic information for the purpose listed above is optional and purely voluntary, and is provided during registration by selecting an option from the drop-down for the corresponding category. Demographic information is considered confidential and private. Voluntary information requested includes: Do you identify as a person of color? (Prefer not to Answer, Yes, No) Sub question when Yes is selected to question above: With which racial/ethnic background(s) do you identify? (check all that apply: Prefer not to answer, Asian, Black, Hispanic/Latino, Indigenous Peoples, Pacific Islander, Self Identity (fill in) )  What gender do you identify with? (Prefer not to answer, Woman, Man, Other Gender Identity)  How old are you? (Prefer not to answer, 0-19, 20-39, 40-60, 61+)
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` Each demographic question has the first option as Prefer not to answer. At the beginning of the demographic section we explain that it is all voluntary and the added language: "Should you choose to provide any demographic information, you may request removal of that information at any time by writing to privacy@linuxfoundation.org." Example of question with opt-out: What gender do you identify with? (Prefer not to answer, Woman, Man, Other Gender Identity)
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Sub question when answer is YES: Please provide additional details here: (text input box). With which racial/ethnic background(s) do you identify? check all that apply: Prefer not to answer, Asian, Black, Hispanic/Latino, Indigenous Peoples, Pacific Islander, Self Identity (text input box) 

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` https://www.surveymonkey.com/r/cnwasmdayna21
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes. We added an inclusivity question to our event survey - that has helped inform planning for this cycle.  We shared this data in the transparency report. https://www.cncf.io/reports/cloud-native-wasm-day-north-america-2021/
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Post-event, Program Committees review all survey data that covers attendee experience, expectations, and content appraisal and adjust the next event's schedule, experiences, and speakers to reflect feedback provided.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` https://events.linuxfoundation.org/cloud-native-wasm-day-europe/attend/diversity-inclusion/#onsite-resources
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` There is a tech support and contact button for attendees to connect directly with MeetingPlay. Attendees can also direct their feedback, questions and suggestions to the event team directly.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, the event platform MeetingPlay will be available 24/7 for all registered attendees and speakers up to 45 days post event. Recordings of keynotes and sessions will also be uploaded to YouTube.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes - the Code of Conduct is posted at the Event venue, on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/cloud-native-wasm-day-europe/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` The Dan Kohn Scholarship Fund exists to support individuals who may not otherwise have the opportunity to attend in three categories: Diversity, Need-based, Student. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity: Applicants must be from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities who are unable to attend without some financial assistance. Including, but not limited to persons identifying as LGBTQIA+, women, persons of color, and/or persons with disabilities. (Virtual or In-Person); Need-Based: Applicants should be active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons. (Virtual or In-Person); Student: Applicants must be students currently enrolled in high school, college / university, or a full / part-time coding course or bootcamp. (Available for Virtual Only)
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/cloud-native-wasm-day-europe/attend/scholarships/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, we are pleased to offer complimentary childcare in Valencia.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will be providing a private nursing room to aid in the comfort and accessibility of our nursing attendees. The room will be available all days of the event and will be located onsite. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/cloud-native-wasm-day-europe/attend/diversity-inclusion/#onsite-resources

**Comment by djmitche** [comment]
All ✅  :)

**Comment by ElizabethN** [comment]
@Gemarodri hi!! just making sure you saw this ping :blush: Thank you so much!

**Comment by Gemarodri** [comment]
Sorry for the late review! I'm done now :)

**Comment by ElizabethN** [comment]
@Wendi-West I'm going to go out on a limb and say you're probably ok with this badge 😉  so I'm just going to go ahead and issue it. Let us know if there is anything else to discuss with regard to this application. It looks like an awesome event! :tada:

**Comment by Wendi-West** [comment]
Thank you again!
