### ISSUE TITLE
[In-Person Event] Berlin Buzzwords

### ISSUE THREAD

**Issue by plainschwarz-team** [badging/event-diversity-and-inclusion#170]
# In-Person Event Submission

## Requirements

- Event Name: Berlin Buzzwords
- Link to the Event Website: https://2022.berlinbuzzwords.de
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Event demographics for Berlin Buzzwords is exclusively measured using our voluntary demographic & feedback survey (You can read the report for Berlin Buzzwords 2021 here: https://2022.berlinbuzzwords.de/sites/berlinbuzzwords.de/files/2022-03/bbuzz%202021%20D%26I%20report.pdf) . We do not collect speaker/attendee demographics at registration due to privacy concerns.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` Does not apply for event registration, but participants of our demographic & feedback survey may skip every question of the survey and there will also be a dedicated option to skip the demographic part of the survey completely. Also, "Prefer not to answer" options are available for all demographic questions  
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` Does not apply for event registration but for our demographic & feedback survey, we provide additional text input boxes for most demographic items such as e.g. ethnic background: "Please write any other ethnic backgrounds that you identify with here" 

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` Feedback can be provided using our demographics and feedback survey, which will be send to every attendee, speaker and volunteer after the event. The anonymized results will be published in our annual Diversity Report, which is available for everyone on our website. Last year's report is available on our website at: https://2022.berlinbuzzwords.de/diversity-inclusivity 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes. For example, at FOSS Backstage (which is also organized by the Berlin Buzzwords event team) one of the most requested improvements was adding live subtitles. (See: https://foss-backstage.de/wp-content/uploads/2022/05/fossb22-diversity-report.pdf) As a consequence, live subtitles will be available at Berlin Buzzwords 2022. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes. As mentioned above, we will collect feedback using our demographics and feedback survey. Feedback regarding diversity, accessibility and inclusivity will be published in our Diversity Report. Feedback will also be discussed after the event within the team.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` By visiting the diversity & inclusivity page on our website: https://2022.berlinbuzzwords.de/diversity-inclusivity
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Attendees and speakers can suggest future improvements for the event in our annual feedback survey.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Our website will be available after the event. Our online platform Venueless is also available for a limited time after the event. The talks and sessions will be made available for everyone on our [YouTube-Channel](https://www.youtube.com/c/PlainSchwarzUG/playlists?view=50&sort=dd&shelf_id=3) after the event. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` The code of conduct is posted on our website. Attendees and speaker must tick a checkbox at registration that they have read and consent to our code of conduct. The code of conduct will be published on our online platform Venueless and in physical form at the entrance to our venue Kulturbrauerei in Berlin.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://2022.berlinbuzzwords.de/code-conduct

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We provide Diversity Online-Tickets and Diversity Onsite-Tickets. Both tickets are fully sponsored (i.e. free) and provide full access either to our online or onsite event.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity Tickets are available to people from underrepresented groups within the Berlin Buzzwords community. This includes, but is not limited to: women, people of colour, LGBTQIA people, disabled people, and people facing economic or social hardships. Please note that there is no "qualification process" for Diversity Tickets, and one can simply order a Diversity Ticket without being vetted, since we as organizers are unable to judge if someone is actually a member of a underrepresented group, and this would create all kinds of obvious problems.  
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://2022.berlinbuzzwords.de/diversity-inclusivity 

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by plainschwarz-team** [comment]
> Hi, @plainschwarz-team Thanks for submitting your event! We have taken down your note and will also work for that option!

Hi @Ruth-ikegah, thanks for getting back. Could you also provide some guidance for some of the questions we didn't quite understand?

1. "Does the event platform allow attendees to suggest future accomodations for the event?" 
2.  "Will the event platform be accessible to attendees and speakers after the event?"

As a hybrid event, we have our venue in Berlin, then there is our website and we have our online platform Venueless - to which of those are you referring with "event platform"?  Also, what do you mean by "future accommodations"?

Thanks for your help!

**Comment by Anita-ihuman** [comment]
@plainschwarz-team 

> > Hi, @plainschwarz-team Thanks for submitting your event! We have taken down your note and will also work for that option!
> 
> Hi @Ruth-ikegah, thanks for getting back. Could you also provide some guidance for some of the questions we didn't quite understand?
> 
> 1. "Does the event platform allow attendees to suggest future accomodations for the event?"
> 2. "Will the event platform be accessible to attendees and speakers after the event?"
> 
> As a hybrid event, we have our venue in Berlin, then there is our website and we have our online platform Venueless - to which of those are you referring with "event platform"? Also, what do you mean by "future accommodations"?
> 
> Thanks for your help!

[plainschwarz-team](https://github.com/plainschwarz-team)
1. Does the event provide support for Attendees to direct their feedback, questions and suggestions to the event team regarding attendee welfare? Any medium at all(feedback survey, etc) 
2.  We want to know if the event platform will be available to speakers or attendees post-event. That could include access to the Recordings of keynotes and YouTube uploads. Since it's a hybrid, there must be a platform for the virtual attendees to participate right?

**Comment by Anita-ihuman** [comment]
@plainschwarz-team Thank you for applying for a DEI Badge for your event.
- I observed that the "Family Friendliness" metrics are left unanswered. Is that intentional or need clarity on that?

**Comment by Ruth-ikegah** [comment]
> > Hi, @plainschwarz-team Thanks for submitting your event! We have taken down your note and will also work for that option!
> 
> Hi @Ruth-ikegah, thanks for getting back. Could you also provide some guidance for some of the questions we didn't quite understand?
> 
> 1. "Does the event platform allow attendees to suggest future accomodations for the event?"
> 2. "Will the event platform be accessible to attendees and speakers after the event?"
> 
> As a hybrid event, we have our venue in Berlin, then there is our website and we have our online platform Venueless - to which of those are you referring with "event platform"? Also, what do you mean by "future accommodations"?
> 
> Thanks for your help!

Hi @plainschwarz-team, so sorry for the confusion! Let me clarify these two questions.

1. "Does the event platform allow attendees to suggest future accommodations for the event?"
This means: Allowing feedback for "Future accommodations" means the event must have a feedback system that feeds recommendations into consideration for the next iteration of the event. For example, if someone recommends some wheelchair accessibility updates for the Berlin Buzzwords 2022 to be considered when planning Berlin Buzzwords 2023.

2.  "Will the event platform be accessible to attendees and speakers after the event?"
This means: The event platform here is the online platform for virtual attendees. Will it be available for attendees to still visit the talks after the event?

Let me know if you have more questions! I would be happy to explain more.

**Comment by plainschwarz-team** [comment]
Thanks @Ruth-ikegah and @Anita-ihuman for explaining the questions! We have added our answers to the application.

Regarding Family Friendliness: We've left this blank intentionally, since we can't commit to to offering childcare facilities for this year's edition of Berlin Buzzwords due to planning and budgetary constraints, and we don't want to promise something we may not be able to keep.

**Comment by ElizabethN** [comment]
@KafayahL Hiiiii -  just making sure you saw this notification :blush:

**Comment by KafayahL** [comment]
@ElizabethN I've completed my review. 
Thank you

**Comment by ElizabethN** [comment]
@Anita-ihuman is this review complete or is there more discussion on this?

**Comment by Anita-ihuman** [comment]
I am done with my review. 
That answers my questions

> Thanks @Ruth-ikegah and @Anita-ihuman for explaining the questions! We have added our answers to the application.
> 
> Regarding Family Friendliness: We've left this blank intentionally, since we can't commit to to offering childcare facilities for this year's edition of Berlin Buzzwords due to planning and budgetary constraints, and we don't want to promise something we may not be able to keep.

**Comment by plainschwarz-team** [comment]
Hi, is there anything else we have to do and what are the next steps?

**Comment by Anita-ihuman** [comment]
Hey @ElizabethN @Ruth-ikegah, I am done with my review.

@plainschwarz-team Thank you for applying for a DEI Badge. 
I also thank your team for working on improving the Accessibility metrics.
Good luck with the event.

**Comment by Ruth-ikegah** [comment]
> Hi, is there anything else we have to do and what are the next steps?

Hi @plainschwarz-team I am so sorry, this got lost in my notifications. I will go ahead and issue the badge now!

**Comment by Ruth-ikegah** [comment]
> ![Assigned badge: gold](https://camo.githubusercontent.com/528ea84dddc2395887ead07da0a0e03d067adcc93e54a8ae5641c0db88af7bd8/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f44253236492d476f6c642d79656c6c6f773f7374796c653d666c61742d737175617265266c6162656c436f6c6f723d35383335383626266c696e6b3d68747470733a2f2f6769746875622e636f6d2f62616467696e672f6576656e742d6469766572736974792d616e642d696e636c7573696f6e2f6973737565732f3137302f266c6f676f3d646174613a696d6167652f7376672b786d6c3b6261736536342c50484e325a7942325a584a7a61573975505349784c6a4569494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a794967646d6c6c64304a76654430694d434177494449314d4341794e54416950676f38634746306143426d615778735053496a4d554d35516b51324969426b50534a4e4f5463754d5377304f53347a597a45344c5459754e79777a4e7934344c5459754f4377314e5334354c5441754d6d77784e7934314c544d774c6a4a6a4c5449354c5445794c6a4d744e6a45754f4330784d6934794c546b774c6a67734d43347a54446b334c6a45734e446b754d336f694c7a344b50484268644767675a6d6c7362443069497a5a42517a64434f5349675a443069545445354e4334324c444d794c6a684d4d5463334c6a49734e6a4e6a4d5451754f4377784d69347a4c4449304c6a63734d6a6b754e5377794e7934354c4451344c6a566f4d7a51754f554d794d7a59754d6977344d4334794c4449784f5334354c4455784c6a63734d546b304c6a59734d7a49754f486f694c7a344b50484268644767675a6d6c736244306949304a474f554e444f5349675a443069545449774e4334354c44457a4f533430597930334c6a6b734e444d754f5330304f5334354c44637a4c546b7a4c6a67734e6a55754d574d744d544d754f4330794c6a55744d6a59754f4330344c6a59744d7a63754e5330784e793432624330794e6934344c4449794c6a514b43574d304e6934324c44517a4c6a51734d5445354c6a55734e4441754f5377784e6a49754f5330314c6a646a4d5459754e5330784e7934334c4449334c5451774c6a49734d7a41754d5330324e433479534449774e4334356569497650676f38634746306143426d615778735053496a52445978524456474969426b50534a4e4e5455754e6977784e6a55754e6b4d7a4e5334354c44457a4d5334344c44517a4c6a4d734f4467754f4377334d7934784c44597a4c6a564d4e5455754e79777a4d793479517a63754e5377324f5334344c5451754d6977784d7a63754e4377794f4334344c4445344f4577314e5334324c4445324e5334326569497650676f384c334e325a7a344b) **Markdown Badge Link:**
> 
> ```
> ![Assigned badge: gold](https://img.shields.io/badge/D%26I-Gold-yellow?style=flat-square&labelColor=583586&&link=https://github.com/badging/event-diversity-and-inclusion/issues/170/&logo=data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDI1MCAyNTAiPgo8cGF0aCBmaWxsPSIjMUM5QkQ2IiBkPSJNOTcuMSw0OS4zYzE4LTYuNywzNy44LTYuOCw1NS45LTAuMmwxNy41LTMwLjJjLTI5LTEyLjMtNjEuOC0xMi4yLTkwLjgsMC4zTDk3LjEsNDkuM3oiLz4KPHBhdGggZmlsbD0iIzZBQzdCOSIgZD0iTTE5NC42LDMyLjhMMTc3LjIsNjNjMTQuOCwxMi4zLDI0LjcsMjkuNSwyNy45LDQ4LjVoMzQuOUMyMzYuMiw4MC4yLDIxOS45LDUxLjcsMTk0LjYsMzIuOHoiLz4KPHBhdGggZmlsbD0iI0JGOUNDOSIgZD0iTTIwNC45LDEzOS40Yy03LjksNDMuOS00OS45LDczLTkzLjgsNjUuMWMtMTMuOC0yLjUtMjYuOC04LjYtMzcuNS0xNy42bC0yNi44LDIyLjQKCWM0Ni42LDQzLjQsMTE5LjUsNDAuOSwxNjIuOS01LjdjMTYuNS0xNy43LDI3LTQwLjIsMzAuMS02NC4ySDIwNC45eiIvPgo8cGF0aCBmaWxsPSIjRDYxRDVGIiBkPSJNNTUuNiwxNjUuNkMzNS45LDEzMS44LDQzLjMsODguOCw3My4xLDYzLjVMNTUuNywzMy4yQzcuNSw2OS44LTQuMiwxMzcuNCwyOC44LDE4OEw1NS42LDE2NS42eiIvPgo8L3N2Zz4K)
> ```
> 
> **HTML Badge Link:**
> 
> ```
> <img src='https://img.shields.io/badge/D%26I-Gold-yellow?style=flat-square&labelColor=583586&&link=https://github.com/badging/event-diversity-and-inclusion/issues/170/&logo=data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDI1MCAyNTAiPgo8cGF0aCBmaWxsPSIjMUM5QkQ2IiBkPSJNOTcuMSw0OS4zYzE4LTYuNywzNy44LTYuOCw1NS45LTAuMmwxNy41LTMwLjJjLTI5LTEyLjMtNjEuOC0xMi4yLTkwLjgsMC4zTDk3LjEsNDkuM3oiLz4KPHBhdGggZmlsbD0iIzZBQzdCOSIgZD0iTTE5NC42LDMyLjhMMTc3LjIsNjNjMTQuOCwxMi4zLDI0LjcsMjkuNSwyNy45LDQ4LjVoMzQuOUMyMzYuMiw4MC4yLDIxOS45LDUxLjcsMTk0LjYsMzIuOHoiLz4KPHBhdGggZmlsbD0iI0JGOUNDOSIgZD0iTTIwNC45LDEzOS40Yy03LjksNDMuOS00OS45LDczLTkzLjgsNjUuMWMtMTMuOC0yLjUtMjYuOC04LjYtMzcuNS0xNy42bC0yNi44LDIyLjQKCWM0Ni42LDQzLjQsMTE5LjUsNDAuOSwxNjIuOS01LjdjMTYuNS0xNy43LDI3LTQwLjIsMzAuMS02NC4ySDIwNC45eiIvPgo8cGF0aCBmaWxsPSIjRDYxRDVGIiBkPSJNNTUuNiwxNjUuNkMzNS45LDEzMS44LDQzLjMsODguOCw3My4xLDYzLjVMNTUuNywzMy4yQzcuNSw2OS44LTQuMiwxMzcuNCwyOC44LDE4OEw1NS42LDE2NS42eiIvPgo8L3N2Zz4K' alt='D&I Badging badge state: gold'/>
> ```

Hi @plainschwarz-team congratulations on your Gold badge!

**Comment by plainschwarz-team** [comment]
> > Hi, is there anything else we have to do and what are the next steps?
> 
> Hi @plainschwarz-team I am so sorry, this got lost in my notifications. I will go ahead and issue the badge now!
> 
> Thanks @Anita-ihuman and @KafayahL for your review!

Hey @Ruth-ikegah no worries and thanks for the quick response! Also thank you to @Anita-ihuman and @KafayahL for the review and help!
