### ISSUE TITLE
[In-Person Event] Elizabeth's Cool Awesome Event

### ISSUE THREAD

**Issue by ElizabethN** [badging/event-diversity-and-inclusion#173]
# In-Person Event Submission

## Requirements

- Event Name: Elizabeth's Cool Awesome Event
- Link to the Event Website: https://elizabethsevent.com
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask everyone to complete a survey.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` hi
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` hi

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` blah balh
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` yes
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` yes
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` https;//website.com
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` 

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by Nebrethar** [comment]
Great work @ElizabethN! Better luck next time!
