### ISSUE TITLE
[Virtual Event] PrestoCon Day 2022

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#174]
# Virtual Event Submission

## Requirements

- Event Name: PrestoCon Day 2022
- Link to the Event Website: https://events.linuxfoundation.org/prestocon-day/
- Provide verification that you are an event organizer: Yes, Rachel Braun, Senior Event Planner, Linux Foundation

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A`  During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite, and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete.   Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Do you identify as a person of color? What gender do you identify with? How old are you? 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` Not applicable. 

## Inclusive Experience at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the Linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, after each event, a feedback survey is deployed to speakers, attendees, sponsors, etc. We use the feedback provided in this survey to help plan for future events, including the current year’s event. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We include Resources available to our attendees on the event webpage: ​​https://events.linuxfoundation.org/prestocon-day/attend/diversity-inclusion/. 
  - `Q` Does the event platform allow attendees to suggest future accommodations for the event?
  - `A` Not applicable, other than the post-event survey. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` We will use Hopin for PrestoCon Day 2022 - the virtual platform will close shortly after the last session. Keynotes and other event recordings will be made available on the Presto Foundation YouTube Channel shortly after the event concludes. 

## Time Inclusion for Virtual Events

- [x] This event commits to Time Inclusion for Virtual Events.
  - `Q` Are speakers able to pre-record their presentations, as opposed to presenting them live?
  - `A` While it is preferred that speakers present live at PrestoCon Day, speakers do have the option to pre-record their presentations. Pre-recorded videos are due by July 15. 
  - `Q` Can attendees change video quality on the Event platform while viewing a presentation?
  - `A` Not applicable. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/prestocon-day/attend/code-of-conduct/
  
 ## Diversity Access Tickets
  
- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` N/A - complimentary event
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` N/A - complimentary event
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  N/A - complimentary event

**Comment by RachelBraunLF** [comment]
Hi @kristiprogri !
Thanks so much for seeking clarification on this - I was under the incorrect impression that our attendees could not change the video quality, so I reached out to our virtual platform to confirm. 

Attendees can improve their streaming experience by manually selecting a video resolution. By default, the setting is auto, which means the player will adjust to the best resolution for the attendee's connection, but an attendee can choose the quality settings on their own. 

Please let me know if you have any further questions.
Thanks!

**Comment by kristiprogri** [comment]
Awesome! @RachelBraunLF 
Thanks for the quick reply

**Comment by Victorybrown** [comment]
@ElizabethN I'm done with my review.

**Comment by RachelBraunLF** [comment]
Yes, very ok in the best way. :) Thank you!
