### ISSUE TITLE
[In-Person Event] DPDK Userspace Summit

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#176]
# In-Person Event Submission

## Requirements

- Event Name: DPDK Userspace Summit
- Link to the Event Website: https://events.linuxfoundation.org/dpdk-userspace-summit/
- Are you an organizer of this event? Yes, Rachel Braun, Senior Event Planner, Linux Foundation

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite, and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete.   Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Do you identify as a person of color? What gender do you identify with? How old are you? 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you. 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` There is not a text input box on the event registration page. 

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, after each event a feedback survey is deployed to speakers, attendees, sponsors, etc. We use the feedback provided in this survey to help plan for future events, including the current year’s event. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We include Resources available to our attendees on the event webpage: ​​https://events.linuxfoundation.org/dpdk-userspace-summit/attend/diversity-inclusion/. 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Attendees receive a post-event survey where we encourage suggestions for future accommodations at the event. Additionally, attendees are welcome to stop by the registration desk and provide feedback at any time during the event. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Content from DPDK Userspace Summit will be streamed to YouTube and made available live for registered virtual attendees. Keynotes and other event recordings will be made available on the DPDK YouTube Channel shortly after the event concludes. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/dpdk-userspace-summit/attend/code-of-conduct/ 

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by Delight362** [comment]
Thank you @RachelBraunLF  for applying for chaoss badge.
am done with my review @Ruth-ikegah

**Comment by oma131** [comment]
Hi @RachelBraunLF the review questions on Family friendliness and Diversity Access Tickets were not answered. Have your events made provisions for these two review questions, or should we continue the review with the answers you've already provided?

**Comment by RachelBraunLF** [comment]
Hi @oma131 Thanks for your question! Yes, the boxes for Family Friendliness and Diversity Access Tickets have been left unchecked as these are not items we have the means to include in our CHAOSS application for this year. 

Please proceed with the review using the answers provided. 
Thank you!

**Comment by oma131** [comment]
Thank you! @RachelBraunLF for applying for the chaoss event badge.
@Ruth-ikegah I am done with the review.

**Comment by oma131** [comment]
Thank you! @RachelBraunLF for applying for the CHAOSS event badge.
@Ruth-ikegah I am done with the review
