### ISSUE TITLE
[In-Person Event] API Specifications Conference (ASC) 2022

### ISSUE THREAD

**Issue by celiastampslf** [badging/event-diversity-and-inclusion#179]
# In-Person Event Submission

## Requirements

- Event Name: API Specifications Conference (ASC) 2022
- Link to the Event Website: https://events.linuxfoundation.org/openapi-asc/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite, and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete.   Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Specify dietary needs (if any.) Do you identify as a person of color? What gender do you identify with? How old are you? 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` At this time, a text input box on Event registration is not available. 

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”   We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. For example, an attendee of a previous event recommended live captioning for keynotes this year and we are looking into providing this at our event.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We do not have a specific event platform as this is an in-person event. Can you clarify what you are looking for with regards to in-person events?
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` We do not have a specific event platform as this is an in-person event. Can you clarify what you are looking for with regards to in-person events? Our sessions will be recorded and placed on our public YouTube channel for anyone to view post-event.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/openapi-asc/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` OpenAPI Initiative’s Scholarship Fund is intended to enable open source developers and community members to attend when they would otherwise be unable due to a lack of funding. We place an emphasis on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status. If you work for a company that has the ability to fund your travel, we ask that you not apply, to save funds for those that need it.  Please fill out the form below to have your funding request considered. In order to maximize spending, scholarship fund assistance may only be used for:  Coach airfare tickets Accommodation for the dates of the event plus one night prior to the event start date Ground transportation to/from the airport
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` ASC places an emphasis on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status. If an individual works for a company that has the ability to fund travel, we ask that they not apply to save scholarship funds for those who need it.   We ask applicants to provide a few key pieces of information on their application including their Company or Organization, whether they can receive funds from their organization, a brief description of the ways they are involved in technology and/or open source communities, and why they want to attend the conference.   We also ask if they belong to an underrepresented and/or marginalized group. This field is not required, and is optional to include.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/openapi-asc/attend/scholarships/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, complimentary child care is available at the event. Information can be viewed here: https://events.linuxfoundation.org/openapi-asc/attend/child-care/
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will provide a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event, and will be located onsite.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/openapi-asc/attend/child-care/

**Comment by oma131** [comment]
Hi @celiastampslf Thank you for applying for an event badge
@Ruth-ikegah I am done with the review

**Comment by KafayahL** [comment]
Thank you for applying @celiastampslf  everything looks good. 
@Ruth-ikegah I'm done with my review.

**Comment by Ruth-ikegah** [comment]
Thanks @celiastampslf, for applying a DEI Badge! I will go ahead and assign the badge!

Thanks @oma131 and @KafayahL for your review!

**Comment by Ruth-ikegah** [comment]
Thanks, @celiastampslf once again! Congratulations on your gold badge!

**Comment by celiastampslf** [comment]
@oma131 @KafayahL @Ruth-ikegah Thank you all for the speedy review!
