### ISSUE TITLE
[Virtual Event] Open Source Summit Latin America 2022

### ISSUE THREAD

**Issue by mgoytia04** [badging/event-diversity-and-inclusion#181]
# Virtual Event Submission

## Requirements

- Event Name: Open Source Summit Latin America 2022
- Link to the Event Website: https://events.linuxfoundation.org/open-source-summit-latin-america/
- Provide verification that you are an event organizer: Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendee virtually to ensure they can enjoy the event to the fullest:  Do you have a disability that needs to be accommodated? Do you identify as a person of color?  Do you identify as part of the LGBTQIA+ Community? What gender do you identify with?  How old are you?  (Please note, none of these questions are required, they are optional for attendees to fill out) 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` We send out a post-event survey to all speakers and attendees where we ask the following question:”Is there anything you'd like to share with us regarding your experience about this virtual event and/or do you have additional feedback on how we can improve our virtual events in the future?.”   We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` All demographic questions on our registration are optional.

## Inclusive Experience at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers and attendees where we ask the following question:”Is there anything you'd like to share with us regarding your experience about this virtual event and/or do you have additional feedback on how we can improve our virtual events in the future?.”   We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's post-event survey was considered when planning 2022. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Information for interpreting and captioning is available on our event website under the Diversity and Inclusion page (https://events.linuxfoundation.org/open-source-summit-latin-america/attend/diversity-inclusion/#interpretation-captioning) 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events made easily accessible should anyone want to share their feedback prior, during, or after the event.  Additionally, attendees have the opportunity to share any accommodations requests in our Lobby (our virtual event platform main page), which is tracked by the event staff.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, the platform will be open for 30 days post-event and then we will migrate the recordings over to the Linux Foundation YouTube channel.

## Time Inclusion for Virtual Events

- [x] This event commits to Time Inclusion for Virtual Events.
  - `Q` Are speakers able to pre-record their presentations, as opposed to presenting them live?
  - `A` Yes, speakers are able to pre-recored their presentations, as opposed to presenting them live. 
  - `Q` Can attendees change video quality on the Event platform while viewing a presentation?
  - `A` No

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct linked in all event emails, as well as event website for easy reference. The Diversity and Inclusion website also provides contact information of our SVP & General Manager of Events should they need additional assistance during their virtual experience. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/open-source-summit-latin-america/attend/code-of-conduct/
  
 ## Diversity Access Tickets
  
- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We offer 2 types of scholarships for this event, Diversity Registration Scholarships and Need-Based Registration Scholarships. There is no limit to the number of diversity or need-based registration scholarships that we offer for this event. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity Registration Scholarships - Applicants must be from a traditionally underrepresented and/or marginalized group in the technology and/or open source communities who are unable to attend without some financial assistance. Including, but not limited to: persons identifying as LGBTQIA+, women, persons of color, and/or persons with disabilities. Need-based Registration Scholarships - Individuals who apply should be active members of the open source community who are unable to attend for financial reasons and are unable to get funding from their companies.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/open-source-summit-latin-america/attend/scholarships/

**Comment by tetris4** [comment]
Hi @mgoytia04 and thanks for applying for a D&I badge! 

There is only one thing that is not clear to me regarding the question on the Text Input option under Event Demographics: "Text Input - The Event provides a text box to input certain data such as Gender, Race, or Ethnicity".

Is a text input option provided? When I tried to register, the page was not loading for me, so I couldn't check. Can you please clarify this?

In any case, @Ruth-ikegah this doesn't seem to affect the level of the badge. =)

**Comment by ElizabethN** [comment]
@mgoytia04 are you ok with this badge? If so, let us know and we will issue it. If you'd like to discuss anything further, feel free to hop in here, in this issue. Thank you!

**Comment by ElizabethN** [comment]
@mgoytia04 here is your badge! Thank you so much!!
