### ISSUE TITLE
[In-Person Event] ONE Summit

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#183]
# In-Person Event Submission

## Requirements

- Event Name: ONE Summit
- Link to the Event Website: https://events.linuxfoundation.org/one-summit-north-america/
- Are you an organizer of this event? Yes, Rachel Braun, Senior Event Planner, The Linux Foundation

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite, and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete.   Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Do you identify as a person of color? What gender do you identify with? How old are you? 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic-related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you. 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` There is not a text input box on the event registration page. 

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, after each event, a feedback survey is deployed to speakers, attendees, sponsors, etc. We use the feedback provided in this survey to help plan for future events, including the current year’s event. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We include Resources available to our attendees on the event webpage: https://events.linuxfoundation.org/one-summit-north-america/attend/diversity-inclusion/#onsite-resources 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.  Additionally, during the registration process, we ask registrants if they have any accommodations requests we should be aware of. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Keynotes and other event recordings will be made available on the LFN YouTube Channel shortly after the event concludes. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/one-summit-north-america/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We offer 2 types of access tickets for the event; need-based registration scholarships + travel funding. We use a scholarship program to provide diversity access tickets to support individuals who may not otherwise have the opportunity to attend. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` We place an emphasis on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status. If an individual works for a company that has the ability to fund travel, we ask that they not apply to save scholarship funds for those who need it.   We ask applicants to provide a few key pieces of information on their application including their Company or Organization, whether they can receive funds from their organization, a brief description of the ways they are involved in technology and/or open source communities, and why they want to attend the conference.   We also ask if they belong to an underrepresented and/or marginalized group. This field is not required and is optional to include. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/one-summit-north-america/attend/scholarships/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, complimentary child care is available at the event. Information can be viewed here: https://events.linuxfoundation.org/one-summit-north-america/attend/child-care/ 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A`  We will provide a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event, and will be located onsite. We will also have gender-neutral restrooms available to all attendees at the event. 
  - `Q` Provide relevant links related to family-friendliness at the Event.
  - `A` https://events.linuxfoundation.org/one-summit-north-america/attend/diversity-inclusion/#onsite-resources

**Comment by Victorybrown** [comment]
@ElizabethN I'm done with my review

**Comment by ElizabethN** [comment]
Sorry, @kaxada were you finished with your review?

**Comment by kaxada** [comment]
@ElizabethN I am done. There where two checks I had not yet confirmed but I have checked them

**Comment by ElizabethN** [comment]
@kaxada @Victorybrown thank you so much! 

@RachelBraunLF are you satisfied with this badge? If so I will happily issue it for you to use. 🙌

**Comment by RachelBraunLF** [comment]
@ElizabethN I accept the badge!
 Thank you @kaxada and @Victorybrown for your reviews!

**Comment by kaxada** [comment]
> 

you are welcome

**Comment by kaxada** [comment]
> @ElizabethN I accept the badge! Thank you @kaxada and @Victorybrown for your reviews!

You are welcome

**Comment by ElizabethN** [comment]
Here is your badge @RachelBraunLF! Apologies for the delay and keep up the awesome work!
