### ISSUE TITLE
[In-Person Event] O3DCon 2022

### ISSUE THREAD

**Issue by NicoleBlessing** [badging/event-diversity-and-inclusion#184]
# In-Person Event Submission

## Requirements

- Event Name: O3DCon 2022
- Link to the Event Website: https://events.linuxfoundation.org/o3dcon/
- Are you an organizer of this event? Yes, Event Coordinator

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendees onsite to ensure they can enjoy the event to the fullest: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s). Do you identify as a person of color? What gender do you identify with? How old are you? (Please note, none of these questions are required, they are optional for attendees to fill out) 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the attendee information page we provide a list of pronouns to chose from but also provide a space for text input if none of the options provided apply.  Criteria: Measuring Demographics - The Event has a process for measuring speaker demographics. Opt-Out - The Event provides an opportunity to opt-out of providing demographic data. Text Input - The Event provides a text box to input certain data such as Gender, Race, or Ethnicity

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers and attendees. We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's post-event survey was considered when planning 2022.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Under the Diversity and Inclusion page on the event website there is a section that speaks to venue accessibility. https://events.linuxfoundation.org/o3dcon/attend/diversity-inclusion/
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We send out a post-event survey to all speakers and attendees. We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, it will be made available at the conclusion of the event via YouTube to all at no charge. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the onsite Diversity & Inclusion resources flyer. This flyer has all DEI-related resources, as well as event team members they can contact should they need anything onsite.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/o3dcon/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We offer 2 types of scholarships for this event, Diversity Registration Scholarships and Need-Based Registration Scholarships. There is no limit to the number of diversity or need-based registration scholarships that we offer for this event. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity Registration Scholarships - Applicants must be from a traditionally underrepresented and/or marginalized group in the technology and/or open source communities who are unable to attend without some financial assistance. Including, but not limited to: persons identifying as LGBTQIA+, women, persons of color, and/or persons with disabilities. Need-based Registration Scholarships - Individuals who apply should be active members of the open source community who are unable to attend for financial reasons and are unable to get funding from their companies.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/o3dcon/attend/scholarships/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Unfortunately, we are no longer able to offer complimentary childcare as the budget and scope of the event has decreased.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We offer our attendees a private nursing room that they can access throughout the event, gender-neutral restrooms, pronoun stickers, and have ADA-accessible transportation provided to any offsite venues.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/o3dcon/attend/diversity-inclusion/#onsite-resources

**Comment by Gemarodri** [comment]
Hi! @NicoleBlessing, thank you for the submission.

I have a few questions that I hope you can clarify. 
1. Your approach to measure demographics only includes participants, how are you going to measure the speakers' demographics?
2. How the demographic data would be presented or used?
3. Could you clarify the process to incorporate feedback from previous years into this year's conference?
4. How are the participants enforced to accept the Code of Conduct?  

Thank you in advance!

**Comment by NicoleBlessing** [comment]
Hello!

Thank you for your questions, please see the answers below in red:

1. Your approach to measure demographics only includes participants, how
are you going to measure the speakers' demographics? Speakers are also
required to register for the event and in the registration form are the
same questions presented to attendees such as: Do you have a disability
that we should be mindful of as we try to accommodate everyone for this
event? Please specify dietary needs (if any). If you have a dietary need
that isn’t listed, email us at ***@***.*** and we will make
every reasonable effort to accommodate your need(s). Do you identify as a
person of color? What gender do you identify with? How old are you? (Please
note, none of these questions are required, they are optional for attendees
to fill out)
2. How the demographic data would be presented or used? The data is used in
post event reports and also added to the website on an event to event basis
3. Could you clarify the process to incorporate feedback from previous
years into this year's conference?  Post-event, an attendee survey is sent
out to collect feedback on different elements of the events as well as an
open-ended question for any feedback they would like to give. After the
survey closes we add feedback to a SWOT doc. When planning the next event
we reference the SWOT doc to incorporate all feedback.
4. How are the participants enforced to accept the Code of Conduct? The
participants in the Event are required to accept the Code of Conduct when
registering. It is ensured that the Code of Conduct is findable on the
event website as well as being posted on signage throughout the event. It
is also in attendee emails. While onsite if there are any CoC issues it is
escalated to the event manager onsite to be handled appropriately.

Let me know if you have any additional questions.

Thank you!
Nicole

*--*
*Nicole Blessing*
Senior Event Coordinator

<https://linuxfoundation.org/>

T: 1.757.375.2231 (Eastern Time)
E: ***@***.***

**Comment by Dhruv-Sachdev1313** [comment]
Thank You @NicoleBlessing, that answers all my questions as well. All the best for the Event!

Hi @ElizabethN, I have completed my review! 🙂

**Comment by Gemarodri** [comment]
Thank you @NicoleBlessing. 

@ElizabethN, I have finished my review as well

**Comment by ElizabethN** [comment]
@NicoleBlessing awesome job! I'm going to go ahead and assign your badge. Keep up the great work! 🙌

**Comment by NicoleBlessing** [comment]
Amazing, thank you all so much!!
