### ISSUE TITLE
[In-Person Event] Spinnaker Summit

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#187]
# In-Person Event Submission

## Requirements

- Event Name: Spinnaker Summit
- Link to the Event Website: https://events.linuxfoundation.org/spinnaker-summit/
- Are you an organizer of this event? Yes, Rachel Braun, Sr. Event Planner - The Linux Foundation

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A`  During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete. Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Do you identify as a person of color? What gender do you identify with? How old are you?
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic-related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` There is not a text input box on the event registration page.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the Linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, or during, or after the event.
  - `Q` Is the event team using feedback from previous event attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, after each event, a feedback survey is deployed to speakers, attendees, sponsors, etc. We use the feedback provided in this survey to help plan for future events, including the current year’s event.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We include Resources available to our attendees on the event webpage: https://events.linuxfoundation.org/spinnaker-summit/attend/diversity-inclusion/#onsite-resources
  - `Q` Does the event platform allow attendees to suggest future accommodations for the event?
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. Additionally, during the registration process, we ask registrants if they have any accommodations requests we should be aware of.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Keynotes and other event recordings will be made available on the Continuous Delivery YouTube Channel shortly after the event concludes.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/spinnaker-summit/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Unfortunately, we are not able to offer complimentary childcare due to budget restrictions. We are happy to provide a list of childcare resources to our attendees upon request. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will provide a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event and will be located onsite. We will also have gender-neutral restrooms available to all attendees at the event.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/spinnaker-summit/attend/diversity-inclusion/#onsite-resources

**Comment by Delight362** [comment]
Hi @RachelBraunLF
Thanks you very much submitting your application.

I have a question to ask, is there any provision for the  diversity access tickets ?

**Comment by RachelBraunLF** [comment]
Hi @Delight362 - thanks for your question! I have left the box for Diversity Access Tickets unchecked as these are unfortunately not items that we have the ability to include for this year's event due to budgetary restrictions.

**Comment by djmitche** [comment]
Nice to hear from you again Rachel!

@ElizabethN: I'm away for the week starting tomorrow morning.  If it's OK for me to get to this next week, I can do that -- otherwise, it will be best to assign to someone else.

**Comment by Delight362** [comment]
Okay thanks @RachelBraunLF  
Hi @ElizabethN  am done with my review

**Comment by ElizabethN** [comment]
@djmitche ok, great! Thanks for letting us know. I'll reassign :+1:

**Comment by KafayahL** [comment]
Thanks for the application @RachelBraunLF 
I'm done with my review @ElizabethN

**Comment by RachelBraunLF** [comment]
Hi @KafayahL @Delight362 - apologies for coming back here with an update, but we just recently were able to add Scholarships to Spinnaker Summit! https://events.linuxfoundation.org/spinnaker-summit/attend/scholarships/ 

We are offering 1 type of Diversity Access Tickets in the form of Travel Funding scholarships - an approved applicant will receive travel funding assistance in addition to an in-person ticket to Spinnaker Summit.

**Comment by ElizabethN** [comment]
@RachelBraunLF that's amazing news! @KafayahL @Delight362 I'll wait to issue this badge until you've had a chance to revisit the checklist in light of this new information. 🙌

**Comment by KafayahL** [comment]
That's awesome! @RachelBraunLF 
@ElizabethN I've revisited and updated the checklist accordingly. Thanks!

**Comment by Delight362** [comment]
Thanks so much for that @RachelBraunLF .
@ElizabethN I have updated my check list . Thanks

**Comment by ElizabethN** [comment]
@RachelBraunLF if you're ok with this new result, it would be my pleasure to issue this badge 🎉

**Comment by RachelBraunLF** [comment]
@ElizabethN @Delight362 @KafayahL - I accept the badge! 
Thank you so much for your review, and your willingness to re-review given the new information!

**Comment by ElizabethN** [comment]
Here you go @RachelBraunLF! Thanks again for applying, and keep up the great work! 😍
