### ISSUE TITLE
[In-Person Event] CHAOSScon Europe 2022

### ISSUE THREAD

**Issue by ElizabethN** [badging/event-diversity-and-inclusion#188]
# In-Person Event Submission

## Requirements

- Event Name: CHAOSScon EU 2022
- Link to the Event Website: https://chaoss.community/chaosscon-2022-eu/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Registration happens through the main registration for the Linux Foundation's Open Source Summit EU. Here, an attendee will be asked about any special needs, as well as these four demographic questions: Do you identify as a person of color? Do you identify as part of the LGBTQIA+ Community?  What gender do you identify with? How old are you (range)?
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions have an opt-out answer. As well, even after opting in, an attendee can ask for their demographic information to be removed at any time by emailing privacy@linuxfoundation.org. 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` This is not an option on the LF registration page.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` The LF offers a feedback survey, and CHAOSS will ask for additional feedback specific to our conference. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes. The LF uses survey responses to improve attendees', speakers, and volunteers experiences. As well, CHAOSS has improved DEI at this event based on previous year's events. An example is here: https://github.com/chaoss/community/issues/291
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes. The CHAOSS team plans to send a follow up survey to attendees, speakers, and volunteers. Last year's survey is here (https://docs.google.com/forms/d/e/1FAIpQLSd6kzyyafJRTSa1D_xEH_T4tICbSJ-24j0dqsOVvlmOsLZwcw/viewform) but we may iterate on that for this year. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` This information is provided by the LF on this page: https://events.linuxfoundation.org/open-source-summit-europe/attend/diversity-inclusion/.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Yes. Attendees are encouraged to email events@linuxfoundation.org with specific feedback and suggestions for future events.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes. CHAOSS slides will be available on our website, and talks will be available on our YouTube channel. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes. The LF posts the Code of Conduct at the venue, and CHAOSScon participants are directed to adhere to this Code of Conduct.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/about/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` The LF provides Diversity and Need-Based Scholarships. The LF also provides support in terms of travel funding for those who are in need. As well, CHAOSScon will be livestreamed for free to virtual participants.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` For the Diversity Scholarship, Applicants must be from a traditionally underrepresented and/or marginalized group in the technology and/or open source communities who are unable to attend without some financial assistance. Including, but not limited to: persons identifying as LGBTQIA+, women, persons of color, and/or persons with disabilities. For the Need-Based Scholarship, Individuals who apply should be active members of the open source community who are unable to attend for financial reasons and are unable to get funding from their companies.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/open-source-summit-europe/attend/scholarships/#scholarships and https://events.linuxfoundation.org/open-source-summit-europe/attend/travel-funding/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes. The LF provides complimentary on-site childcare. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` Nursing room will be available on-site at the venue. As well, the LF has planned family friendly social events, including a boat tour, 5K Fun Run, and a tea bus tour. The CHAOSScon team also plans to host an informal family friendly outing after CHAOSScon, but the details are to be determined. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` Childcare: https://events.linuxfoundation.org/open-source-summit-europe/attend/child-care/. Family friendly social events: https://events.linuxfoundation.org/open-source-summit-europe/features/onsite-activities/

**Comment by kaxada** [comment]
@ElizabethN I see that in the registration process, there is no `text box to input variable demographics such as Gender, Race, or Ethnicity` but it provides for drop downs as shown in the clipped image below. Doesn't that suffice for `text input`?

![image](https://user-images.githubusercontent.com/54111299/188297767-1d14e7cf-11f2-4b62-9680-8a2ec906ba6b.png)

**Comment by kaxada** [comment]
@ElizabethN Does this suffice for the Diversity Acess Tickets?
![image](https://user-images.githubusercontent.com/54111299/188298054-bef7350e-8355-4577-873f-dc8710c20b3a.png)

**Comment by Anita-ihuman** [comment]
@ElizabethN I think CHAOSScon should reference Family friendliness and Diversity access ticket information derived from the open source summit website on the CHAOSScon site for "Findability".

**Comment by ElizabethN** [comment]
>...there is no text box to input variable demographics such as Gender, Race, or Ethnicity but it provides for drop downs as shown in the clipped image below. Doesn't that suffice for text input?

@kaxada Great question! I think this specifically refers to an open format text box that allows the registrant to express themselves in their own words instead of picking from a set of options. So in that regard, we don't have that capability in the registration form. 

>Does this suffice for the Diversity Acess Tickets?

@kaxada Hmm, that might help as supporting documentation but more specific information can be found here: https://events.linuxfoundation.org/open-source-summit-europe/attend/scholarships/#scholarships. I think the LF calls these "scholarships" instead of "Diversity Access Tickets"

>@ElizabethN I think CHAOSScon should reference Family friendliness and Diversity access ticket information derived from the open source summit website on the CHAOSScon site for "Findability".

@Anita-ihuman Great idea! I'll submit a PR for that. 

Thanks to both of you @kaxada and @Anita-ihuman ! :pray:

**Comment by kaxada** [comment]
@ElizabethN I am done with this review

**Comment by ElizabethN** [comment]
Thank you!
