### ISSUE TITLE
[In-Person Event] PrestoCon 2022

### ISSUE THREAD

**Issue by stearnsbridget** [badging/event-diversity-and-inclusion#192]
# In-Person Event Submission

## Requirements

- Event Name: PrestoCon 2022
- Link to the Event Website: https://events.linuxfoundation.org/prestocon/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask for gender, age, first time attendance, disabilities, etc. on our registration forum. 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` The Linux Foundation uses the information you provide to us to contact you about upcoming events. You may unsubscribe from these communications at any time. For more information, please see our Privacy Policy.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` What gender do you identify with? Including: Woman, Man, Other, Prefer Not to identify 

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` https://events.linuxfoundation.org/prestocon/contact-us/
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, we use a SWOT document to ensure feedback from attendees from previous events and use that in creating each upcoming event to be more inclusive. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes. See question above. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Attendees are able to contact the event team email for accessibility at the event and we will also be including a FAQ page on the website shortly. 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Yes, after the event a survey goes out to all attendees for feedback. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes. The website will be live through the end and after the end of the event. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/prestocon/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` By enabling welcome language and ensuring all family dynamics are welcome. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by djmitche** [comment]
Thanks for applying for a badge!  This is looking good so far.. just a few questions for the remaining items:

Regarding measuring demographics:
 * The "Other" category for gender does not allow text entry, just selecting "other"
 * The opt-out is an opt-out from communication (I do appreciate that it's actually opt-in!) rather than from the demographics collection.

Regarding inclusive experience:
 * The link for feedback is to a contact-us page.  The expectation is that there is a system for gathering feedback uniformly from attendees, such as a post-event survey.

Regarding CoC:
 * The link on https://events.linuxfoundation.org/prestocon/attend/diversity-inclusion/ goes to ArgoCon's CoC, instead of the expected https://events.linuxfoundation.org/prestocon/attend/code-of-conduct/.  That page seems to have similar content, but different contact/reporting information.  Otherwise, this CoC is great!

Regarding family friendliness:
 * I can't find any information about child-care on the website.

Finally, I began the registration process under `dustin@v.igoro.us` using test values.  If that's left a permanent record anywhere, please feel free (or, if I'll end up getting contacted, please feel encouraged!) to delete it.

**Comment by ElizabethN** [comment]
@stearnsbridget hiiiiii! :wave: Just making sure you saw the above questions and comments from @djmitche ☺️

**Comment by stearnsbridget** [comment]
Hi Elizabeth!

Yes! Thank you for your patience on my delay. Since this is my first time
applying for the badge, forgive my extra clarifying questions!

See below for my answers in purple:

Regarding measuring demographics:

   - The "Other" category for gender does not allow text entry, just
   selecting "other"
   - The opt-out is an opt-out from communication (I do appreciate that
   it's actually opt-in!) rather than from the demographics collection.
      - How does keeping this as is affect the badging process?

Regarding inclusive experience:

   - The link for feedback is to a contact-us page. The expectation is that
   there is a system for gathering feedback uniformly from attendees, such as
   a post-event survey.
      - There will be a post event survey that will be sent out through
      survey monkey once the event is complete in December.

Regarding CoC:

   - The link on
   https://events.linuxfoundation.org/prestocon/attend/diversity-inclusion/
goes
   to ArgoCon's CoC, instead of the expected
   https://events.linuxfoundation.org/prestocon/attend/code-of-conduct/.
   That page seems to have similar content, but different contact/reporting
   information. Otherwise, this CoC is great!
      - Thank you for catching this. This has been updated!

Regarding family friendliness:

   - I can't find any information about child-care on the website.
      - I'm not 100% sure that we will have child-care at this event. How
      does not having this affect things?


Thank you, thank you! Appreciate the follow up :)

Best,
Bridget

Bridget Stearns (she/her/hers)
Senior Event Coordinator, The Linux Foundation
<https://events.linuxfoundation.org/>

*PHONE | *+1 609.289.1868
*EMAIL | ***@***.***
*WORKING HOURS | *8:00 AM - 5:00 PM (EASTERN TIME - US)
*At The Linux Foundation, we work flexibly. While it suits me to email now,
I do not expect a response or action outside of your own working hours. *
*Upcoming Out of Office:*
*October 7 - 11: **PTO*

**Comment by djmitche** [comment]
Thanks!  I've updated the checkboxes for the post-event survey.  As for the other two, it seems they're not the case, so I'll leave the checkboxes un-checked.  In general, part of the purpose of my review is to verify assertions made here are also visible to prospective attendees/speakers -- for example, if the event provides child care but attendees don't know about it, then it doesn't really help sole-caretaker visitors to decide they can attend!

I know it's a lot of hard work to put all of these things into an event, and I appreciate that everything is a work in progress!  I believe that the program can issue a "partial" badge as things stand, but I'll let @ElizabethN give the authoritative answer.

**Comment by oma131** [comment]
@stearnsbridget thanks for applying for an event badge, the outline of your event so far has been amazing!
In the Family friendliness section, I think it would be useful to state on your event website the type of experience attendees will have as regards family friendliness. 

@ElizabethN I'm done with the review

**Comment by stearnsbridget** [comment]
Hi all,

Thank you for the work you have put into this so far!

As a point of reference, if I remove the family friendliness aspect from
the application will we not qualify for a badge? Trying to come up with my
next move here as now I don't believe this event will have family friendly
activities.

Let me know!

Best,
Bridget

Bridget Stearns (she/her/hers)
Senior Event Coordinator, The Linux Foundation
<https://events.linuxfoundation.org/>

*PHONE | *+1 609.289.1868
*EMAIL | ***@***.***
*WORKING HOURS | *8:00 AM - 5:00 PM (EASTERN TIME - US)
*At The Linux Foundation, we work flexibly. While it suits me to email now,
I do not expect a response or action outside of your own working hours. *
*Upcoming Out of Office:*
*October 7 - 11: **PTO*

**Comment by djmitche** [comment]
Hopefully @ElizabethN can answer that authoritatively :)

**Comment by ElizabethN** [comment]
Hi @djmitche @oma131 @stearnsbridget! 

Just a point of note regarding the Family Friendliness section, a nursing room is provided on-site according to the [FAQ page under "Diversity and Inclusion"](https://events.linuxfoundation.org/prestocon/attend/faq/#diversity-and-inclusion) so maybe that could be included under the main Diversity and Inclusion Page? This would absolutely count as an effort to include families. 👍

**Comment by djmitche** [comment]
Oh, I missed that - that's great!  I've checked the boxes.  But, as a note for next time, it might make sense to centralize that information on the D&I page (https://events.linuxfoundation.org/prestocon/attend/diversity-inclusion/)!
