### ISSUE TITLE
Attention Badgers, Please Read! A few tweaks, and feedback requested

### ISSUE THREAD

**Issue by ElizabethN** [badging/event-diversity-and-inclusion#193]
Hello everyone and sorry for the out-of-the-blue mention! 

Thanks to the amazing work of @kaxada during GSoC you will see some tweaks to our badging process from your side. The Badging Bot is stepping in to make things a little easier for you.

###  **Change # 1**: 
You will be given a chance to accept or decline a review that has been assigned to you. We need you to **respond to this prompt within 24 hours** or the bot will ping a maintainer to re-assign. 

### **Change # 2**:
Your checklist will look a little different, as the applicants' information will be copied inline with your checklist. This will keep you from having to scroll up and down until the end of days. 

### Future Changes:
These are the only changes that affect you right at this moment, but if you're curious we are also working on:
- auto updating the README for new badges assigned
- auto assigning Badgers
- potential Slack integration

**Please use this issue for feedback on the new changes** or you can email me at <Elizabeth -at- chaoss -dot- community> with your thoughts. And as always thank you for being so awesome! 

![b3bc4be9616995543fa2917aab0ae1de](https://user-images.githubusercontent.com/57594/191272916-2305b4e0-7ad1-42cf-9c49-781a67f75335.jpeg)

cc
@kaxada
@delight
@oma131
@kristiprogri
@Ruth-ikegah
@tetris4
@Dhruv-Sachdev1313
@Anita-ihuman
@Gemarodri
@djmitche
@KafayahL
@brownie
@germonprez
@spotz
@xiaoya-Esther
@geekygirldawn
@klumb
@thecraftman
@bistaastha

**Comment by kaxada** [comment]
Thank you @ElizabethN for this update. I almost asked how effective we could make this communication for the updates.

Just to clarify, the README can now be automatically updated once you issue the command `/end`. But the command is only effective for maintainers.

**Comment by ElizabethN** [comment]
Also, we are looking to grow our team of Badgers, so if you know someone who might be interested in joining this team, please let them know there is a meeting on October 26 at 11:00 am US Central/Chicago time for orientation. Details can be found here: https://chaoss.community/participate. Thanks everyone!

**Comment by ElizabethN** [comment]
I'm closing this issue, because we've added these things to the documentation. Thanks everyone! :heart:
