### ISSUE TITLE
Badge List

### ISSUE THREAD

**Issue by germonprez** [badging/event-diversity-and-inclusion#194]
Hi @ElizabethN and @kaxada 

The awarded badge list seems a bit off. I think there are events that have received badges (i.e., OSS Europe) that are not listed along with some tests that are listed.

**Comment by kaxada** [comment]
@ElizabethN informed me that there are some events she hadn't yet entered manually before the automation was made. 

Please provide the link(s) to the event review(s) (issue) so that that we can add them

**Comment by germonprez** [comment]
https://github.com/badging/event-diversity-and-inclusion/issues/187
https://github.com/badging/event-diversity-and-inclusion/issues/184
https://github.com/badging/event-diversity-and-inclusion/issues/183
https://github.com/badging/event-diversity-and-inclusion/issues/181
https://github.com/badging/event-diversity-and-inclusion/issues/179
https://github.com/badging/event-diversity-and-inclusion/issues/178
https://github.com/badging/event-diversity-and-inclusion/issues/177
https://github.com/badging/event-diversity-and-inclusion/issues/176
