### ISSUE TITLE
[In-Person Event] The Linux Foundation Member Summit

### ISSUE THREAD

**Issue by mgoytia04** [badging/event-diversity-and-inclusion#195]
# In-Person Event Submission

## Requirements

- Event Name: The Linux Foundation Member Summit
- Link to the Event Website: https://events.linuxfoundation.org/lf-member-summit/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendee to ensure they can enjoy the event to the fullest:  Do you have a disability that we should be mindful of as we try to accommodate everyone for this event?  Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s).  Do you identify as a person of color?  What gender do you identify with?  How old are you? (Please note, none of these questions are required, they are optional for attendees to fill out)
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the attendee information page we provide a list of pronouns to choose from but also provide a space for text input if none of the options provided apply.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers and attendees where we ask the following question:”Is there anything you'd like to share with us regarding your experience about this virtual event and/or do you have additional feedback on how we can improve our virtual events in the future?.”   We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's post-event survey was considered when planning 2022. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Under the Diversity and Inclusion page on the event website there is a section that speaks to venue accessibility. (https://events.linuxfoundation.org/lf-member-summit/attend/diversity-inclusion/#onsite-resources) 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, it will be made available at the conclusion of the event via YouTube to all at no charge.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the onsite Diversity & Inclusion resources flyer. This flyer has all DEI-related resources, as well as event team members they can contact should they need anything onsite. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/lf-member-summit/attend/code-of-conduct/ 

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We offer travel funding to our event. There is no limit to the number of travel fundings that we offer for this event. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The Linux Foundation’s Travel Fund is intended to enable open source developers and community members to attend events that they would otherwise be unable to attend due to a lack of funding. We place an emphasis on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status. If you work for a company that has the ability to fund your travel, we ask that you not apply, to save funds for those that need it.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/lf-member-summit/attend/travel-funding/  

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, we are offering complimentary onsite child care this year.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We offer our attendees a private nursing room that they can access throughout the event, gender-neutral restrooms, pronoun stickers, and have ADA-accessible transportation provided to any offsite venues.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/lf-member-summit/attend/diversity-inclusion/#general

**Comment by Victorybrown** [comment]
@ElizabethN I'm done with my review.

**Comment by Delight362** [comment]
Will be available

**Comment by Delight362** [comment]
Thank you for applying for this badge @mgoytia04. @ElizabethN am done with my review.

**Comment by ElizabethN** [comment]
@mgoytia04 I am going to go ahead and issue this badge since it doesn't get much better than :100: 😄 Keep up the awesome work!
