### ISSUE TITLE
[In-Person Event] SODACON 2022

### ISSUE THREAD

**Issue by stearnsbridget** [badging/event-diversity-and-inclusion#205]
# In-Person Event Submission

## Requirements

- Event Name: SODACON 2022
- Link to the Event Website: https://events.linuxfoundation.org/sodacon-japan/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` On our Call for Proposals page, we require all speakers to adhere to the Code of Conduct and encourage that they We also highly recommend that speakers take our online Inclusive Speaker Orientation Course. Additionally, we do not accept submissions with all-male panels in an effort to increase speaker diversity.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` Attendees and speakers are able to select the answer "Prefer not to answer" for questions including: "Do you identify as a person of color?", "Do you identify as part of the LGBTQIA+ Community?", "What gender do you identify with?", "How old are you?"
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` N/A

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` After every event, we send a post-event survey to all attendees that asks questions about their experiences. In that survey, we also have an open-ended section where they can tell us about any element of the event that we could do better on. Also, on our D&I page, we have language that specifically states "If you have ideas on how we can create a more inclusive event, please do not hesitate to let us know" with the contact information for the event manager.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, there was a post-event meeting and the event managers went over aspects to improve DEI at the in-person event this year. This included updating the registration form with more D+I questions and striving to have more diversity in speakers.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we always try to incorporate attendee feedback in surveys to improve future events.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We have a D+I page on the website and it lists on-site resources and to have any questions be directed to the event manager. 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Yes, after the event a survey goes out to all attendees for feedback. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes. The website will be live through the end and after the end of the event. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/sodacon-japan/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` At this time we are not providing diversity access tickets, but it may be implemented in the coming weeks.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, this is a co-located event with OSS Japan which means all attendees will have access to childcare facilities. More information can be found here: https://events.linuxfoundation.org/open-source-summit-japan/attend/child-care/
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` There will also be a nursing room available for attendees that will be able to access through the registration desk. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/open-source-summit-japan/attend/child-care/

**Comment by ElizabethN** [comment]
@Victorybrown just making sure you saw that ping :heart:

Also @djmitche have you had a chance to review this yet? There may be an issue with checkboxes not checking properly so let me know if you have time to take a look at this. Thank you!

**Comment by djmitche** [comment]
Oh, sorry!  I wasn't really thinking ahead, and I was away for a long weekend.  I'm back now :)

**Comment by djmitche** [comment]
For session accessibility, I don't see anything about the sessions being available afterward (recorded), so I didn't check that box.

I'm glad to hear the conf has childcare and nursing rooms available!  I didn't check the family-friendliness boxes because  that information is not discoverable on the website.  Perhaps it's worth adding it to the D+I page?  Maybe something like

> This event is co-located with _OSS Japan_, which provides attendees with access to additional resources such as child care and a nursing room.

Otherwise, I think I've checked all of the boxes I can at the moment.

**Comment by ElizabethN** [comment]
@stearnsbridget would you be able to shed some light on @djmitche's suggestions?

**Comment by stearnsbridget** [comment]
Hi Dustin (and Elizabeth),

Thanks for flagging these. I added the line for D&I under Venue
Accessibility to include that this event is in association with OSSJ. I
also just got confirmation that the sessions will be recorded and added to
the project's YouTube channel after the event.

I am finishing up a FAQ page that will answer a lot of questions that will
be centrally located that I plan to have finished and up by early next
week, can we put a pin in this one until I have that finalized? I think
that will be best for you all to review and I will keep that in mind moving
forward.

I will circle back with you as soon as I can. Thank you!



Best,
Bridget

Bridget Stearns (she/her/hers)
Senior Event Coordinator, The Linux Foundation
<https://events.linuxfoundation.org/>

*PHONE | *+1 609.289.1868
*EMAIL | ***@***.***
*WORKING HOURS | *8:00 AM - 5:00 PM (EASTERN TIME - US)
*At The Linux Foundation, we work flexibly. While it suits me to email now,
I do not expect a response or action outside of your own working hours. *
*Upcoming Out of Office:*
*October 21 - 28: KubeCon + CloudNativeCon North America- Delay in
response *

**Comment by djmitche** [comment]
Awesome, that sounds great!

**Comment by Victorybrown** [comment]
@ElizabethN i just finished my review. @stearnsbridget would you update us when the Diversity tickets are made available, so we can update the checklist.

**Comment by stearnsbridget** [comment]
Hello all!

Hoping you are having a lovely week, I have been trying to enjoy my time
here in Detroit :). The FAQ page for SODACON
<https://events.linuxfoundation.org/sodacon-japan/attend/faq/> is uploaded
and hopefully will answer some of the final questions that we have in order
for the badging process. Please see here for the link and let me know
what questions I can answer for you!

All the best,
Bridget

Bridget Stearns (she/her/hers)
Senior Event Coordinator, The Linux Foundation
<https://events.linuxfoundation.org/>

*PHONE | *+1 609.289.1868
*EMAIL | ***@***.***
*WORKING HOURS | *8:00 AM - 5:00 PM (EASTERN TIME - US)
*At The Linux Foundation, we work flexibly. While it suits me to email now,
I do not expect a response or action outside of your own working hours. *
*Upcoming Out of Office:*
*October 21 - 28: KubeCon + CloudNativeCon North America- Delay in
response *

**Comment by djmitche** [comment]
Awesome, my review is updated!

**Comment by stearnsbridget** [comment]
Hello!

I just wanted to follow up to see where SODACON stood for the badging
process? Thank you!

Best,
Bridget

Bridget Stearns (she/her/hers)
Senior Event Coordinator, The Linux Foundation
<https://events.linuxfoundation.org/>

*PHONE | *+1 609.289.1868
*EMAIL | ***@***.***
*WORKING HOURS | *8:00 AM - 5:00 PM (EASTERN TIME - US)
*At The Linux Foundation, we work flexibly. While it suits me to email now,
I do not expect a response or action outside of your own working hours. *
*Upcoming Out of Office:*
*November 4: PTO - No response*
*November 11: Veteran's Day - LF Holiday - No response*

**Comment by Ruth-ikegah** [comment]
Hi @stearnsbridget, sorry for the delay! My name is Ruth Ikegah, a maintainer at Event badging Project.  I will go ahead to initiate the result process.

**Comment by Ruth-ikegah** [comment]
Hi @stearnsbridget, thanks for applying for a DEI event badge, congratulations on your Silver Badge. Please let me know if you have any questions or feedback.

**Comment by stearnsbridget** [comment]
Thank you!

Best,
Bridget

Bridget Stearns (she/her/hers)
Senior Event Coordinator, The Linux Foundation
<https://events.linuxfoundation.org/>

*PHONE | *+1 609.289.1868
*EMAIL | ***@***.***
*WORKING HOURS | *8:00 AM - 5:00 PM (EASTERN TIME - US)
*At The Linux Foundation, we work flexibly. While it suits me to email now,
I do not expect a response or action outside of your own working hours. *
*Upcoming Out of Office:*
*November 4: PTO - No response*
*November 11: Veteran's Day - LF Holiday - No response*
