### ISSUE TITLE
[In-Person Event] FOSS Backstage 2023

### ISSUE THREAD

**Issue by plainschwarz-team** [badging/event-diversity-and-inclusion#206]
# In-Person Event Submission

## Requirements

- Event Name: FOSS Backstage 2023
- Link to the Event Website: https://23.foss-backstage.de
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Event demographics for FOSS Backstage is measured primarily using our voluntary demographic survey, which is attached but not connected to the registration process (i.e. the survey is external and anonymous and not connected to the personal data entered during registration).  We have very few demographic question directly included in the registration due to privacy concerns.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` “Prefer not to answer” options are available for all demographic questions asked during the registration process.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` For example, the questions “What are your pronouns?” provides a list of pronouns including a “prefer not to answer” option), as well as an option to provide pronouns not listed in a text input field:  “My pronouns are: [text input]”

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` Feedback can be provided using our feedback survey, which will be send to every speaker, attendee and volunteer after the conference. Feedback regarding diversity, accessibility and inclusivity will be published in our annual Diversity Report, which is available for everyone on our website. Last year's report is available on our website at: https://23.foss-backstage.de/wp-content/uploads/2022/09/FOSS-Backstage-2022-Diversity-report.pdf
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes. For example, at FOSS Backstage 2022 we got feedback that holding the conference at the end of the week was difficult for some due to religious holidays. As a consequence, FOSS Backstage 2023 will take place at the beginning of the week and we checked if the conference date is coinciding with religious holidays.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes. As mentioned above, we will collect feedback using our feedback survey. Feedback regarding diversity, accessibility and inclusivity will be published in our Diversity Report. Feedback will also be discussed after the event within the team.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` By visiting the pages on diversity & inclusivity (https://23.foss-backstage.de/diversity/) and on accessibility (https://23.foss-backstage.de/accessibility/) on our website.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Attendees and speakers can suggest future improvements for the event in our annual feedback survey or send feedback to a dedicated Email address, which is linked on our Diversity and Accessibility pages on our website, and will also be linked at our online event platform.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Our website will be available after the event. Our online platform Venueless is also available for a limited time after the event. The talks and sessions will be made available for everyone on our YouTube-Channel after the event. (https://www.youtube.com/c/PlainSchwarzUG/playlists?view=50&sort=dd&shelf_id=4)

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` The code of conduct is posted on our website. Attendees and speaker must tick a checkbox at registration that they have read and consent to our code of conduct. The code of conduct will be published on our online event platform and in physical form at the entrance to our venue in Berlin.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://23.foss-backstage.de/code-of-conduct/ 

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We provide Diversity Online-Tickets and Diversity Onsite-Tickets. Both tickets are fully sponsored (i.e. free) and provide full access either to our online or onsite event.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity Tickets are available to people from underrepresented groups within the FOSS Backstage community. This includes, but is not limited to: women, people of colour, LGBTQIA people, disabled people, and people facing economic or social hardships. Please note that there is no "qualification process" for Diversity Tickets, and one can simply order a Diversity Ticket without being vetted, since we as organizers are unable to judge if someone is actually a member of a underrepresented group, and this would create all kinds of obvious problems. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://23.foss-backstage.de/diversity/ 

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Due to budgetary constraints, we cannot provide childcare facilities at FOSS Backstage.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by Anita-ihuman** [comment]
Hello @plainschwarz-team Thank you for applying for a CHAOSS DEI Badge  for your event.
My observation is, I noticed that the event does not provide any facilities that support family friendliness, but I suppose this is all as a result of the budgetary constraints. 

Have a successful with your event!
@ElizabethN I am done with my review

**Comment by ElizabethN** [comment]
@Anita-ihuman it looks like your checkboxes did not get checked for some reason. Can you take a look again? Thank you so much!

**Comment by ElizabethN** [comment]
@KafayahL have you had a chance to look at this yet? it looks like there may be an issue with checkboxes not getting checked for some reason, so would you mind just verifying your review? Thank you!

**Comment by ElizabethN** [comment]
@Anita-ihuman it looks like that's been resolved when I reloaded the page. Maybe it's the GitHub interface had a glitch, I don't know. Sorry for the confusion! 😆 It's all good now.

**Comment by ElizabethN** [comment]
@plainschwarz-team :wave: Hiiiii! If you're ok with this badge we will go ahead and issue it. Let us know if there's anything you'd like to discuss further :blush:

**Comment by plainschwarz-team** [comment]
Hi @ElizabethN! Sure, we're happy with the result :)

Thanks @KafayahL and @Anita-ihuman for your review!

**Comment by plainschwarz-team** [comment]
Hey @ElizabethN, sorry to bug you, but could you issue the badge and close this issue? :)

**Comment by Ruth-ikegah** [comment]
Sure @plainschwarz-team 

My name is Ruth and I am one of the maintainers, issuing the badge right away, thanks for applying again!

**Comment by Ruth-ikegah** [comment]
Hi @plainschwarz-team, congratulations on your Gold badge!

**Comment by plainschwarz-team** [comment]
Thank you @Ruth-ikegah!
