### ISSUE TITLE
[In-Person Event] TESTING EVENT ElizabethCon 2023

### ISSUE THREAD

**Issue by ElizabethN** [badging/event-diversity-and-inclusion#208]
# In-Person Event Submission

## Requirements

- Event Name: TESTING EVENT ElizabethCon 2023
- Link to the Event Website: elizabethcon2023.com
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We survey speakers when they register for their demographic information.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` registration page is here: xyz.com
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` registration page is here: xyz.com

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` Feedback page is here: xyz.com
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` yes, here's an example. blah blah balh
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` yes here's an example blah blah blah
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` accesibilty page is here: page.com
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` yes, here's the process. blah
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` yes, link to you tube recordings is here: blah

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` yes
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` codeofconduct.com

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` info is here:
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` infor is here
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` blah.com 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` yes 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` fun events and activities
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` links to stuff.com

**Comment by ElizabethN** [comment]
@ElizabethN I am done with my review.

**Comment by Ruth-ikegah** [comment]
@ElizabethN I am done with my review! Thanks Elizabeth for applying for a badge

**Comment by ElizabethN** [comment]
Hey event organizer @ElizabethN are you ok with this badge? (I'm assuming so because it is 100%)
