### ISSUE TITLE
Create Wiki Page for Event Badging

### ISSUE THREAD

**Issue by Ruth-ikegah** [badging/event-diversity-and-inclusion#215]
Problem: @oma131 created a document to help explain Event Badging to new contributors, which currently lives on google docs on this [link](https://docs.google.com/document/d/1k1QKSWmysFQjX6_ho77J2fJscK1tKVNXRqSsWo0Gfww/edit#)

Solution: Use the content in the google doc to create wiki pages following the section structure.

Check out this resource to help you understand setting up a wiki page: https://gist.github.com/omaraboumrad/35654da0a376c57a2e0ab4d92ad0c339

**Comment by activus-d** [comment]
@Ruth-ikegah I would like to take on this task.

**Comment by Ruth-ikegah** [comment]
sure! assigned it to you now @activus-d

**Comment by activus-d** [comment]
@Ruth-ikegah the task has been completed. [DEI Badging wiki page](https://github.com/activus-d/event-diversity-and-inclusion/wiki)

**Comment by Ruth-ikegah** [comment]
Added here @activus-d : https://github.com/badging/event-diversity-and-inclusion/wiki

Thank you for contributing!
