### ISSUE TITLE
[In-Person Event] Automotive Grade Linux All Member Meeting Spring 2023

### ISSUE THREAD

**Issue by natannefine** [badging/event-diversity-and-inclusion#216]
# In-Person Event Submission

## Requirements

- Event Name: Automotive Grade Linux All Member Meeting Spring 2023
- Link to the Event Website: https://events.linuxfoundation.org/agl-amm/
- Are you an organizer of this event? Yes, Event Planner

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendees onsite to ensure they can enjoy the event to the fullest: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s). Do you identify as a person of color? What gender do you identify with? How old are you? (Please note, none of these questions are required, they are optional for attendees to fill out) 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the attendee information page we provide a list of pronouns to chose from but also provide a space for text input if none of the options provided apply.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers and attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's post-event survey was considered when planning the next event.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Under the Diversity and Inclusion page on the event website there is a section that speaks to venue accessibility.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We send out a post-event survey to all speakers where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` No, this event will not be recorded since it is for members for AGL.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/agl-amm/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We do not offer scholarships to this event as it is a free event. However, it is for member companies of Automotive Grade Linux. As long as the attendee is affiliated with the company they can join the event.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Affiliated with member company.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/agl-amm/register/  

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` No
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by ElizabethN** [comment]
@kaxada is there a workaround for the bot not populating the checklist? Should I just copy and paste?

**Comment by LamiWilliams** [comment]
Yes, I am @kaxada 
I can't seem to click on the "yes" option

**Comment by kaxada** [comment]
hey @adeyinkaoresanya and @LamiWilliams how is this review going? Do you need some help?

**Comment by LamiWilliams** [comment]
> hey @adeyinkaoresanya and @LamiWilliams how is this review going? Do you need some help?

Hi @kaxada ... I have been able to review most of the metrics, save for some that I need the organiser's help with. I'll mention it to them immediately

**Comment by adeyinkaoresanya** [comment]
> hey @adeyinkaoresanya and @LamiWilliams how is this review going? Do you need some help?

Hey @kaxada Yes I need help. Still unable to click on the checklist.

**Comment by LamiWilliams** [comment]
Hi @natannefine 

I encountered an issue with getting into the registration page; my IP address was blocked. Could you direct me on how this can be resolved? Thanks!

**Comment by ElizabethN** [comment]
cc @kaxada for assistance with checking the checklist as mentioned above. Thanks everyone, and thanks @natannefine for your help!

**Comment by ElizabethN** [comment]
It looks like we have sorted out the checklist, so I'm going to go ahead and run the result

**Comment by ElizabethN** [comment]
@natannefine are you satisfied with this badge? If you'd like to make any adjustments to your application before we issue the badge let us know as soon as possible. We are happy to continue the conversation and support you any way we can :blush: 🙌 . Let us know how you'd like to move forward. 🏃‍♀️

**Comment by natannefine** [comment]
Hi @ElizabethN ! What steps could we do to help us get closer to the Gold Badge?

**Comment by natannefine** [comment]
Hi Elizabeth,

Thanks for the follow up.
I don't think we will be offering those options that you suggested.

As for the videos - we won't record this event since it's a Member Meeting
only.

Thanks!

**Comment by ElizabethN** [comment]
@kaxada hmm it doesn't look like the badge is getting issued properly. Would you be able to take a look at that?

**Comment by natannefine** [comment]
Hello! We will now be live-streaming keynotes and record sessions to post
on YouTube after. Will that get us the gold badge now?

**Comment by ElizabethN** [comment]
@natannefine you have earned a Gold Badge! I'm going to assume you are ok with this badge so I will go ahead and issue it. Here is the code you can use to post your badge wherever you like. Thanks again for being a part of the process and best of luck with your event! :rocket: ✨
