### ISSUE TITLE
[In-Person Event] State of Open Conference 2023

### ISSUE THREAD

**Issue by nvibert** [badging/event-diversity-and-inclusion#223]
# In-Person Event Submission

## Requirements

- Event Name: State of Open Conference 2023
- Link to the Event Website: https://stateofopencon.com/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During registration, attendees are asked about their gender, ethnicity and whether they identify as neurodiverse.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` Attendees have the option to select “Prefer not to say” when asked about their gender, ethnicity or whether they consider themselves neurodiverse.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` There’s no text input box in the Event Registration page.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` The event feedback page is not yet available but, following the event, a post-event survey to all attendees where we ask the following question: “Diversity, Equity and Inclusion are key values of the OpenUK and we hope the sense of “belonging” was reflected during the event. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` It’s a newly formed conference and therefore there isn’t feedback from previous events but the organizational team has experience running and participating in other technological events. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` The event team plans to record feedback from events in a feedback form but attendees will be also encouraged to submit feedback to the event team during the event.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` During registration, attendees are asked whether they have any accessibility needs that can be accommodated to help them participate in the event.   The venue itself was selected because of its accessibility facilities - parking facilities, disabled toilet facilities, induction loops, etc… More details can be found on the venue’s website (https://qeiicentre.london/).
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. During registration, we also ask the attendees whether "they would say that their day-to-day activities are limited because of a health problem or disability which has lasted, or is expected to last, at least 12 months?".
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, all the sessions will be streamed live, recorded and posted on YouTube afterwards.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` The code of conduct will be printed and available at the venue ; on large displays, on each floor of the venue. The code of conduct will also be linked on event emails and also on the event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://openuk.uk/wp-content/uploads/2020/08/Code-of-respect-Final-Aug-20.pdf

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` There are multiple diversity access tickets available. The price of the conference has overall been heavily discounted for a conference of that size, to encourage a more diverse audience to attend the event.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` To be published shortly but the focus will be the funding will be primarily on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` To be provided shortly 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` A creche will be available for attendees and speakers. During registration, attendees are asked whether they would require the use of a creche.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` A nursing room will also be available on the 4th floor of the venue. Even a "Doggy Day Care" will be available!
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://stateofopencon.com/delegate-experience/

**Comment by Anita-ihuman** [comment]
Hey @nvibert,

Thanks for applying for a DEI badge for your Event.
After reviewing  this, here are my feedbacks

- I did not see any provision for attentees and speakers to inquire if accomodations are available and make suggestions for future accomodations at events.
- Code of conduct is barely visible where it is located(at the bottom in small text)
- Also I did not noticed any venue for reporting violation of COC 
- I also noticed that the event does not also have provision for Diversity access tickets or are there plans to include this soon?

**Comment by nvibert** [comment]
Thanks for the feedback @Anita-ihuman - much appreciated. I will get back to you shortly on these points.

**Comment by Nene-S** [comment]
Hi @nvibert 
Thanks for applying for a DEI badge
Here is my suggestion after reviewing

 * I suggest that the Code of conduct and support for victims of inappropriate behavior should be customized to suit the purpose/need of the event.

**Comment by nvibert** [comment]
Thanks @Nene-S and @Anita-ihuman 

We will move our Code of Respect to the top to make it more visible. Our Code of Respect is based on the [Contributor Covenant Code of Conducti](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and includes an email address to use to report any violation of our code of conduct. It's applicable for all our behaviour of anyone involved in OpenUK events - whether online and on-site events. If you recommend we have a separate Code of Conduct for the event, please let me know.

With regards to the access tickets, we are offering them to volunteers first but what is not used by that volunteering community will be shared publicly, with the intention to offer them first to applicants from historically underrepresented or untapped groups and/or those of lower socioeconomic status.
But it's on us to publish this information on our website, which we hope to do in the coming weeks.

Thanks again for your patience.

**Comment by Anita-ihuman** [comment]
@nvibert There is no need to draft a new code of conduct if it similar to that of OpenUK events. Making it more visible should do. Looking forward to seeing the access tickets information on the website soon. Goodluck with the event
@Ruth-ikegah I am done with my review.

**Comment by nvibert** [comment]
Many thanks @Anita-ihuman @Nene-S @Ruth-ikegah 

We have updated our website to make our code of conduct more visible (you can see it now - it's at the top of the page).

On the community/access tickets, we will announce 100 ticket giveaway and an Open Source Job Hub Sponsored Job Board today. The Job Board will be hosted throughout the conference.

Would it be possible to receive a badge for our upcoming event?

**Comment by Anita-ihuman** [comment]
@nvibert Thank you for taking time work on the feedback provided. 

@Ruth-ikegah I am done with my review

**Comment by ElizabethN** [comment]
@nvibert thank you so much for letting us know about your changes! That's awesome!! 

@Nene-S would you be able to take a second look at this application now that changes have been made?

**Comment by ElizabethN** [comment]
@Nene-S I will ping you on Slack just in case you have notifications off :blush:

**Comment by Nene-S** [comment]
> @Nene-S I will ping you on Slack just in case you have notifications off 😊

my apologies @ElizabethN, Indeed I had my notifications turned off

**Comment by Nene-S** [comment]
Thank you  @nvibert for applying and acting on the feedback provided.

@Ruth-ikegah I am done with my review

**Comment by Ruth-ikegah** [comment]
@kaxada I think the bot is having some issues, could you help check

**Comment by Ruth-ikegah** [comment]
Hi @nvibert, Thanks so much for applying for a DEI Badge! I really loved how you worked on our feedback and made these implementations. 

Thank you @Anita-ihuman and @Nene-S for your wonderful review and patience

**Comment by Ruth-ikegah** [comment]
Congratulations on your gold badge @nvibert
