### ISSUE TITLE
[In Person Event] The Linux Foundation Legal Summit

### ISSUE THREAD

**Issue by mgoytia04** [badging/event-diversity-and-inclusion#224]
# In-Person Event Submission

## Requirements

- Event Name: The Linux Foundation Legal Summit
- Link to the Event Website: https://events.linuxfoundation.org/lf-legal-summit/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendee to ensure they can enjoy the event to the fullest:  Do you have a disability that we should be mindful of as we try to accommodate everyone for this event?  Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s).  Do you identify as a person of color?  Do you identify as part of the LGBTQIA+ Community? What gender do you identify with?  How old are you? (Please note, none of these questions are required, they are optional for attendees to fill out)
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the attendee information page we provide a list of pronouns to choose from but also provide a space for text input if none of the options provided apply.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers and attendees where we ask the following question:”If you have additional feedback on how we can improve The Linux Foundation Legal Summit, please include it here.”   We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's post-event survey was considered when planning 2023.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Under the Diversity and Inclusion page on the event website there is a section that speaks to venue accessibility. (https://events.linuxfoundation.org/lf-legal-summit/attend/diversity-inclusion/#onsite-resources)
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` No

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the onsite Diversity & Inclusion resources flyer. This flyer has all DEI-related resources, as well as event team members they can contact should they need anything onsite.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/lf-legal-summit/attend/code-of-conduct/ 

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Not an offering at this time as it’s an invitation only event for member companies of The Linux Foundation.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Not an offering at this time as it’s an invitation only event for member companies of The Linux Foundation.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` Not an offering at this time as it’s an invitation only event for member companies of The Linux Foundation. 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, we are offering complimentary onsite child care this year if requested.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We offer our attendees a private nursing room that they can access throughout the event, gender-neutral restrooms, and pronoun stickers.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/lf-legal-summit/attend/diversity-inclusion/#general

**Comment by Delight362** [comment]
Yea, @ElizabethN thanks for that. am also done with my review

**Comment by Delight362** [comment]
Thanks @mgoytia04 for applying for this badge.

**Comment by mgoytia04** [comment]
Hello! I just wanted to receive an update on our CHAOSS badging and when we can expect a final award. Thank you!
