### ISSUE TITLE
Health and Safety policies a necessary consideration amid ongoing pandemic

### ISSUE THREAD

**Issue by joshsimmons** [badging/event-diversity-and-inclusion#226]
Hi folks,

I've just noticed some gold medals have been awarded to events which are failing to implement any health and safety measures, which puts everyone at risk but in particular harms and excludes people with disabilities and chronic illness, caregivers, and those who live with them.

As the author of the [Public Health Pledge](https://phpledge.com), I am working on a badging standard to assess event health and safety policies. Those policies and practices are a necessary extension of a Code of Conduct in today's environment.

I've long admired the CHAOSS project's work and regret not getting involved on this specific initiative sooner, because it seems to me no event that disproportionately excludes people with disabilities should be seen to have a gold medal on DEI.

Where should a community member like me start showing up so that these considerations have a chance of being folded into version 4 of your event badging standard?

With a mix of gratitude and concern,
Josh

**Comment by germonprez** [comment]
Hi Josh,

Thanks so much for this. We'd love to have you participate. Your insight would be amazing.

We have a badging specific meeting week 2 times per month. The next meeting is Feb 1 at 8:30am US Central
We also have a DEI working group meeting weekly. The next meeting is Feb 1 at 10am US Central.

You can also check out this page: https://chaoss.community/participate/
Both use this connection link: https://zoom.us/j/4998687533 

Both are also on Slack. Here is the invite:
https://join.slack.com/t/chaoss-workspace/shared_invite/zt-1ofsi4h00-pe_M1bm6DmInEbJTzRisPw

#badging        
#wg-diversity-inclusion

Pinging @ElizabethN and @Ruth-ikegah as well. 

Thanks again!
Matt

**Comment by joshsimmons** [comment]
Thank you so much, @germonprez. I've just joined the Slack and relevant channels, and have added both of the upcoming meetings to my calendar. I'll be there!

**Comment by joshsimmons** [comment]
In case folks want to get a sense of how we're thinking about this ahead of upcoming meetings, I figured I should share this pre-release draft standard. The biggest change between now and publication next week will be switching away from, or augmenting, the proposed "red/yellow/green" ratings in order to be inclusive of people with colorblindness.

[2023-01 PHPledge Event Badging Standard draft.pdf](https://github.com/badging/event-diversity-and-inclusion/files/10523945/2023-01.PHPledge.Event.Badging.Standard.draft.pdf)

And this is all an extension of the pledge itself, which was inspired by the Code of Conduct pledge:

> I am committed to diversity and inclusion, including people with disabilities, chronic illness, and caregivers, therefore I pledge to only participate in or organize events that have robust Health and Safety policies.
> 
> Events with in-person gatherings must meet these criteria:
> 
> 1. The event has a Health and Safety policy, and if the policy changes it is only strengthened – never weakened – between the event’s announcement and the event itself.
> 2. The event actively communicates this policy by including it on their website, in the registration flow, and speaker proposal process, discussing the policy regularly during events, and including it everywhere important announcements are shared.
> 3. The event’s policy includes active measures designed to minimize the number of participants who are infected with transmissible diseases like COVID-19, as well as mitigate transmission between participants.

Looking forward to getting oriented and working together!

**Comment by ElizabethN** [comment]
This is amazing work @joshsimmons! Looking forward to chatting with you more about how we can incorporate this into our badging initiative! 😍

**Comment by ElizabethN** [comment]
Great conversation today in the DEI Event Badging meeting - we will discuss more at the DEI Working Group

**Comment by joshsimmons** [comment]
Just leaving a note here for anybody who stumbles into this issue that the work is in progress! https://github.com/chaoss/wg-dei/issues/474

**Comment by ElizabethN** [comment]
This has finally been implemented and included in Badging 4.0! :tada: Thank you to all who worked so hard to get this completed and thank you to @joshsimmons for kicking off this discussion in the first place! :heart:

**Comment by joshsimmons** [comment]
Yay! This makes my week 🥳 Thank you all so much!
