### ISSUE TITLE
Attention Badgers! This is for you :)

### ISSUE THREAD

**Issue by ElizabethN** [badging/event-diversity-and-inclusion#227]
### :badger: Hi Badgers! (@badging/reviewers) :badger:

We want to connect with you for a few reasons:

- **First, we want to verify your Badger status**.  If you've been out of rotation for a while and you'd like to jump back in, let us know! Or it's perfectly fine if you would like to be removed from the Badger team altogether. Please [fill out this form](https://docs.google.com/forms/d/e/1FAIpQLSdyV3_R-ofEEUFFZAQkJKJIqtkR3KC3A1aMIa3rCKs_JLPiqg/viewform?pli=1) if your Badger status has changed. 
- **Second, we are missing some information from some of you**. If you could please [fill out this form ](https://docs.google.com/forms/d/e/1FAIpQLSdyV3_R-ofEEUFFZAQkJKJIqtkR3KC3A1aMIa3rCKs_JLPiqg/viewform?pli=1) and provide us with your email address so we can connect offline, that would be fantastic! (If you've already filled this out, we appreciate it! No need to fill it out again.)
- **Third, we want to schedule a monthly call with everyone**. We have some upcoming changes in the badging process we'd like you to know about, and we want to make sure you feel connected to the group. We'll be sending around a Doodle poll via email to see if there's a good time that works for most of you.

If you can react to this issue to indicate that you've seen it (and completed the form if applicable), that would be awesome! 

Thank you so much! :heart: :badger:

**Comment by Preshh0** [comment]
Seen, and filled out the form❤️.

**Comment by geekygirldawn** [comment]
I haven't really been active. If you have enough people working on this, I can be removed, but if you still need help, I'm also happy to pitch in :)

**Comment by Maryblessing** [comment]
I have also filled out the form. New, so you can let me know if you need anything else

**Comment by uoduckswtd1** [comment]
Thanks for reaching out, Elizabeth. Form completed!

~ Nicole

**Comment by tetris4** [comment]
Form completed. ☺️

**Comment by kaxada** [comment]
@ElizabethN I request that the proposed monthly call be put together with one of the DEI badging meetings instead of creating a new one

**Comment by oma131** [comment]
Form Completed☺

**Comment by xiaoya-yaya** [comment]
sorry for the delay! form completed.

**Comment by Nene-S** [comment]
form completed! my apologies for the delay

**Comment by mollydb** [comment]
Unfortunately, I do not have the time for this anymore. I appreciate you reaching out to check in. Thanks!

**Comment by lucasgonze** [comment]
I need to move on, but I really appreciate and respect the DEI badging project.

**Comment by ElizabethN** [comment]
Going to close this issue as it is stale and doesn't need to be open anymore. All our Badgers are in Slack now and that is our primary mode of connection. Thanks everyone!
