### ISSUE TITLE
[In-Person Event] Linux App Summit

### ISSUE THREAD

**Issue by sramkrishna** [badging/event-diversity-and-inclusion#242]
# In-Person Event Submission
## Requirements
- Event Name: Linux App Summit
- Link to the Event Website: https://linuxappsummit.org/
- Are you an organizer of this event? Yes - Sri Ramkrishna
## Event Demographics
- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Demographics are collected of all attendees through the registration process.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` Yes, demographic information fields are optional and can be left blank.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` Yes, gender identity and other demographic fields are text.
## Inclusive Experience at Event
    
- [ ] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We have a feedback survey that we send out after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` No. We have collected feedback but don't use it specifically to improve DEI. A challenge we face is that community members have trouble getting Visa's to attend, something we cannot fix easily.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` No. We need to develop that.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We don't explicitly provide accessibility information on our website. All questions are answered through Telegram and info@linuxappsummit.org
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` No, probably not. Not sure what this question means in the context of an in-person event.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` No, probably not. Not sure what this question means in the context of an in-person event. All recordings will be available on YouTube.
## Code of Conduct at Event
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` I don't know. I'll ask
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://linuxappsummit.org/coc/
## Diversity Access Tickets
- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Not required because the event tickets are free for everyone.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Not applicable.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` Not applicable. 
## Family Friendliness
- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes. We ask all registrants if they require childcare.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We don't explicitly have family-friendly activities at the event.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` (it's on the registration page where we ask about child care, we don't have a dedicated page for this)

**Comment by germonprez** [comment]
Thanks for your application @sramkrishna! 

@Ruth-ikegah would you be able to assign the reviewers?

**Comment by Ruth-ikegah** [comment]
> Thanks for your application @sramkrishna!
> 
> @Ruth-ikegah would you be able to assign the reviewers?

yes I just did!

**Comment by Ruth-ikegah** [comment]
Hi @sramkrishna ! Great to see you here, thanks so much for submitting an application for a badge!

Here are some comments and answers to some questions I saw on your application:

- On Inclusive experience at event: I do understand the visa situation because I have had my own share of it, but other things that fit in this category or question is platform/venue accessibility (if a virtual event, is captions available, if physical, are there sign readers), food inclusive (vegan options), experience, speaker diversity. Is there a way LAS collects feedback for these and a process for improving them in the next event?
- On future accommodation: sorry that was not clear, it means is there a way attendees can recommend for something that was not provided in the conference for future ones?

I will wait for your response and update my review accordingly!

**Comment by sramkrishna** [comment]
Some of these options we can do. Linux App Summit doesn't provide any catering so food options are up to attendees. Sign language and braille options are difficult for this conference as it doesn't raise enough money to be able to fund those kind of options. This year especially sponsorship has not been high due to uncertainty in high tech sector. But given funding we would absolutely especially if we do online talks provide sign language options.

Speaker diversity will improve but currently still overwhelming white men. Part of the purpose of LAS is to improve diversity. Diversity cannot improve until we provide ways for developers to sustain themselves writing applications on the Linux platform, but also to increase partnership within the ecosystem. We track speaker diversity when a speaker does a CfP. We also track gender on our registration. We do not ask attendees to state their race only their country of origin.

> On future accommodation: sorry that was not clear, it means is there a way attendees can recommend for something that was not provided in the conference for future ones?

Yes, there is generally a survey that is sent out to attendees at the end of the summit for them to fill out. Of course, we also are available in person to get feedback. There is also a telegram channel where attendees can actively give feedback about the talks and about the conference.

Regarding family friendliness - yes, we could do a better job of getting more family friendly information. There is some debate on what family friendly means and so that needs to be defined so that we can adhere to it.

**Comment by germonprez** [comment]
Hi @sramkrishna -- Not officially part of this review but the CHAOSS metric on family friendliness might help here: 
https://chaoss.community/kb/metric-family-friendliness/

**Comment by sramkrishna** [comment]
Oh lovely! Thanks for that - I'll review!

**Comment by Ruth-ikegah** [comment]
> Some of these options we can do. Linux App Summit doesn't provide any catering so food options are up to attendees. Sign language and braille options are difficult for this conference as it doesn't raise enough money to be able to fund those kind of options. This year especially sponsorship has not been high due to uncertainty in high tech sector. But given funding we would absolutely especially if we do online talks provide sign language options.
> 
> Speaker diversity will improve but currently still overwhelming white men. Part of the purpose of LAS is to improve diversity. Diversity cannot improve until we provide ways for developers to sustain themselves writing applications on the Linux platform, but also to increase partnership within the ecosystem. We track speaker diversity when a speaker does a CfP. We also track gender on our registration. We do not ask attendees to state their race only their country of origin.
> 
> > On future accommodation: sorry that was not clear, it means is there a way attendees can recommend for something that was not provided in the conference for future ones?
> 
> Yes, there is generally a survey that is sent out to attendees at the end of the summit for them to fill out. Of course, we also are available in person to get feedback. There is also a telegram channel where attendees can actively give feedback about the talks and about the conference.
> 
> Regarding family friendliness - yes, we could do a better job of getting more family friendly information. There is some debate on what family friendly means and so that needs to be defined so that we can adhere to it.

Thanks for providing this feedback @sramkrishna! I perfectly understand it is a work in progress about speaker diversity. I have updated my review.

In the meantime our badging bot that handles automation is bad, once it is back up, we will conclude with this review. Thank you for your patience.

**Comment by Anita-ihuman** [comment]
@sramkrishna Thanks for the feedback provided. 
I have updated my review. @Ruth-ikegah

**Comment by Ruth-ikegah** [comment]
Thanks once again for applying for a DEI badge @sramkrishna , congratulations on your gold badge!
