### ISSUE TITLE
[In-Person Event] KubeDay Israel

### ISSUE THREAD

**Issue by stearnsbridget** [badging/event-diversity-and-inclusion#243]
# In-Person Event Submission

## Requirements

- Event Name: KubeDay Israel
- Link to the Event Website: https://events.linuxfoundation.org/kubeday-israel/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendees onsite to ensure they can enjoy the event to the fullest: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s). Do you identify as a person of color? What gender do you identify with? How old are you? (Please note, none of these questions are required, they are optional for attendees to fill out) 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the attendee information page we provide a list of pronouns to chose from but also provide a space for text input if none of the options provided apply.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers and attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's post-event survey was considered when planning 2023. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Under the Diversity and Inclusion page on the event website there is a section that speaks to venue accessibility.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We send out a post-event survey to all speakers where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, it will be made available at the conclusion of the event via YouTube to all at no charge. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the onsite Diversity & Inclusion resources flyer. This flyer has all DEI-related resources, as well as event team members they can contact should they need anything onsite.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/kubeday-israel/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Cloud Native Computing Foundation is pleased to offer three types of scholarships; Diversity, Need-Based, and Maintainer Scholarships
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity Registration Scholarships - Applicants must be from a traditionally underrepresented and/or marginalized group in the technology and/or open source communities who are unable to attend without some financial assistance. Including, but not limited to: persons identifying as LGBTQIA+, women, persons of color, and/or persons with disabilities. Need-based Registration Scholarships - Individuals who apply should be active members of the open source community who are unable to attend for financial reasons and are unable to get funding from their companies. MAINTAINER SCHOLARSHIPS Applicants should be active CNCF project maintainers who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/kubeday-israel/attend/scholarships/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, we are offering complimentary onsite child care this year. Children (as well as professional child care providers) must be fully vaccinated or show negative COVID-19 test to participate. Fully vaccinated is defined as two weeks (14 full days) after the final dose of a vaccine approved for emergency or full use by the WHO. Proof of vaccination will be required. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We offer our attendees a private nursing room that they can access throughout the event, gender-neutral restrooms, pronoun stickers, and have ADA-accessible transportation provided to any offsite venues.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/kubeday-israel/attend/diversity-inclusion/

**Comment by Maryblessing** [comment]
I am done with reviewing for this event. All good on my end @ElizabethN

**Comment by stearnsbridget** [comment]
Hi all,

I wanted to circle back on this and see where we stood for the badging on
this website? Thanks!

Best,
Bridget

Bridget Stearns (she/her/hers)
Senior Event Coordinator, The Linux Foundation
<https://events.linuxfoundation.org/>

*PHONE | *+1 609.289.1868
*EMAIL | ***@***.***
*WORKING HOURS | *8:00 AM - 5:00 PM (EASTERN TIME - US)
*At The Linux Foundation, we work flexibly. While it suits me to email now,
I do not expect a response or action outside of your own working hours. *

**Comment by ElizabethN** [comment]
Apologies for the delay @stearnsbridget! Here is your generated badge, and keep up the great work! 💖

**Comment by stearnsbridget** [comment]
Thank you!!

Best,
Bridget

Bridget Stearns (she/her/hers)
Senior Event Coordinator, The Linux Foundation
<https://events.linuxfoundation.org/>

*PHONE | *+1 609.289.1868
*EMAIL | ***@***.***
*WORKING HOURS | *8:00 AM - 5:00 PM (EASTERN TIME - US)
*At The Linux Foundation, we work flexibly. While it suits me to email now,
I do not expect a response or action outside of your own working hours. *
