### ISSUE TITLE
[Virtual Event] R/Medicine 2023

### ISSUE THREAD

**Issue by JessicaRoheLF** [badging/event-diversity-and-inclusion#246]
# Virtual Event Submission

## Requirements

- Event Name: R/Medicine 2023
- Link to the Event Website: https://events.linuxfoundation.org/r-medicine/
- Provide verification that you are an event organizer: Yes, Jessica Rohe, Event Coordinator at The Linux Foundation

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite, and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete.   Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Do you identify as a person of color? What gender do you identify with? How old are you? 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` All demographic related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you. 

## Inclusive Experience at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, after each event, a feedback survey is deployed to speakers, attendees, sponsors, etc. We use the feedback provided in this survey to help plan for future events, including the current year’s event. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We provide details to our attendees on the event website: https://events.linuxfoundation.org/r-medicine/attend/diversity-inclusion/
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.  Additionally, during the registration process, we ask registrants if they have any accommodations requests we should be aware of. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Content from R/Medicine 2023 will be streamed to YouTube and made available live for registered virtual attendees. Keynotes and other event recordings will be made available on the R Consortium YouTube Channel shortly after the event concludes. 

## Time Inclusion for Virtual Events

- [x] This event commits to Time Inclusion for Virtual Events.
  - `Q` Are speakers able to pre-record their presentations, as opposed to presenting them live?
  - `A` No, for R/Medicine all sessions will be live. 
  - `Q` Can attendees change video quality on the Event platform while viewing a presentation?
  - `A` R/Medicine is taking place in Zoom. Attendees have the ability to change the video quality in the following way "To turn off HD in your Zoom client: In your desktop Zoom client, click Settings (the gear icon). Click Video in the left-hand menu. In the My Video section, uncheck the box beside Enable HD if it is checked."

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Since this is a virtual event, the code of conduct will be posted on the event website. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/r-medicine/attend/code-of-conduct/
  
 ## Diversity Access Tickets
  
- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` R/Medicine has 2 types of diversity access tickets, 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` We place an emphasis on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/r-medicine/attend/scholarships/#scholarships

**Comment by Delight362** [comment]
Thank you @JessicaRoheLF  for badging your event with us.
Am done with my review @ElizabethN

**Comment by LamiWilliams** [comment]
Thank you for applying for a DEI Badge! @JessicaRoheLF 
I'm done with my review @ElizabethN

**Comment by kaxada** [comment]
@ElizabethN the bot was down yesterday because I was deploying the badging website on the same server. But it is now up and running

**Comment by JessicaRoheLF** [comment]
Hi @ElizabethN & @kaxada - does a 91 give us a gold badge for this event? Usually we get a graphic, but I can pull the graphic from our last event if gold is the right one to pull. Thanks!

**Comment by ElizabethN** [comment]
Sorry @JessicaRoheLF! Here you go -- keep up the great work! 💖
