### ISSUE TITLE
[In-Person Event] Open Source Congress

### ISSUE THREAD

**Issue by JessicaRoheLF** [badging/event-diversity-and-inclusion#249]
# In-Person Event Submission

## Requirements

- Event Name: Open Source Congress
- Link to the Event Website: https://events.linuxfoundation.org/open-source-congress/
- Are you an organizer of this event? Yes, Jessica Rohe, Event Coordinator, The Linux Foundation

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite, and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete. Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Do you identify as a person of color? What gender do you identify with? How old are you?
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic-related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` There is not a text input box on the event registration page.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` This is the first time hosting Open Source Congress, but after each event that The Linux Foundation hosts, a feedback survey is deployed to speakers, attendees, sponsors, etc. We use the feedback provided in this survey to help plan for future events, including the current year’s event.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We include Resources available to our attendees on the event webpage: https://events.linuxfoundation.org/open-source-congress/attend/diversity-inclusion/#onsite-resources
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. Additionally, during the registration process, we ask registrants if they have any accommodations requests we should be aware of.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` This event is in-person only and will not be recorded due to falling under the jurisdiction of the Chatham House Rule (https://www.chathamhouse.org/about-us/chatham-house-rule). 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/open-source-congress/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We are offering 1 diversity access ticket type via travel funding. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Those in need of travel funding will need to complete the form linked in the next answer. We ask applicants to provide a few key pieces of information on their application including their Company or Organization, whether they can receive funds from their organization, a brief description of the ways they are involved in technology and/or open source communities, and why they want to attend the conference. We also ask if they belong to an underrepresented and/or marginalized group. This field is not required and is optional to include.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/about/travel-fund-request/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Though it's not publicized on the website, we will provide child care if requested. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will provide a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event, and will be located onsite. We will also have gender-neutral restrooms available to all attendees at the event.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/open-source-congress/attend/diversity-inclusion/#onsite-resources

**Comment by Dhruv-Sachdev1313** [comment]
Hey @JessicaRoheLF: Thanks for applying to the badging program!
I had a small feedback about the Diversity Access Tickets. Let me know if I am missing something but I cannot find the information about travel funding publicly mentioned on the Open Source Congress event website. I saw the link you provided in the form, which seems to be a generalized travel fund request to LF.  It would be great to include this on the event page as well!
Thanks again! 🙂

**Comment by ElizabethN** [comment]
@Joynels-Ogbogu Hi! Just making sure you saw this ping. Thank you!

**Comment by JessicaRoheLF** [comment]
Hi - I’m stepping in as Jessica is no longer with the Linux Foundation.

This score seems reasonable given the nature of the event. Please allow me until the EOD to confirm with my team.

Thank you,

Emily

Emily Ruf, CMP
Senior Event Manager
The Linux Foundation
M: 512-745-1456
E: ***@***.***
Time Zone: East Coast (UTC -04:00)

Upcoming OOO
May 29-June 5: LF Energy Summit
July 15-22: PTO
July 23-29: OS Congress

**Comment by JessicaRoheLF** [comment]
Hi All - We’re good with the Silver Badge.

Thank you!

Emily Ruf, CMP
Senior Event Manager
The Linux Foundation
M: 512-745-1456
E: ***@***.***
Time Zone: East Coast (UTC -04:00)

Upcoming OOO
May 29-June 5: LF Energy Summit
July 15-22: PTO
July 23-29: OS Congress

**Comment by ElizabethN** [comment]
Here you go! Thanks so much!

**Comment by JessicaRoheLF** [comment]
Thank you!

Emily Ruf, CMP
Senior Event Manager
The Linux Foundation
M: 512-745-1456
E: ***@***.***
Time Zone: East Coast (UTC -04:00)

Upcoming OOO
May 29-June 5: LF Energy Summit
July 15-22: PTO
July 23-29: OS Congress
