### ISSUE TITLE
[In-Person Event] GUADEC 

### ISSUE THREAD

**Issue by kristiprogri** [badging/event-diversity-and-inclusion#256]
# In-Person Event Submission

## Requirements

- Event Name: GUADEC 2023
- Link to the Event Website: https://events.gnome.org/event/101/
- Are you an organizer of this event? Yes, I am one of the organizers

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Within our registration process we include optional questions to help us measure our event demographics. As support for this effort, we also include another set of optional demographic questions in our post-event survey.  These questions include: Age (listed in ranges), Primary Language, Country of Residence, Gender, Identity.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration forms and surveys are optional and for any question that requires the filer to select a choice we include “prefer not answer” as an option.  For example, our answers for the age section are listed as: Under 15, 15-30, 31-45, 46-60, 61 and over, Prefer not to answer
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` In our optional demographics section of the registration form, we include a question for “Gender Identity” which uses a text input box for the response. For this question we do not provide options, we let the attendee enter their own text. We use the same text box input for any questions regarding what details our attendees would like included on their conference name badges. They have the option to write in a response for pronouns and languages spoken along with their printed name.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We provide two feedback pages, one for in-person attendees and the other for online ones. This is the page of last year's edition: https://events.gnome.org/event/77/surveys/ We also proactively ask for attendee input on our registration forms to ensure we capture everyone’s needs and do our best to help attendees enjoy the event to the fullest. Within our in-person registration form we as if attendees have any dietary restrictions, require childcare, or need any accessibility accommodations. On our remote registration form, we include the same question about accessibility accommodations.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, after the conference we send out a survey to our in-person attendees to capture their thoughts on how the event went and what they think could be improved. Speakers and volunteers are included on this list and receive the invitation to provide their feedback. We also have a post-event meeting with the organizing team of volunteers to discuss what went well and things we should change for next year.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, after the conference we send out one survey to our in-person attendees and another to our remote attendees to capture their thoughts on how the event went and what they think could be improved. Once we receive survey responses we go through all the answers as a team and keep notes to improve for next year.  There are many adjustments that we are planning to do or have already done based on the feedback that attendees provided to us, such as:  Printed names on both sides of the attendee badges, better inclusivity for dietary preferences/needs such as vegetarian and vegan options, speakers can share notes from their talks after the event
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We have a dedicated page for accessibility at our conference venue where attendees can learn more about the space and what accommodations and support we have available. https://events.gnome.org/event/101/page/234-accessibility-at-the-venue
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We include a spot on our registration forms for attendees to let us know they need accessibility accommodations and write in more details. We also include a an additional prompt at the end of the registration form that asks attendees  “any additional notes you want to add to your registration?” and provides a large text box for write in requests.  Aside from the registration form we encourage all attendees to share any ideas with us during the event and have the contact information on our website. We also include this invitation in our conference welcome, so people will feel more encouraged to share their thoughts with us during or after the event.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, all the presentations are available on youtube right after the event and our conference chat channels remain active post-event for attendees to continue asking questions or share thoughts.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have our code of conduct on our conference website and during the conference, we include a link to the page and CoC contact information on the attendee badges. This year we are also planning to print the code of conduct as a poster and have it posted at the conference venue. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.gnome.org/event/101/page/179-code-of-conduct

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We always have an unlimited number of free tickets available for our conference. We also include an opt in donation/ticket cost of anyone who does want to contribute monetarily to the conference, or for attendees who have travel budgets from their employers. For the optional donation/ticket cost we provide various costs so attendees can select an amount they are comfortable with.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` It is open to everyone. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` Here is the registration link, open and free for everyone to attend: https://events.gnome.org/event/101/registrations/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, we provide childcare support based on the attendees needs and covering a range of ages starting from infants. We are not able to cover the cost of childcare, but we handle all of the coordination and bookings.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` Children of all ages are welcome at our conference, we have no age restriction. However, we understand that parents may not want to bring their kids to the conference talks so we offer childcare services and provide dedicated spaces for families if needed, including a space at the venue for childcare, pumping rooms, etc. We ensure that we always include family-friendly options for social events as well. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` That is included in the registration form, after we receive the requests, we go through them carefully and accommodate all the requests we are able to. We also include childcare details on our website. Parents in need of childcare and learn more about our provider and associated costs here: https://events.gnome.org/event/101/page/175-childcare-support

**Comment by ElizabethN** [comment]
@kristiprogri :wave: hiiiii! do you have the information from the application? You'll need to copy and paste that information here in the issue. Let me know if you need any help with this! Thank you!

**Comment by kristiprogri** [comment]
Hi, oh my bad, let me please try this again

**Comment by ElizabethN** [comment]
@kristiprogri looks like it worked great, thank you!

**Comment by djmitche** [comment]
Hi everyone! I can likely get to this review this weekend.

**Comment by Ruth-ikegah** [comment]
Hi @kristiprogri, pretty solid DEI work on GUADEC! I enjoyed this review!

I noticed on the code of conduct that the contact information section was empty. Could you have a look and update it?

@ElizabethN I am done with my review!

**Comment by kristiprogri** [comment]
@Ruth-ikegah just updated that :D Thanks a lot

**Comment by djmitche** [comment]
Agreed with @Ruth-ikegah - this is fantastic. The registration form makes the openness to accomodations _very_ clear, and I love the opt-in ticket donation. I've checked all of the boxes in my review, so I think this is ready to go.

**Comment by ElizabethN** [comment]
@kristiprogri This is a gold level badge so I'm going to go ahead and issue it. If you do make any more changes and want to re-run this badge that's completely fine and we're happy to do so! Thank you!
