### ISSUE TITLE
[In-Person Event] DPDK Summit

### ISSUE THREAD

**Issue by stearnsbridget** [badging/event-diversity-and-inclusion#264]
# In-Person Event Submission

## Requirements

- Event Name: DPDK Summit
- Link to the Event Website: https://events.linuxfoundation.org/dpdk-summit/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendees onsite to ensure they can enjoy the event to the fullest: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s). Do you identify as a person of color? What gender do you identify with? How old are you? (Please note, none of these questions are required, they are optional for attendees to fill out) 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the attendee information page we provide a list of pronouns to chose from but also provide a space for text input if none of the options provided apply.  Criteria: Measuring Demographics - The Event has a process for measuring speaker demographics. Opt-Out - The Event provides an opportunity to opt-out of providing demographic data. Text Input - The Event provides a text box to input certain data such as Gender, Race, or Ethnicity

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers and attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's post-event survey was considered when planning 2023. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We have a D+I page on the website and it lists on-site resources and to have any questions be directed to the event manager. 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We send out a post-event survey to all speakers where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, it will be made available at the conclusion of the event via YouTube to all at no charge. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the onsite Diversity & Inclusion resources flyer. This flyer has all DEI-related resources, as well as event team members they can contact should they need anything onsite.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/dpdk-summit/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` At this time we are not providing diversity access tickets.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` N/A
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` N/A 

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` We are unable to offer childcare for this event. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We offer our attendees a private nursing room that they can access throughout the event, gender-neutral restrooms, pronoun stickers, and have ADA-accessible transportation provided to any offsite venues.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/dpdk-summit/attend/diversity-inclusion/#onsite-resources

**Comment by ElizabethN** [comment]
@germonprez @klumb Hiii just making sure you all saw these pings. Thanks so much! :pray:

**Comment by germonprez** [comment]
Thanks for the application @stearnsbridget! Everything looks great. I couldn't help but wonder if providing a virtual option to attend could be identified as an approach towards family friendliness. It is not in the current CHAOSS metric but by providing both options, there is an opportunity for people to attend who may have family reasons for not being able to travel. For example: 

While we are unable to provide family services onsite, such as child care or onsite family activities, we encourage people attending to family members to join us via our virtual platform option. 

This may be something we could bring up in the DEI WG call. @ElizabethN

**Comment by klumb** [comment]
Thanks for the ping @ElizabethN, I missed the previous emails

**Comment by klumb** [comment]
@stearnsbridget I couldn't find information about the nursing rooms on the website. For Family friendliness, I checked the availability based on your statement but did not check findability.  If you would like to add that info to the DEI page I will hold off on finishing. Otherwise, I have completed my review.

**Comment by klumb** [comment]
Also, I agree with @germonprez the virtual platform information could be marketed as a family-friendliness option on the DEI page (in addition to the nursing rooms).

**Comment by ElizabethN** [comment]
Hi @stearnsbridget! Are you ok with this badge or would you like to make a few changes based on the feedback from @germonprez and @klumb ? Totally fine to run it as-is or wait; either way!

**Comment by stearnsbridget** [comment]
Hi Elizabeth,

This event is pretty bare boned, so I am going to take this percentage and
post on the website. Can you send over the badge? Thanks!

Best,
Bridget

Bridget Stearns (she/her/hers)
Senior Event Coordinator, The Linux Foundation
<https://events.linuxfoundation.org/>

*PHONE | *+1 609.289.1868
*EMAIL | ***@***.***
*WORKING HOURS | *8:00 AM - 5:00 PM (EASTERN TIME - US)
*At The Linux Foundation, we work flexibly. While it suits me to email now,
I do not expect a response or action outside of your own working hours. *
*Upcoming Out of Office:*
*July 20 - July 24: PTO - no response*

**Comment by stearnsbridget** [comment]
Hi Elizabeth,

Following up here - thanks!

Best,
Bridget

Bridget Stearns (she/her/hers)
Senior Event Coordinator, The Linux Foundation
<https://events.linuxfoundation.org/>

*PHONE | *+1 609.289.1868
*EMAIL | ***@***.***
*WORKING HOURS | *8:00 AM - 5:00 PM (EASTERN TIME - US)
*At The Linux Foundation, we work flexibly. While it suits me to email now,
I do not expect a response or action outside of your own working hours. *
*Upcoming Out of Office:*
*July 20 - July 24: PTO - no response*

**Comment by ElizabethN** [comment]
@stearnsbridget here you go! Sincere apologies for the delay! 💖

**Comment by stearnsbridget** [comment]
Thank you!

Best,
Bridget

Bridget Stearns (she/her/hers)
Senior Event Coordinator, The Linux Foundation
<https://events.linuxfoundation.org/>

*PHONE | *+1 609.289.1868
*EMAIL | ***@***.***
*WORKING HOURS | *8:00 AM - 5:00 PM (EASTERN TIME - US)
*At The Linux Foundation, we work flexibly. While it suits me to email now,
I do not expect a response or action outside of your own working hours. *
*Upcoming Out of Office:*
*Aug 18 - Aug 27: PTO - no response*
