### ISSUE TITLE
[In-Person Event] FOSS Security Campus 2023

### ISSUE THREAD

**Issue by plainschwarz-team** [badging/event-diversity-and-inclusion#273]
# In-Person Event Submission

## Requirements

- Event Name: FOSS Security Campus 2023
- Link to the Event Website: [foss-security-campus.de](https://foss-security-campus.de)
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Event demographics is mainly measured using our voluntary demographic survey which is attached but not connected to the registration process. (i.e. the survey is external and anonymous and not connected to the personal data entered during registration) We only collect limited speaker/attendee demographics at registration due to privacy concerns.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` “Prefer not to answer” options are available for all demographic questions asked during the registration process and attendees can also completely skip the question.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` For example, the question “What are your pronouns?” provides a list of pronouns including a “prefer not to answer” option), as well as an option to provide pronouns not listed in a text input field: “My pronouns are: [text input]”

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` Feedback can be provided using our demographics and feedback survey, which will be send to every attendee, speaker and volunteer after the event. The anonymized results will be published in our annual Diversity Report, which will be available for everyone on our website. It is also possible to provide feedback via mail at any time, the mail address is listed on the page for diversity & inclusivity.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` This is the first edition of FOSS Security Campus, but we are planning to incorporate feedback from this year’s event for future editions.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes. Feedback regarding diversity, accessibility and inclusivity will be published in our Diversity Report. Feedback will also be discussed after the event within the team.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` By visiting the pages on Diversity & Inclusivity (https://foss-security-campus.de/diversity-inclusivity) or Accessibility (https://foss-security-campus.de/accessibility)
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Attendees and speakers can suggest future improvements for the event in our annual feedback survey or send feedback to a dedicated Email address, which is linked on our Diversity and Accessibility pages on our website.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Our website will be available after the event. Our online platform Venueless is also available for a limited time after the event. The talks and sessions will be made available for everyone on our YouTube-Channel after the event. (https://www.youtube.com/c/PlainSchwarzUG/)

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` The code of conduct is posted on our website. Attendees and speaker must tick a checkbox at registration that they have read and consent to our code of conduct. The code of conduct will be published on our online platform Venueless and in physical form at the entrance to our venue in Berlin.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://foss-security-campus.de/code-of-conduct

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We provide Diversity Online-Tickets and Diversity Onsite-Tickets. Both tickets are fully sponsored (i.e. free) and provide full access either to our online or onsite event.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity Tickets are available to people from underrepresented groups within the FOSS Security Campus community. This includes, but is not limited to: women, people of colour, LGBTQIA people, disabled people, and people facing economic or social hardships. Please note that there is no "qualification process" for Diversity Tickets, and one can simply order a Diversity Ticket without being vetted, since we as organizers are unable to judge if someone is actually a member of a underrepresented group, and this would create all kinds of obvious problems.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://foss-security-campus.de/diversity-inclusivity 

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` We currently do not offer childcare facilities at FOSS Security Campus.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` -
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` -

**Comment by ElizabethN** [comment]
@kaxada I am so sorry to bug you again - but this doesn't seem to be populating the checklists for some reason 😢

**Comment by kaxada** [comment]
Ooh @ElizabethN I forgot to put things back in order after testing

**Comment by kaxada** [comment]
@daluclemas and @Anita-ihuman the lists have been assigned. @ElizabethN Sorry for the delay

**Comment by daluclemas** [comment]
hi @ElizabethN ,i am done with my review

**Comment by Anita-ihuman** [comment]
Hello @plainschwarz-team, Thank you for applying for a DEI badge for your event.  I see you indicated that your event has not included a family friendliness metrics yet. Hopefully for the next years application this will be put into consideration.

@ElizabethN I am done with my review

**Comment by ElizabethN** [comment]
Hi @kaxada :wave: I think we need to restart again?

**Comment by kaxada** [comment]
@ElizabethN that was right. Now works perfectly

**Comment by plainschwarz-team** [comment]
Great, thanks for the gold badge! :) And thank you @Anita-ihuman and @daluclemas for your reviews!
