### ISSUE TITLE
[In-Person Event] gRPC Conf 2023

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#276]
# In-Person Event Submission

## Requirements

- Event Name: gRPC Conf 2023
- Link to the Event Website: https://events.linuxfoundation.org/grpc-conf/
- Are you an organizer of this event? My name is Wendi West and I manage the DEI event activities and scholarship program for CNCF events. Tin Matienzo is the event lead.

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Demographic information is collected solely for the purpose of compiling, analyzing and disclosing aggregate statistics regarding diversity of attendance at our events, to help track progress towards meeting our commitment to diversity initiatives. Consent to provide demographic information for the purpose listed above is optional and purely voluntary, and is provided during registration by selecting an option from the drop-down for the corresponding category. Demographic information is considered confidential and private. Voluntary information requested includes: Do you identify as a person of color? (Prefer not to Answer, Yes, No) Sub question when Yes is selected to question above: With which racial/ethnic background(s) do you identify? (check all that apply: Prefer not to answer, Asian, Black, Hispanic/Latino, Indigenous Peoples, Pacific Islander, Self Identity (fill in) )  What gender do you identify with? (Prefer not to answer, Woman, Man, Other Gender Identity)  How old are you? (Prefer not to answer, 0-19, 20-39, 40-60, 61+)
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` Each demographic question has the first option as Prefer not to answer. At the beginning of the demographic section we explain that it is all voluntary and the added language: "Should you choose to provide any demographic information, you may request removal of that information at any time by writing to privacy@linuxfoundation.org." Example of question with opt-out: What gender do you identify with? (Prefer not to answer, Woman, Man, Other Gender Identity)
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Sub question when answer is YES: Please provide additional details here: (text input box). With which racial/ethnic background(s) do you identify? check all that apply: Prefer not to answer, Asian, Black, Hispanic/Latino, Indigenous Peoples, Pacific Islander, Self Identity (text input box) 

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` On the event website we have a Contact Us section with the following statement: If you have ideas on how we can create a more inclusive event, please do not hesitate to let us know. Contact Vanessa Heric, Director of CNCF Events, vheric@linuxfoundation.org. Additionally we will send an attendee survey post event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Due to feedback received regarding interest in this event and topic(s) we have expanded from a co-located event to a CNCF hosted stand-alone event for 2023. As part of the CNCF / LF event programming, we implement our overall DEI initiatives and information such as interaction pins, communication stickers and pronoun stickers.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes. We review all feedback received, discuss as a team, and implement changes or suggestions as needed per event during our post-event team call and then take bigger issues or discussion topics to our team face to face meeting.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` The Diversity + Inclusion page (https://events.linuxfoundation.org/grpc-conf/attend/diversity-inclusion/#onsite-resources) of our event website lists on site resources such as Venue accessibility, Communication & Interaction stickers, etc.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Our registration form includes a text input box for anyone who may require additional assistance or accommodation for the existing event, and then attendees can share feedback in the post event survey and/or by emailing events@cncf.io at any time.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` This is an in-person event only. However, we do plan to record the keynotes and breakout sessions and then post to YouTube after the event.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes - the Code of Conduct is posted at the Event venue, as well as on the event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/grpc-conf/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` The Dan Kohn Scholarship Fund exists to support individuals who may not otherwise have the opportunity to attend in three categories: Diversity, Need-based, and Maintainer.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity: Applicants must be from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities who are unable to attend without some financial assistance. Including, but not limited to persons identifying as LGBTQIA+, women, persons of color, and/or persons with disabilities. Need-Based: Applicants should be active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons. Maintainer: Applicants should be active CNCF project maintainers who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/grpc-conf/attend/scholarships/ 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` CNCF and The Linux Foundation strive to provide childcare at our events. However, this event is being hosted at the Google Campus and due to liability restrictions, we are not able to provide childcare facilities at this one-day event.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` There are nursing / mother's rooms on the Google campus and we are working with the contacts at Google to have those open and available for our attendees
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by FeazUI** [comment]
@ElizabethN  Done.

**Comment by Ijeoma-Onwuka** [comment]
Review Done @ElizabethN

**Comment by ElizabethN** [comment]
Thank you @FeazUI and @Ijeoma-Onwuka ! 🤩
