### ISSUE TITLE
[In-Person Event] PeculiarTestCon

### ISSUE THREAD

**Issue by peculiaruc** [badging/event-diversity-and-inclusion#279]
# In-Person Event Submission

## Requirements

- Event Name: PeculiarTestCon
- Link to the Event Website: peculiartestcon.org
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` All good
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` Provided
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` Female

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` Recorded feedback from participant at the event venue
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Sample can be found here: peculiartestcon.org
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, The feedback from previous event will be used to compare the present, it will be analyzed and use to improve DEI
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` There is a topic on that
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Yes. Process is confidential
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` yes, peculiartestcon.org

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` peculiartestcon.org/codeofconduct

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 255
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The process can be found here peculiartestcon.org/diversity/criteria
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` peculiartestcon.org/diversity 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` A hall is provided for them and our employers are in change of that
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` peculiartestcon.org/family/friendliness

**Comment by seeewhy** [comment]
new review/
