### ISSUE TITLE
[Virtual Event] GitOpsCon Europe 2024

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#281]
# Virtual Event Submission

## Requirements

- Event Name: GitOpsCon Europe 2024
- Link to the Event Website: https://events.linuxfoundation.org/gitopscon-europe/
- Provide verification that you are an event organizer: Yes, Rachel Braun, Senior Event Planner, The Linux Foundation

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite, and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete.   Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Do you identify as a person of color? What gender do you identify with? How old are you?  Geographical region   All demographic related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you. 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` All demographic related questions on our registration are optional - no opt-out necessary. 

## Inclusive Experience at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. We continue to use our post-event surveys as a consideration to improve all future events. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` N/A - Accessibility features are still being determined as we are sourcing and finalizing the virtual event platform. 
  - `Q` Does the event platform allow attendees to suggest future accommodations for the event?
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager, made easily accessible should anyone want to share their feedback prior, during, or after the event.  Additionally, during the registration process, we ask registrants if they have any accommodation requests we should be aware of. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` TBD - We are still finalizing the event platform for this event. At a minimum, the session recordings will posted to a public YouTube Channel - the link to this channel will be emailed to all registrants AND posted to the event website. 

## Time Inclusion for Virtual Events

- [x] This event commits to Time Inclusion for Virtual Events.
  - `Q` Are speakers able to pre-record their presentations, as opposed to presenting them live?
  - `A` TBD - we are still finalizing the event platform. In most cases, we will accept pre-recorded presentations to accommodate speakers in different timezones. 
  - `Q` Can attendees change video quality on the Event platform while viewing a presentation?
  - `A` TBD - likely yes, as this is a feature of our many of our virtual event platforms. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be visible on the virtual event platform.  We have the code of conduct linked in all event emails, as well as on the event website for easy reference. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/gitopscon-europe/attend/code-of-conduct/
  
 ## Diversity Access Tickets
  
- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 3 types of scholarships - Need-Based, Diversity + Maintainer. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity Scholarship: Applicants must be from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities who are unable to attend without some financial assistance. Including, but not limited to persons identifying as LGBTQIA+, women, persons of color, and/or persons with disabilities.  
  - Need-based scholarships: for members of the community who may be unable to attend due to lack of funding, and do not work for a company that has the ability to fund your attendance.   
  - Maintainer Scholarships: Applicants should be active CNCF project maintainers who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/gitopscon-europe/attend/scholarships/#scholarships

**Comment by Abenacodes** [comment]
@ElizabethN I am done with my review

**Comment by Omokiti** [comment]
@RachelBraunLF Well done!!. @ElizabethN I am done reviewing.

**Comment by ElizabethN** [comment]
Here is your badge, @RachelBraunLF ! Thanks so much for applying and best of luck with your event 🤩
