### ISSUE TITLE
[In-Person Event] LFN Developer & Testing Forum 2023 - Fall

### ISSUE THREAD

**Issue by AndreaCalderonLF** [badging/event-diversity-and-inclusion#282]
# In-Person Event Submission

## Requirements

- Event Name: LFN Developer & Testing Forum 2023 - Fall
- Link to the Event Website: https://events.linuxfoundation.org/lfn-developer-testing-forum/
- Are you an organizer of this event? Yes, Andrea Calderon, Senior Event Coordinator, The Linux Foundation

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During the registration process, we ask several questions related to attendee demographics to allow us to better serve our attendees onsite, and ensure our attendees can make the most of the event, as well as be comfortable. Important to note, these questions are not required, and are optional for attendees to complete.   Examples of these questions include: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Do you identify as a person of color? What gender do you identify with? How old are you?  Geographical region   All demographic related questions are not required - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”. A selection of Prefer Not to Answer is available for the following questions: Do you identify as a person of color, What gender do you identify with, and How old are you.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic related questions on our registration are optional - no opt-out necessary.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the attendee information page we provide a list of pronouns to choose from but also provide a space for text input if none of the options provided apply.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. We continue to use our post-event surveys as a consideration to improve all future events. 
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We include resources available to our attendees on the event webpage:https://events.linuxfoundation.org/lfn-developer-testing-forum/attend/diversity-inclusion/ 
  - `Q` Does the event platform allow attendees to suggest future accommodations for the event?
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager, made easily accessible should anyone want to share their feedback prior, during, or after the event.  Additionally, during the registration process, we ask registrants if they have any accommodation requests we should be aware of. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Keynotes and other event recordings will be made available on the LFN Wiki shortly after the event concludes. https://wiki.lfnetworking.org/display/LN/2023-06+-+FD.io%3A+SONiC+VPP+platform+Use+Case

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/lfn-developer-testing-forum/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` At this time, we are not providing diversity access tickets.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` At this time, we are not providing diversity access tickets.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` At this time, we are not providing diversity access tickets. 

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` We are unable to provide childcare due to budget limitations. We will, however, provide a list of local childcare providers to attendees upon request. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will provide a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event, and will be located onsite. We will also have gender-neutral restrooms available to all attendees at the event. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/lfn-developer-testing-forum/attend/diversity-inclusion/#onsite-resources

**Comment by Busayo-ojo** [comment]
Hi @ElizabethN I'm done with my review. @AndreaCalderonLF Have a great event!

**Comment by ElizabethN** [comment]
@oma131 :wave: hiiii! Just wanted to make sure you saw this ping. Thank you! :heart:

**Comment by oma131** [comment]
Hi @ElizabethN Sorry for the delay, I am done with my review. @AndreaCalderonLF Thank you for applying for a badge, have an amazing event!

**Comment by AndreaCalderonLF** [comment]
@ElizabethN Hello! I just wanted to follow up on the status of the badging process. Please let me know if there is anything I can do on my end. Thanks!!

**Comment by ElizabethN** [comment]
@AndreaCalderonLF Apologies for the delay! I was traveling and I've gotten behind on many things 🙃  Is this level badge ok for you? Totally fine if so, I just wanted to double check :heart:

**Comment by AndreaCalderonLF** [comment]
Hi @ElizabethN sorry to bug you while you're catching up from traveling! When you have a moment, can you share the link for the badge so we can add to our event website? Thank you so much!! :)

**Comment by ElizabethN** [comment]
@AndreaCalderonLF sincere apologies! Here is your badge:

**Comment by ElizabethN** [comment]
> @ElizabethN This badge is great, thank you! Can I ask what would have gotten us a gold badge for future events? I'm guessing it's the Family Friendliness? Thank you again!!

Great question!! It looks like if you're able to offer a reduced cost or free diversity access ticket for underrepresented individuals, that would be super helpful. Also it looks like you can make information about the family friendly accommodations a little more prominent and easy to find on the website. Hope that helps and best of luck with your event! 🤩
