### ISSUE TITLE
[In-Person Event] State of OpenCon 2024

### ISSUE THREAD

**Issue by nvibert** [badging/event-diversity-and-inclusion#287]
# In-Person Event Submission

## Requirements

- Event Name: State of Open Conference 2024
- Link to the Event Website: https://stateofopencon.com/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` During registration, attendees are asked about their gender, ethnicity and whether they identify as neurodiverse.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` Attendees have the option to select “Prefer not to say” when asked about their gender, ethnicity or whether they consider themselves neurodiverse.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` There’s no text input box in the Event Registration page.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` The event feedback page is not yet available but, following the event, a post-event survey to all attendees where we ask the following question: “Diversity, Equity and Inclusion are key values of the OpenUK and we hope the sense of “belonging” was reflected during the event. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A`Yes. This is only second edition of State of Open Con and the first edition was one of the most diverse tech conferences in the UK, with 49% non-white and 30% non-male attendees. The team organizing the event is very diverse and DEI is a core value of OpenUK, as demonstrated by the recent events for International Women's Day and Black History Month.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` The event team plans to record feedback from events in a feedback form but attendees will be also encouraged to submit feedback to the event team during the event.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` During registration, attendees are asked whether they have any accessibility needs that can be accommodated to help them participate in the event.   The venue itself was selected because of its accessibility facilities.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. During registration, we also ask the attendees whether "they would say that their day-to-day activities are limited because of a health problem or disability which has lasted, or is expected to last, at least 12 months?".
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, all the sessions will be streamed live, recorded and posted on YouTube afterwards.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` The code of conduct will be printed and available at the venue ; on large displays across the venue. The code of conduct will also be linked on event emails and also on the event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://stateofopencon.com/code-of-respect/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` There are multiple diversity access tickets available. The price of the conference has overall been heavily discounted for a conference of that size, to encourage a more diverse audience to attend the event.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` To be published shortly but the focus will be the funding will be primarily on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` To be provided shortly 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` A creche will be available for attendees and speakers. During registration, attendees are asked whether they would require the use of a creche.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` A nursing room will be available and even a "Doggy Day Care" will be available!
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://stateofopencon.com/delegate-experience/

**Comment by nvibert** [comment]
Thanks @ElizabethN !

**Comment by daluclemas** [comment]
hi @ElizabethN , the  link to the page containing information about Diversity Access Tickets has not been provided yet. do i just wait for it?

**Comment by ElizabethN** [comment]
@Busayo-ojo :wave: Hi! Just making sure you saw this ping. :blush: 

@daluclemas that's an excellent question! I think we can go ahead and check that box in good faith. @nvibert would you kindly just reference that Diversity Access Ticket page on your site when you have it ready? :pray: Thank you! ✨

**Comment by Busayo-ojo** [comment]
Hi @ElizabethN, I've completed my review. Thank you for the ping 🫶🏽

**Comment by daluclemas** [comment]
hi @ElizabethN , i am done with my review.

**Comment by ElizabethN** [comment]
@nvibert We are moving servers and need to restart our badging bot. Apologies for the delay here!

**Comment by nvibert** [comment]
No worries at all !

**Comment by ElizabethN** [comment]
@nvibert Here you go! Thanks again for applying and best of luck with your event! (And I'll be there in person, so I'll see you there  :smile:)

**Comment by nvibert** [comment]
amazing - thanks @ElizabethN and the team for this ! See you in London in February, Elizabeth!
