### ISSUE TITLE
[In-Person Event] FOSS Backstage

### ISSUE THREAD

**Issue by plainschwarz-team** [badging/event-diversity-and-inclusion#290]
# In-Person Event Submission

## Requirements

- Event Name: FOSS Backstage
- Link to the Event Website: foss-backstage.de
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Event demographics for FOSS Backstage is measured primarily using our voluntary demographic survey, which is attached but not connected to the registration process (i.e. the survey is external and anonymous and not connected to the personal data entered during registration). We have very few speaker/attendee demographic question directly included in the registration due to privacy concerns.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` “Prefer not to answer” options are available for all demographic questions asked during the registration process
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` For example, the questions “What are your pronouns?” provides a list of pronouns including a “prefer not to answer” option), as well as an option to provide pronouns not listed in a text input field:  “My pronouns are: [text input]”

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` Feedback can be provided using our feedback survey, which will be send to every speaker, attendee and volunteer after the conference. Feedback regarding diversity, accessibility and inclusivity will be published in our annual Diversity Report, which is available for everyone on our website.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes. For example, at FOSS Backstage 2022 we got feedback that holding the conference at the end of the week was difficult for some due to religious holidays. As a consequence, we've checked dates more careful in 2023 and 2024 to make sure the conference date is not coinciding with religious holidays.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes. As mentioned above, we will collect feedback using our feedback survey. Feedback regarding diversity, accessibility and inclusivity will be published in our Diversity Report. Feedback will also be discussed after the event within the team.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` By visiting the pages on diversity & inclusivity (https://24.foss-backstage.de/diversity-inclusion/) as well as on accessibility (https://24.foss-backstage.de/accessibility/).
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Attendees and speakers can suggest future improvements for the event in our annual feedback survey or send feedback to a dedicated Email address, which is linked on our Diversity and Accessibility pages on our website.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Our website will be available after the event. Our online platform Venueless is also available for a limited time after the event. The talks and sessions will be made available for everyone on our YouTube-Channel after the event. (https://www.youtube.com/c/PlainSchwarzUG

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` The code of conduct is posted on our website. Attendees and speaker must tick a checkbox at registration that they have read and consent to our code of conduct. The code of conduct will be published on our online event platform and in physical form at the entrance to our venue in Berlin.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://24.foss-backstage.de/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We provide Diversity Online-Tickets and Diversity Onsite-Tickets. Both tickets are fully sponsored (i.e. free) and provide full access either to our online or onsite event.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity Tickets are available to people from underrepresented groups within the FOSS Backstage community. This includes, but is not limited to: women, people of colour, LGBTQIA people, disabled people, and people facing economic or social hardships. Please note that there is no "qualification process" for Diversity Tickets, and one can simply order a Diversity Ticket without being vetted, since we as organizers are unable to judge if someone is actually a member of a underrepresented group, and this would create all kinds of obvious problems.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://24.foss-backstage.de/diversity-inclusion/ 

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Increased family-friendliness is a topic we are working on, but have no concrete measures in place for now. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by ElizabethN** [comment]
@plainschwarz-team sincere apologies for the delay on this! It came through during break and I missed it! 🤦‍♀️ So sorry!

**Comment by Abenacodes** [comment]
@ElizabethN that's fine

**Comment by ElizabethN** [comment]
@kaxada I know this is a super busy week for you, but if you get time can you give the bot a kick for us? Thanks friend! :pray: 💖

**Comment by peculiaruc** [comment]
@ElizabethN I have reviewed this PR. 
I am not sure if the bot has been activated

**Comment by ElizabethN** [comment]
@kaxada is working on it today @Abenacodes :+1:

**Comment by kaxada** [comment]
@ElizabethN this has finally been resolved. it has not been an easy crack. I am just looking at the logs and trying to locate this issue so that I trigger it again

**Comment by ElizabethN** [comment]
@kaxada am I ok to move forward with assigning reviewers then?

**Comment by Abenacodes** [comment]
@ElizabethN I was unassigned and @peculiaruc has now been assigned.

**Comment by kaxada** [comment]
I'm going to reassign them my self. I unassigned them to trigger a couple of events. @ElizabethN @Abenacodes

**Comment by Abenacodes** [comment]
@kaxada Thank you for the feedback.

**Comment by peculiaruc** [comment]
> # Checklist for @peculiaruc
> @peculiaruc Thank you for becoming a part of this Event Badging review.
> 
> Make sure you have looked into the following documents:
> 
> * [Reviewer guide](https://github.com/badging/diversity-and-inclusion/blob/master/reviewer-guide.md)
> * [Reviewer role](https://github.com/badging/diversity-and-inclusion/blob/master/roles/reviewer.md)
> * [Submission guidelines](https://github.com/badging/event-diversity-and-inclusion/blob/master/submission/guidelines.md) (In order to get familiar with applicant actions)
> 
> In order to avoid receiving excessive notifications from this repository, set your subscription status to `Not Watching`.
> 
> # In-Person Event Submission
> ## Requirements
> * Event Name: FOSS Backstage
> * Link to the Event Website: foss-backstage.de
> * Are you an organizer of this event? Yes
> 
> ## Initial checks
> * [x]  Event is about Open Source technologies and systems.
> * [x]  Event information is publicly available on a website.
> * [x]  The Event Code of Conduct is publicly available.
> * [x]  The applicant is the organizer of the event.
> 
> 💡 ` Ensure all the initial checks are marked before proceeding with Metric based checks`
> 
> ## Event Demographics
> This event commits to Event Diversity and Inclusion.
> 
> * `Q` Detail the process for measuring Event Demographics.
> * `A` Event demographics for FOSS Backstage is measured primarily using our voluntary demographic survey, which is attached but not connected to the registration process (i.e. the survey is external and anonymous and not connected to the personal data entered during registration). We have very few speaker/attendee demographic question directly included in the registration due to privacy concerns.
> * `Q` Provide an example of an opt-out option on the Event registration page if available.
> * `A` “Prefer not to answer” options are available for all demographic questions asked during the registration process
> * `Q` Provide an example of a demographics text input box on the Event registration page if available.
> * `A` For example, the questions “What are your pronouns?” provides a list of pronouns including a “prefer not to answer” option), as well as an option to provide pronouns not listed in a text input field:  “My pronouns are: [text input]”
> 
> ### Event Demographics
> * [x]  **Measuring Demographics** - The Event has a process for measuring demographics.
> * [x]  **Opt-Out** - The Event provides an opportunity to opt-out of providing demographic data
> * [x]  **Text Input** - The Event provides a text box to input variable demographics such as Gender, Race, or Ethnicity
> 
> ## Inclusive Experience at Event
> This event commits to the Code of Conduct at Event.
> 
> * `Q` Provide an example of the Event Feedback page if available.
> * `A` Feedback can be provided using our feedback survey, which will be send to every speaker, attendee and volunteer after the conference. Feedback regarding diversity, accessibility and inclusivity will be published in our annual Diversity Report, which is available for everyone on our website.
> * `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
> * `A` Yes. For example, at FOSS Backstage 2022 we got feedback that holding the conference at the end of the week was difficult for some due to religious holidays. As a consequence, we've checked dates more careful in 2023 and 2024 to make sure the conference date is not coinciding with religious holidays.
> * `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
> * `A` Yes. As mentioned above, we will collect feedback using our feedback survey. Feedback regarding diversity, accessibility and inclusivity will be published in our Diversity Report. Feedback will also be discussed after the event within the team.
> * `Q` How can attendees learn more about accessibility at the event?
> * `A` By visiting the pages on diversity & inclusivity (https://24.foss-backstage.de/diversity-inclusion/) as well as on accessibility (https://24.foss-backstage.de/accessibility/).
> * `Q` Does the event platform allow attendees to suggest future accomodations for the event?
> * `A` Attendees and speakers can suggest future improvements for the event in our annual feedback survey or send feedback to a dedicated Email address, which is linked on our Diversity and Accessibility pages on our website.
> * `Q` Will the event platform be accessible to attendees and speakers after the event?
> * `A` Our website will be available after the event. Our online platform Venueless is also available for a limited time after the event. The talks and sessions will be made available for everyone on our YouTube-Channel after the event. (https://www.youtube.com/c/PlainSchwarzUG
> 
> ### Inclusive Experience at Event
> * [x]  **Speaker Inclusivity** - The Event requests feedback from speakers regarding Diversity & Inclusion.
> * [x]  **Attendee Inclusivity** - The Event requests feedback from attendees regarding Diversity & Inclusion.
> * [x]  **Retention** - The Event incorporates feedback from past events, or has a strategy to incorporate feedback into future iterations of the event.
> * [x]  **Accessibility Requests** - Attendees are able to inquire if accomodations are available and make suggestions for future accomodations at events.
> * [x]  **Session Accessibility** - Event attendees are able to access the event platform after the event
> 
> ## Code of Conduct at Event
> This event commits to the Code of Conduct at Event.
> 
> * `Q` Is the code of conduct posted at Event venue?
> * `A` The code of conduct is posted on our website. Attendees and speaker must tick a checkbox at registration that they have read and consent to our code of conduct. The code of conduct will be published on our online event platform and in physical form at the entrance to our venue in Berlin.
> * `Q` Provide a link for the Event Code of Conduct.
> * `A` https://24.foss-backstage.de/code-of-conduct/
> 
> ### Code of Conduct at Event
> * [x]  **Findability** - It is possible to find the Code of Conduct on the Event website.
> * [x]  **Clarity** - Event Code of Conduct provides a definition of expected behaviour.
> * [x]  **Reporting venue** - The event has a venue for reporting violations of the CoC at the event website.
> * [x]  **Support at Event** - The Event Code of Conduct provided information about possible methods to provide support to victims of inappropriate behavior.
> * [x]  **Enforcement** - The participants in the Event are required to accept the Code of Conduct.
> 
> ## Diversity Access Tickets
> This event commits to the Diversity Access Tickets.
> 
> * `Q` How many different types of diversity access tickets are available for the event?
> * `A` We provide Diversity Online-Tickets and Diversity Onsite-Tickets. Both tickets are fully sponsored (i.e. free) and provide full access either to our online or onsite event.
> * `Q` What are the criteria for qualifying for a diversity access ticket?
> * `A` Diversity Tickets are available to people from underrepresented groups within the FOSS Backstage community. This includes, but is not limited to: women, people of colour, LGBTQIA people, disabled people, and people facing economic or social hardships. Please note that there is no "qualification process" for Diversity Tickets, and one can simply order a Diversity Ticket without being vetted, since we as organizers are unable to judge if someone is actually a member of a underrepresented group, and this would create all kinds of obvious problems.
> * `Q` Provide a link to the page containing information about Diversity Access Tickets.
> * `A` https://24.foss-backstage.de/diversity-inclusion/
> 
> ### Diversity Access tickets
> * [x]  **Availability** - The event provides one or more Diversity Access Tickets.
> * [x]  **Ticket allocation** - The Event has a process for allocating diversity access tickets.
> * [x]  **Findability** - The information about Diversity Access Tickets is public.
> 
> ## Family Friendliness
> This event commits to Family Friendliness.
> 
> * `Q` Does the Event provide childcare facilities for its attendees and speakers?
> * `A` Increased family-friendliness is a topic we are working on, but have no concrete measures in place for now.
> * `Q` What are the other ways that a family-friendly environment is being created in the Event?
> * `A`
> * `Q` Provide relevant links related to family friendliness at the Event.
> * `A`
> 
> ### Family Friendliness
> * [ ]  **Availability** - The Event provides one or more services/facilities for families.
> * [ ]  **Findability** - The information about the family friendly services provided at the Event is easy to find on the website.

@ElizabethN I am done,

**Comment by Abenacodes** [comment]
@ElizabethN I am done with my review.

**Comment by ElizabethN** [comment]
@plainschwarz-team THANK YOU for your generous patience as we sorted out our bot issues and for the delay because of the holiday. Here is your badge and we hope you have an amazing event! Thanks for being such great supporters of our badging initiative! :pray: ✨

**Comment by plainschwarz-team** [comment]
@ElizabethN No worries! Thank you for the badge and thank you @Abenacodes and @peculiaruc for your reviews! :)
