### ISSUE TITLE
[In-Person Event] Open Source Forum 2024 

### ISSUE THREAD

**Issue by mollyalexander** [badging/event-diversity-and-inclusion#292]
# In-Person Event Submission

## Requirements

- Event Name: Open Source Forum 2024 
- Link to the Event Website: https://events.linuxfoundation.org/aswf-open-source-forum/
- Are you an organizer of this event? Yes, Event manager

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendees onsite to ensure they can enjoy the event to the fullest: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at [events@linuxfoundation.org](mailto:events@linuxfoundation.org) and we will make every reasonable effort to accommodate your need(s). Do you identify as a person of color? What gender do you identify with? How old are you? (Please note, none of these questions are required, they are optional for attendees to fill out) 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the attendee information page we provide a list of pronouns to choose from but also provide a space for text input if none of the options provided apply.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers and attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's post-event survey was considered when planning 2024.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Under the Diversity and Inclusion page on the event website there is a section that speaks to venue accessibility.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We send out a post-event survey to all speakers where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, it will be made available at the conclusion of the event via YouTube to all at no charge. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the onsite Diversity & Inclusion resources flyer. This flier has all DEI-related resources, as well as event team members they can contact should they need anything onsite.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/aswf-open-source-forum/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` N/A
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` N/A
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` N/A 

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` N/A
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` N/A
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` N/A

**Comment by the-techgurl** [comment]
Hi @ElizabethN I'm done with my review.

**Comment by Busayo-ojo** [comment]
Hi @ElizabethN, I'm done with my review.

@mollyalexander Have a great event!

**Comment by mollyalexander** [comment]
Thank you so much! :)

**Comment by ElizabethN** [comment]
@mollyalexander thanks for your application! 

@Busayo-ojo @the-techgurl  I slightly adjusted your reviews to account for the Code of Conduct Enforcement and Text Box input checks. As this is a part of the LF they provide those things, but I don't think there's any way that you would have known that without going through the whole registration process. We just know that from previous LF events. I hope that's ok! :pray:

Also - @mollyalexander I saw this on the site: 
> Will child care be provided?

> Unfortunately, we cannot offer child care services at this event. We can, however, provide a list of local childcare providers. We apologize for this disruption to our normal event plans. We will be making this service available as soon as we can for future events.

Childcare is very expensive and we totally understand it's not something every organizer can provide. But what you've provided is a reasonable alternative! So I think you deserve a check :blush: I might suggest that this information is placed on the Diversity and Inclusion page of your site, instead of the FAQ. Adding it to the D&I page gives it greater visibility.

@Busayo-ojo @the-techgurl I hope it's ok that I add an extra check to this application for this accommodation in lieu of on-site childcare.   :pray:

**Comment by mollyalexander** [comment]
@ElizabethN Great point! I have made the request to add the information to our DEI website page. It should be updated no later than Friday, Feb 2, 2024.

**Comment by ElizabethN** [comment]
@mollyalexander that's so awesome! I'm going to go ahead check those boxes and issue your badge based on that info, since I'll be traveling this week and somewhat out of pocket. Best of luck with the event! ❤️
