### ISSUE TITLE
[In-Person Event] ONE Summit 2024 

### ISSUE THREAD

**Issue by AndreaCalderonLF** [badging/event-diversity-and-inclusion#294]
# In-Person Event Submission

## Requirements

- Event Name: ONE Summit 2024
- Link to the Event Website: https://events.linuxfoundation.org/one-summit-north-america/
- Are you an organizer of this event? Yes, Andrea Calderon, Sr. Event Coordinator, The Linux Foundation

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendees onsite to ensure they can enjoy the event to the fullest: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s). During the CFP process, we ask several questions related to speaker demographics such as gender identify, if the speaker identifies as a person of color, or identifies with any other underrepresented groups. All LF events commit to speaker diversity and we do not allow all male speaker lineups or panels. All demographic-related questions are not required and remain confidential - an attendee may choose to answer, or not. In addition to making these questions not required, we also provide the option for a registrant to select “prefer not to answer”.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic related questions on our registration are optional - no opt-out necessary.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the attendee details page we ask if there are any disabilites we should be mindful of and provide a text box for individuals to provide details so we can better accomodate them at the event.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.”  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Any feedback provided in the post-event survey is shared with event stakeholders and planning committees for discussion on implementation. We continue to use our post-event surveys as a consideration to improve all future events.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We include resources available to our attendees on the event webpage: https://events.linuxfoundation.org/one-summit-north-america/attend/diversity-inclusion/#onsite-resources
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events, as well as the specific Event Manager, made easily accessible should anyone want to share their feedback prior, during, or after the event.  Additionally, during the registration process, we ask registrants if they have any accommodation requests we should be aware of.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Keynotes and other event recordings will be made available on the LF Networking YouTube Channel shortly after the event concludes.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the code of conduct will be printed and available onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the event website for easy reference.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/one-summit-north-america/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We offer 2 types of access tickets for the event; need-based registration scholarships + travel funding. We use a scholarship program to provide diversity access tickets to support individuals who may not otherwise have the opportunity to attend. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` We place an emphasis on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status. If an individual works for a company that has the ability to fund travel, we ask that they not apply to save scholarship funds for those who need it.   We ask applicants to provide a few key pieces of information on their application including their Company or Organization, whether they can receive funds from their organization, a brief description of the ways they are involved in technology and/or open source communities, and why they want to attend the conference. We also ask if they belong to an underrepresented and/or marginalized group. This field is not required and is optional to include.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/one-summit-north-america/attend/scholarships/#scholarships 

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` We are unable to provide childcare at this time due to budget restrictions.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We will provide a private nursing room to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event, and will be located onsite. We will also have gender-neutral restrooms available to all attendees at the event. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/one-summit-north-america/attend/diversity-inclusion/

**Comment by ElizabethN** [comment]
@AndreaCalderonLF thanks so much for your application! we are having a few issues with our badging bot but we will get this reviewed as soon as we can. We appreciate your patience! :pray:

**Comment by AndreaCalderonLF** [comment]
Thank you for the update! :) @ElizabethN

**Comment by Maryblessing** [comment]
Amazing work @AndreaCalderonLF!

Hi @ElizabethN, I am done with my review.

**Comment by Young-W1** [comment]
Hello @ElizabethN, I am done with my review.

**Comment by AndreaCalderonLF** [comment]
@ElizabethN Hello! Can I get our badging score at your earliest convenience? Thank you so much!!

**Comment by ElizabethN** [comment]
@AndreaCalderonLF apologies! 🙏 Here you go!

**Comment by ElizabethN** [comment]
Best of luck with the event, @AndreaCalderonLF !

**Comment by AndreaCalderonLF** [comment]
@ElizabethN @Young-W1 @Maryblessing Thank you everyone!
