### ISSUE TITLE
[In-Person Event] SOSS Community Day North America 2024

### ISSUE THREAD

**Issue by mrsjent** [badging/event-diversity-and-inclusion#297]
# In-Person Event Submission

## Requirements

- Event Name: SOSS Community Day North America 2024
- Link to the Event Website: https://events.linuxfoundation.org/soss-community-day-north-america/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendees onsite to ensure they can enjoy the event to the fullest: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s). (Please note, none of these questions are required, they are optional for attendees to fill out) 
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` n/a

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers and attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's post-event survey was considered when planning 2023.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Under the Diversity and Inclusion page on the event website there is a section that speaks to venue accessibility.
  - `Q` Does the event platform allow attendees to suggest future accommodations for the event?
  - `A` We send out a post-event survey to all speakers where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, it will be made available at the conclusion of the event via YouTube to all at no charge. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the onsite Diversity & Inclusion resources flyer. This flier has all DEI-related resources, as well as event team members they can contact should they need anything onsite.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/soss-community-day-north-america/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` There is no cost to attend this event. Registration is free.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` There is no cost to attend this event. Registration is free.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` n/a 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes! As a colocated event with Open Source Summit North America we are able to offer complimentary onsite child care.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We offer our attendees a private nursing room that they can access throughout the event and gender-neutral restrooms.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/soss-community-day-north-america/attend/diversity-inclusion/

**Comment by Busayo-ojo** [comment]
Hi @ElizabethN, the registration of this event is free, so I'd be checking all the boxes that are related to Diversity Access Ticket. Additionally, I think it might be good to have a metric that considers events that are completely free of charge.

**Comment by Busayo-ojo** [comment]
@mrsjent Have an amazing event! @ElizabethN I'm done with my review.

**Comment by ElizabethN** [comment]
>Additionally, I think it might be good to have a metric that considers events that are completely free of charge.

@Busayo-ojo I love this idea of thinking about ticket prices. Let's bring it up at the next DEI meeting! If you're not able to attend I'm happy to bring it up on your behalf. :heart:

**Comment by Busayo-ojo** [comment]
I'd try to join the next meeting but if I do not, pls feel free to bring it up ❤️

**Comment by ElizabethN** [comment]
@the-techgurl just wanted to make sure you saw this ping. Thank you!

**Comment by the-techgurl** [comment]
Hi, @ElizabethN I'm sorry it took time to get to this, I'm done with my review
Just like @Busayo-ojo mentioned I also ticked off the boxes relating to diversity since registration is free.

Have an amazing event @mrsjent
