### ISSUE TITLE
[In-Person Event] Cloud Foundry Day NA 2024

### ISSUE THREAD

**Issue by NicoleBlessing** [badging/event-diversity-and-inclusion#307]
# In-Person Event Submission

## Requirements

- Event Name: Cloud Foundry Day NA 2024
- Link to the Event Website: https://events.linuxfoundation.org/cloud-foundry-day-north-america/
- Are you an organizer of this event? Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendees to ensure they can enjoy the event to the fullest:  Do you have a disability that we should be mindful of as we try to accommodate everyone for this event?  Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s).  (Please note, none of these questions are required, they are optional for attendees to fill out)
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On the attendee information page we provide a list of pronouns to choose from but also provide a space for text input if none of the options provided apply.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all speakers and attendees where we ask the following question: “Is there anything you'd like to share with us regarding your experience about this event and/or do you have additional feedback on how we can improve our events in the future?”   We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, we continue to use our post-event survey to collect feedback to be considered for future events.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we gather feedback post event and enter it into our event SWOT analysis doc which we refer to when planning the next event
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Under the Diversity and Inclusion page on the event website there is a section that speaks to venue accessibility. https://events.linuxfoundation.org/cloud-foundry-day-north-america/attend/diversity-inclusion/
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, it will be made available at the conclusion of the event via YouTube to all at no charge.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed on signage onsite and at all off-site venues. We also have the code of conduct linked in all event emails
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/cloud-foundry-day-north-america/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Unfortunately for this event there is no budget for travel funding
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` unfortunately we cannot provide childcare for this event
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by adeyinkaoresanya** [comment]
@Maryblessing  @Busayo-ojo 
Hi! Just making sure you saw these pings. Thank you!

**Comment by Busayo-ojo** [comment]
Hi @adeyinkaoresanya, I'm done with my review.

**Comment by adeyinkaoresanya** [comment]
Thank you @Busayo-ojo @Maryblessing  for taking the time to review. ❤️

**Comment by adeyinkaoresanya** [comment]
@NicoleBlessing here is your badge! Congratulations and best of luck with the event! ✨ 🙌

**Comment by NicoleBlessing** [comment]
Thank you all so much!!
*--*
*Nicole Blessing*
Senior Event Coordinator

<https://linuxfoundation.org/>

T: 1.757.375.2231 (Eastern Time)
E: ***@***.***
