### ISSUE TITLE
[In-Person Event] Community over Code EU

### ISSUE THREAD

**Issue by FloorD** [badging/event-diversity-and-inclusion#308]
Thank you for your consideration!

# In-Person Event Submission

## Requirements

- Event Name: Community over Code EU
- Link to the Event Website: https://eu.communityovercode.org/
- Are you an organizer of this event? yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We will provide pronoun stickers for badges and can count how many of whatever set are being used. We will do a rough headcount which will be flawed, but want to mainly see how we're doing event over event, roughly. We asked for pronouns (optional) during the Call for Papers so as to come up with a diverse line-up.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` We decided not to ask for demographics information at the registration step. Several organizers come from groups underrepresented in tech and feel uncomfortable being "tracked". 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` -

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We will promote feedback surveys for attendees, speakers, and sponsors. 
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Absolutely! The way the project team is set up we get the experience from ASF's event team (Community over Code is the current iteration of ApacheCon), from SoftwareGuru (event agency) and a team of volunteers from the community. We have Chairs for all topic areas (think: sponsors, speakers, communications), I'm the Chair for DEI, and as such there's time allocated every meeting to discuss concerns and ideas.. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Absolutely! We'll email feedback surveys and promote them during the closing of the event, and have a retrospective meeting with the team. There's already an effort ongoing to recruit next year's organizers and they'd get access to all notes at a handover.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Linked directly from the homepage: https://eu.communityovercode.org/diversity-&-inclusion/ We hope to offer captioning for the event, pending sponsorship for "Live Captioning" in our prospectus: https://eu.communityovercode.org/files/community-over-code-prospectus-2024.pdf
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Via the survey after the conference / opened during theclosing ceremony
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` We'll post the talk recordings publicly.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, at the registration desk, and repeated in the opening slides on every day.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://eu.communityovercode.org/coc/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We have discounted tickets for underrepresented groups in tech, as well as a discount for students. We offer a Women and Non-binary Open Source breakfast, pending sponsorship: https://eu.communityovercode.org/files/community-over-code-prospectus-2024.pdf
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Folks need to fill out a form, we trust that when they say that they're from a underrepresented group that they are. Students need to bring some kind of student identification with them to the event.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://eu.communityovercode.org/tickets/ 

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Sadly childcare facilities are not budgetted for.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` -
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` -

**Comment by peculiaruc** [comment]
> # Checklist for @peculiaruc
> @peculiaruc Thank you for becoming a part of this Event Badging review.
> 
> Make sure you have looked into the following documents:
> 
> * [Reviewer guide](https://github.com/badging/diversity-and-inclusion/blob/master/reviewer-guide.md)
> * [Reviewer role](https://github.com/badging/diversity-and-inclusion/blob/master/roles/reviewer.md)
> * [Submission guidelines](https://github.com/badging/event-diversity-and-inclusion/blob/master/submission/guidelines.md) (In order to get familiar with applicant actions)
> 
> In order to avoid receiving excessive notifications from this repository, set your subscription status to `Not Watching`.
> 
> Thank you for your consideration!
> 
> # In-Person Event Submission
> ## Requirements
> * Event Name: Community over Code EU
> * Link to the Event Website: https://eu.communityovercode.org/
> * Are you an organizer of this event? yes
> 
> ## Initial checks
> * [x]  Event is about Open Source technologies and systems.
> * [x]  Event information is publicly available on a website.
> * [x]  The Event Code of Conduct is publicly available.
> * [x]  The applicant is the organizer of the event.
> 
> 💡 ` Ensure all the initial checks are marked before proceeding with Metric based checks`
> 
> ## Event Demographics
> This event commits to Event Diversity and Inclusion.
> 
> * `Q` Detail the process for measuring Event Demographics.
> * `A` We will provide pronoun stickers for badges and can count how many of whatever set are being used. We will do a rough headcount which will be flawed, but want to mainly see how we're doing event over event, roughly. We asked for pronouns (optional) during the Call for Papers so as to come up with a diverse line-up.
> * `Q` Provide an example of an opt-out option on the Event registration page if available.
> * `A` We decided not to ask for demographics information at the registration step. Several organizers come from groups underrepresented in tech and feel uncomfortable being "tracked".
> * `Q` Provide an example of a demographics text input box on the Event registration page if available.
> * `A` -
> 
> ### Event Demographics
> * [x]  **Measuring Demographics** - The Event has a process for measuring demographics.
> * [x]  **Opt-Out** - The Event provides an opportunity to opt-out of providing demographic data
> * [ ]  **Text Input** - The Event provides a text box to input variable demographics such as Gender, Race, or Ethnicity
> 
> ## Inclusive Experience at Event
> This event commits to the Code of Conduct at Event.
> 
> * `Q` Provide an example of the Event Feedback page if available.
> * `A` We will promote feedback surveys for attendees, speakers, and sponsors.
> * `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
> * `A` Absolutely! The way the project team is set up we get the experience from ASF's event team (Community over Code is the current iteration of ApacheCon), from SoftwareGuru (event agency) and a team of volunteers from the community. We have Chairs for all topic areas (think: sponsors, speakers, communications), I'm the Chair for DEI, and as such there's time allocated every meeting to discuss concerns and ideas..
> * `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
> * `A` Absolutely! We'll email feedback surveys and promote them during the closing of the event, and have a retrospective meeting with the team. There's already an effort ongoing to recruit next year's organizers and they'd get access to all notes at a handover.
> * `Q` How can attendees learn more about accessibility at the event?
> * `A` Linked directly from the homepage: https://eu.communityovercode.org/diversity-&-inclusion/ We hope to offer captioning for the event, pending sponsorship for "Live Captioning" in our prospectus: https://eu.communityovercode.org/files/community-over-code-prospectus-2024.pdf
> * `Q` Does the event platform allow attendees to suggest future accomodations for the event?
> * `A` Via the survey after the conference / opened during theclosing ceremony
> * `Q` Will the event platform be accessible to attendees and speakers after the event?
> * `A` We'll post the talk recordings publicly.
> 
> ### Inclusive Experience at Event
> * [x]  **Speaker Inclusivity** - The Event requests feedback from speakers regarding Diversity & Inclusion.
> * [x]  **Attendee Inclusivity** - The Event requests feedback from attendees regarding Diversity & Inclusion.
> * [x]  **Retention** - The Event incorporates feedback from past events, or has a strategy to incorporate feedback into future iterations of the event.
> * [x]  **Accessibility Requests** - Attendees are able to inquire if accomodations are available and make suggestions for future accomodations at events.
> * [x]  **Session Accessibility** - Event attendees are able to access the event platform after the event
> 
> ## Code of Conduct at Event
> This event commits to the Code of Conduct at Event.
> 
> * `Q` Is the code of conduct posted at Event venue?
> * `A` Yes, at the registration desk, and repeated in the opening slides on every day.
> * `Q` Provide a link for the Event Code of Conduct.
> * `A` https://eu.communityovercode.org/coc/
> 
> ### Code of Conduct at Event
> * [x]  **Findability** - It is possible to find the Code of Conduct on the Event website.
> * [x]  **Clarity** - Event Code of Conduct provides a definition of expected behaviour.
> * [x]  **Reporting venue** - The event has a venue for reporting violations of the CoC at the event website.
> * [x]  **Support at Event** - The Event Code of Conduct provided information about possible methods to provide support to victims of inappropriate behavior.
> * [x]  **Enforcement** - The participants in the Event are required to accept the Code of Conduct.
> 
> ## Diversity Access Tickets
> This event commits to the Diversity Access Tickets.
> 
> * `Q` How many different types of diversity access tickets are available for the event?
> * `A` We have discounted tickets for underrepresented groups in tech, as well as a discount for students. We offer a Women and Non-binary Open Source breakfast, pending sponsorship: https://eu.communityovercode.org/files/community-over-code-prospectus-2024.pdf
> * `Q` What are the criteria for qualifying for a diversity access ticket?
> * `A` Folks need to fill out a form, we trust that when they say that they're from a underrepresented group that they are. Students need to bring some kind of student identification with them to the event.
> * `Q` Provide a link to the page containing information about Diversity Access Tickets.
> * `A` https://eu.communityovercode.org/tickets/
> 
> ### Diversity Access tickets
> * [x]  **Availability** - The event provides one or more Diversity Access Tickets.
> * [x]  **Ticket allocation** - The Event has a process for allocating diversity access tickets.
> * [x]  **Findability** - The information about Diversity Access Tickets is public.
> 
> ## Family Friendliness
> This event commits to Family Friendliness.
> 
> * `Q` Does the Event provide childcare facilities for its attendees and speakers?
> * `A` Sadly childcare facilities are not budgetted for.
> * `Q` What are the other ways that a family-friendly environment is being created in the Event?
> * `A` -
> * `Q` Provide relevant links related to family friendliness at the Event.
> * `A` -
> 
> ### Family Friendliness
> * [ ]  **Availability** - The Event provides one or more services/facilities for families.
> * [ ]  **Findability** - The information about the family friendly services provided at the Event is easy to find on the website.

@ElizabethN I am done with this

**Comment by peculiaruc** [comment]
@ElizabethN  I am done with this

**Comment by Young-W1** [comment]
Hi, @adeyinkaoresanya ... I am done with this.

**Comment by adeyinkaoresanya** [comment]
@FloorD here is your badge! Congratulations and best of luck with the event! ✨ 🙌

**Comment by FloorD** [comment]
Thank you so much, on behalf of the entire team!
