### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by JoeMurray** [badging/event-diversity-and-inclusion#320]
The links in https://github.com/badging/event-diversity-and-inclusion/blob/v3/CHAOSS-metrics.md are broken on master and v3. Could they be fixed? Thanks! (I'm wanting to propose my community start using you!)

**Comment by adeyinkaoresanya** [comment]
@JoeMurray Thanks for reporting this issue. We will work on a fix as soon as possible

**Comment by ElizabethN** [comment]
Hi @JoeMurray! Thanks so much. We have a PR [here](https://github.com/badging/event-diversity-and-inclusion/pull/321) to fix those. I also added the three metrics we are working on adding in, for full transparency! Great catch!

**Comment by JoeMurray** [comment]
Wonderful. Thanks for what you folks are doing. Getting communities to focus the basics and measuring and getting oriented towards practices that are known or thought to lead to improvements in DEI. We can use it to help turn good intentions into effective actions.

**Comment by ElizabethN** [comment]
This has been fixed so I'm closing this issue. Thanks again for your support @JoeMurray ! 🤩
