### ISSUE TITLE
[Virtual Event] ChapelCon '24

### ISSUE THREAD

**Issue by sarah-coghlan** [badging/event-diversity-and-inclusion#327]
# Virtual Event Submission

## Requirements

- Event Name: ChapelCon '24
- Link to the Event Website: https://chapel-lang.org/ChapelCon24.html
- Provide verification that you are an event organizer: Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We will be providing a survey at the end of the event to collect this information
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` 
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` 

## Inclusive Experience at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` This is not yet available but will be after the event
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes - no example available, however
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes - we will utilize feedback collected after the event to improve upon next year's event
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes - we will provide attendees with a recording of the event (Zoom)

## Time Inclusion for Virtual Events

- [x] This event commits to Time Inclusion for Virtual Events.
  - `Q` Are speakers able to pre-record their presentations, as opposed to presenting them live?
  - `A` Yes
  - `Q` Can attendees change video quality on the Event platform while viewing a presentation?
  - `A` Yes

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://github.com/chapel-lang/chapel/blob/main/CODE_OF_CONDUCT.md
  
 ## Diversity Access Tickets
  
- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`

**Comment by adeyinkaoresanya** [comment]
Hi @KafayahL @Victorybrown Pinging you to make sure you saw this. Thank you!

**Comment by KafayahL** [comment]
Thank you for applying @sarah-coghlan. @adeyinkaoresanya I'm done with my review. Thank you!

**Comment by adeyinkaoresanya** [comment]
Thank you @KafayahL @divya-mohan0209  for taking time to review! ❤️

**Comment by Pizza-Ria** [comment]
Thank you so much @adeyinkaoresanya!!!!
