### ISSUE TITLE
[In-Person Event] CppCon 2024

### ISSUE THREAD

**Issue by linuxuser27** [badging/event-diversity-and-inclusion#337]
# In-Person Event Submission

## Requirements

- Event Name: CppCon 2024
- Link to the Event Website: https://cppcon.org/
- Are you an organizer of this event? Yes

## Event Demographics
- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Non-speaking attendees are not asked for any demographic information, other than preferred pronouns. All speakers are asked if they identify as an underrepresented minority in the technology industry.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` "Would you like to add your preferred pronouns to your conference badge?"
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` "Would you like to add your preferred pronouns to your conference badge?"

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` At the end of the conference all attendees (that is, speakers, volunteers, etc) are sent a survey asking questions and requesting feedback.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes. Purchasing menstrual products at the venue was reported to be very expensive. The conference decided this year to ensure they were complementary and will provide them in all restrooms arranged for the conference in the venue.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes. We will continue to elicit feedback from all attendees and integrate feedback to help improve our DEI goals.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` https://cppcon.org/accessibility/
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Yes, this is asked in the end of conference survey.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes. We also have a contact page https://cppcon.org/contact/.
## Code of Conduct at Event
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://cppcon.org/codeofconduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` There is a single "Support" ticket. Its primary goal is improving diversity and encouragement of underrepresented minorities in technology.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` https://cppcon.org/cppcon-2024-attendance-support-ticket-program/
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://cppcon.org/cppcon-2024-attendance-support-ticket-program/ 

## Family Friendliness
- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes - https://cppcon.org/child-care/.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` The venue has a myriad of family friendly options that can be used while parents are attending the conference - https://updates.gaylordhotels.com/WelcomeToGaylordRockies.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://updates.gaylordhotels.com/WelcomeToGaylordRockies
  
## Event Accessibility
  
 - [x] This event commits to Event Accessibility.
  - `Q` Is the Event in a wheelchair-accessible venue?
  - `A` Yes - https://cppcon.org/accessibility/
  - `Q` Are speakers given guidance about creating slides that are colorblind accessible?
  - `A` No.
  - `Q` Is signage at the event and the event website colorblind accessible?
  - `A` Yes.
  - `Q` Does the Event provide other accessibility accommodations, or will upon request?
  - `A` Yes.
  - `Q` Provide relevant links related to event accessibility at the Event.
  - `A` https://cppcon.org/accessibility/
  
## Event Location Inclusivity
  
 - [x] This event commits to Event Location Inclusivity.
 - `Q` Has the Event’s location been checked against lists of places of concern for the following demographics: sexual and gender minorities, people with disabilities, racial and ethnic minorities, women, or religious minorities?
 - `A` Yes.
 - `Q`  Have the Event's dates been checked for other events happening in the same location at the same time that could potentially bring harm to a subset of any attendees?
  - `A` Yes.
  - `Q` The Event website addresses or acknowledges any cause for concern for marginalized attendees.
  - `A` The conference actively communicates with all attendees when events that could impact them are discovered.

## Public Health and Safety
  
 - [x] This event commits to Public Health and Safety.
 - `Q` Have you participated in the Public Health Pledge Badging Program?
 - `A` No.
 - `Q` Provide a link to the PHPledge Badges received.
 - `A` 
 - `Q` Provide a link to publicly available information about public health and safety on the event website.
 - `A`

**Comment by Mo-wo** [comment]
Hi @linuxuser27,

I hope this message finds you well. I have reviewed your submission and would appreciate some clarification on a few points to assist in the review process:

1. Is the Code of Conduct (CoC) enforced? If so, at what point during the registration process are attendees asked to accept the event's CoC?
2. I noticed there is no guide for speakers on addressing colourblindness. Could this be provided before the event?
3. There appears to be no information on Public Health and Safety in your application. Could you please provide this information?

Your prompt response will be greatly appreciated and will help facilitate a thorough review. Thank you in advance for your cooperation.

cc: @adeyinkaoresanya

**Comment by linuxuser27** [comment]
@Mo-wo 

> 1. Is the Code of Conduct (CoC) enforced? If so, at what point during the registration process are attendees asked to accept the event's CoC?

This is a required checkbox during conference registration. All attendees (that is, speakers, volunteers, etc.) are required to acknowledge it. We also have a display highlighting out commitment to Diversity and Inclusion, with a QRCode link to the CoC, on a meter board at the registration desk throughout the conference.

> 2. I noticed there is no guide for speakers on addressing colourblindness. Could this be provided before the event?

Yes, this is something we can add to our speaker guidance. We have some suggestions at https://cppcon.org/submissions/ and https://cppcon.org/presenterinfo/. Would adding notes about colourblindness to these pages be sufficient?

> 3. There appears to be no information on Public Health and Safety in your application. Could you please provide this information?

We provide a physical flyer at the registration/information desk throughout the conference. A digital copy of the flyer can be found at https://docs.google.com/document/d/1YDHsIyV9x92cDEIMrvtEUWAYzx8OU8fTaFkyPuaNMsQ/edit?usp=sharing.

**Comment by adeyinkaoresanya** [comment]
@linuxuser27 I wanted to check in to know if you would like to apply for the [Public Health Badging Program](https://publichealthpledge.com/)  as suggested by @Mo-wo  or I should go ahead and run the results

**Comment by linuxuser27** [comment]
@Mo-wo

> Making the information available on the website will be sufficient, as it will inform attendees with colourblindness that their needs are being considered.

Are there recommended sites/resources that we can share with speakers for how best to meet these needs?

> Additionally, could you confirm if the digital copy of the flyer is available on the website?

Updated: https://cppcon.org/codeofconduct/

**Comment by Mo-wo** [comment]
@linuxuser27,

While we do not provide specific resources to organizers, the following general guidelines can assist you in developing a guide for the speakers:

**General Guidelines for Colorblind-Friendly Presentations**

1. Use High Contrast: Ensure there is a high contrast between text and background. Avoid using light text on a light background or dark text on a dark background.
2. Avoid Reliance on Color Alone: Utilize patterns, shapes, or text in addition to colour to convey information.
3. Use Colorblind-Friendly Palettes: Implement colour schemes that are distinguishable for individuals with colourblindness. Tools such as ColorBrewer can aid in selecting these palettes.
4. Test Your Materials: Employ tools and simulators to check how your materials appear to individuals with colour blindness.


In addition to the above guidelines, the following tool may also prove helpful for the speakers:

[Color Oracle Overview](http://colororacle.org/)
A free colour blindness simulator for Windows, Mac, and Linux that demonstrates how images and graphics will appear to people with different types of colour blindness.

**Comment by linuxuser27** [comment]
@Mo-wo Thanks. I've applied this notes to https://cppcon.org/presenterinfo/.

**Comment by Mo-wo** [comment]
Awesome! Good luck with your event @linuxuser27 
@adeyinkaoresanya I am done with my review.

**Comment by adeyinkaoresanya** [comment]
Thank you @Mo-wo for the efforts put into this!

> Awesome! Good luck with your event @linuxuser27 @adeyinkaoresanya I am done with my review.

**Comment by adeyinkaoresanya** [comment]
Thank you @winnerbright and @Mo-wo  for reviewing this application.

**Comment by adeyinkaoresanya** [comment]
@linuxuser27 Thank you for taking the time for this application. Your badge is ready! ✨

**Comment by linuxuser27** [comment]
@adeyinkaoresanya Thank you much! I've added the badge to our CoC page - https://cppcon.org/codeofconduct/.

A quick follow-up, when will our conference appear in the official list - https://badging.chaoss.community/event-badging/events?

**Comment by adeyinkaoresanya** [comment]
> @adeyinkaoresanya Thank you much! I've added the badge to our CoC page - https://cppcon.org/codeofconduct/.
> 
> A quick follow-up, when will our conference appear in the official list - https://badging.chaoss.community/event-badging/events?

Oh, it should be there by now. I will check to know why it is not. I will inform you when it is fixed.

**Comment by adeyinkaoresanya** [comment]
@linuxuser27 your event is on the official list now. You can check it [here](https://badging.chaoss.community/event-badging/events)

**Comment by linuxuser27** [comment]
Thank you much!
