### ISSUE TITLE
Slack access

### ISSUE THREAD

**Issue by djmitche** [badging/event-diversity-and-inclusion#339]
Hi! I see in https://github.com/badging/event-diversity-and-inclusion/issues/227#issuecomment-2137504358 that "all Badgers are in Slack now" but .. I'm not!

**Comment by adeyinkaoresanya** [comment]
> Hi! I see in [#227 (comment)](https://github.com/badging/event-diversity-and-inclusion/issues/227#issuecomment-2137504358) that "all Badgers are in Slack now" but .. I'm not!

@djmitche please kindly join the Slack channel [here](https://chaoss-workspace.slack.com/ssb/redirect). Thank you!

**Comment by djmitche** [comment]
It says I don't have an account on that workspace.

**Comment by djmitche** [comment]
Bump ^^ I think I'm being unnecessarily excluded?

**Comment by ElizabethN** [comment]
Hmm @djmitche sometimes the slack link is super weird. No clue why! Try [this one](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-28p56bayt-67TRjdA4yJWQmUd4hCzULg) and let us know if that works! If it doesn't then I can just send an invite directly to your email. We *reallllly* want you in Slack! :pray: 🫶

**Comment by djmitche** [comment]
I'm in! Thanks!
