### ISSUE TITLE
[In-Person Event] Conference for Open Source Coders, Users, and Promoters (COSCUP)

### ISSUE THREAD

**Issue by yoyo930021** [badging/event-diversity-and-inclusion#346]
# In-Person Event Submission

## Requirements

- Event Name: Conference for Open Source Coders, Users, and Promoters (COSCUP)
- Link to the Event Website: https://coscup.org/
- Are you an organizer of this event? Yes

## Event Demographics
- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` COSCUP is an event open to the public, which is gratuitous and no registration needed. Based on this design of the event, we measure the  participant demographics information in three main ways: 1. For proposal submitters and speakers, we collect their background information through the proposal submission process. The following information will be collected from speakers: Name/ID, Email, Self introduction, Resident country (optional), Affiliation (optional), Personal contact (optional), Pronouns (used for CNCF Transparency Reports) 2. By the number of badges given at the entrance, we can know the estimated number of participants at the event.  Meanwhile, the number of participants in each session will be recorded for knowing the number of actual participation. 3. Through our newsletter system, we will send a pre-event survey to all participants. This survey is optional, and participants can choose whether to provide or disclose their personal information. Last year's survey results can be referenced at https://coscup.org/2023-survey/report/.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` Since COSCUP does not require registration, providing information does not affect their participation rights. In the "participant survey," each participant can choose not to fill it out, and skip options are available for each survey item. For speakers, COSCUP only collects the basic information necessary for the agenda. Communities responsible for each track may collect additional information such as "student status," but these are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` There is no registration page as COSCUP is an open event for all. We only encourage participants to join the demographic survey. You can find the content of the survey in the following document: "COSCUP 2024 Attendee Survey" document: https://hackmd.io/JL_sgC8OT5WiVq67srqj-Q?view

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` There are two methods for COSCUP events to collect feedback from participants: one is online co-working notes that are open to all event volunteers. This coworking notes is editable and accessible for all volunteers, and all the feedback from volunteers are recorded here in event preparation, event execution and event closing periods. The other one is the NEWS page, by encouraging all participants and media to share their thoughts/feedback, people can see all the feedback from the public about this event. https://hackmd.io/@coscup/NEWS
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` From the previous feedback, we found many event volunteers are from other areas of Taiwan rather than Taipei, the event hosted city. It decreased the possibility of participation for people out of town. Since 2009, COSCUP provided accommodation for volunteers to support them.   The other change was swifting the preparation meetings from offline to online format since 2017. Considering the difference of geographic areas, working conditions, family situations and accessibilities, online meetings can better involve all volunteers. If the meeting requires a physical meetup, a subsidy for transportation will be provided.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we are planning to collect feedbacks by the following four methods:  1. Providing a post-event survey for attendees to collect their feedback on conference agenda, processes, venue, and community booths and more. By this, to improve the events in the future.  2. Each host community of tracks will send the post-event survey to speakers in their track as a reference for future agenda designing.  3. "Community Reporters" to collect the onsite observations and feedback on  key points, sessions, and venue matters. Those community reporters are selected from volunteers who are interested in being event observers. 4. Continuously holding volunteer reviewing meetings to consolidate feedback collected during the process and through the aforementioned methods, in order to improve future event planning.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` COSCUP is held at the National Taiwan University of Science and Technology buildings. all of these buildings are equipped with accessible ramps, universal restrooms, covered corridors, and elevators.  The information about these facilities can be found on the COSCUP website (https://coscup.org/2023/en/venue) and the university's website (https://student.ntust.edu.tw/p/412-1053-8444.php?Lang=zh-tw). Additionally, large maps will be posted on the entrance of each floor to assist participants find the relative locations. There will also be help desks at the entrance of the buildings to provide assistance and information on accessibility upon request.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` COSCUP is an annual event, and all information is open to the public through various online platforms, from preparation, volunteer recruitment, event days, sessions, to venue details. Participants can directly communicate and provide feedback to the organizers in real-time. Besides, the feedback from the year before is incorporated into the planning process for the following year's event. Meanwhile, participants can suggest facilities and services for future events through COSCUP’s social platforms, which include Facebook page, X, Instagram, Mastodon, and Telegram channels.  Lastly, for the prompt response to immediate and emergency needs in the event, participants can give their feedback to the help desk, and there will be a team of volunteers to give immediate responses. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, COSCUP is an annual event that has its own official website, the conference videos, presentations, and collaborative documents every year are archived on the website. All these records and information can be found in the footer at https://coscup.org .
## Code of Conduct at Event
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` The code of conduct is not printed and posted as physical copies, but the full text and linkages are delivered to all participants fully in the three major information platforms of the event: official website, event app and the opening ceremony.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` COSCUP Code of Conduct: https://hackmd.io/@coscup/cococo-en

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` To encourage broader participation, since 2020, COSCUP clearly stated on the official website that registration or ticket purchase is not required, allowing anyone to participate freely. Additionally, to reward all contributors in the open-source field, we collaborate with the Open Culture Foundation to provide the “Open Source Contributor VIP Pass” to these contributors. With the pass, the contributors can redeem free beverages or a free photography service during the event. (the pass application details available at: https://docs.google.com/forms/d/e/1FAIpQLSe2obc5467kCZgVmrsyR2T8FRkgHeOoc1GrHJYPeT8FgWtO1Q/viewform) 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` This event does not require registration or ticket purchase. We aim to welcome everyone without any barriers. All relevant information is disclosed on the official website.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` This event does not require registration or ticket purchase. However, the Open Source Contributor VIP Pass can be applied for the open source contributors in order to reward their contribution. The pass can be applied by this form: https://docs.google.com/forms/d/e/1FAIpQLSe2obc5467kCZgVmrsyR2T8FRkgHeOoc1GrHJYPeT8FgWtO1Q/viewform . 

## Family Friendliness
- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` We offer parenting activities for families with children. Children under 10 must be accompanied by their parent, while those over 10 can register the activities independently. Those activities in previous years can be found here: https://blog.coscup.org/2023/07/parent-child-workshops.html .
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` The event venue offers water dispensers, diaper-changing stations, and free spaces for resting. We also provide activities such as open-source themed board games, Yoga Wine, Massage Station, and the Open Source Fair. Those activities are all family-friendly. Additionally, the event service desk provides pronoun stickers and language stickers.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` This year's ancillary activities mostly are still being planned and have not been announced. At the current stage, we have planned the Open Source Fair for this year, and the related information can be found in the May newsletter: https://volunteer.coscup.org/docs/about_coscup/newsletters/2024/20240515/ .  The introduction of Yoga Wine and the Massage Station can be found in last year’s announcement: https://blog.coscup.org/2023/07/introducing-healing-market-with-yoga.html .
  
## Event Accessibility
  
 - [x] This event commits to Event Accessibility.
  - `Q` Is the Event in a wheelchair-accessible venue?
  - `A` Yes, COSCUP is held at buildings within the National Taiwan University of Science and Technology, which offers wheelchair ramps, universal restrooms, covered corridors, and elevators.
  - `Q` Are speakers given guidance about creating slides that are colorblind accessible?
  - `A` We are in the process of adding general guidelines for colorblind-friendly presentations to the speaker handbook. The progress can be tracked on the GitHub issue: https://github.com/COSCUP/COSCUP-Volunteer/issues/215 
  - `Q` Is signage at the event and the event website colorblind accessible?
  - `A` Currently, our event signage and website have not been specifically designed for colorblind accessibility.
  - `Q` Does the Event provide other accessibility accommodations, or will upon request?
  - `A` Participants can submit their needs and suggestions through COSCUP’s social media platforms or reach out to the community contacts of the tracks before the event. On the day of the event, they also can directly request accommodations at the event service desk.
  - `Q` Provide relevant links related to event accessibility at the Event.
  - `A` Information about the facilities can be found on the COSCUP website https://coscup.org/2023/en/venue and on the NTUST website https://student.ntust.edu.tw/p/412-1053-8444.php?Lang=zh-tw .
  
## Event Location Inclusivity
  
 - [ ] This event commits to Event Location Inclusivity.
- `Q` Has the Event’s location been checked against lists of places of concern for the following demographics: sexual and gender minorities, people with disabilities, racial and ethnic minorities, women, or religious minorities?
- `A` To the best of our ability, we have ensured that the event location at NTUST in Taipei is suitable and safe for all attendees. While we have not specifically checked the location against formal lists of concern, we have taken several factors into consideration. NTUST is in the heart of Taipei, a city known for its accessibility, including public transportation and private vehicle parking. The area offers a wide range of accommodation, dining, and entertainment options. Furthermore, Taiwan is ranked as the fourth safest country in the world according to the NUMBEO Crime Index by Country 2024. Taiwan's legal framework supports equality and non-discrimination, further ensuring a safe and inclusive atmosphere for everyone.
- `Q` Have the Event's dates been checked for other events happening in the same location at the same time that could potentially bring harm to a subset of any attendees?
- `A` There are no other large-scale events scheduled at NTUST during the COSCUP event dates. On the event days, only a few classrooms and research labs will be used for NTUST's summer courses, which do not pose any potential harm to COSCUP participants. We have coordinated with NTUST to ensure that the campus environment remains safe and conducive for all attendees.
- `Q` The Event website addresses or acknowledges any cause for concern for marginalized attendees.
- `A` Any major information is announced on the COSCUP official website, Blog, social platforms (FB, IG, X, Mastodon, Telegram channel, Telegram group), and the app "OPass." To address concerns of marginalized attendees, we provide detailed information on accessibility features, gender-neutral restrooms, and the process for reporting inappropriate behaviour. Each building used for the event has a service desk for guidance. COSCUP has a dedicated CoC team, and participants can contact team members via coc@coscup.org or at the service desk to address concerns or needs at any time.

## Public Health and Safety
  
 - [ ] This event commits to Public Health and Safety.
 - `Q` Have you participated in the Public Health Pledge Badging Program?
 - `A` 
 - `Q` Provide a link to the PHPledge Badges received.
 - `A` 
 - `Q` Provide a link to publicly available information about public health and safety on the event website.
 - `A`

**Comment by Mo-wo** [comment]
Hello @yoyo930021, 

Thank you for your application. I noticed the sections on 'Event Location Inclusivity' and 'Public Health and Safety' are unanswered. Could you please confirm whether this was intentional or an oversight? 

Thank you in advance for your prompt response

**Comment by yoyo930021** [comment]
> Hello @yoyo930021,
> 
> Thank you for your application. I noticed the sections on 'Event Location Inclusivity' and 'Public Health and Safety' are unanswered. Could you please confirm whether this was intentional or an oversight?
> 
> Thank you in advance for your prompt response

Hi Mo-wo

Thank you for bringing the incomplete sections to our attention. We appreciate the opportunity to provide further information.

Regarding the “Event Location Inclusivity”, we initially left this section blank because we felt COSCUP did not have sufficient commitments in this area at the time of application. However, after discussions with the team, I would like to supplement our response with what we are currently doing:

- `Q` Has the Event’s location been checked against lists of places of concern for the following demographics: sexual and gender minorities, people with disabilities, racial and ethnic minorities, women, or religious minorities?
- `A` To the best of our ability, we have ensured that the event location at NTUST in Taipei is suitable and safe for all attendees. While we have not specifically checked the location against formal lists of concern, we have taken several factors into consideration. NTUST is in the heart of Taipei, a city known for its accessibility, including public transportation and private vehicle parking. The area offers a wide range of accommodation, dining, and entertainment options. Furthermore, Taiwan is ranked as the fourth safest country in the world according to the NUMBEO Crime Index by Country 2024. Taiwan's legal framework supports equality and non-discrimination, further ensuring a safe and inclusive atmosphere for everyone.
- `Q` Have the Event's dates been checked for other events happening in the same location at the same time that could potentially bring harm to a subset of any attendees?
- `A` There are no other large-scale events scheduled at NTUST during the COSCUP event dates. On the event days, only a few classrooms and research labs will be used for NTUST's summer courses, which do not pose any potential harm to COSCUP participants. We have coordinated with NTUST to ensure that the campus environment remains safe and conducive for all attendees.
- `Q` The Event website addresses or acknowledges any cause for concern for marginalized attendees.
- `A` Any major information is announced on the COSCUP official website, Blog, social platforms (FB, IG, X, Mastodon, Telegram channel, Telegram group), and the app "OPass." To address concerns of marginalized attendees, we provide detailed information on accessibility features, gender-neutral restrooms, and the process for reporting inappropriate behaviour. Each building used for the event has a service desk for guidance. COSCUP has a dedicated CoC team, and participants can contact team members via coc@coscup.org or at the service desk to address concerns or needs at any time.


For the “Public Health and Safety” section, our current volunteer team doesn’t have the capacity to apply for the Public Health Pledge Badging Program. While we have AEDs, first aid kits, and a list of nearby hospitals for staff, we currently lack the resources to make these internal documents public and translated. We acknowledge the importance of this area and will work towards improving our public health measures in the future.

Additionally, we have noticed that the "Event submission requirements" and "guidelines" links provided by the badging-bot for applicants are broken. Could you please verify if these are the correct document links for [Event submission requirements](https://github.com/badging/event-diversity-and-inclusion/blob/main/info-for-applicants/requirements.md) and [guidelines](https://github.com/badging/event-diversity-and-inclusion/blob/main/info-for-applicants/guidelines.md)?

We sincerely appreciate your understanding, thank you for your support and guidance.

**Comment by Mo-wo** [comment]
Hi @yoyo930021,

Thank you for your response. However, this information needs to be updated in the main application for easy reference in the future.

> Q Has the Event’s location been checked against lists of places of concern for the following demographics: sexual and gender minorities, people with disabilities, racial and ethnic minorities, women, or religious minorities?
> A To the best of our ability, we have ensured that the event location at NTUST in Taipei is suitable and safe for all attendees. While we have not specifically checked the location against formal lists of concern, we have taken several factors into consideration. NTUST is in the heart of Taipei, a city known for its accessibility, including public transportation and private vehicle parking. The area offers a wide range of accommodation, dining, and entertainment options. Furthermore, Taiwan is ranked as the fourth safest country in the world according to the NUMBEO Crime Index by Country 2024. Taiwan's legal framework supports equality and non-discrimination, further ensuring a safe and inclusive atmosphere for everyone.
> Q Have the Event's dates been checked for other events happening in the same location at the same time that could potentially bring harm to a subset of any attendees?
> A There are no other large-scale events scheduled at NTUST during the COSCUP event dates. On the event days, only a few classrooms and research labs will be used for NTUST's summer courses, which do not pose any potential harm to COSCUP participants. We have coordinated with NTUST to ensure that the campus environment remains safe and conducive for all attendees.
> Q The Event website addresses or acknowledges any cause for concern for marginalized attendees.
> A Any major information is announced on the COSCUP official website, Blog, social platforms (FB, IG, X, Mastodon, Telegram channel, Telegram group), and the app "OPass." To address concerns of marginalized attendees, we provide detailed information on accessibility features, gender-neutral restrooms, and the process for reporting inappropriate behaviour. Each building used for the event has a service desk for guidance. COSCUP has a dedicated CoC team, and participants can contact team members via [coc@coscup.org](mailto:coc@coscup.org) or at the service desk to address concerns or needs at any time.

Yes, the links provided are correct. Is there any additional information you are seeking or hoping to find in these links?

>  Additionally, we have noticed that the "Event submission requirements" and "guidelines" links provided by the badging-bot for applicants are broken. Could you please verify if these are the correct document links for [Event submission requirements](https://github.com/badging/event-diversity-and-inclusion/blob/main/info-for-applicants/requirements.md) and [guidelines](https://github.com/badging/event-diversity-and-inclusion/blob/main/info-for-applicants/guidelines.md)?

**Comment by yoyo930021** [comment]
> Thank you for your response. However, this information needs to be updated in the main application for easy reference in the future.

We have completed.

> Yes, the links provided are correct. Is there any additional information you are seeking or hoping to find in these links?

No thanks.

**Comment by adeyinkaoresanya** [comment]
Hello @riahtgl checking in to see make sure you got the notification

**Comment by Mo-wo** [comment]
Thank you @yoyo930021 for the update. Good luck with your event.
@adeyinkaoresanya I am done with my review.

**Comment by riahtgl** [comment]
Thank you @yoyo930021 for your application
@adeyinkaoresanya I'm done with my review.

**Comment by adeyinkaoresanya** [comment]
> Thank you @yoyo930021 for the update. Good luck with your event. @adeyinkaoresanya I am done with my review.

Thank you very much @Mo-wo for the detailed review!

**Comment by adeyinkaoresanya** [comment]
> Thank you @yoyo930021 for your application @adeyinkaoresanya I'm done with my review.

@riahtgl Thank you for the review, Gloria!

**Comment by adeyinkaoresanya** [comment]
@yoyo930021 Your badge is ready! 🥇

**Comment by yoyo930021** [comment]
Thank you very much.

**Comment by yoyo930021** [comment]
Do you have any estimated time for adding the event to the README? Or do we submit a PR?

**Comment by adeyinkaoresanya** [comment]
> Do you have any estimated time for adding the event to the README? Or do we submit a PR?
@yoyo930021 we no longer use the READMe to display the badged events. We display them on the badging website now. Find it [here](https://badging.chaoss.community/event-badging/events)
