### ISSUE TITLE
[In-Person Event] IndiaFOSS 2024

### ISSUE THREAD

**Issue by RuchikaByte** [badging/event-diversity-and-inclusion#348]
# In-Person Event Submission

## Requirements

- Event Name: IndiaFOSS 2024
- Link to the Event Website: https://fossunited.org/indiafoss/2024
- Are you an organizer of this event? yes

## Event Demographics
- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` We do not collect demographic information from speakers during the registration process. As a privacy-centric FOSS event, we strive to avoid requesting such data altogether.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` Opting out is not possible because we need certain details for accounting purposes. However, we ensure that we collect only the bare minimum information required from attendees.`
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` NA

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` https://indiafoss.net/2023/feedback/new and through our https://forum.fossunited.org/t/indiafoss-3-0-feedback/2497
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes. we analyze feedback from previous events to identify areas for improvement. For example, based on feedback from IndiaFOSS3.0, we have made some changes in the diversity scholarships and included improved accessibility services.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` yes. we will collect and analyse feedback from IndiaFOSS 2024 to continue enhancing our DEI efforts. These forms will include specific questions related to DEI, such as the inclusivity of the event environment, accessibility of sessions, and overall satisfaction with DEI initiatives.We will also conduct focus groups and interviews with a diverse selection of participants to gain deeper insights into their experiences and suggestions for improvement. Collected feedback will be analyzed quantitatively and qualitatively to identify trends, strengths, and areas needing improvement. We will compile this data into a comprehensive report.Based on the feedback analysis, we will develop actionable insights and specific initiatives to address identified gaps and enhance DEI efforts. This may include improving accessibility features, increasing the diversity of speakers and attendees, and enhancing support services. We will prioritise implementing changes that have a significant impact on inclusivity and accessibility for future events. Regular check-ins and reviews will ensure that feedback from each event is incorporated into the planning and execution of subsequent events, fostering an environment of continuous improvement. Attendees and speakers will be encouraged to engage with the event organisers/volunteers to provide ongoing feedback and suggestions
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` The IndiaFOSS 2024 website will soon feature accessibility details. This will includes details about venue accessibility, available resources and additional accommodations related to diversity scholarship.
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` yes, through feedback form. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes. The event platform will remain accessible after the event. https://fossunited.org/indiafoss/2024
## Code of Conduct at Event
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, the Code of Conduct is prominently displayed on our website and announced at the event venue during the conference.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://fossunited.org/code-of-conduct

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We offer diversity access tickets for the event through a scholarship program which is meant for providing opportunities for students, women, and underrepresented communities. The availability of these tickets depends on the number of applications we receive, amount we raise and the geographic locations of the applicants. There is no fixed number of tickets; it will be determined based on the criteria mentioned.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The Diversity Scholarship is intended for individuals from underrepresented groups in the tech community, including women, LGBTQ+ individuals, people with disabilities, and individuals from marginalised socio-economic backgrounds. Applicants must demonstrate their involvement or interest in FOSS and their financial need.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://forum.fossunited.org/t/diversity-scholarship-indiafoss-2024/3596 

## Family Friendliness
- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, we are planning to offer on-site childcare facilities at the event, as we have taken into account feedback from previous experiences that highlighted the need for such services.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` In addition to providing on-site childcare facilities, we will also include breastfeeding/ resting rooms
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` TBD
  
## Event Accessibility
  
 - [x] This event commits to Event Accessibility.
  - `Q` Is the Event in a wheelchair-accessible venue?
  - `A` Yes, the venue is wheelchair accessible. We are aware that a few areas need additional attention and are actively working to address these to ensure a fully accessible experience for all attendees.
  - `Q` Are speakers given guidance about creating slides that are colorblind accessible?
  - `A` Yes, guidance on creating colourblind accessible slides will be included in the guidelines provided to speakers or on our website. We aim to ensure that all presentations are accessible to a diverse audience.
  - `Q` Is signage at the event and the event website colorblind accessible?
  - `A` Yes. 
  - `Q` Does the Event provide other accessibility accommodations, or will upon request?
  - `A` Yes, we provide additional accommodations upon request, such as sign language interpreters. We ask for any special needs from our participants, speakers, and diversity scholars in the respective registration form. https://forum.fossunited.org/t/diversity-scholarship-indiafoss-2024/3596
  - `Q` Provide relevant links related to event accessibility at the Event.
  - `A` TBD
  
## Event Location Inclusivity
  
 - [x] This event commits to Event Location Inclusivity.
 - `Q` Has the Event’s location been checked against lists of places of concern for the following demographics: sexual and gender minorities, people with disabilities, racial and ethnic minorities, women, or religious minorities?
 - `A` Yes, we have checked and ensured that our location is inclusive and safe for all attendees.
 - `Q`  Have the Event's dates been checked for other events happening in the same location at the same time that could potentially bring harm to a subset of any attendees?
  - `A` Yes, we have checked and confirmed that no conflicting events pose a risk.
  - `Q` The Event website addresses or acknowledges any cause for concern for marginalized attendees.
  - `A` Our communications include information on resources and a clear code of conduct to ensure a safe environment for all attendees.

## Public Health and Safety
  
 - [x] This event commits to Public Health and Safety.
 - `Q` Have you participated in the Public Health Pledge Badging Program?
 - `A` No, we have not participated in the Public Health Badging Program.
 - `Q` Provide a link to the PHPledge Badges received.
 - `A` NA
 - `Q` Provide a link to publicly available information about public health and safety on the event website.
 - `A`

**Comment by Mo-wo** [comment]
Hello @RuchikaByte, thank you for your application. I noticed a few answers marked with "TBD." Please let me know if you'd like to leave them as is, or should we wait for the relevant information before assigning your badge?

**Comment by RuchikaByte** [comment]
The answers marked with "TBD" are a work in progress and may take some time to complete. However, you can go ahead with assigning the badge based on the information provided so far.

**Comment by Mo-wo** [comment]
Okay @RuchikaByte good luck with your event.
@adeyinkaoresanya I am done with my review.

**Comment by riahtgl** [comment]
Thank you @RuchikaByte for your application
Hi @adeyinkaoresanya I am done with my review.

**Comment by adeyinkaoresanya** [comment]
@riahtgl @Mo-wo Thank you so much!

**Comment by adeyinkaoresanya** [comment]
@RuchikaByte Your badge is ready! 🥇

**Comment by RuchikaByte** [comment]
Awesome! Thank you so much! 😊 @Mo-wo @adeyinkaoresanya @riahtgl
