### ISSUE TITLE
[In-Person Event] Open Compliance Summit 2024

### ISSUE THREAD

**Issue by mgoytia04** [badging/event-diversity-and-inclusion#352]
# In-Person Event Submission

## Requirements

- Event Name: Open Compliance Summit 2024
- Link to the Event Website: https://events.linuxfoundation.org/open-compliance-summit/ 
- Are you an organizer of this event? Yes

## Event Demographics
- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` For data privacy reasons, we have removed the (optional) attendee demographics questions from our event registration forms. However, in the registration process to better cater to our attendees to ensure they can enjoy the event to the fullest, we ask the following questions:  Do you have a disability that we should be mindful of as we try to accommodate everyone for this event?  Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s).  (Please note, none of these questions are required, they are optional for attendees to fill out).
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` All demographic questions on our registration page are optional.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` On our event registration, we ask the question:  "Do you have a disability that we should be mindful of as we try to accommodate everyone for this event?" Sub question when answer is YES: Please provide additional details here: (text input box).

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, the information gathered from the previous year's feedback was considered when planning 2024. 
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes, we continue to collect feedback to be considered for future events.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` Under the Diversity and Inclusion page on the event website there is a section that speaks to venue accessibility. (https://events.linuxfoundation.org/open-compliance-summit/attend/diversity-inclusion/#onsite-resources) 
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Our registration form includes a text input box for anyone who may require additional assistance or accommodation for the existing event. We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events made easily accessible should anyone want to share their feedback prior, during, or after the event.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Open Compliance Summit is an in-person-only event, and there is no recording or event platform.
## Code of Conduct at Event
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the onsite Diversity & Inclusion resources flyer. This flyer has all DEI-related resources, as well as event team members they can contact should they need anything onsite. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/open-compliance-summit/attend/code-of-conduct/ 

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We offer travel funding to our event. There is no limit to the number of travel fundings that we offer for this event. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The Linux Foundation’s Travel Fund is intended to enable open source developers and community members to attend events that they would otherwise be unable to attend due to a lack of funding. We place an emphasis on funding applicants who are from historically underrepresented or untapped groups and/or those of lower socioeconomic status. If you work for a company that has the ability to fund your travel, we ask that you not apply, to save funds for those that need it.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/open-compliance-summit/attend/travel-funding/  

## Family Friendliness
- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, we are offering complimentary onsite child care this year.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We offer our attendees a private nursing room that they can access throughout the event, gender-neutral restrooms, and pronoun stickers. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://events.linuxfoundation.org/open-compliance-summit/attend/diversity-inclusion/#general 
  
## Event Accessibility
  
 - [x] This event commits to Event Accessibility.
  - `Q` Is the Event in a wheelchair-accessible venue?
  - `A` Yes, we choose to host our events in venues that are wheelchair-accessible. We note this information during our research and site visits in order to find venues that are accessible for all. We also work closely with the venue to ensure we have the best ways to accommodate any attendees who will be using a wheelchair onsite.
  - `Q` Are speakers given guidance about creating slides that are colorblind accessible?
  - `A` Yes, in our pre-event communications and on our website we share a Speaker Guide that includes presentation templates and guidelines. Speakers are directed to create slides that are colorblind accessible. 
  - `Q` Is signage at the event and the event website colorblind accessible?
  - `A` Yes, we do pre-event testing of our event website to ensure it is colorblind accessible. We also collaborate with our Creative Services team to ensure that our event signage is colorblind accessible.
  - `Q` Does the Event provide other accessibility accommodations, or will upon request?
  - `A` Yes, we offer several standard accessibility accommodations, such as a Zen Zone (quiet room), accessible washrooms, access to session slides during and after the event, gender-neutral restrooms, childcare, nursing rooms, and adequate space and guidance in crowded areas. We also offer several accommodations to attendees based on need, such as sign language interpreters, specialty meals, and sighted guides.
  - `Q` Provide relevant links related to event accessibility at the Event.
  - `A` https://events.linuxfoundation.org/open-compliance-summit/attend/diversity-inclusion/#onsite-resources 
  
## Event Location Inclusivity
  
 - [x] This event commits to Event Location Inclusivity.
 - `Q` Has the Event’s location been checked against lists of places of concern for the following demographics: sexual and gender minorities, people with disabilities, racial and ethnic minorities, women, or religious minorities?
 - `A` Yes, the event organizers have used resources such as EqualDex, Human Rights Watch, and the United Nations website to research the social and political climate of Tokyo to ensure all attendees will have a welcoming environment during the event. 
 - `Q`  Have the Event's dates been checked for other events happening in the same location at the same time that could potentially bring harm to a subset of any attendees?
  - `A` Yes, during our RFP process, we ask venues in the event location to provide information on national and local holidays, as well as additional events that occur at the same time, to ensure that we will not be in a location that will be hosting events or festivals that could cause harm in any form to our attendees. 
  - `Q` The Event website addresses or acknowledges any cause for concern for marginalized attendees.
  - `A` We acknowledge and support marginalized attendees by including our Code of Conduct in all pre-event communications, and we also provide local resources for trauma and emergencies on our website and onsite resource flyers. 

## Public Health and Safety
  
 - [x] This event commits to Public Health and Safety.
 - `Q` Have you participated in the Public Health Pledge Badging Program?
 - `A` No.
 - `Q` Provide a link to the PHPledge Badges received.
 - `A` N/A.
 - `Q` Provide a link to publicly available information about public health and safety on the event website.
 - `A` https://events.linuxfoundation.org/open-compliance-summit/attend/health-and-safety/

**Comment by Maryblessing** [comment]
hi @adeyinkaoresanya you can assign this issue to me!

**Comment by adeyinkaoresanya** [comment]
@Maryblessing @Young-W1 Hi! Making sure you got this ping!

**Comment by Maryblessing** [comment]
Hi @adeyinkaoresanya, I'm done with my review

**Comment by Young-W1** [comment]
Hey @adeyinkaoresanya, I am done with my review.

**Comment by adeyinkaoresanya** [comment]
Thank you so much @Young-W1 and @Maryblessing

**Comment by adeyinkaoresanya** [comment]
@mgoytia04 Your badge is ready!
