### ISSUE TITLE
[In-Person Event] She Code Africa Summit 2024

### ISSUE THREAD

**Issue by Maryblessing** [badging/event-diversity-and-inclusion#354]
# In-Person Event Submission

## Requirements

- Event Name: She Code Africa Summit 2024
- Link to the Event Website: https://summit.shecodeafrica.org/
- Are you an organizer of this event? Yes. I am the community manager and co-organiser of the SCA Summit

## Event Demographics
- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` The key demographics relevant to this event are gender and geographic location and this event is solely for Africa women and we do not collect any additional demographics data. We only accept female speakers at our summit but due to the structure we have for this year's event, the team reached out to female speakers ourselve.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` No opt-out option as we don't collect any demographic question.
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` No input box for the same reason mentioned above.

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` We send out a post-event survey to all attendees where we ask the following multi choice question: "Please rate the following aspects of this year's summit: Date & time, Food and beverages, Summit location inclusivity and Program agenda.'  We also encourage all attendees to share any ideas with us during the event, and have the contact information for the community manager and specific event program team made easily accessible should anyone want to share their feedback prior, during, or after the event on the website
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, any feedback provided in the post-event survey is shared with event stakeholders and the planning committee for discussion on implementation.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` We continue to use our post-event surveys as a consideration to improve future events.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` We include resources available to our attendees on the event webpage: https://summit.shecodeafrica.org/diversity-and-inclusion
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A`  We encourage all attendees to share any ideas with us during the event, and have the contact information for the community manager and specific event program team made easily accessible should anyone want to share their feedback prior, during, or after the event on the website and on our communication channels; like our Slack community etc
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Keynote and other event recordings will be made available on the She Code Africa YouTube Channel a few days after the event concludes
## Code of Conduct at Event
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` The event code of conduct is on the event website for easy reference. We do not print it onsite but are linked in event emails and shared with online viewers on the event day.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://summit.shecodeafrica.org/diversity-and-inclusion

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We partnered with a few organizations to provide diversity access tickets to women who otherwise wouldn't afford to attend.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` There's no specific criteria for qualifying. We only encourage that recipients truly have a need for it before claiming one.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://summit.shecodeafrica.org/diversity-and-inclusion 

## Family Friendliness
- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes, we are offering complimentary onsite child care this year.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` In addition to childcare facilities, we offer our Muslim attendees a private prayer room and also offer free intra-state transportation to and from selected locations within event host country.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://summit.shecodeafrica.org/diversity-and-inclusion
  
## Event Accessibility
  
 - [x] This event commits to Event Accessibility.
  - `Q` Is the Event in a wheelchair-accessible venue?
  - `A` While this year's venue may have some accessibility limitations, we encourage people with any mobility needs or require further accessibility information to let us know in advance by contacting the community team or speak to a trained volunteer at the summit site
  - `Q` Are speakers given guidance about creating slides that are colorblind accessible?
  - `A` Our design team provide our speakers with slide template that are colorblind accessible.
  - `Q` Is signage at the event and the event website colorblind accessible?
  - `A` At this time, we are not able to provide signage at the event.
  - `Q` Does the Event provide other accessibility accommodations, or will upon request?
  - `A` Yes, we offer several standard accessibility accommodations, such as a quiet/prayer room, access to session slides after the event, complimentary onsite child care and closed captioning.  We also encourage attendees to contact us if they require any further help.
  - `Q` Provide relevant links related to event accessibility at the Event.
  - `A` https://summit.shecodeafrica.org/diversity-and-inclusion
  
## Event Location Inclusivity
  
 - [x] This event commits to Event Location Inclusivity.
 - `Q` Has the Event’s location been checked against lists of places of concern for the following demographics: sexual and gender minorities, people with disabilities, racial and ethnic minorities, women, or religious minorities?
 - `A` While this year's venue may have some accessibility limitations, we encourage people with any special needs or require further accessibility information to let us know in advance by contacting the community team or speak to a trained volunteer at the summit site
 - `Q`  Have the Event's dates been checked for other events happening in the same location at the same time that could potentially bring harm to a subset of any attendees?
  - `A` Yes, it has been.
  - `Q` The Event website addresses or acknowledges any cause for concern for marginalized attendees.
  - `A` We acknowledge and support all attendees by including expected behaviour in the event Code of Conduct, and we also provide local resources for emergencies and medical care on our website. 

## Public Health and Safety
  
 - [ ] This event commits to Public Health and Safety.
 - `Q` Have you participated in the Public Health Pledge Badging Program?
 - `A` No, I haven't.
 - `Q` Provide a link to the PHPledge Badges received.
 - `A` n/a
 - `Q` Provide a link to publicly available information about public health and safety on the event website.
 - `A` n/a

**Comment by Young-W1** [comment]
Hi @ElizabethN,  @adeyinkaoresanya! I'd like for this to be assigned to me!

**Comment by Mo-wo** [comment]
Hi @ElizabethN, @adeyinkaoresanya! I's like for this to be assigned to me too

**Comment by adeyinkaoresanya** [comment]
@Mo-wo @Young-W1 

Thank you for the swift response to this application!

**Comment by adeyinkaoresanya** [comment]
@Maryblessing Your badge is ready!

**Comment by Young-W1** [comment]
Hi @adeyinkaoresanya , I'm done with my review.

**Comment by Maryblessing** [comment]
Thank you so much everyone!
