### ISSUE TITLE
Excessive issues opened on this repository

### ISSUE THREAD

**Issue by Nebrethar** [badging/event-diversity-and-inclusion#36]
Hey everyone! Sorry for the 20 or so issues I automated tonight.  I'm testing out a new feature that I'll be excited to show you!

Will close this issue when the feature is released :)

**Comment by Ruth-ikegah** [comment]
That's nice, I was already scared to see the tons of mails. I can't wait to hear the cool feature!

**Comment by Nebrethar** [comment]
Closing because the bot is out and about!
