### ISSUE TITLE
[In-Person Event] FOSS Backstage 2025

### ISSUE THREAD

**Issue by plainschwarz-team** [badging/event-diversity-and-inclusion#365]
# In-Person Event Submission

## Requirements

- Event Name: FOSS Backstage 2025
- Link to the Event Website: https://25.foss-backstage.de/
- Are you an organizer of this event? Yes

## Event Demographics
- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Event demographics for FOSS Backstage is measured primarily using our voluntary demographic survey, which is attached but not connected to the registration process (i.e. the survey is external and anonymous and not connected to the personal data entered during registration). We have very few speaker/attendee demographic question directly included in the registration due to privacy concerns.
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` “Prefer not to answer” options are available for all demographic questions asked during the registration process
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` For example, the questions “What are your pronouns?” provides a list of pronouns including a “prefer not to answer” option), as well as an option to provide pronouns not listed in a text input field: “My pronouns are: [text input]”

## Inclusive Experience at Event
    
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` Feedback can be provided using our feedback survey, which will be send to every speaker, attendee and volunteer after the conference. Feedback regarding diversity, accessibility and inclusivity will be published in our annual Diversity Report, which is available for everyone on our website.
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes. For example, at FOSS Backstage 2022 we got feedback that holding the conference at the end of the week was difficult for some due to religious holidays. As a consequence, we since check dates more carefully to make sure the conference date is not coinciding with religious holidays.
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Yes. As mentioned above, we will collect feedback using our feedback survey. Feedback regarding diversity, accessibility and inclusivity will be published in our Diversity Report. Feedback will also be discussed after the event within the team.
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` By visiting the pages on diversity & inclusivity (https://25.foss-backstage.de/diversity-inclusion/) as well as on accessibility (https://25.foss-backstage.de/accessibility/).
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Attendees and speakers can suggest future improvements for the event in our annual feedback survey or send feedback to a dedicated Email address, which is linked on our Diversity and Accessibility pages on our website.
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Our website will be available after the event. Our online platform Venueless is also available for a limited time after the event. The talks and sessions will be made available for everyone on our YouTube-Channel after the event. (https://www.youtube.com/c/PlainSchwarzUG
## Code of Conduct at Event
- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` The code of conduct is posted on our website. Attendees and speaker must tick a checkbox at registration that they have read and consent to our code of conduct. The code of conduct will be published on our online event platform and in physical form at the entrance to our venue in Berlin.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://25.foss-backstage.de/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We provide Diversity Online-Tickets and Diversity Onsite-Tickets. Both tickets are fully sponsored (i.e. free) and provide full access either to our online or onsite event.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A`  Diversity Tickets are available to people from underrepresented groups within the FOSS Backstage community. This includes, but is not limited to: women, people of colour, LGBTQIA people, disabled people, and people facing economic or social hardships. Please note that there is no "qualification process" for Diversity Tickets, and one can simply order a Diversity Ticket without being vetted, since we as organizers are unable to judge if someone is actually a member of a underrepresented group, and this would create all kinds of obvious problems.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://25.foss-backstage.de/diversity-inclusion/ 

## Family Friendliness
- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` We provide shared "quiet rooms" and baby changing facilities which are also used by other guests in the venue. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` Attendees and speakers may bring their children under the age of 16 free of charge. We also offer free entry for one accompanying adult. The chaperone will not have access to the programme of the conference. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` We are still working on the website and will provide the link as soon as our website is ready. 
  
## Event Accessibility
  
 - [x] This event commits to Event Accessibility.
  - `Q` Is the Event in a wheelchair-accessible venue?
  - `A` Our venue, bUm, is fully wheelchair-accessible: The main entrance is step-free, as is the main event room. Our second stage “Wintergarten” as well as all rooms are accessible by elevator. There are wheelchair accessible toilets.
  - `Q` Are speakers given guidance about creating slides that are colorblind accessible?
  - `A` We plan to include a guide to creating colourblind friendly presentations in our speaker briefings. 
  - `Q` Is signage at the event and the event website colorblind accessible?
  - `A` We are planning to make our information signage colour blind friendly for the next conference.
  - `Q` Does the Event provide other accessibility accommodations, or will upon request?
  - `A` On request, we can provide an on-site accessibility assistant for people who need help navigating the venue.
  - `Q` Provide relevant links related to event accessibility at the Event.
  - `A` https://25.foss-backstage.de/accessibility/
  
## Event Location Inclusivity
  
 - [x] This event commits to Event Location Inclusivity.
 - `Q` Has the Event’s location been checked against lists of places of concern for the following demographics: sexual and gender minorities, people with disabilities, racial and ethnic minorities, women, or religious minorities?
 - `A` Our conference will take place in Berlin Kreuzberg. A very open, multicultural and diverse area. The venue is accessible to people with reduced mobility by bus and subway. 
 - `Q`  Have the Event's dates been checked for other events happening in the same location at the same time that could potentially bring harm to a subset of any attendees?
  - `A` Yes, we have checked this issue. 
  - `Q` The Event website addresses or acknowledges any cause for concern for marginalized attendees.
  - `A` At the moment we do not see any cause for concern for marginalised attendees at our conference. Should any cause for concern arise, we will of course communicate and highlight the issue to all attendees on our website, on site and/or through emails and social posts.

## Public Health and Safety
  
 - [x] This event commits to Public Health and Safety.
 - `Q` Have you participated in the Public Health Pledge Badging Program?
 - `A` No.
 - `Q` Provide a link to the PHPledge Badges received.
 - `A` No.
 - `Q` Provide a link to publicly available information about public health and safety on the event website.
 - `A` https://25.foss-backstage.de/health-safety/

**Comment by ijayhub** [comment]
@adeyinkaoresanya good✅

**Comment by Amalearner** [comment]
Everything else is okay aside from the event organizers have not participated in the Public Health Badging Program.

**Comment by adeyinkaoresanya** [comment]
@ijayhub @Amalearner Thanks for your review!

**Comment by plainschwarz-team** [comment]
Hello, here is the link to our updated website https://25.foss-backstage.de/diversity-inclusion/. We have now added information about the children's policy at our event and also updated our FAQ's.

**Comment by adeyinkaoresanya** [comment]
@ijayhub @Amalearner Thank you for your review!

**Comment by adeyinkaoresanya** [comment]
@plainschwarz-team Your badge is ready! 🥇

**Comment by plainschwarz-team** [comment]
Great, thank you!!
