### ISSUE TITLE
[Virtual Event] .NET Conf 2024

### ISSUE THREAD

**Issue by JaymeSingleton** [badging/event-diversity-and-inclusion#375]
# Virtual Event Submission

## Requirements

- Event Name: .NET Conf 2024
- Link to the Event Website: https://www.dotnetconf.net/
- Provide verification that you are an event organizer: Yes

## Event Demographics

- [x] This event commits to Event Diversity and Inclusion.
  - `Q` Detail the process for measuring Event Demographics.
  - `A` Region, Language, Gender, Age, years as a .NET developer
  - `Q` Provide an example of an opt-out option on the Event registration page if available.
  - `A` N/A
  - `Q` Provide an example of a demographics text input box on the Event registration page if available.
  - `A` Option of "Prefer not to answer": Gender, Pronouns, Age

## Inclusive Experience at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Provide an example of the Event Feedback page if available.
  - `A` N/A
  - `Q` Is the event team using feedback from previous event's attendees, speakers, and volunteers to improve DEI at this event?
  - `A` Yes, we use survey results for every event to guide future events/decisions both in-person and online
  - `Q` Does the event team plan to use feedback from this event's attendees, speakers, and volunteers to improve DEI at future events?
  - `A` Absolutely. We survey all participants: organizers, speakers, & attendees (during & post-event) and use this feedback to guide future event decisions. Here are the links to each survey, Event Survey: https://forms.office.com/r/ZLWUXVBMan   Speaker Survey: https://forms.office.com/r/XZ07mrebah Organizer Survey: https://forms.office.com/r/pM0hM6dYkK
  - `Q` How can attendees learn more about accessibility at the event?
  - `A` N/A
  - `Q` Does the event platform allow attendees to suggest future accomodations for the event?
  - `A` Yes, the entire event is streamed on StreamYard, YouTube, and Twitter live and allows for live commentary via chat which is monitored by moderators. 
  - `Q` Will the event platform be accessible to attendees and speakers after the event?
  - `A` Yes, all content is recorded with subtitles (& using localized translation) to be posted on both YouTube and Bilibili immediately following the event for access. 

## Time Inclusion for Virtual Events

- [x] This event commits to Time Inclusion for Virtual Events.
  - `Q` Are speakers able to pre-record their presentations, as opposed to presenting them live?
  - `A` Yes, this is always an option for our events.
  - `Q` Can attendees change video quality on the Event platform while viewing a presentation?
  - `A` Yes, if using YouTube, attendees can adjust the video quality.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://www.dotnetconf.net/code-of-conduct
  
 ## Diversity Access Tickets
  
- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` The event is 100% free for everyone anywhere in the world.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` N/A
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` N/A 

## Event Accessibility
  
- [x] This event commits to Event Accessibility.
  - `Q` Closed captioning is provided for this event.
  - `A` Yes
  - `Q` Other accommodations are provided, or will be provided upon request.
  - `A` Localized captioning + fulfillment upon request.
  - `Q` Provide a link to the page containing information about Event Accessibility.
  - `A` N/A

**Comment by adeyinkaoresanya** [comment]
Hey @Delight362! Making sure you got this pingh!

**Comment by Amalearner** [comment]
Done @adeyinkaoresanya

**Comment by adeyinkaoresanya** [comment]
@oma131 @Amalearner Thank you for the review!

**Comment by adeyinkaoresanya** [comment]
@JaymeSingleton your badge is ready!

**Comment by JaymeSingleton** [comment]
@adeyinkaoresanya  thank you so much!!!
