### ISSUE TITLE
Event Reviewer Guide

### ISSUE THREAD

**Issue by Nebrethar** [badging/event-diversity-and-inclusion#42]
Hello! This is Aastha and Matt and we are glad you are here. This guide will help you understand the review process for D&I Event Badging.

Please review the [Reviewer Guide](https://github.com/badging/diversity-and-inclusion/blob/master/reviewer-guide.md), the Diversity and Inclusion [Event Requirements](https://github.com/badging/event-diversity-and-inclusion/blob/master/submission/requirements.md) and the [Reviewer Definition](https://github.com/badging/diversity-and-inclusion/blob/master/roles/reviewer.md) before applying to be a reviewer.

Here are a few things you need to do in order to become a part of the review process:
- Create a pull request to this repository to add your GitHub username to [.github/reviewers.md](https://github.com/badging/event-diversity-and-inclusion/blob/master/.github/reviewers.md), which is a file the bot uses for review assignments.
- If your PR is accepted, make sure you are a part of `badging/Reviewers` team. If you are not a part of it yet, please post a comment below to let us know.

Please review all events under the only a few restrictions:

- Do your best!
- Nothing harmful or targeted please (for example, if you think you shouldn't, you probably shouldn't)
- Try to have fun with it 😁

Please let me know if you have any other questions! I will update this document with FAQs as they come up.

## FAQ

`Q` What kind of commitment is reviewing for Event Badging?
`A` We see a lot of variables affecting this time commitment, including our number of reviewers and number of applicants. We expect, at the highest load, for the project to require about 20 minutes every few days from each reviewer. At lowest, we'd expect 20 minutes or so every few weeks

`Q` Your question can be added here!

**Comment by germonprez** [comment]
I'm happy to serve as a reviewer

**Comment by Ruth-ikegah** [comment]
Accepted! Happy to contribute as a reviewer.

**Comment by Nebrethar** [comment]
Thanks @Ruth-ikegah and @germonprez 😄

**Comment by Nebrethar** [comment]
Please see #45 to better understand the new process of submitting for an event badge 😁

**Comment by bistaastha** [comment]
Hi @germonprez and @Ruth-ikegah 

I have added your GitHub usernames to [.github/reviewers.md](https://github.com/badging/event-diversity-and-inclusion/blob/master/.github/reviewers.md), which is the file the bot would be using for review assignments.

**Comment by Ruth-ikegah** [comment]
okay thanks @bistaastha

**Comment by bistaastha** [comment]
@Ruth-ikegah I re-sent you the invite for Reviewers team, it gives you access to edit the commented checklists.

**Comment by Ruth-ikegah** [comment]
great thanks @bistaastha seen!

**Comment by germonprez** [comment]
@Nebrethar @bistaastha 

-- Comment on the review. Make the order of items in the Submission the same as in the Review. 

1) Code of Conduct
2) Speaker Demographics
3) Attendee Demographics
4) Diversity Access Tickets 
5) Family Friendliness

-- Another comment 

1) When reviewing the Speaker Demographics, it was not clear as a reviewer as to how I would identify that the conference had a diverse review team.

**Comment by Nebrethar** [comment]
Thanks @germonprez 😁 we have taken your comments into account. 

We will not change the environment until after the second pilot test, but we are working on it!

/cc @bistaastha

**Comment by tetris4** [comment]
Hi everyone, I'd like to help as a reviewer as well. Thanks for the all the great work so far!

**Comment by Nebrethar** [comment]
Hi @tetris4 and welcome! I'm including @bistaastha here, who worked the most on the badging workflow.

We are currently reaching the end of our second and final badging pilot test. Our application for new reviewers is still under construction for the next day or two.

If you are interested in reviewing for /badging, my recommendation is that you [connect with us on Slack](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-dqeab4ab-4XrH51rc4y_WXjN~uI~6rA) or [attend one of our CHAOSS Badging meetings](https://calendar.google.com/calendar/b/3?cid=Y2hhb3NzLmJhZGdpbmdAZ21haWwuY29t). That way we can get acquainted; I have office hours tomorrow!

Thanks for your interest. Hope to see you around.

**Comment by Anita-ihuman** [comment]
Hello I’d love to volunteer  as a reviewer

**Comment by Nebrethar** [comment]
Hello @Anita-ihuman and I appreciate that you are interested in reviewing. 😄 

Feel free to [connect with us on Slack](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-dqeab4ab-4XrH51rc4y_WXjN~uI~6rA) or [attend one of our CHAOSS Badging meetings](https://calendar.google.com/calendar/b/3?cid=Y2hhb3NzLmJhZGdpbmdAZ21haWwuY29t). We'd be glad to get to know you. 😁 

Right now the best way to apply to review with the project is to submit a pull request to the [list of reviewers](https://github.com/badging/event-diversity-and-inclusion/edit/master/.github/reviewers.md). We have a pull request template built that will guide you through the process. Members of the review team are automatically assigned from the list of reviewers.

I'm including @bistaastha (workflow) and @xiaoya-Esther (documentation) and you can cite any one of us with any specific questions. Looking forward to seeing you around!

**Comment by ElizabethN** [comment]
We are consolidating the docs, so I'm going to close this issue. Thanks everyone! ❤️
