### ISSUE TITLE
Event Applicant Guide

### ISSUE THREAD

**Issue by Nebrethar** [badging/event-diversity-and-inclusion#43]
Hello! This is Aastha and Matt and we are glad you are here. This guide will help you understand the application process for D&I Event Badging.

Please review the Diversity and Inclusion [Event Submission Guidelines](https://github.com/badging/event-diversity-and-inclusion/blob/master/submission/guidelines.md) and the [Applicant Definition](https://github.com/badging/diversity-and-inclusion/blob/master/roles/applicant.md) before applying for an Event badge.

Please submit all events under these restrictions:

- Nothing harmful or targeted please (for example, if you think you shouldn't, you probably shouldn't)
- Try to have fun with it 😁 
- Do your best!

A direct link for the Event application can be found [here](https://chaoss.community/diversity-and-inclusion-badging/).

Please let me know if you have any other questions! I will update this document with FAQs as they come up.

## FAQ

`Q` What kind of commitment is the application process for an Event Badge?
`A` The initial form will likely take about 15 minutes to fill out. After submitting your application, you are required to communicate, at least a few times, to ensure that the information is accurate and confusion is resolved. You must also confirm that the badge your event receives is clear.

`Q` Your question can be added here!

**Comment by Nebrethar** [comment]
Please see #45 to better understand the new process of submitting for an event badge 😁

**Comment by ElizabethN** [comment]
We are consolidating docs, so i'm going to close this issue. Thanks everyone! :heart:
