### ISSUE TITLE
Event Moderator Guide

### ISSUE THREAD

**Issue by bistaastha** [badging/event-diversity-and-inclusion#44]
Hello! This is Aastha and Matt and we are glad you are here. This guide will help you understand the application process for D&I Event Badging.

Please review the Diversity and Inclusion [Moderator guide](https://github.com/badging/diversity-and-inclusion/blob/master/moderator-guide.md) and the [Moderator Definition](https://github.com/badging/diversity-and-inclusion/blob/master/roles/moderator.md) to understand the work of a moderator.

If you are currently a moderator, make sure you are added to `badging/badging-moderators` team. If you are not a part of it yet, please write a comment below to let us know.

Please let us know if you have any other questions!

Comment below to let us know that you will be participating in the process as a moderator. 

Please moderate all events under these restrictions:

- Nothing harmful or targeted please (for example, if you think you shouldn't, you probably shouldn't)
- Do your best to mitigate arguments and solve problems in this pilot test
- Try to have fun with it 😁 

Please let me know if you have any other questions! I will update this document with FAQs as they come up.

## FAQ

`Q` What kind of commitment is moderating for Event Badging?
`A` We see a lot of variables affecting this time commitment, including our number of moderators and number of applicants. We expect, at the highest load, for the project to require about 20 minutes every couple of days for each moderator. As we get more moderators into the project, that commitment will shrink.

`Q` What happens if a reviewer is not responding or providing a review?
`A` In this case, we use a week as our reference time. If the reviewer has been assigned for a week and has not provided their review or responded to requests, you can unassign them. At this point, you must also assign a new reviewer. You can use your judgement to request a reviewer that you haven't seen on any events recently, or someone that you know will be reliable.

`Q` Your question can be added here!

**Comment by Nebrethar** [comment]
Please see #45 to better understand the new process of submitting for an event badge 😁

**Comment by xiaoya-Esther** [comment]
Sorry I' late!  is it still in time to sing up for the moderator?

**Comment by Nebrethar** [comment]
Hi @xiaoya-Esther :) We have you down as a moderator. Thank you!

**Comment by Nebrethar** [comment]
@xiaoya-Esther I added some questions in the FAQ, including your inactivity question 😁

**Comment by ElizabethN** [comment]
We are consolidating docs, so I'm going to close this issue. Thanks everyone! :heart:
