### ISSUE TITLE
Event Badge Submission: The Beenz Meetup

### ISSUE THREAD

**Issue by Nebrethar** [badging/event-diversity-and-inclusion#46]
# Event Submission

## Requirements

- Event Name: The Beenz Meetup
- Link to the Event Website: https://deadcurrency.io/meetup

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Speakers can opt-in to fill out a demographic form when they sign-up for the event.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://deadcurrency.io/meetup/speakers

## Attendee Demographics

- [ ] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` N/A no process yet
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` N/A

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://deadcurrency.io/meetup/code

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 1
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` It requires being a member of an underrepresented population
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://deadcurrency.io/meetup/diversity

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We give free bubblegum to children that attend
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` None

**Comment by germonprez** [comment]
- Code of Conduct: It is not clear how CoC violations are reported and how the event would provide support for victims. Please update. 

- Speaker Demographics: It is not clear who is on the review panel. Please update. 

- Attendee Demographics: While you didn't provide any information, please let us know if you would like to address this. 

- Diversity Access Tickets: Well done. 

- Family Friendliness: Bubblegum is bad for kids. Fix this. Also, you should provide a link that explains family friendliness as provided at the event.

**Comment by Ruth-ikegah** [comment]
**Additional Comments**

- Speaker Demographics: Speaker opt-in to fill the demographic form will not be a good process to measure 

- Attendee Demographics: This wasn't provided, kindly state your reason or provide it

- Diversity Acess Tickets: One type of diversity ticket is not okay as it should reflect gender, race, color, etc.

- Family Friendliness: Giving bubblegum to kids is not advisable, please kindly provide a link too.

**Comment by xiaoya-Esther** [comment]
Thanks for the application and review! The current Badge state is "Passing", would @Nebrethar like to provide more information in detail with regard to the feedback from reviewers, or finalize this application and generate the final badge?

**Comment by Nebrethar** [comment]
@xiaoya-Esther We are happy with the current badge level for The Beenz Meetup. We've switched to apple juice for next year, and we are planning out more diversity access tickets for future years.

**Comment by Nebrethar** [comment]
Congratulations @Nebrethar. Check the [README](https://github.com/badging/event-diversity-and-inclusion)!

Thanks to @Ruth-ikegah @germonprez @xiaoya-Esther for aiding in the Badging process.
