### ISSUE TITLE
Event Badge Submission: The DevTown meetup

### ISSUE THREAD

**Issue by bistaastha** [badging/event-diversity-and-inclusion#49]
# Event Submission

## Requirements

- Event Name: The DevTown meetup
- Link to the Event Website: devtown-meet.com

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` We have an additional form which is completely voluntary to fill out after CFP selection for the speakers who join us for the event.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` 

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` We have an additional form which is completely voluntary to fill out during attendee sign up for recording demographic data. 
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` devtown-meet.com/register

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` Yes
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` devtown-meet.com/code-of-conduct

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` devtown-meet.com/highlights

**Comment by germonprez** [comment]
Hi @bistaastha 

Thanks for you application. Could you help us

1) Determine if you are an organizer for the event
2) Explain how you are going to enforce Code of Conduct violations
3) Determine who is on the reviewing panel for selecting Event Speakers.
4) Know if you are planning on including Diversity Access Tickets as part of your event 
5) Think about ways that Family Friendliness could be considered beyond childcare only. 

We look forward to working with you!

**Comment by Nebrethar** [comment]
Closing this issue to prepare for the project launch.

Get ready for September 14, 2020

Thanks @bistaastha !!!
