### ISSUE TITLE
Event Badge Submission: The Party Ponies Open Source Convention

### ISSUE THREAD

**Issue by GeorgLink** [badging/event-diversity-and-inclusion#50]
# Event Submission

## Requirements

- Event Name: The Party Ponies Open Source Convention
- Link to the Event Website: party-ponies-osc.com

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` We ask speakers to self-identify when we put the schedule together.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` party-ponies-osc.com/schedule

## Attendee Demographics

- [ ] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` No, we accept anyone, there is no registration process or anyway to know who shows up.
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` none

## Code of Conduct at Event

- [ ] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` We don't need this.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` N/A

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We don't have tickets, anyone is free to come to the convention.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` N/A
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` party-ponies-osc.com/join-us

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` No. We don't know what attendees need, since they don't need to tell us in advance that they are coming.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` The event is next to a camp ground with fun-activities for family members of all ages.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` party-ponies-osc.com/how-to-get-there

**Comment by germonprez** [comment]
Thanks for you application @GeorgLink 

There are a few things that we'd love to see you improve on in an effort to obtain a CHAOSS D&I Event Badge. Please take a look and provide your feedback: 

1) Could you please let us know if you are an organizer for the conference? 

2) As part of even applying for a CHAOSS D&I Event Badge, it's important for your event to provide a Code of Conduct for event participants. This not only includes the text of the Code of Conduct but also: 

- Reporting venue - There is a clear venue for reporting violations of the CoC at the event website / event venue.
- Support at Event - The Event Code of Conduct OR event website provide information about possible ways to provide support to victims of inappropriate behavior.
- Findability - It is easy to find the Code of Conduct on the Event website.
- Enforcement - The participants in the Event are required to accept the Code of Conduct. 

Let us know how we can help you in this. 

3) With respect to Speaker Demographics, do you have documentation regarding the make-up of the reviewing panel for selecting Event Speakers? 

4) With respect to Attendee Demographic, would it be possible to ask attendees for this information when they register? There are great resources to help capture this information. 

5) With respect to Diversity Access Tickets, the goal is to provide an opportunity for people who may not be able to attend your conference with an opportunity to do so. This could include support for local arrangements or travel. However, if your event is a virtual event then this may be okay. 

6) With respect to Family Friendliness, the event can provide a proactive approach towards supporting families and family caregivers. This could include daycare facilities, a mother's room, activities that support children, or explicit encouragement from the event organizers to bring children. 

Again, thanks for your submission and we look forward to working with you in hopes of obtaining a CHAOSS D&I Event Badge.

**Comment by GeorgLink** [comment]
> Thanks for you application @GeorgLink

Thank you for your reply.


> There are a few things that we'd love to see you improve on in an effort to obtain a CHAOSS D&I Event Badge. Please take a look and provide your feedback:
> 
> 1. Could you please let us know if you are an organizer for the conference?

Yes, I'm on the organizing committee.


> 2. As part of even applying for a CHAOSS D&I Event Badge, it's important for your event to provide a Code of Conduct for event participants. This not only includes the text of the Code of Conduct but also:
> 
> * Reporting venue - There is a clear venue for reporting violations of the CoC at the event website / event venue.
> * Support at Event - The Event Code of Conduct OR event website provide information about possible ways to provide support to victims of inappropriate behavior.
> * Findability - It is easy to find the Code of Conduct on the Event website.
> * Enforcement - The participants in the Event are required to accept the Code of Conduct.
> 
> Let us know how we can help you in this.

I can ask the others on our organizing committee, but we have not had this in the past. Do you have an example of what that might look like?


> 1. With respect to Speaker Demographics, do you have documentation regarding the make-up of the reviewing panel for selecting Event Speakers?

The speakers are decided by the organizing committee. Are you asking for their demographics? We are 1 woman and 4 men.


> 2. With respect to Attendee Demographic, would it be possible to ask attendees for this information when they register? There are great resources to help capture this information.

We do not have a registration process. Anyone can simply show up to the event. We don't want to add registration because it goes against the culture of the event. Hm... how do other events capture attendee demographics when there is no registration process? I would guess we will have 30% women and 70% men.


> 3. With respect to Diversity Access Tickets, the goal is to provide an opportunity for people who may not be able to attend your conference with an opportunity to do so. This could include support for local arrangements or travel. However, if your event is a virtual event then this may be okay.

This is not a virtual event but an in-person event (sorry if that wasn't clear from my previous answers). Because we don't have a registration fee, we are running on a shoe-string budget and cannot support attendee's travel arrangements financially. Would it count if we provided tips for attending and facilitating between attendees who would share an accommodation with other attendees?

> 4. With respect to Family Friendliness, the event can provide a proactive approach towards supporting families and family caregivers. This could include daycare facilities, a mother's room, activities that support children, or explicit encouragement from the event organizers to bring children.

I think we could do some of these things. A dedicated mother's room should be no issue. Maybe we can find volunteers to organize children's activities. For sure, we can invite families to bring children.


> Again, thanks for your submission and we look forward to working with you in hopes of obtaining a CHAOSS D&I Event Badge.

Thank you. I know we are not perfect. We are not doing this professionally. Any help you can give us would be appreciated.

Best,
Georg

**Comment by germonprez** [comment]
> > Thanks for you application @GeorgLink
> 
> Thank you for your reply.
> 
> > There are a few things that we'd love to see you improve on in an effort to obtain a CHAOSS D&I Event Badge. Please take a look and provide your feedback:
> > 
> > 1. Could you please let us know if you are an organizer for the conference?
> 
> Yes, I'm on the organizing committee.

Thanks! 

> 
> > 1. As part of even applying for a CHAOSS D&I Event Badge, it's important for your event to provide a Code of Conduct for event participants. This not only includes the text of the Code of Conduct but also:
> > 
> > 
> > * Reporting venue - There is a clear venue for reporting violations of the CoC at the event website / event venue.
> > * Support at Event - The Event Code of Conduct OR event website provide information about possible ways to provide support to victims of inappropriate behavior.
> > * Findability - It is easy to find the Code of Conduct on the Event website.
> > * Enforcement - The participants in the Event are required to accept the Code of Conduct.
> > 
> > Let us know how we can help you in this.
> 
> I can ask the others on our organizing committee, but we have not had this in the past. Do you have an example of what that might look like?

You bet! Here is a code of conduct from a very recent event, KubeCon 2019
https://events19.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/attend/code-of-conduct/

> 
> > 1. With respect to Speaker Demographics, do you have documentation regarding the make-up of the reviewing panel for selecting Event Speakers?
> 
> The speakers are decided by the organizing committee. Are you asking for their demographics? We are 1 woman and 4 men.

Yes, this is great thanks!
(FYI, I've asked to remove this evaluation point as it is not part of the defined metric)

> 
> > 1. With respect to Attendee Demographic, would it be possible to ask attendees for this information when they register? There are great resources to help capture this information.
> 
> We do not have a registration process. Anyone can simply show up to the event. We don't want to add registration because it goes against the culture of the event. Hm... how do other events capture attendee demographics when there is no registration process? I would guess we will have 30% women and 70% men.

There are other ways that you could work to measure attendee demographics. If you take a look at the CHAOSS metric on this, you will see in the Data Collection Strategies, ways that you can better think about attendee demographics: 
https://chaoss.community/metric-attendee-demographics/

> 
> > 1. With respect to Diversity Access Tickets, the goal is to provide an opportunity for people who may not be able to attend your conference with an opportunity to do so. This could include support for local arrangements or travel. However, if your event is a virtual event then this may be okay.
> 
> This is not a virtual event but an in-person event (sorry if that wasn't clear from my previous answers). Because we don't have a registration fee, we are running on a shoe-string budget and cannot support attendee's travel arrangements financially. Would it count if we provided tips for attending and facilitating between attendees who would share an accommodation with other attendees?

Thanks for this! I understand the position you are in and Diversity Access Tickets may simply not be applicable in this case. But that's okay. You can still receive a CHAOSS D&I Event badge by addressing the other issues :) 

> 
> > 1. With respect to Family Friendliness, the event can provide a proactive approach towards supporting families and family caregivers. This could include daycare facilities, a mother's room, activities that support children, or explicit encouragement from the event organizers to bring children.
> 
> I think we could do some of these things. A dedicated mother's room should be no issue. Maybe we can find volunteers to organize children's activities. For sure, we can invite families to bring children.

Great! Please talk through what you can provide and update your website to share this information. Once you've done that, let me know! 

> 
> > Again, thanks for your submission and we look forward to working with you in hopes of obtaining a CHAOSS D&I Event Badge.
> 
> Thank you. I know we are not perfect. We are not doing this professionally. Any help you can give us would be appreciated.
> 
> Best,
> Georg


Hopefully, we can move this forward in a way that's helpful for everyone!!

Matt

**Comment by Nebrethar** [comment]
Closing this issue to prepare for the project launch.

Get ready for September 14, 2020

Thanks @GeorgLink !!!

**Comment by GeorgLink** [comment]
👍
