### ISSUE TITLE
Event Badge Submission: LizzCon 2020

### ISSUE THREAD

**Issue by ElizabethN** [badging/event-diversity-and-inclusion#52]
# Event Submission

## Requirements

- Event Name: LizzCon 2020
- Link to the Event Website: https://lizzcon2020.com

## Speaker Demographics

- [ ] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` We do not look at speaker demographics as this is personal information.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` 

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` We ask people on the registration form if they are male or female.
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted at Event venue?
  - `A` No.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://lizzcon2020.com/code-of-conduct

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` What's a diversity access ticket?
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` 

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` Kids track, mother's nursing room, no alcohol at the evening events.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`

**Comment by ElizabethN** [comment]
That form was wayyyyyy easier to submit! Love it!!

**Comment by Nebrethar** [comment]
Closing this issue to prepare for the project launch.

Get ready for September 14, 2020

Thanks @ElizabethN !!!
