### ISSUE TITLE
[Virtual Event] All Things Open

### ISSUE THREAD

**Issue by amitkul87** [badging/event-diversity-and-inclusion#58]
# Virtual Event Submission

## Requirements

- Event Name: All Things Open
- Link to the Event Website: https://allthingsopen.6connex.com/event/ATO/en-us/?mcc=ato-platform-link#!/CHAOSSbooth
- Provide verification that you are an event organizer: 

## Speaker Demographics

- [ ] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` 
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` 

## Attendee Demographics

- [ ] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` 
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` 

## Code of Conduct at Event

- [ ] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` 

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`

**Comment by Nebrethar** [comment]
Closing this one, as we have no content and no updates. 

We hope you re-apply!
