### ISSUE TITLE
[Virtual Event] DPDK Summit APAC 2021

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#60]
# Virtual Event Submission

## Requirements

- Event Name: DPDK Summit APAC 2021
- Link to the Event Website: https://events.linuxfoundation.org/dpdk-summit-apac/
- Provide verification that you are an event organizer: Meeting & Event Planner at the Linux Foundation, working specifically on DPDK Summit APAC 2021.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` "Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity, identification with an underrepresented group in technology (race, ethnicity, disability, LGBTQ, etc.), no all-man programs or panels"
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` Link to the current CFP (now accepting proposals): https://www.surveymonkey.com/r/DPDK_APAC_CFP

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity, Identification with an underrepresented group in technology (race, ethnicity, disability, LGBTQ, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` Event registration is open and available to all: https://www.cvent.com/d/77qyd4/4W?ct=50221cf5-5496-4c34-9ec0-3b52b1bf1204

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes, the Code of Conduct is posted on the virtual event platform. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/dpdk-summit-apac/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` DPDK APAC is a free event - there are no barriers to entry, and all are encouraged to attend and participate. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` DPDK APAC is a free event - there are no barriers to entry, and all are encouraged to attend and participate. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  NA

**Comment by Nebrethar** [comment]
Hi @RachelBraunLF! Thank you for submitting an Event application to the CHAOSS D&I Badging Project. 

Feel free to chat with the reviewers assigned to this issue if you need anything. Also, this is also a fairly new program, so we are always open to suggestions for improvement!

You can @ me if you need anything. 😁

**Comment by RachelBraunLF** [comment]
Thanks @Nebrethar - we are excited to participate in the program, and look forward to the review!

**Comment by Ruth-ikegah** [comment]
Hi, @RachelBraunLF Thanks for submitting an application t the D/I badging project!

Before I go ahead with ticking the checklist, I would love to ask some a question and a suggestion

- As regards Attendee and Speaker demographics, what's the plan on sharing the demographic information publicly?
- Since the event is free, a note can be put up somewhere on the website or otherwise, that shows it is a free event strongly supporting registration from people across the globe, members from underrepresented groups to attend, hoping that those who would not be able to attend such events can easily do so.

**Comment by RachelBraunLF** [comment]
Hi @Ruth-ikegah - thanks for your questions!

- For the event, we will be putting together a post-event report that will include the collected demographic information, which could be shared publicly, however the committee that will need to approve this decision is already out for holiday break. I will be able to follow-up with you after the holiday season to share the decision that was made. Will that work?
- This is a great suggestion. We will plan to add the following language to the website:  DPDK APAC Summit will take place virtually, allowing you to attend from anywhere in the world, and include opportunities to network with other attendees, attend sessions with live speaker Q&A, and much more.

**Comment by Ruth-ikegah** [comment]
> Hi @Ruth-ikegah - thanks for your questions!
> 
> * For the event, we will be putting together a post-event report that will include the collected demographic information, which could be shared publicly, however, the committee that will need to approve this decision is already out for holiday break. I will be able to follow-up with you after the holiday season to share the decision that was made. Will that work?
> * This is a great suggestion. We will plan to add the following language to the website:  DPDK APAC Summit will take place virtually, allowing you to attend from anywhere in the world, and include opportunities to network with other attendees, attend sessions with live speaker Q&A, and much more.

Hi, @RachelBraunLF, thanks for the detailed response!

Yeah, this works as regards the decision for demographic info! I'd kindly wait for your feedback on this.

Secondly, another suggestion for tweaking the note for the website will be making a direct statement indicating DPDK Summit accepts diverse and inclusive participation. 

Thanks!

**Comment by djmitche** [comment]
Hi there!  Regarding the Code of Conduct, I see both https://events.linuxfoundation.org/dpdk-summit-apac/attend/code-of-conduct/ and, linked from https://events.linuxfoundation.org/dpdk-summit-apac/program/cfp/#code-of-conduct, https://events.linuxfoundation.org/agl-amm/attend/code-of-conduct/.  Neither of those links to you for reporting.  Perhaps some of those links need an update?

I also don't see a requirement to accept that CoC.  I didn't click through the registration process since I don't have an LF account.  If it's required as part of that process, that's great - just let me know.

I'm following the conversation above as well, and will check those items off as the updates are made.

**Comment by RachelBraunLF** [comment]
Hi @djmitche! 
On the Code of Conduct page, if you scroll down to the "What to do if you witness or are subject to unacceptable behavior", it includes a link and email address to my manager, Emily Ruf. We direct all concerns related to CoC to event managers rather than individual event planners so that it may be escalated as quickly as possible, as appropriate. 

In order to officially register for the event, registrants are required to accept the CoC, which as you indicated, is indeed part of the registration process. 

@Ruth-ikegah - I am hopeful to have an update regarding publishing the post-event report on the website yet this week, and will ping back once I have confirmation.

**Comment by Ruth-ikegah** [comment]
> Hi @djmitche!
> On the Code of Conduct page, if you scroll down to the "What to do if you witness or are subject to unacceptable behavior", it includes a link and email address to my manager, Emily Ruf. We direct all concerns related to CoC to event managers rather than individual event planners so that it may be escalated as quickly as possible, as appropriate.
> 
> In order to officially register for the event, registrants are required to accept the CoC, which as you indicated, is indeed part of the registration process.
> 
> @Ruth-ikegah - I am hopeful to have an update regarding publishing the post-event report on the website yet this week, and will ping back once I have confirmation.

A happy and wonderful New year to you @RachelBraunLF :) 
Sure that isfine, I will be expecting your response.

**Comment by djmitche** [comment]
Thanks for the update!  So Emily Ruf is correct, but note the incorrect link from https://events.linuxfoundation.org/dpdk-summit-apac/program/cfp/#code-of-conduct to https://events.linuxfoundation.org/agl-amm/attend/code-of-conduct/ (that doesn't block badging though).

**Comment by RachelBraunLF** [comment]
Hi @djmitche and @Ruth-ikegah -

I am back with some further information - so sorry for the delay on my part! 
Rather than the previously mentioned event recap, we are planning to post a number of statistics that will address the requirements for the badge on a newly created Diversity and Inclusion subpage on the event webpage.

Can you please review the below statement and stats and let me know if what I've proposed below will meet your requirements?

Education and collaboration are important to the DPDK community and it is imperative to us that everyone in the community that wants to participate feels welcome to do so regardless of gender, gender identity, sexual orientation, disability, race, ethnicity, age, religion, or economic status. Below are the opt-in statistics from the 2020 DPDK Userspace event. Please note, attendee demographic questions are optional for speakers and attendees, and are based on opt-in only responses.

Attendee Gender
Man - 85%
Woman - 1%
Non-Binary - 0%
Prefer Not to Answer - 14%

Speaker Gender - DPDK did not request for the 2020 event so we will not include this statistic, however is now requesting it for the 2021 event. 

Geographic Representation
46 Countries

If the information provided above is adequate, I will go ahead and get this implemented on the [website](https://events.linuxfoundation.org/dpdk-summit-apac/) ASAP.

**Comment by Ruth-ikegah** [comment]
> Hi @djmitche and @Ruth-ikegah -
> 
> I am back with some further information - so sorry for the delay on my part!
> Rather than the previously mentioned event recap, we are planning to post a number of statistics that will address the requirements for the badge on a newly created Diversity and Inclusion subpage on the event webpage.
> 
> Can you please review the below statement and stats and let me know if what I've proposed below will meet your requirements?
> 
> Education and collaboration are important to the DPDK community and it is imperative to us that everyone in the community that wants to participate feels welcome to do so regardless of gender, gender identity, sexual orientation, disability, race, ethnicity, age, religion, or economic status. Below are the opt-in statistics from the 2020 DPDK Userspace event. Please note, attendee demographic questions are optional for speakers and attendees, and are based on opt-in only responses.
> 
> Attendee Gender
> Man - 85%
> Woman - 1%
> Non-Binary - 0%
> Prefer Not to Answer - 14%
> 
> Speaker Gender - DPDK did not request for the 2020 event so we will not include this statistic, however is now requesting it for the 2021 event.
> 
> Geographic Representation
> 46 Countries
> 
> If the information provided above is adequate, I will go ahead and get this implemented on the [website](https://events.linuxfoundation.org/dpdk-summit-apac/) ASAP.

Hi @RachelBraunLF, no worries about the delay :)

This improvement looks great to me! Thanks for the change!
I will go ahead and start my review as soon as @djmitche checks and it is implemented on the site. Thanks for your patience on this.

**Comment by djmitche** [comment]
Yes, that looks good to me.

**Comment by Nebrethar** [comment]
@djmitche @Ruth-ikegah @RachelBraunLF

Wow! This is exactly what we were looking for when we started the badging project. I see great communication and positive change. I am going to go ahead and generate a badge. 

Note that this isn't the end of the process. I will still need your approval, but that's it! 😁

**Comment by Nebrethar** [comment]
@RachelBraunLF

Your event has earned a CHAOSS D&I Gold Badge! Congratulations! Now, I need your consent to close the review and award the badge. Thank you so much!

**Comment by RachelBraunLF** [comment]
This is great news! I consent to close the review and receive the badge. 
Thanks!

**Comment by Nebrethar** [comment]
Congratulations @RachelBraunLF on behalf of DPDK Summit APAC 2021! This event has earned a CHAOSS D&I GOLD badge. The event will now be added to the list in this project's README, Thank you for responding to all of our questions and working with us. We're excited to have you 😁 

Thank you @djmitche and @Ruth-ikegah for responding in a timely manner and showing careful consideration during your review. This project can't happen without you.

**Comment by Ruth-ikegah** [comment]
Congratulations @RachelBraunLF on the Gold badge. Thanks for your patience with our review. Please do share the word of this project. Thanks :)

**Comment by Ruth-ikegah** [comment]
> @djmitche @Ruth-ikegah @RachelBraunLF
> 
> Wow! This is exactly what we were looking for when we started the badging project. I see great communication and positive change. I am going to go ahead and generate a badge.
> 
> Note that this isn't the end of the process. I will still need your approval, but that's it! 😁

I enjoyed every bit of it!

**Comment by RachelBraunLF** [comment]
@Nebrethar - hi! We are looking to get our finalized D&I page up on the website, and include the badge (yay!). Is there an actual file type of the badge that you can share? Our web manager has asked for a .svg or .png for her to be able to format it on the page. 
Is that possible?

**Comment by Nebrethar** [comment]
@RachelBraunLF Of Course! I just created them.

SVG: https://svgur.com/s/TX5

PNG:
![image](https://user-images.githubusercontent.com/34951354/106024237-31609300-608d-11eb-9bae-7bd8af48a27c.png)

**Comment by RachelBraunLF** [comment]
@Nebrethar This is perfect - thanks so much!
