### ISSUE TITLE
[Virtual Event] PrestoCon Day

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#62]
# Virtual Event Submission

## Requirements

- Event Name: PrestoCon Day
- Link to the Event Website: https://events.linuxfoundation.org/prestocon-day/
- Provide verification that you are an event organizer: My manager, Emily Ruf is the event manager. This is a Linux Foundation event - my email address is rbraun@linuxfoundation.org

## Speaker Demographics

- [x ] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes:
-Gender identity
-Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)
-No all-man programs or panels

  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/prestocon-day/attend/diversity-inclusion/

## Attendee Demographics

- [x ] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes:
-Gender identity
-Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)

  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/prestocon-day/attend/diversity-inclusion/

## Code of Conduct at Event

- [ x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the code of conduct is posted on the event website and will be posted in the virtual event platform. We also require all registrants to agree to the code of conduct before their registration can be completed. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/prestocon-day/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` NA - PrestoCon Day is a free event - there are no barriers to entry and all those interested are encouraged to attend and participate. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` NA - PrestoCon Day is a free event - there are no barriers to entry and all those interested are encouraged to attend and participate. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  NA - PrestoCon Day is a free event - there are no barriers to entry and all those interested are encouraged to attend and participate.

**Comment by Nebrethar** [comment]
Looks like everything is checked off! 

@tetris4 @Ruth-ikegah can I certify that you both filled out your respective checklists? I just want to make sure you are both done and have no questions 😁

**Comment by Nebrethar** [comment]
Also.. @RachelBraunLF !!

Thank you for submitting another event to our program. You are doing a great job of helping kick-start the process. We appreciate you!

**Comment by Ruth-ikegah** [comment]
> Looks like everything is checked off!
> 
> @tetris4 @Ruth-ikegah can I certify that you both filled out your respective checklists? I just want to make sure you are both done and have no questions 😁
> 
> Edit: I am removing the Diversity Access Tickets section from the review checklists, as it does not apply. This will actually not change the score, in this case 😄

Yes, I am done, and no questions.

**Comment by Ruth-ikegah** [comment]
Thanks @RachelBraunLF for applying for a D/I Badge for PrestoCon

**Comment by tetris4** [comment]
@Nebrethar yup, done also. Thanks and congrats @RachelBraunLF  =)

**Comment by Nebrethar** [comment]
Congratulations! 

I'm going to go ahead and get a badge result. @Ruth-ikegah @tetris4 Now is an opportunity if you have any feedback to provide. I'm thinking you may be getting the process down 😁 

@RachelBraunLF I will need you to confirm the badge status once it is generated. Thank you again!

**Comment by Nebrethar** [comment]
I'm proud of that 100 🎉 and I hope you are too

**Comment by RachelBraunLF** [comment]
Thank you @Nebrethar - I can confirm the badge. Thank you!
Thank you @Ruth-ikegah and @tetris4 for your time on this review!

**Comment by Nebrethar** [comment]
Thanks again Rachel. We're so glad to have your applications. You can find the reference badges here:

SVG: https://svgur.com/s/TX5

PNG:
![image](https://user-images.githubusercontent.com/34951354/106024237-31609300-608d-11eb-9bae-7bd8af48a27c.png)

**Comment by Ruth-ikegah** [comment]
You're welcome @RachelBraunLF for submitting applications. After reviewing this particular application I noticed a lot was fixed as regards the first application DPDK, which shows the badging project is making a good impact!

**Comment by RachelBraunLF** [comment]
@Ruth-ikegah Yes! We have taken all the feedback received from the reviews and implemented as much as we can, and it's been a great exercise for our own internal processes.

**Comment by Ruth-ikegah** [comment]
> @Ruth-ikegah Yes! We have taken all the feedback received from the reviews and implemented as much as we can, and it's been a great exercise for our own internal processes.

So excited to know this!
