### ISSUE TITLE
New Reviewer

### ISSUE THREAD

**Issue by germonprez** [badging/event-diversity-and-inclusion#63]
Hi all, 

As new requests come in, I'd be happy to serve as a reviewer.

**Comment by germonprez** [comment]
Ha ha! This isn't a new event. I'm offering to help with reviews.

**Comment by Nebrethar** [comment]
Hi @germonprez! As you are currently a moderator on the project, I'm glad to add you to the reviewer list.

**Comment by Nebrethar** [comment]
I have added you to the reviewer list. I'll leave this as a reminder to add an "if then else" to the bot to avoid that issue in the future

**Comment by bistaastha** [comment]
Maybe there could be a default issue template other kinds of issues apart from reviews so the bot doesn't react to them

**Comment by Nebrethar** [comment]
Moved to #66
