### ISSUE TITLE
[Virtual Event] OpenJS World 2021

### ISSUE THREAD

**Issue by celiastampslf** [badging/event-diversity-and-inclusion#64]
# Virtual Event Submission

## Requirements

- Event Name: OpenJS World 2021
- Link to the Event Website: https://openjsf.org/openjs-world-2021/
- Provide verification that you are an event organizer: https://www.linkedin.com/in/celia-stamps-765641a/

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.) -No all-man programs or panels
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` Link to information on website: https://openjsf.org/openjs-world-2021/ ----- Link to CFP: https://linuxfoundation.smapply.io/prog/openjs_world_2021_/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` Link to information on website: https://openjsf.org/openjs-world-2021/ ----- Link to registration: https://sso.linuxfoundation.org/login/?state=g6Fo2SBrcks0Q3dlUXV2cWkySU43QmJhZ2sxM1U2WmpLSU9WV6N0aWTZIHpfakxRZDZuQzdXcmhORTdaZ2syVjE0X3lWU3lwS1RUo2NpZNkgMUVNRjhrR2ZzNFVXYlVqeHRwVk5IbzZNd3VYeGtQNW0&client=1EMF8kGfs4UWbUjxtpVNHo6MwuXxkP5m&protocol=samlp&eventName=OpenJSWorld2021v2&e=1989fd71-5c0f-4c25-a486-6737e040c635&RelayState=http:%2F%2Fwww.cvent.com%2Fd%2F17qhqx%2F4W%3Fct%3D50221cf5-5496-4c34-9ec0-3b52b1bf1204%26fqp%3Dtrue%26e%3D1989fd71-5c0f-4c25-a486-6737e040c635

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes, the Code of Conduct is posted on the virtual event platform.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` Linked out on our event website: https://openjsf.org/openjs-world-2021/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` OpenJS World is a free event - there are no barriers to entry, and all are encouraged to attend and participate.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` OpenJS World is a free event - there are no barriers to entry, and all are encouraged to attend and participate.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` OpenJS World is a free event - there are no barriers to entry, and all are encouraged to attend and participate.

**Comment by Ruth-ikegah** [comment]
Thanks, @celiastampslf for applying for a D/I Badge for OpenJS World!

**Comment by Nebrethar** [comment]
Thanks for the submission 😁 I am gonna go ahead and remove the diversity access ticket checkboxes from the review lists.

Let me know if you need anything else 😎

**Comment by tetris4** [comment]
Thanks for applying @celiastampslf!

Regarding the last check point "Enforcement - The participants in the Event are required to accept the Code of Conduct.", trying to register for the event I didn't find a particular check box or message that I should accept the code of conduct in order to proceed. Did I miss something?

**Comment by celiastampslf** [comment]
Hi @tetris4!  Thanks for touching base and reviewing my application.  
The Code of Conduct acceptance is within the Terms & Conditions that must be accepted before continuing to the order confirmation.  See screenshot below:
![image](https://user-images.githubusercontent.com/78926439/108731655-c3c44d00-74fa-11eb-938e-b07ac3620b3c.png)

**Comment by Nebrethar** [comment]
This is really exciting to see! Thank you for providing your valuable feedback @celiastampslf 

@tetris4 Thanks for asking questions :) Let me know when your review is finished for now, and I will go ahead and generate a badge.

**Comment by tetris4** [comment]
Great, thank you @celiastampslf and congrats, as I see you scored 100%! =)

@Nebrethar I've updated my review, so you can proceed with the badge.

**Comment by Nebrethar** [comment]
Thanks @tetris4. Great!

Congratulations @celiastampslf on the result of the review. I am going to produce the result, and I will need your approval of the badge.

**Comment by celiastampslf** [comment]
@tetris4 @Nebrethar Thank you both!  The badge result is approved.

**Comment by Nebrethar** [comment]
Congratulations again! We are testing out a new bot right now, so don't worry if nothing happens at first. You can find the badge images here, with markdown links below:

SVG: https://svgur.com/s/TX5

PNG:
![image](https://user-images.githubusercontent.com/34951354/106024237-31609300-608d-11eb-9bae-7bd8af48a27c.png)

**Comment by Nebrethar** [comment]
It (mostly) Worked!!!
