### ISSUE TITLE
[Virtual Event] Hyperledger Global Forum 2021

### ISSUE THREAD

**Issue by celiastampslf** [badging/event-diversity-and-inclusion#65]
# Virtual Event Submission

## Requirements

- Event Name: Hyperledger Global Forum 2021
- Link to the Event Website: https://events.linuxfoundation.org/hyperledger-global-forum/
- Provide verification that you are an event organizer: https://www.linkedin.com/in/celia-stamps-765641a/

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.) -No all-man programs or panels
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/hyperledger-global-forum/attend/diversity-inclusion/#event-demographics

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/hyperledger-global-forum/attend/diversity-inclusion/#event-demographics

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes, the Code of Conduct is posted on the virtual event platform.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/hyperledger-global-forum/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We have a scholarship program available, based on need and impact, providing support to traditionally underrepresented and/or marginalized persons in the technology and/or open source communities (including, but not limited to persons identifying as LGBT, women, persons of color, and/or persons with disabilities) who may not otherwise have the opportunity to attend Hyperledger events for financial reasons.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Completing the application form (linked on webpage below) with key questions as follows: 1.) Can you receive funding from your company or organization for this event?  2.) Which underrepresented and/or marginalized group do you belong to?  3.) Briefly describe the ways in which you are involved in the technology and/or open source communities.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/hyperledger-global-forum/attend/scholarships/

**Comment by Anita-ihuman** [comment]
@celiastampslf  I would like to know if the Event requests feedback from attendees regarding Diversity & Inclusion.
 and what method is used to achieve this?

**Comment by Anita-ihuman** [comment]
@celiastampslf 
Please I would like to clarify, does the Event requests feedback from attendees regarding Diversity & Inclusion?
 If yes, how do you achieve this?

**Comment by celiastampslf** [comment]
@Anita-ihuman We collect feedback and ideas from the community via email, linked on the [Diversity & Inclusion page](https://events.linuxfoundation.org/hyperledger-global-forum/attend/diversity-inclusion/) of our event website.

**Contact Us With Ideas**
If you have ideas on how we can create a more inclusive event, please do not hesitate to let us know. Contact the Hyperledger Events Team, events@hyperledger.org.

**Comment by Ruth-ikegah** [comment]
> @Anita-ihuman We collect feedback and ideas from the community via email, linked on the [Diversity & Inclusion page](https://events.linuxfoundation.org/hyperledger-global-forum/attend/diversity-inclusion/) of our event website.
> 
> **Contact Us With Ideas**
> If you have ideas on how we can create a more inclusive event, please do not hesitate to let us know. Contact the Hyperledger Events Team, [events@hyperledger.org](mailto:events@hyperledger.org).

Hi @celiastampslf, thanks for clarifying this up. I have done my review!. Thanks also for applying for a D/I badge for Hyperledger Global Forum!

**Comment by Nebrethar** [comment]
Thanks for applying @celiastampslf !! I am really excited to see where the review is now.

I will go ahead and generate a badge level --- once I do, please provide your feedback on the badge status; whether you accept the result or want to have further discussion on the status.

**Comment by celiastampslf** [comment]
@Nebrethar Thank you!  This result is accepted.

**Comment by Nebrethar** [comment]
Congratulations!! You will be in the list of badged events in about 5 minutes. You can find your badge images here, with markdown links below:

SVG: https://svgur.com/s/TX5

PNG:
![image](https://user-images.githubusercontent.com/34951354/106024237-31609300-608d-11eb-9bae-7bd8af48a27c.png)
