### ISSUE TITLE
Bot Updates

### ISSUE THREAD

**Issue by Nebrethar** [badging/event-diversity-and-inclusion#66]
We need to make a few improvements to the badging-bot. Planning notes will be kept here.

Feel free to add any ideas for features that you want in the comments!

**Comment by Nebrethar** [comment]
Sorry @InquisitiveVi @germonprez 😁 A review-check is one of the features we will be implementing so that doesn't happen!!!

**Comment by germonprez** [comment]
@Nebrethar did you need something on this?

**Comment by Nebrethar** [comment]
@germonprez I don't. This is an issue for collecting ideas for improvements to the current bot.

Right now, I've got
 - Add a bot-check to avoid treating regular issues like applications
 - Create a better system for reviewer assignment

**Comment by Nebrethar** [comment]
I am doing the testing on my fork of this project. So far, I have replicated the process!

https://github.com/Nebrethar/event-diversity-and-inclusion/issues/10

**Comment by Nebrethar** [comment]
A note here, those two issues I mentioned above are going to be fixed within a couple days. I have the necessary code written, just need to integrate it.

**Comment by Nebrethar** [comment]
I have plugged in the new bot. I'll leave this open for any issues that may come up.
