### ISSUE TITLE
[Virtual Event] Berlin Buzzwords

### ISSUE THREAD

**Issue by Max-Plain-Schwarz** [badging/event-diversity-and-inclusion#68]
# Virtual Event Submission

## Requirements

- Event Name: Berlin Buzzwords
- Link to the Event Website: https://2021.berlinbuzzwords.de/
- Provide verification that you are an event organizer: You can send an email to info@berlinbuzzwords.de and I will respond. You can also find me (Max King) on the team page here https://2021.berlinbuzzwords.de/team

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Please follow the link to see the demographic survey we will be using for 2021. This will be sent to speakers before the event and to attendees after the event. https://crumpet.webo.family/index.php/apps/forms/SNXgQT6gT3yx5oQX
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` This is the first year we are collecting this data, so we will display the data for Berlin Buzzwords 2021 after the event.

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Please follow the link to see the demographic survey we will be using for 2021. This will be sent to speakers before the event and to attendees after the event. https://crumpet.webo.family/index.php/apps/forms/SNXgQT6gT3yx5oQX
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` This is the first year we are collecting this data, so we will display the data for Berlin Buzzwords 2021 after the event.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` The event is online, however attendees must read and agreed to abide by the code of conduct before purchasing a ticket. The CoC can also be found on the Berlin Buzzwords landing page.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://2021.berlinbuzzwords.de/code-conduct

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` One
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity Access Tickets are available to people from underrepresented groups within the FOSS community. This includes, but is not limited to: women, people of colour, LGBTQIA people, disabled people, and people facing economic or social hardships. We do not place any barriers to accessing these tickets, and access to these tickets is at the individual's digression.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://2021.berlinbuzzwords.de/diversity-and-inclusivity-berlin-buzzwords

**Comment by germonprez** [comment]
Thanks so much for the application @Max-Plain-Schwarz! We really appreciate it :) 

I had two small questions/comments:

1) Why are you measuring attendee demographics after the event? I'm really just curious as to why you chose this order as I saw that speaker demographics are measured prior to the event. 

2) Would it be possible to provide a link to diversity access tickets on the register page? Just a small comment. It may help with findability. https://2021.berlinbuzzwords.de/tickets

Thanks again!

**Comment by Max-Plain-Schwarz** [comment]
Thank for the feedback @germonprez. I'll work on putting the link to the diversity tickets on the main tickets page. 

Regarding the demographic survey, the timing is something were experimenting with. With FOSS Backstage we sent out the survey after the event so we wouldn't overload attendees and speakers when they were registering and during on-boarding. We only got about a 15% response rate from that, so maybe sending the survey out with the registration confirmation would be a good idea. I'll look into including it with the registration confirmation for attendees, and the on-boarding email we send out to speakers.

**Comment by germonprez** [comment]
Great. Thanks @Max-Plain-Schwarz 

I'd be really interested to learn how the timing of the survey impacts response rates. I see your point in not wanting to overwhelm people early. I really trust on your judgment.

**Comment by Nebrethar** [comment]
Hi there! Just some housekeeping here.

I'm reassigning one review due to inactivity.

**Comment by Gemarodri** [comment]
Hi @Max-Plain-Schwarz, 
Thank you for the application!

I went through it and I have some small questions:
1) This is the first year you are collecting speakers' demographics data and you are collecting it after the event. So, you obviously cannot display it before the event. However, you can possibly add some information/link in the website to announce that speakers' demographics data is going to be displayed after the event. Maybe, a brief explanation of the importance of collecting and showing this speakers' demographics data would help to obtain more answers in the survey after the event. 

2) I was wondering whether the information about who can get a diversity ticket is self-explanatory. It says: "This includes, but is not limited to: women, people of colour, LGBTQIA people, disabled people, and people facing economic or social hardships." 
However, what does it mean to be a "people of colour" or to "face economic or social hardships"? Maybe, just adding an information contact to ask in case of doubts would be enough, or just a note to clarify these aspects.

Thanks again for the application.

**Comment by Max-Plain-Schwarz** [comment]
Thanks for all the feedback. I have updated the Diversity page to take into account @Gemarodri's comments, and have updated the tickets page with @germonprez's idea. Thanks :)

**Comment by Gemarodri** [comment]
Thanks @Max-Plain-Schwarz for considering my comments. I have done my review!. Thanks also for applying for a D/I badge for Berlin Buzzwords!

**Comment by germonprez** [comment]
Indeed! Thanks @Max-Plain-Schwarz I appreciate the time and effort you all have put into this.

**Comment by Nebrethar** [comment]
Looks like both reviewers are finished. Thanks @Gemarodri @germonprez 

Congratulations!! I am going to generate the badge now. @Max-Plain-Schwarz I'll need your acceptance of the badge, then we can go ahead and apply it.

**Comment by Max-Plain-Schwarz** [comment]
Thank you all for your input and the badge. We are really happy to receive a gold badge.

**Comment by Nebrethar** [comment]
Congratulations on your gold badge. Here you can find the badges in SVG and PNG format. You should also see it in the main badging list in about 5 minutes. Thanks @Max-Plain-Schwarz !!!

SVG: https://svgur.com/s/TX5

PNG:
![image](https://user-images.githubusercontent.com/34951354/106024237-31609300-608d-11eb-9bae-7bd8af48a27c.png)
