### ISSUE TITLE
[Virtual Event] KubeCon+CloudNativeCon Europe 2021 Virtual

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#72]
# Virtual Event Submission

## Requirements

- Event Name: KubeCon+CloudNativeCon Europe 2021 Virtual
- Link to the Event Website: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/
- Provide verification that you are an event organizer: My Name is Wendi West (wwest@contractor.linuxfoundation.org) and I am a contractor with The Linux Foundation working on Cloud Native Computing Foundation events. I manage the Diversity + Inclusion event activities and the scholarship program. My direct supervisor is Vanessa Heric, Associate Director of CNCF Events.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://www.cncf.io/blog/2021/03/08/a-look-inside-the-kubecon-cloudnativecon-schedule-selection-process/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.); and Details regarding a dis/ability that we should be mindful of as we try to accommodate everyone for this event.
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/register/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Cloud Native Computing Foundation’s scholarship program for KubeCon + CloudNativeCon Europe 2021 – Virtual exists to support individuals who may not otherwise have the opportunity to attend in two categories: Diversity and Need-Based. Additionally, KubeCon+CloudNativeCon Europe 2021-Virtual has a complimentary event pass type for the Keynotes + Solutions Showcase only, should anyone want an introduction to the event and not want to apply for a scholarship or participate in the full event experience.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Cloud Native Computing Foundation’s diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities) who may not otherwise have the opportunity to attend CNCF events. The Need-based scholarship is CNCF’s support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/attend/scholarships/

**Comment by Dhruv-Sachdev1313** [comment]
@Wendi-West Thank you for your response !!

I did go through the tranparency reports , Display of demographics seems pretty good to me , but we always recommend to display the demographics on the event page where it is findable and easily visible. Adding a reference to the report on the event website would help.

I have updated my review,
Thanks again for applying !!

**Comment by Wendi-West** [comment]
@Dhruv-Sachdev1313 Thank you for the feedback! Yes, I'm realizing through this process that displaying demographics on the event website would be good and can maybe post past event to show as an example, etc. And/or linking to the transparency reports on the event website as well. I can probably get that added prior to this event. And then will be working on the demographic listings specifically for our North American event in October, and future events.

**Comment by Nebrethar** [comment]
@mollydb 
Pinging for your review. 😁 Let me know if you need anything from me

**Comment by Dhruv-Sachdev1313** [comment]
@Wendi-West That would be really amazing !!!

**Comment by Nebrethar** [comment]
Both reviews are finished! I will generate a badge now 😁 
@Wendi-West Please let me know whether you accept the result 🎉

**Comment by Wendi-West** [comment]
@Nebrethar yes, we absolutely accept the result and badge!!! Thank you @mollydb and @Dhruv-Sachdev1313 for all of your work and assistance!!!

**Comment by Nebrethar** [comment]
Congratulations @Wendi-West on behalf of KubeCon And CloudNativeCon Europe 2021 for earning a CHAOSS D&I Gold Badge!

I will add this to the list in the README now. Thanks 😁
