### ISSUE TITLE
[Virtual Event] Magma Day

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#73]
# Virtual Event Submission

## Requirements

- Event Name: Magma Day
- Link to the Event Website: https://events.linuxfoundation.org/magma-day/
- Provide verification that you are an event organizer: My name is Wendi West (wwest@contractor.linuxfoundation.org) and I manage the Diversity + Inclusion scholarship program for CNCF and the KubeCon co-located events.

## Speaker Demographics

- [ ] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.) 
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` Magma Day will not have a CFP process and is curating their content for this 4 hour event.

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/magma-day/register/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/magma-day/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Magma Day is offering two types of diversity access tickets: Diversity and Need-Based.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities) who may not otherwise have the opportunity to attend. The Need-based scholarship is for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/magma-day/attend/scholarships/

**Comment by Nebrethar** [comment]
Hi @Wendi-West and thank you for the applications!!! We will get to them as soon as we possibly can. I am going to reassign @mollydb and @Dhruv-Sachdev1313 as the badging-bot seems to have assigned them for both applicaitons. Thanks again 😁

**Comment by Wendi-West** [comment]
Thank you! There are more coming. :) So, assign as you best see fit and I know that it will take time to get through them all. KubeCon+CloudNativeCon is a big event and there are a lot of CNCF sponsored co-located events.

**Comment by germonprez** [comment]
Thanks for the submission @Wendi-West! 

1. Regarding speaker demographics, because this is a curated event, could you describe the process by which the event attends to DEI in: 

1) The selection committee making the choices as to who to invite. The process by which the committee was assembled.
2) The speakers who are invited. The process by which this is done. 

Both of these items might be nice to include on the website for transparency. 

2. when I was doing a sample registration, I did not see the items that you listed with respect to Attendee/Speaker demographics. These were what I saw: 

Do you identify as a person of color?
What gender do you identify with?
How old are you? 

Perhaps it was later in the registration but could you provide a bit of clarity between the two? 

3. Would you display speaker/attendee demographics following the event? 

4. Is there a post-conference survey that would ask attendees about their DEI experiences? 

Thanks for your support and I look forward to your responses!! :)

**Comment by Wendi-West** [comment]
Hi @germonprez 

Thank you for your review. I may have jumped on this application a bit too early. The schedule is still being finalized and I'm awaiting additional information about the speakers. Therefore, I think we can pause on this review until I receive more information.

I'm sorry to have submitted without knowing all of the specifics for this event. This is a new one for us, and I was worried about time running out for review / processing the application, but I should've waited.

Thank you,
Wendi

**Comment by germonprez** [comment]
No problem :) 

Hopefully, some of these comments could prove helpful as you finalize specifics. Happy to help.

**Comment by Wendi-West** [comment]
@germonprez Yes, all of these questions and comments and process have been very insightful and thought provoking to better implement and improve our DEI transparency and initiatives. Thank you!

**Comment by Nebrethar** [comment]
I will close this for now, but feel free to re-apply on behalf of Magma Day anytime!
