### ISSUE TITLE
[Virtual Event] Cloud Native Rust Day

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#74]
# Virtual Event Submission

## Requirements

- Event Name: Cloud Native Rust Day
- Link to the Event Website: https://events.linuxfoundation.org/cloud-native-rust-day/
- Provide verification that you are an event organizer: My name is Wendi West (wwest@contractor.linuxfoundation.org) and I manage the Diversity + Inclusion event activities for KubeCon+CloudNativeCon and the scholarship program for CNCF events.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/cloud-native-rust-day/program/cfp/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/cloud-native-rust-day/register/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/cloud-native-rust-day/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Cloud Native Rust Day offers two categories: Diversity and Need-Based. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities) who may not otherwise have the opportunity to attend. The Need-based scholarship provides support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/cloud-native-rust-day/attend/scholarships/

**Comment by tetris4** [comment]
Hi @Wendi-West and thanks for applying for a CHAOSS D&I badge for this event and taking the time to respond to each question.

I don't see any stats regarding demographics for speakers and attendees on the event's website, do let me know if I have missed them! 

If they are not available at the moment, it would be great to have them in future iterations of the event in order to get a higher rating.

**Comment by Nebrethar** [comment]
@Ruth-ikegah  Pinging for your review 😁 Let me know if you need anything from me

**Comment by Wendi-West** [comment]
Hi @tetris4 

Thank YOU for reviewing all of these applications and providing valuable feedback!! You didn't miss the demographics. Based on these reviews and feedback, the events team is talking about all of this and are working on adding past demographics to our event websites. Otherwise, the way we currently share stats regarding speaker and attendee demographics is that CNCF publishes a transparency report following each KubeCon event that includes overall attendee and speaker demographic information. These conference transparency reports are published and can be viewed on the CNCF website: [https://www.cncf.io/reports/#conference-transparency-reports]The reports are also shared with the Marketing Committee to distribute and posted on Social Media. Prior to the full transparency report being completed, overall conference attendee and speaker demographic information is part of an infographic that is also shared with the Sponsors, Marketing Committee and on Social Media.

**Comment by tetris4** [comment]
Thanks for the prompt response @Wendi-West! I couldn't find past stats related to this particular event in the reports (again, do let me know if I missed them!), so I will maintain my review as is for now. Hopefully you can adjust this going forward and I'd be happy to give a 100%. =)

**Comment by Wendi-West** [comment]
@tetris4 I don't think you missed them, as not every co-located / CNCF sponsored event is specifically listed. Thank you again!

**Comment by Ruth-ikegah** [comment]
> @Ruth-ikegah Pinging for your review 😁 Let me know if you need anything from me

@Nebrethar done with my review! I'm sorry this took some time!

**Comment by Ruth-ikegah** [comment]
> @tetris4 I don't think you missed them, as not every co-located / CNCF sponsored event is specifically listed. Thank you again!

yeah, @Wendi-West I noticed I did not see Cloud-Native Rust Day in [this list](https://www.cncf.io/reports/#conference-transparency-reports). 

My suggestion is subsequently with coming events you can have it displayed like the way Hyperledger Global Forum did theirs [here](https://events.linuxfoundation.org/hyperledger-global-forum/attend/diversity-inclusion/#event-demographics) (psst. they also have a D/I badge from us)!

Thanks again for applying. It feels good to make these suggestions and changes to make it better for all!

**Comment by Nebrethar** [comment]
@Wendi-West I am generating a badge now. I'm excited for you and Cloud Native Rust Day! Please let me know if you accept the result.

**Comment by Wendi-West** [comment]
Thank you @Ruth-ikegah and @tetris4 for your review, information and suggestions! @Nebrethar we accept!!! Thank you for the badge!!!

**Comment by Nebrethar** [comment]
Thanks 😁 I will go ahead and close this review. Then i will add it to the README list!
