### ISSUE TITLE
[Virtual Event] Cloud Native Security Day Europe 2021

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#75]
# Virtual Event Submission

## Requirements

- Event Name: Cloud Native Security Day Europe 2021
- Link to the Event Website: https://events.linuxfoundation.org/cloud-native-security-day-europe/
- Provide verification that you are an event organizer: My name is Wendi West (wwest@contractor.linuxfoundation.org) and I manage the Diversity + Inclusion event activities for KubeCon+CloudNativeCon and the scholarship program for CNCF events.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/cloud-native-security-day-europe/program/cfp/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/cloud-native-security-day-europe/register/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/cloud-native-security-day-europe/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Cloud Native Security Day offers two categories: Diversity and Need-Based.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities) who may not otherwise have the opportunity to attend. Need-based scholarship provides support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/cloud-native-security-day-europe/attend/scholarships/

**Comment by Wendi-West** [comment]
Hello @Gemarodri. Thank you for your feedback. Please find answers to your questions below:

1. Page 3 of the registration form (after selecting registration pass type and providing contact information) includes additional questions (industry type, job level, etc.) and then dis/ability and demographic questions. Demographic information is collected solely for the purpose of compiling, analyzing and disclosing aggregate statistics regarding diversity of attendance at our events, to help track progress towards meeting our commitment to diversity initiatives. Consent to provide demographic information for the purpose listed above is optional and purely voluntary, and is provided by selecting an option from the drop-down for the corresponding category. Demographic information is considered confidential and private. It will not be shared with others as part of the attendee's registration details, nor will it be used to subject the attendee to adverse treatment. Internally, we can run a report from our registration system to get attendee statistics.

2. CNCF publishes a transparency report following each event that includes attendee demographic information. These conference transparency reports are published and can be viewed on the CNCF website: https://www.cncf.io/reports/#conference-transparency-reports The reports are also shared with the Marketing Committee to distribute and posted on Social Media. Prior to the full transparency report being completed, attendee demographic information is part of an infographic that is also shared with the Marketing Committee and on Social Media.

3. On the Diversity + Inclusion page (https://events.linuxfoundation.org/cloud-native-security-day-europe/attend/diversity-inclusion/#contact-us) of the event website we have a section to contact us "If you have ideas on how we can create a more inclusive event, please do not hesitate to let us know. Contact Angela Brown, General Manager of Events, at angela@linuxfoundation.org" Additionally, we have a D+I Slack Channel where attendees can provide feedback, and on the registration form if someone selected that they have a dis/ability we have a follow up question asking for details regarding the dis/ability that we should be mindful of as we try to accommodate everyone for this event. We run registration reports for the dis/ability question once a week to make note of any suggestions / comments / feedback.

4. Yes, page 6 of the registration form is Terms & Conditions. The code of conduct is listed there and must be accepted by the attendee in order to complete registration. 

Let me know if I answered your questions, or if you need any further information or explanation. 

Thank you!!!
Wendi

**Comment by Gemarodri** [comment]
Thank you @Wendi-West, you have answered all my questions perfectly.

I updated my review taking into account your answers, and I'm finished with the review.

Thank you again for applying!

**Comment by Nebrethar** [comment]
@Anita-ihuman Hi 😁 

Looks like all checks are met on your side. May I confirm that you have finished?

**Comment by Anita-ihuman** [comment]
Yes, all check are met on my end.

**Comment by Nebrethar** [comment]
@Wendi-West 
It looks like the application is finished, so I will go ahead and generate a badge for Cloud Native Security Day Europe 2021. You'll have the option to accept the result, so that we can award the badge 🎉

**Comment by Wendi-West** [comment]
Oh my gosh, this is so exciting! Thank you!!!

**Comment by Nebrethar** [comment]
It's just generally a matter of saying "Looks good to me!". It's a formality to put closure on the review process 😁

**Comment by Wendi-West** [comment]
Ohhhhh, ok, great. I was wondering if there was a formal acceptance process or a button I should be clicking or something. :) In that case...this looks good to me! Thank you so very much for the thorough and thought provoking review process.

**Comment by Nebrethar** [comment]
I'm so glad. And thank you too! Congratulations @Wendi-West on a CHAOSS D&I Gold Badge for Cloud Native Security Day 2021! I'll post some resources here and the bot will close it up.

SVG: https://svgur.com/s/TX5

PNG:
![image](https://user-images.githubusercontent.com/34951354/106024237-31609300-608d-11eb-9bae-7bd8af48a27c.png)
