### ISSUE TITLE
[Virtual Event] Cloud Native Wasm Day

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#76]
# Virtual Event Submission

## Requirements

- Event Name: Cloud Native Wasm Day
- Link to the Event Website: https://events.linuxfoundation.org/cloud-native-wasm-day/
- Provide verification that you are an event organizer: My name is Wendi West (wwest@contractor.linuxfoundation.org) and I manage the Diversity + Inclusion event activities for KubeCon+CloudNativeCon and the scholarship program for CNCF events.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/cloud-native-wasm-day/program/cfp/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/cloud-native-wasm-day/register/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/cloud-native-wasm-day/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Cloud Native Wasm Day offers two categories: Diversity and Need -Based.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities) who may not otherwise have the opportunity to attend. The Need-based scholarship provides support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/cloud-native-wasm-day/attend/scholarships/

**Comment by Gemarodri** [comment]
Thank you @Wendi-West for this application.

The application looks good to me, I only have a minor comment to consider:

In a previous issue, you have mentioned that the conference transparency reports are published and can be viewed on the CNCF website: https://www.cncf.io/reports/#conference-transparency-reports. I think that it may be nice to have a link to these reports in the current website of the event.

Thanks :)

**Comment by Wendi-West** [comment]
@Gemarodri Thank you! Yes, after going through this application process I have made notes about sharing / posting demographic information, and think that a link to the transparency reports is a good idea. I'm bringing all of this to the events team so that we can begin to implement these various suggestions.

**Comment by Nebrethar** [comment]
@Gemarodri Checking in, are you finished with this review? Thanks 😁 

@djmitche It looks like you just recently checked your boxes 😆  Let me know when you are finished and have no more questions.

**Comment by djmitche** [comment]
The speaker-demographics answers link to https://events.linuxfoundation.org/cloud-native-wasm-day/program/cfp, but I don't see any information about gathered demographics there.  I trust that the registration process asks the relevant questions, so that's fine.

The [transparency reports](https://www.cncf.io/reports/#conference-transparency-reports) don't break down demographics specifically for speakers.  Is it possible to break those out individually?

I also didn't find anything indicating what is asked of attendees regarding D&I ("The Event requests feedback from attendees regarding Diversity & Inclusion.") -- what is that process?

**Comment by Wendi-West** [comment]
@djmitche thank you for your review and questions. Please find answers below:

Page 3 of the registration form (after selecting registration pass type and providing contact information) includes additional questions (industry type, job level, etc.) and then dis/ability and demographic questions:

Do you have a dis/ability that we should be mindful of as we try to accommodate everyone for this event?
Sub question when answer is YES: Please provide additional details here:

Do you identify as a person of color?
Sub question when Yes is selected to question above: With which racial/ethnic background(s) do you identify? (check all that apply)

What gender do you identify with?

Each attendee and speaker would complete the registration form and answer these questions (if they so choose / they are voluntary questions)

As an example from the North America 2020 transparency report, in the Diversity + Inclusion section they mention speakers: "Of the keynote speakers, 48% identified as men and 52% as women or gender non-conforming. For track sessions, 84% of speakers identified as men and 16% as women or gender non-conforming. Increasing gender diversity and attendance
of other underrepresented groups continues to be a priority for CNCF."

Additionally, we provide initial demographic infographics to Sponsors, Staff and the Marketing Committee to share. Here is an example of one from Europe 2020 
[KubeCon_EU_2020_Virtual_DiversityData_v3.pdf](https://github.com/badging/event-diversity-and-inclusion/files/6246786/KubeCon_EU_2020_Virtual_DiversityData_v3.pdf)

In regards to D+I feedback: On the Diversity + Inclusion page https://events.linuxfoundation.org/cloud-native-wasm-day/attend/diversity-inclusion/#contact-us of the event website we have a section to contact us "If you have ideas on how we can create a more inclusive event, please do not hesitate to let us know. Contact Angela Brown, General Manager of Events, at angela@linuxfoundation.org" Additionally, we have a D+I Slack Channel where attendees can provide feedback, and on the registration form if someone selected that they have a dis/ability we have a follow up question asking for details regarding the dis/ability that we should be mindful of as we try to accommodate everyone for this event. We run registration reports for the dis/ability question once a week to make note of any suggestions / comments / feedback.

Let me know if this answers your questions, or if there is anything else I can help provide.

Thank you!!!
Wendi

**Comment by Gemarodri** [comment]
Yes, @Nebrethar, I have finished

**Comment by djmitche** [comment]
Perfect, thanks!  @Gemarodri it looks like there's one more checkbox for you? (displaying attendee demographics)

**Comment by Gemarodri** [comment]
It's checked now, thank you @djmitche :)

**Comment by Nebrethar** [comment]
Thanks @Gemarodri and @djmitche for your attention to detail and thoughtful review 😁 

@Wendi-West I am so glad to see this! I'm going to go ahead and generate the badge; let me know if you accept the result, or otherwise.

**Comment by Wendi-West** [comment]
Thank you @djmitche @Gemarodri @Nebrethar !!! This all looks wonderful, and we graciously accept the badge!!! :)

**Comment by Nebrethar** [comment]
Thanks again @Wendi-West. Sorry for lagging a bit here. I will add this to the badging list now!!!

Congratulations again :) and thanks for your hard work.
