### ISSUE TITLE
[Virtual Event] Crossplane Community Day Europe

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#77]
# Virtual Event Submission

## Requirements

- Event Name: Crossplane Community Day Europe
- Link to the Event Website: https://events.linuxfoundation.org/crossplane-community-day-europe/
- Provide verification that you are an event organizer: My name is Wendi West (wwest@contractor.linuxfoundation.org) and I manage the Diversity + Inclusion event activities for KubeCon+CloudNativeCon and the scholarship program for CNCF events.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/crossplane-community-day-europe/program/cfp/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/crossplane-community-day-europe/register/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/crossplane-community-day-europe/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Crossplane Community Day Europe offers two categories: Diversity and Need-based.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities) who may not otherwise have the opportunity to attend. The Need-based scholarship provides support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/crossplane-community-day-europe/attend/scholarships/

**Comment by germonprez** [comment]
Thanks for the submission @Wendi-West :) 

A few questions regarding Speaker/Attendee Demographics: 

1) I really liked your answer regarding speaker demographics. Are their going to be keynotes at the conference? If so, could you describe the process by which you ensure DEI in this process? 

2) Will the demographic be reported publicly or used internally? 

3) With respect to registration you mention underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc but I do not see this in the registration from. I see: 

Do you identify as a person of color?
What gender do you identify with?
How old are you? 

Could you please align these? Either as updating the registration form (best) or modifying the issue. 

4) Is there a process by which you will requesting feedback from attendees, either during the conference or with a post-survey, to better understand inclusivity from an attendee perspective? 

I look forward to your responses and thanks again for participating in the CHAOSS DEI Event Badging Program!!

**Comment by Wendi-West** [comment]
@germonprez y'all are going to get sick of me ;) 

Crossplane Community Day Europe is a co-located event with KubeCon+CloudNativeCon. The Crossplane event takes place the day before KubeCon. May 4 from 10am - 4pm CEST. There is only 1 opening Keynote (10 minutes) for Crossplane Community Day, and then it opens to Breakout Sessions and Lightning Talks.

**Comment by germonprez** [comment]
100% not sick of you :) 

What you say makes sense and certainly addresses my first question. Thanks!

**Comment by Wendi-West** [comment]
@germonprez I accidentally hit comment before I was finished. Sorry about that. I've updated / completed the response.

**Comment by germonprez** [comment]
Got it. I wasn't clicking on the drop down boxes so I wasn't seeing the sub questions. Thanks for pointing that out. 

I could not get the Aside from gender, if you identify with an underrepresented minority group in technology, please indicate that group below.(I.e. race/ethnicity, disability, LGBTQ, etc.) box to show up or I don't see it on the page. I'm using Firefox if that makes any difference. Sorry to be difficult on this one but now I'm interested :) 

Awesome answer on the 'seeking feedback' part. How is the Slack Channel provided to folks? Is it shared at the event? I could see why you may not want to put it on the webpage.

**Comment by Wendi-West** [comment]
I inquired about the form and question, and found out that we used to have just the one broad stroke question "aside from gender, if you identify with an underrepresented group in technology..." listed on the form, but have replaced it with specific questions around Gender, Dis/Ability, Race and Age. As those were the areas that one question would cover, but we wanted to track it more intentionally. We use the "aside from gender..." question only if an event did not use the more detailed questions. Upon review of this, I realize that LGBTQ+ is not asked in those other 4 questions. If you have feedback regarding that, we would be very interested. If anyone is applying for a Diversity Scholarship, we do have a specific question "Which underrepresented and/or marginalized group(s) do you identify with?" And then list options: LGBTQIA, Person of Color, Person with a dis/ability, Woman, Other (please specify)

All Access registered attendees receive an invitation to the CNCF Slack and a list of channels specific to the event, including D+I. The list of channels are added to the KubeCon event website, and information on how to join, etc. as well as provided in an all-attendee pre-event email.

**Comment by germonprez** [comment]
Super helpful. Thanks @Wendi-West 

For the first part, there is an excellent guide from https://github.com/drnikki/open-demographics/blob/master/SURVEY.md that suggests a series of categories that can be used in this regard. 

*. Ability - Mental and/or physical
*. Age
*. Ethnicity
*. Gender
*. Race
*. Religion
*. Sexual Orientation
*. Socio-Economic Status/Class

With the detailed set of questions for each at: https://github.com/drnikki/open-demographics/tree/master/doc-source/questions 

For the specific issue regarding LGBTQ+, the Sexual Orientation questions could be helpful in this regard. Perhaps it is possible to add a drop down question of Sexual Orientation and include all, or a subset, of the questions from the link provided. This could be LGB + Prefer Not to Specify + Other/Specify. 

For the second part, this is fantastic!!

**Comment by Ruth-ikegah** [comment]
Ayyyyy! I'm late for the party! So much enlightening conversation went on here! 

Hi, @Wendi-West Thanks for applying for a D/I badge for Crossplane Community Day :)

I have a question, so as not to repeat the same conversation on your other submissions, [one of which I am reviewing](https://github.com/badging/event-diversity-and-inclusion/issues/74). The same thing applies to demographics in that conference right?

**Comment by Nebrethar** [comment]
@germonprez @Ruth-ikegah

I'm here to confirm, have you finished your reviews? Thanks 😁

**Comment by Wendi-West** [comment]
@Ruth-ikegah yes, the registration form and demographic questions would apply for the other event (if it's one that I submitted) you're reviewing as well. However, please don't hesitate to ask any questions.

**Comment by germonprez** [comment]
I won't be making changes to my review @Nebrethar. However! I'd love to hear from @Wendi-West on the one open point I had above on the demographic questions :)

**Comment by Wendi-West** [comment]
@germonprez I brought this up on a team call this morning, but before I had a chance to thoroughly read your response and the links provided. The team member who handles registration was very interested and asked that I share the information you provided. So, she and I will be discussing further tomorrow.

**Comment by germonprez** [comment]
Fantastic! I'm happy to provide anymore insight where I can. Thanks!!

**Comment by Wendi-West** [comment]
I will definitely reach out if we need additional guidance! Overall, I'm compiling all of the notes and questions provided through this review process (for all of the applications I submitted) so that we can implement various aspects  and improve our event websites and registration forms / questions, display of demographics, etc. This is all very informative and helpful!! And you have all been so lovely to work with!

**Comment by Wendi-West** [comment]
@germonprez I just found out that you the "team member who handles registration" I was referring to (sorry about my lackluster description...she's a super star!) Annie Leroux! She asked who I'm working on this with and I gave your name and she told me that she had weekly calls with you when she was assisting with Program Management this past year. Small world!

**Comment by germonprez** [comment]
Haha! That's awesome :) Tell her hello!

**Comment by Nebrethar** [comment]
@germonprez @Ruth-ikegah Thank you for your thoughtful reviews.

@Wendi-West I am going to generate a badge. I'm excited for you! Please let me know if you accept the result or otherwise 😁

**Comment by Wendi-West** [comment]
@Nebrethar I accept!!!! :) Thank you @germonprez @Ruth-ikegah !!!

Additionally, since I have you all here :), for future applications (will be applying again in October for events) should I include all of the information in the initial application sections that reviewers have followed up with / requested? Or keep the application simple and wait for the questions, like we've done thus far? Want to make the process the most efficient and effective for everyone. Thanks!

**Comment by germonprez** [comment]
Thanks @Wendi-West! 

In the future, I would likely recommend that you just answer the questions as appropriate to the event. No history needs to be provided. I'm guessing that through this process, the October events will have slight different submissions so the history is sort of implicitly captured :) 

Congratulations and thanks for participating in the CHAOSS DEI Badging Program!!

**Comment by Ruth-ikegah** [comment]
> @germonprez @Ruth-ikegah
> 
> I'm here to confirm, have you finished your reviews? Thanks 😁

Yes I am done with my review!

**Comment by Ruth-ikegah** [comment]
> @Ruth-ikegah yes, the registration form and demographic questions would apply for the other event (if it's one that I submitted) you're reviewing as well. However, please don't hesitate to ask any questions.

Alright definitely! Congratulations on your Gold badge and thanks for applying!

**Comment by Wendi-West** [comment]
@Nebrethar do I use the same link for the badge / graphic that you shared for the Cloud Native Security Day badge? https://svgur.com/s/TX5

**Comment by Nebrethar** [comment]
Thank you @Wendi-West and congratulations again! We have no link attached to that SVG so it can be used for any badging event. The URL in each markdown badge will link to the original application, but these links are much longer.

Here is the linking version of the SVG, as taken from the above bot comment, and its link:

<img src='https://img.shields.io/badge/D%26I-Gold-yellow?style=flat-square&labelColor=583586&&link=https://github.com/badging/event-diversity-and-inclusion/issues/77/&logo=data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDI1MCAyNTAiPgo8cGF0aCBmaWxsPSIjMUM5QkQ2IiBkPSJNOTcuMSw0OS4zYzE4LTYuNywzNy44LTYuOCw1NS45LTAuMmwxNy41LTMwLjJjLTI5LTEyLjMtNjEuOC0xMi4yLTkwLjgsMC4zTDk3LjEsNDkuM3oiLz4KPHBhdGggZmlsbD0iIzZBQzdCOSIgZD0iTTE5NC42LDMyLjhMMTc3LjIsNjNjMTQuOCwxMi4zLDI0LjcsMjkuNSwyNy45LDQ4LjVoMzQuOUMyMzYuMiw4MC4yLDIxOS45LDUxLjcsMTk0LjYsMzIuOHoiLz4KPHBhdGggZmlsbD0iI0JGOUNDOSIgZD0iTTIwNC45LDEzOS40Yy03LjksNDMuOS00OS45LDczLTkzLjgsNjUuMWMtMTMuOC0yLjUtMjYuOC04LjYtMzcuNS0xNy42bC0yNi44LDIyLjQKCWM0Ni42LDQzLjQsMTE5LjUsNDAuOSwxNjIuOS01LjdjMTYuNS0xNy43LDI3LTQwLjIsMzAuMS02NC4ySDIwNC45eiIvPgo8cGF0aCBmaWxsPSIjRDYxRDVGIiBkPSJNNTUuNiwxNjUuNkMzNS45LDEzMS44LDQzLjMsODguOCw3My4xLDYzLjVMNTUuNywzMy4yQzcuNSw2OS44LTQuMiwxMzcuNCwyOC44LDE4OEw1NS42LDE2NS42eiIvPgo8L3N2Zz4K' alt='D&I Badging badge state: gold'/>


https://img.shields.io/badge/D%26I-Gold-yellow?style=flat-square&labelColor=583586&&link=https://github.com/badging/event-diversity-and-inclusion/issues/77/&logo=data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDI1MCAyNTAiPgo8cGF0aCBmaWxsPSIjMUM5QkQ2IiBkPSJNOTcuMSw0OS4zYzE4LTYuNywzNy44LTYuOCw1NS45LTAuMmwxNy41LTMwLjJjLTI5LTEyLjMtNjEuOC0xMi4yLTkwLjgsMC4zTDk3LjEsNDkuM3oiLz4KPHBhdGggZmlsbD0iIzZBQzdCOSIgZD0iTTE5NC42LDMyLjhMMTc3LjIsNjNjMTQuOCwxMi4zLDI0LjcsMjkuNSwyNy45LDQ4LjVoMzQuOUMyMzYuMiw4MC4yLDIxOS45LDUxLjcsMTk0LjYsMzIuOHoiLz4KPHBhdGggZmlsbD0iI0JGOUNDOSIgZD0iTTIwNC45LDEzOS40Yy03LjksNDMuOS00OS45LDczLTkzLjgsNjUuMWMtMTMuOC0yLjUtMjYuOC04LjYtMzcuNS0xNy42bC0yNi44LDIyLjQKCWM0Ni42LDQzLjQsMTE5LjUsNDAuOSwxNjIuOS01LjdjMTYuNS0xNy43LDI3LTQwLjIsMzAuMS02NC4ySDIwNC45eiIvPgo8cGF0aCBmaWxsPSIjRDYxRDVGIiBkPSJNNTUuNiwxNjUuNkMzNS45LDEzMS44LDQzLjMsODguOCw3My4xLDYzLjVMNTUuNywzMy4yQzcuNSw2OS44LTQuMiwxMzcuNCwyOC44LDE4OEw1NS42LDE2NS42eiIvPgo8L3N2Zz4K
