### ISSUE TITLE
[Virtual Event] Fluentcon (Cloud Native Logging day with Fluentd and Fluent Bit)

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#78]
# Virtual Event Submission

## Requirements

- Event Name: Fluentcon (Cloud Native Logging day with Fluentd and Fluent Bit)
- Link to the Event Website: https://events.linuxfoundation.org/fluentcon/
- Provide verification that you are an event organizer: My name is Wendi West (wwest@contractor.linuxfoundation.org) and I manage the Diversity + Inclusion event activities for KubeCon+CloudNativeCon and the scholarship program for CNCF events.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/fluentcon/program/cfp/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/fluentcon/register/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/fluentcon/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Fluentcon offers two categories for access tickets: Diversity and Need-based.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities) who may not otherwise have the opportunity to attend. The Need-based scholarship provides support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/fluentcon/attend/scholarships/

**Comment by Anita-ihuman** [comment]
@Wendi-West  Does your Event requests feedback from attendees regarding Diversity & Inclusion. If yes, How do you achieve this?

**Comment by Wendi-West** [comment]
@Anita-ihuman On the Diversity + Inclusion page https://events.linuxfoundation.org/fluentcon/attend/diversity-inclusion/#contact-us of the event website we have a section to contact us "If you have ideas on how we can create a more inclusive event, please do not hesitate to let us know. Contact Angela Brown, General Manager of Events, at angela@linuxfoundation.org" Additionally, the overall event has a D+I Slack Channel where attendees can provide feedback, and on the registration form if someone selected that they have a dis/ability we have a follow up question asking for details regarding the dis/ability that we should be mindful of as we try to accommodate everyone for this event. We run registration reports for the dis/ability question once a week to make note of any suggestions / comments / feedback.

**Comment by tetris4** [comment]
Hi @Wendi-West and thanks for applying for a CHAOSS D&I badge for another event!

I will have to ask again the same question as in your other application. =)

> I don't see any stats regarding demographics for speakers and attendees on the event's website, do let me know if I have missed them!
> If they are not available at the moment, it would be great to have them in future iterations of the event in order to get a higher rating.

**Comment by Wendi-West** [comment]
@tetris4 You didn't miss the demographics on the event's website. I have taken all of the notes from these various applications, especially about displaying the demographics and am presenting the information to our team for future events. I believe a new website build request template is being worked on so that we have demographics from the latest / past event on the current event's website. So, that will be coming soon! Otherwise the way we share demographics is CNCF publishes a transparency report that includes overall attendee and speaker demographic information. These conference transparency reports are published and can be viewed on the CNCF website: [https://www.cncf.io/reports/#conference-transparency-reports]The reports are also shared with the Marketing Committee to distribute and posted on Social Media. Prior to the full transparency report being completed, overall conference attendee and speaker demographic information is part of an infographic that is also shared with the Sponsors, Marketing Committee and on Social Media.

**Comment by tetris4** [comment]
Thanks for the prompt response @Wendi-West ! I couldn't find past stats related to this particular event in the reports (again, do let me know if I missed them!), so I will maintain my review as is for now. Hopefully you can adjust this going forward and I'd be happy to give a 100% next time. =)

**Comment by Wendi-West** [comment]
Thank you @tetris4 I completely understand, and yes, we're working on making improvements for future events / event websites based on the feedback and reviews we're receiving.

**Comment by Nebrethar** [comment]
@Anita-ihuman @tetris4

Thank you for your kind and thoughtful reviews. Let me know when you are finished 😁

**Comment by Anita-ihuman** [comment]
I am done with the review. @Wendi-West Thank you once again for choosing to apply for a D&I badge,  Good luck with your forthcoming event.

**Comment by Wendi-West** [comment]
@Nebrethar is there anything else you need from me for this process?

**Comment by Nebrethar** [comment]
@Wendi-West I was just looking at this issue! It looks like we can generate a badge. I will need your approval once it is generated 😁

**Comment by Wendi-West** [comment]
@Nebrethar THANK YOU!!!!!! Yes, we accept!!! :)

**Comment by Nebrethar** [comment]
@Wendi-West Thanks again 😁 I will put it in the README now. Congratulations!!! And thanks for your hard work @tetris4 @Anita-ihuman
