### ISSUE TITLE
[Virtual Event] Kuberenetes AI Day

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#79]
# Virtual Event Submission

## Requirements

- Event Name: Kuberenetes AI Day
- Link to the Event Website: https://events.linuxfoundation.org/kubernetes-ai-day/
- Provide verification that you are an event organizer: My name is Wendi West (wwest@contractor.linuxfoundation.org) and I manage the Diversity + Inclusion event activities for KubeCon+CloudNativeCon and the scholarship program for CNCF sponsored events.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/kubernetes-ai-day/program/cfp/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/kubernetes-ai-day/register/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/kubernetes-ai-day/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Kubernetes AI Day offers two categories: Diversity and Need-based.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities) who may not otherwise have the opportunity to attend. The Need-based scholarship provides support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/kubernetes-ai-day/attend/scholarships/

**Comment by Nebrethar** [comment]
This event is next to be reviewed 😁

My plan for tomorrow is to find out how we are going to assign the remaining 4 reviews.

**Comment by xiaoya-Esther** [comment]
I volunteer to help if we have a shortage of reviewers.

**Comment by Nebrethar** [comment]
Thanks @xiaoya-Esther. It's nice to see you! I'll send an email your way

**Comment by Dhruv-Sachdev1313** [comment]
@Wendi-West Thanks for the submission !!
As you did mention on the previous review for KubeCon + CloudNativeCon, does this event also has transparency reports where speaker and attendee demographics are displayed ?

**Comment by ElizabethN** [comment]
@Wendi-West Hiii! :wave: 

A few questions for you, in addition to the point @Dhruv-Sachdev1313 already asked about. 

Can you tell me a little more about the speaker selection process for this event? Specifically:
- What steps were taken to ensure a diverse speaker lineup (including any outreach to traditionally underrepresented groups prior to the CfP, blind selection process, etc)?
- What steps were taken to ensure a diverse selection committee was in place to choose from the submitted proposals?

I'm curious about this statement, in particular, so I just want to make sure this policy is being enforced for this event.
>All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.

One other quick question: as I went through the registration process, it didn't appear to require me to check a box that I'd read and agree to adhere to the Code of Conduct. Did I overlook that somewhere? I see that it is mentioned in the Code of Conduct itself, but sometimes there is an extra check that require participants to explicitly agree to it before registering. 

Thank you so much! :pray: ✨

**Comment by Wendi-West** [comment]
@Dhruv-Sachdev1313 CNCF publishes a transparency report following each KubeCon event that includes overall attendee and speaker demographic information. These conference transparency reports are published and can be viewed on the CNCF website: [https://www.cncf.io/reports/#conference-transparency-reports]The reports are also shared with the Marketing Committee to distribute and posted on Social Media. Prior to the full transparency report being completed, overall conference attendee and speaker demographic information is part of an infographic that is also shared with the Sponsors, Marketing Committee and on Social Media.

**Comment by Wendi-West** [comment]
@ElizabethN I'm getting the information / details to your speaker questions, but in the meantime, I wanted to answer your question about the Code of Conduct. Yes, page 6 of the registration form is Terms & Conditions. The code of conduct is listed there and must be accepted by the attendee in order to complete registration.

**Comment by ElizabethN** [comment]
> The code of conduct is listed there and must be accepted by the attendee in order to complete registration.
Ah, perfect! Thank you @Wendi-West! ✨

**Comment by Nebrethar** [comment]
@Dhruv-Sachdev1313 @ElizabethN 

It looks like both of your reviews are finished, can I get a confirmation of that? 🎉

**Comment by Wendi-West** [comment]
@Nebrethar, @ElizabethN is waiting for some answers from me. I have a call with the Kubernetes AI Day team tomorrow and hope to get more information to better answer her questions and will add as soon as I have them.

**Comment by Dhruv-Sachdev1313** [comment]
Hello @Wendi-West 
>  These conference transparency reports are published and can be viewed on the CNCF website: [https://www.cncf.io/reports/#conference-transparency-reports]
I had one more question, I am unable to find the transparency report for this event in particular. If there is one , Can you please send a direct link to this event's report? OR is this event happening for the first time ? 
As far as I know , Kubernetes day and Kubernetes AI day are different events. Please do correct me If I am wrong. If this is so , Do you have any other demographics for this one?

Thank you and looking forward to your response !!

**Comment by Wendi-West** [comment]
Hi @Dhruv-Sachdev1313 this is the first event for Kubernetes AI Day. And Kubernetes AI Day is separate from Kubernetes on Edge (also the first event for them)

**Comment by Wendi-West** [comment]
@ElizabethN Here are the diversity questions asked in the CFP process:

What gender does the primary speaker identify with? *- Select an option
Man
Woman
Nonbinary
Prefer not to answer

Does the primary speaker identify as a person of color?
Yes
No
(If no, the submitter will proceed to the next questions. If yes, they will get a selection to choose from)

Which racial/ethnic background does the primary speaker identify with? Select all that apply:
Asian
Black
Latinx
Native American
Pacific Islander
Prefer not to Answer

Regarding the panel we include this information in the CFP process:

Additional Speaker or Panelists

Note: Each session is allowed (1) primary speaker and (1) co­-speaker. The primary speaker for a proposal will receive a complimentary conference pass and the co-speaker will receive a discounted conference pass. 

All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company. The Linux Foundation does not accept panel submissions with all-men panelists of 3 or more in an effort to increase speaker diversity. Additionally, panel submissions must include the names of all participants in the initial submission to be considered.

Is this a panel discussion?
Yes
No
(If yes, the next question asks for panelist information and confirmation of a woman on the panel. If no, the submitter can continue onto the form)

By selecting yes here, I confirm that at least one of the participants on this proposed panel identifies as a woman.
Yes
No
(If no is selected, they receive a message that they cannot move forward and need to come back and finish when there is a woman on the panel)

Once the CFP closes, the Program Committee (recommended / put together based on expertise in subject matter and involvement in the community) receives a report of the submitted proposals and score each on a scale of 1-5. Final decisions are based on the top rated submissions. The PC has access to the diversity questions / answers of each submission, and if additional outreach or invitations need to be made (due to a lack of diverse submissions or top rated submissions) then the Program Committee will do so to help ensure diverse speaker demographics. 

Let me know if this answers your questions.

**Comment by Nebrethar** [comment]
@ElizabethN @Dhruv-Sachdev1313 

It's so nice to see the amount of care you are putting into these reviews! Ping me once your review is updated, and let me know if it is finished or what other information you may need 😁

**Comment by ElizabethN** [comment]
@Wendi-West thank you so much for looking into this and for providing the answers to my questions. All of these are spot-on and it seems as if this is very important to you when building out the schedule. Thank you! ✨ 

@Nebrethar I'm 👍 on my review. All finished!

**Comment by Dhruv-Sachdev1313** [comment]
@Wendi-West  Thank you for the answering ! And Good luck with your forthcoming event !!  
@Nebrethar I am done with this review.

**Comment by Nebrethar** [comment]
Thanks again @Wendi-West. Congratulations! I will go ahead and add it to the README
