### ISSUE TITLE
Feedback from a Mock Applicant

### ISSUE THREAD

**Issue by ElizabethN** [badging/event-diversity-and-inclusion#8]
:wave: Hi! 

I had some feedback as an Event Applicant:

1. Something we might also want to ask when talking about speaker demographics is the talk submission review process, whether it is designed around increasing the diversity of speakers. Maybe ask these questions on the application?
  - If there is an open Call for Papers, is the submission review process anonymous?
  - Is there a diverse panel of abstract reviewers?
  - Is there outreach done to underrepresented and marginalized groups when a Call for Papers is open?

2. Regarding the Code of Conduct, we might also want to ask about
  - the level of training given to those responsible for enforcing it at the event
  - if event registrants are required to read and agree to the CoC as part of the registration process

3. And maybe this is a whole new section, but I think Accessibility/Inclusivity should be a big part of what we ask here:
  - is the event website accessible for visually and hearing impaired folks?
  - is the venue wheelchair friendly?
  - are there sign language interpreters or closed captioning available?
  - are there resources for visually impaired folks? (Volunteers to assist as guides, alternative versions of schedules in Braille or available besides just online?)
  - is the venue easily accessible via public transit?
  - for any food that is served, are there vegan/vegetarian/gluten free/dairy free/kosher/halal options, or accommodations for those with food allergies?
  - does this event conflict with any major religious or cultural holiday? If so, does that affect how you host your event? (which, the timing might be unavoidable, but it would be helpful to know that it's something they were aware of and thought about while planning)

And definitely it will be a little smoother when the process includes a form that can be filled out, but I was able to follow the clear documentation to submit my event. 👍 

ccing @jwflory and @germonprez since they are my reviewers and I'm not sure who else is actively taking part in this testing phase. Would love to get your thoughts here!

**Comment by Nebrethar** [comment]
Thank you @ElizabethN for your feedback. All of the sections of your response provide insights into the Badging Project that we had not considered. 😁 

It also seems that some of the points in the last section could branch out into new D&I Metrics. We really don't have any metric that sounds like "Event Accessibility" or "Physical Access" or "Cultural Accommodations". 
While I'm just throwing some ideas out there, I'd suggest bringing this up in the [D&I Metrics Repository](https://github.com/chaoss/wg-diversity-inclusion). I think that would lead to a great discussion, and those metrics would make it back down to badging 👍 

Thank you for your support!

**Comment by bistaastha** [comment]
Hi @ElizabethN!

I agree with @Nebrethar on the part that some of these points could make it to their own metrics. Particularly, the first four bullets under point 3 made by you can possibly be covered by a single (new) Event metric.

Regarding the first and second points, yes, this feedback will definitely go directly into making a revised Event Checklist.

Thanks for the feedback :)

**Comment by Nebrethar** [comment]
Closing because this is old content, and now out-of-date
