### ISSUE TITLE
[Virtual Event] Kuberenetes on Edge Day

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#80]
# Virtual Event Submission

## Requirements

- Event Name: Kuberenetes on Edge Day
- Link to the Event Website: https://events.linuxfoundation.org/kubernetes-on-edge-day/
- Provide verification that you are an event organizer: My name is Wendi West (wwest@contractor.linuxfoundation.org) and I manage the Diversity + Inclusion event activities for KubeCon+CloudNativeCon and the scholarship program for CNCF sponsored events.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/kubernetes-on-edge-day/program/cfp/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/kubernetes-on-edge-day/register/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/kubernetes-on-edge-day/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Kubernetes on Edge Day offers two categories: Diversity and Need-based.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities) who may not otherwise have the opportunity to attend. The Need-based scholarship provides support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/kubernetes-on-edge-day/attend/scholarships/

**Comment by Nebrethar** [comment]
This review will begin on Tuesday, April 6. (at the latest)

**Comment by spotz** [comment]
@Wendi-West - You mention speaker demographics related to the CFP but they are not on the CFP page. Are they in the CFP system?

**Comment by Wendi-West** [comment]
Hello @spotz are you referring to displaying the speaker demographics? If so, the website doesn't currently display the specific demographics. Instead, CNCF publishes a transparency report following each KubeCon event that includes overall attendee and speaker demographic information. These conference transparency reports are published and can be viewed on the CNCF website: [https://www.cncf.io/reports/#conference-transparency-reports]The reports are also shared with the Marketing Committee to distribute and posted on Social Media. Prior to the full transparency report being completed, overall conference attendee and speaker demographic information is part of an infographic that is also shared with the Sponsors, Marketing Committee and on Social Media. Not each individual co-located event is always listed in the transparency report, but since speakers are also attendees and all of the demographic information is gathered during registration, it is reflected /  part of the overall report information. Based on the various feedback we have been receiving from other applications, we are working on adding demographics from past events on current event websites. This will hopefully be in place for our next events in October.

**Comment by spotz** [comment]
@Wendi-West - I was referring more to the comments that panels must not be all male, from the same company etc. that you mentioned as part of speaker demographics. I understand the report would be released after the event.

**Comment by Wendi-West** [comment]
Ahhh. Ok, sorry. For this event we don't have any panels scheduled. We have mostly single speakers and a few sessions with 2 speakers, most of which include a non male speaker of the two. As an overall guideline for LF Events, if a panel is comprised of 3-5 people, at least one must identify as non male and not all 3-5 people should be from the same company.

**Comment by xiaoya-Esther** [comment]
Thank you @Wendi-West for applying!

Does the event has a process of requesting feedback from attendees regarding Diversity & Inclusion?

Also, I didn't find the transparency report with regard to this event on the CNCF website or any other channels that display speaker and attendee demographics, so I left the checkboxes blank for now!

**Comment by Wendi-West** [comment]
Hi @xiaoya-Esther thank you for reviewing and for your questions. 

On the Diversity + Inclusion page https://events.linuxfoundation.org/kubernetes-on-edge-day/attend/diversity-inclusion/#contact-us of the event website we have a section to contact us "If you have ideas on how we can create a more inclusive event, please do not hesitate to let us know. Contact Angela Brown, General Manager of Events, at angela@linuxfoundation.org" Additionally, we have a D+I Slack Channel where attendees can provide feedback, and on the registration form if someone selected that they have a dis/ability we have a follow up question asking for details regarding the dis/ability that we should be mindful of as we try to accommodate everyone for this event. We run registration reports for the dis/ability question once a week to make note of any suggestions / comments / feedback.

This is the first event for Kubernetes on Edge Day, so that is why you aren't seeing it in past transparency reports. But wanted to give you the information of what those reports look like and how / where we display information. Additionally, based on the various feedback we have been receiving from other applications / reviews, we are working on adding demographics from past events on current event websites. This will hopefully be in place for our next events in October.

**Comment by spotz** [comment]
@nebrethar handing off

**Comment by Nebrethar** [comment]
@xiaoya-Esther

Let me know when your review is finished 😁 Thanks!

**Comment by xiaoya-Esther** [comment]
Thanks for the information @Wendi-West !

@Nebrethar I'm done with the review now:)

**Comment by Nebrethar** [comment]
Thanks @xiaoya-Esther and @spotz for your reviews 😁

Hi @Wendi-West! This review is complete. I am going to go ahead and generate a badge. Please let me know whether you accept the result 😄

**Comment by Wendi-West** [comment]
@Nebrethar thank you! yes, we accept the result!!!

**Comment by Nebrethar** [comment]
Thanks @Wendi-West and congratulations to Kubernetes on Edge Day!

I will go ahead and close this one, and I will add the event to the README. 🎉
