### ISSUE TITLE
[Virtual Event] PromCon Online 2021

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#81]
# Virtual Event Submission

## Requirements

- Event Name: PromCon Online 2021
- Link to the Event Website: https://promcon.io/2021-online/
- Provide verification that you are an event organizer: My name is Wendi West (wwest@contractor.linuxfoundation.org) and I manage the Diversity + Inclusion event activities for KubeCon+CloudNativeCon and the scholarship program for CNCF sponsored events.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://promcon.io/2021-online/submit/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.); and Details regarding a dis/ability that we should be mindful of as we try to accommodate everyone for this event.
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://promcon.io/2021-online/register/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://promcon.io/coc/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` PromCom Online 2021 offers two categories: Diversity and Need-based.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities) who may not otherwise have the opportunity to attend. The Need-based scholarship provides support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://promcon.io/2021-online/

**Comment by Nebrethar** [comment]
This review will also begin on Tuesday, April 6. (at the latest)

**Comment by tetris4** [comment]
Hi @Wendi-West and thanks once more for applying! 

I can't find the attendee and speaker demographics being displayed on the website. If there's a link please share it and I'd be happy to update my review.

**Comment by Wendi-West** [comment]
Hello @tetris4 the website doesn't currently display the specific demographics. Instead, CNCF publishes a transparency report following each KubeCon event that includes overall attendee and speaker demographic information. These conference transparency reports are published and can be viewed on the CNCF website: [https://www.cncf.io/reports/#conference-transparency-reports]The reports are also shared with the Marketing Committee to distribute and posted on Social Media. Prior to the full transparency report being completed, overall conference attendee and speaker demographic information is part of an infographic that is also shared with the Sponsors, Marketing Committee and on Social Media. Not each individual co-located event is always listed in the transparency report, but since speakers are also attendees and all of the demographic information is gathered during registration, it is reflected / part of the overall report information. Based on the various feedback we have been receiving from other applications, we are working on adding demographics from past events on current event websites. This will hopefully be in place for our next events in October.

**Comment by Nebrethar** [comment]
Hi @Ruth-ikegah pinging for your review. I appreciate you!

**Comment by tetris4** [comment]
Thanks @Wendi-West. @Nebrethar I will keep my evaluation as is then, as I consider this a separate event with a different budge application than the main KubeCon one. A

**Comment by Ruth-ikegah** [comment]
Hi, @Wendi-West Thanks for all your applications and your patience with responding to our questions! 

@Nebrethar I am done with my review!

**Comment by Nebrethar** [comment]
Thanks @Ruth-ikegah @tetris4 for your patience and consideration in this review.

@Wendi-West This looks like the last of your applications for now. We hope to see you again soon! I'd like to say thank you for all these applications and the work you've put into them, on behalf of the entire CHAOSS D&I Badging team.

I will go ahead and generate the badge. Let me know if you need anything else from me, and whether you accept the result.

**Comment by Wendi-West** [comment]
@Ruth-ikegah @tetris4 @Nebrethar Thank you so very much! This has all been a very helpful and enlightening process. Thank you for all the work that you've done to review, engage, question, and work with us on these applications. I know I sent you A LOT. :) I'll be back in October ! ;) Yes, we accept the result. Thank you!

**Comment by Nebrethar** [comment]
Thanks @Wendi-West! I'll add PromCon Online 2021 to the event list now.
