### ISSUE TITLE
[Virtual Event] ServiceMeshCon Europe

### ISSUE THREAD

**Issue by Wendi-West** [badging/event-diversity-and-inclusion#82]
# Virtual Event Submission

## Requirements

- Event Name: ServiceMeshCon Europe
- Link to the Event Website: https://events.linuxfoundation.org/servicemeshcon-europe/
- Provide verification that you are an event organizer: My name is Wendi West (wwest@contractor.linuxfoundation.org) and I manage the Diversity + Inclusion event activities for KubeCon+CloudNativeCon and the scholarship program for CNCF sponsored events.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender identity and Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.) All submissions with 3–5 speakers are required to have at least one speaker that does not identify as a man and the speakers must not all be from the same company.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/servicemeshcon-europe/program/cfp/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: Gender Identity; Age; Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQIA, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/servicemeshcon-europe/register/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform, as well as on our event website.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/servicemeshcon-europe/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` ServiceMeshCon Europe offers two categories: Diversity and Need-based.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The diversity scholarship program provides support to those from traditionally underrepresented and/or marginalized groups in the technology and/or open source communities (including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities) who may not otherwise have the opportunity to attend. The Need-based scholarship provides support for active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/servicemeshcon-europe/attend/scholarships/

**Comment by Nebrethar** [comment]
This review will begin on Thursday, April 8. (at the latest)

**Comment by spotz** [comment]
@Wendi-West - Does this one have panels or same as Edge?

**Comment by Wendi-West** [comment]
@spotz ServiceMeshCon has one panel discussion. There are 6 panelists, two of whom are women.

**Comment by spotz** [comment]
@nebrethar - based on answers here and asked previously this is good on my end

**Comment by Nebrethar** [comment]
Thanks @spotz, noted

**Comment by ElizabethN** [comment]
Also good on my end! @Nebrethar

**Comment by bistaastha** [comment]
Thanks @ElizabethN :) I'll go ahead and generate the badge.

**Comment by bistaastha** [comment]
@Wendi-West Let us know if you accept the result :)

/cc @Nebrethar

**Comment by Wendi-West** [comment]
@bistaastha and @Nebrethar Thank you once again! Yes, we accept!!! :)

**Comment by Nebrethar** [comment]
Thanks @Wendi-West and congratulations to you and your team on a stellar 100%!

I will go ahead and end this review, and update the README.

**Comment by Nebrethar** [comment]
Also thank you @bistaastha for stepping in here and generating the badge. I appreciate your help!
