### ISSUE TITLE
[Virtual Event] API Specifications Conference (ASC) 2021

### ISSUE THREAD

**Issue by celiastampslf** [badging/event-diversity-and-inclusion#83]
# Virtual Event Submission

## Requirements

- Event Name: API Specifications Conference (ASC) 2021
- Link to the Event Website: https://events.linuxfoundation.org/openapi-asc/
- Provide verification that you are an event organizer: https://www.linkedin.com/in/celia-stamps-765641a/

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.) -No all-man programs or panels
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/openapi-asc/attend/diversity-inclusion/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/openapi-asc/attend/diversity-inclusion/

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes, the Code of Conduct is posted on the virtual event platform.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/openapi-asc/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We have a scholarship program available, based on need and impact, providing support to traditionally underrepresented and/or marginalized persons in the technology and/or open source communities (including, but not limited to persons identifying as LGBT, women, persons of color, and/or persons with disabilities) who may not otherwise have the opportunity to attend OpenAPI Initiative events for financial reasons.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Completing the application form (linked on webpage below) with key questions as follows: 1.) Can you receive funding from your company or organization for this event? 2.) Which underrepresented and/or marginalized group do you belong to? 3.) Briefly describe the ways in which you are involved in the technology and/or open source communities.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/openapi-asc/attend/scholarships/

**Comment by Nebrethar** [comment]
Hi @celiastampslf and welcome back 😁! It may take until the end of the week to have reviewers assigned to this application, related to an influx of applications. Thanks and let me know if you have any questions.

**Comment by Nebrethar** [comment]
@celiastampslf Thank you for being patient. We have upgraded to v2.0 now, which brings [one change](https://github.com/badging/event-diversity-and-inclusion/pull/69) to the checklist.

**Comment by Dhruv-Sachdev1313** [comment]
@celiastampslf Thank you for the submission !!

I had a question - Is there some kind of process where you take feedback from Speakers and Attendees about D&I during or after the conference, to better understand inclusivity from their perspective ? 

Looking forward to your response.

**Comment by celiastampslf** [comment]
Hi!
This actually came up with regards to one of my other applications - good
question!  We collect feedback and ideas from the community via email,
linked on the Diversity & Inclusion page
<https://events.linuxfoundation.org/openapi-asc/attend/diversity-inclusion/#contact-us>
of
our event website.

Contact Us With Ideas

If you have ideas on how we can create a more inclusive event, please do
not hesitate to let us know. Contact Emily Ruf, Event Manager, at
***@***.***


Celia J. Stamps
Event + Meeting Planner
The Linux Foundation
+1 704.942.6478 (Time Zone: Eastern)

**Comment by germonprez** [comment]
Hi @celiastampslf! These applications are awesome! Thanks so much. 

I have one question/comment and a follow-up with the question from @Dhruv-Sachdev1313 

Question/Comment: 

For the registration, I'm guessing the registration form that I see for attendees is similar for speakers. I think that the registration link I followed on the web page is only for attendees. I could have missed the attendee/speaker distinction. In the registration, I really liked the additional information boxes that appear in association with the:  Do you identify as a person of color?  question. Could you provide a similar approach with:   What gender do you identify with? If they select Other Gender Identity, they are given additional information boxes. Such an option could be built from the excellent work found at: https://github.com/drnikki/open-demographics/blob/master/doc-source/questions/gender.rst

Follow-up Question: 

I see that the collect feedback information is provided. This is great. Thank you for that. It could be nice to encourage people to see that section of the page throughout the conference. Just helping people know that this resource is there during the conference. 

Thanks again!

**Comment by celiastampslf** [comment]
@germonprez Thanks for following up!  To answer your questions:

- Yes, the registration form for speakers is nearly identical to the form for attendees and is hidden via a separate link.  The only piece of information that's different on the speaker registration form is that we ask for their cell phone number in case we need to reach them the day of the event.
- I like the idea of including an open text answer box if Other Gender Identity is selected.  I will provide this feedback to our team and see if we can have that updated across the board.  Thanks for the recommendation!
- Regarding D&I feedback collection, we can definitely make sure attendees see this section of the page throughout the conference.  We are also planning to include a D&I feedback question on our post-event survey.

Thanks again!

**Comment by germonprez** [comment]
Thanks @celiastampslf this is super helpful! I've updated the score based on this feedback. If you are able to update the Other Gender Identity question, could you let us know? That would be great. 

Thanks again!!

**Comment by Dhruv-Sachdev1313** [comment]
@celiastampslf Thanks for the answers !!!  I have also updated the score and good luck for the event !!

**Comment by celiastampslf** [comment]
Thank you both!  I'll wait for the badge level to be generated and let you know if there are any questions.

**Comment by Nebrethar** [comment]
@celiastampslf I am going to go ahead and generate the badge 😁 Thanks!!

**Comment by Nebrethar** [comment]
By the way, congratulations on that shiny 100%!!!

**Comment by celiastampslf** [comment]
@Nebrethar Awesome, thank you!

**Comment by Nebrethar** [comment]
I can go ahead and close this application and provide your badge in the list. Just as a formality, though, I will need you to accept the badge first 😁

I'm excited for you and ASC! Thank you for applying.

**Comment by celiastampslf** [comment]
@Nebrethar Accepted!

**Comment by Nebrethar** [comment]
Thank you @Dhruv-Sachdev1313 @germonprez for your careful review and attention to detail.

Congratulations @celiastampslf and the API Specifications Conference 2021 on your CHAOSS D&I Gold Badge!

I will go ahead and add the event to the main README for this repository
