### ISSUE TITLE
[Virtual Event] LFN Developer & Testing Forums 2021

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#84]
# Virtual Event Submission

## Requirements

- Event Name: LFN Developer & Testing Forums 2021
- Link to the Event Website: https://wiki.lfnetworking.org/x/iIa-Ag
- Provide verification that you are an event organizer: rbraun@linuxfoundation.org 

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` The LF Networking Developer and Testing events are not structured or planned in the way of normal conferences, but are, rather, community events for the technical participants in LFN and related projects to get together for focused discussion on future trends, interoperability, and performance testing, and release planning. Due to the interactive and grassroots nature of the event, we do not differentiate between speakers and attendees in the registration process.  Speaker demographics should therefore be roughly considered consistent with attendee data.   Information on past submissions can be found here:  February 2021 Topic Proposals April 2020 Developer Topic Proposals June 2020 Topic Proposals October 2020 Topic Proposals Generally because the work is being proposed by community members who do that work, we accommodate all proposed topics.   Sessions are usually led by Technical Steering Committee members, project leads, and committee chairs.   Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.) -Geographic information -No all-man programs or panels
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://wiki.lfnetworking.org/x/GAAF 
Information on past submissions can be found here: 
February 2021 Topic Proposals: https://wiki.lfnetworking.org/x/loa-Ag
April 2020 Developer Topic Proposals: https://wiki.lfnetworking.org/x/UQMQAg
June 2020 Topic Proposals: https://wiki.lfnetworking.org/x/2QwQAg
October 2020 Topic Proposals: https://wiki.lfnetworking.org/x/9QhoAg

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A`  Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.) --Geographic information
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://wiki.lfnetworking.org/x/GAAF
 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - posted on the Community Wiki: https://wiki.lfnetworking.org/x/jYa-Ag
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/about/code-of-conduct/

## Diversity Access Tickets

- [] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` The LFN Developer & Testing Forums (both physical and virtual) are free events open to anyone wanting to attend - there are no barriers to entry, and all are encouraged to attend and participate. For this reason, we do not currently have any separate classes of tickets beyond the general attendee registration
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` The LFN Developer & Testing Forums (both physical and virtual) are free events open to anyone wanting to attend - there are no barriers to entry, and all are encouraged to attend and participate. For this reason, we do not currently have any separate classes of tickets beyond the general attendee registration
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` The LFN Developer & Testing Forums (both physical and virtual) are free events open to anyone wanting to attend - there are no barriers to entry, and all are encouraged to attend and participate. For this reason, we do not currently have any separate classes of tickets beyond the general attendee registration

**Comment by bistaastha** [comment]
Hello @RachelBraunLF and welcome back as an Applicant :)

Let me know if you have any questions throughout this review.

**Comment by djmitche** [comment]
I should be able to get to this this weekend -- apologies for the delay!

**Comment by djmitche** [comment]
* Diversity Access Tickets -- I understand and agree the rationale for not having these, but I'm not sure I am qualified to decide that "counts", or if that component of the badge just shouldn't be included.  I'd appreciate some guidance.
 * CoC / "Support At Event" -- since this is a virtual event, "at event" is a bit of a misnomer, but I think the spirit of this checkbox is that there's an immediate response, rather than an email and later follow-up.  I think this could be clarified by understanding how mdolan@linuxfoundation.org would respond to a complaint, of, say, offensive behavior in a zoom breakout room (how quickly, and what kind of response).  Or perhaps there's another more immediate reporting mechanism such as a Slack DM?

**Comment by mollydb** [comment]
I could not find information relating to attendee demographics (though I found other reports) and also could not access the CFP.

**Comment by RachelBraunLF** [comment]
@djmitche 
CoC / "Support At Event" -- since this is a virtual event, "at event" is a bit of a misnomer, but I think the spirit of this checkbox is that there's an immediate response, rather than an email and later follow-up. I think this could be clarified by understanding how mdolan@linuxfoundation.org would respond to a complaint, of, say, offensive behavior in a zoom breakout room (how quickly, and what kind of response). Or perhaps there's another more immediate reporting mechanism such as a Slack DM?

- If we as event organizers received a complaint of offensive behavior, or in general, any report of a Code of Conduct violation, we would address it immediately. Attendees can report CoC concerns or violations via email to events@lfnetworking.org - this email alias includes all involved with the event, including myself and my manager. We respond immediately. There is also a specific Slack channel all attendees are invited to join, and concerns can be addressed there, as well. 

@mollydb Attendee demographics are included here under "Diversity & Inclusion Iniative at LFN Events". Please let me know if I can provide any further direction on where to find this publicly. 

There is not a traditional CFP for this event. Topic proposals can be submitted here for the upcoming June event: https://wiki.lfnetworking.org/display/LN/2021+LFN+Developer+Event+Topics+June

Information on past submissions can be found here: 
February 2021 Topic Proposals: https://wiki.lfnetworking.org/x/loa-Ag
April 2020 Developer Topic Proposals: https://wiki.lfnetworking.org/x/UQMQAg
June 2020 Topic Proposals: https://wiki.lfnetworking.org/x/2QwQAg
October 2020 Topic Proposals: https://wiki.lfnetworking.org/x/9QhoAg

Generally, because the work is being proposed by community members who do that work, we accommodate all proposed topics. 
Sessions are usually led by Technical Steering Committee members, project leads, and committee chairs.

**Comment by djmitche** [comment]
> Attendees can report CoC concerns or violations via email to events@lfnetworking.org

Got it -- but that is different from the address in the CoC itself.  When something does happen, it's important that such information be consistent and easy to find.  Is that address, and the slack channel, on Confluence somewhere?

**Comment by RachelBraunLF** [comment]
@djmitche - thanks so much for this feedback. I've edited the current Confluence page to include the following information: 
**Expected Behavior**
All event participants, whether they are attending an in-person event or a virtual event, are expected to behave in accordance with professional standards, with both this Code of Conduct as well as their respective employer’s policies governing appropriate workplace behavior and applicable laws.

**What To Do If You Witness or Are Subject To Unacceptable Behavior**
If you are being harassed, notice that someone else is being harassed, or have any other concerns relating to harassment, please contact a member of the conference staff immediately at events@lfnetworking.org. You may also reach out to event staff via the LFN Slack Channel. You are also encouraged to contact Emily Ruf, Event Manager, at eruf@linuxfoundation.org.

You can see the full edits here: https://wiki.lfnetworking.org/x/GAAF 
We have updated the contact person to be either the overall Event Manager, OR the Events@lfnetworking.org email alias (which is sent to all event organizers and will receive an immediate response.) I have also included information on the LFN Slack, which anyone can join and is linked out from Confluence.

Please let me know if you have any other feedback to consider.

**Comment by djmitche** [comment]
That looks fantastic -- thanks!

Was the phrase "this Code of Conduct' was intended to be a link?

**Comment by djmitche** [comment]
@bistaastha -- I still need some guidance on this:

> Diversity Access Tickets -- I understand and agree the rationale for not having these, but I'm not sure I am qualified to decide that "counts", or if that component of the badge just shouldn't be included. I'd appreciate some guidance.

**Comment by bistaastha** [comment]
Hello everyone

@djmitche 
Since this event does not have any entry fee, I will be editing the checklists to remove the section about Diversity Access Tickets.

@RachelBraunLF Please unmark the checkbox in your application committing to Diversity Access tickets, since it is something that will not be considered for this review.

Thanks :)

**Comment by RachelBraunLF** [comment]
Thank you @djmitche - I added the link to the CoC in the Expected Behavior, as well as the already existing link the paragraph above. 
I have also unchecked the checkbox in the application related to Diversity Access tickets. 
Thank you!

**Comment by djmitche** [comment]
Awesome, thanks! I think all my checkboxes are checked, but please @ me if there's anything further.

**Comment by mollydb** [comment]
> @mollydb Attendee demographics are included here under "Diversity & Inclusion Iniative at LFN Events". Please let me know if I can provide any further direction on where to find this publicly.

Do you have a link for this? I still couldn't find it on the web site.

> There is not a traditional CFP for this event. Topic proposals can be submitted here for the upcoming June event: https://wiki.lfnetworking.org/display/LN/2021+LFN+Developer+Event+Topics+June

I looked through this, but didn't see any information asking for demographics of proposers/participants.

**Comment by mollydb** [comment]
Re conversation of support at event: I think it should be made explicit, even though it's a virtual event, that support is available and what that could look like. In my experience with virtual (and in-person) events, support includes "listening to someone explain the problem" or potentially "watching a session they're participating in to make sure a harasser does not participate."

**Comment by RachelBraunLF** [comment]
> Re conversation of support at event: I think it should be made explicit, even though it's a virtual event, that support is available and what that could look like. In my experience with virtual (and in-person) events, support includes "listening to someone explain the problem" or potentially "watching a session they're participating in to make sure a harasser does not participate."

@mollydb - Thank you for this feedback! We do already include the following information on the Wiki:

"What To Do If You Witness or Are Subject To Unacceptable Behavior
If you are being harassed, notice that someone else is being harassed, or have any other concerns relating to harassment, please contact a member of the conference staff immediately at events@lfnetworking.org. You may also reach out to event staff via the LFN Slack Channel. You are also encouraged to contact Emily Ruf, Event Manager, at eruf@linuxfoundation.org."

We have tweaked it slightly to include the following addition in bold:
"What To Do If You Witness or Are Subject To Unacceptable Behavior
If you are being harassed, notice that someone else is being harassed, or have any other concerns relating to harassment, please contact a member of the conference staff immediately at events@lfnetworking.org, **so it can be addressed**.  You may also reach out to event staff via the LFN Slack Channel. You are also encouraged to contact Emily Ruf, Event Manager, at eruf@linuxfoundation.org."

**Comment by mollydb** [comment]
@RachelBraunLF I think there are a few potential issues on the wiki about this:

* The top of the left hand bar has a quick link to the Code of Conduct, which is at https://lfprojects.org/policies/code-of-conduct/
* Embedded in the LF community events page is an events specific code of conduct: https://events.linuxfoundation.org/about/code-of-conduct/
* Emily Ruf is mentioned on page: https://wiki.lfnetworking.org/display/LN/LFN+Community+Events

As I understand it "support of victims" is not just about making sure an event has procedures to respond to an incident, but that the people who are receiving harassment/inappropriate behavior have support at the event. I think that is covered in: **https://events.linuxfoundation.org/about/code-of-conduct/**. I think all the information you need is there, but it's in different places, and it's hard to know which is the best person to reach out to, and which CoC to pay the most attention to (one is easy to find, but not the right one; one is hard to find, but is the right one).

**Comment by RachelBraunLF** [comment]
@mollydb - Thank you so much for this feedback. I see the issues you have pointed out and will be working with my team to remedy these. I will swing back once I have an update!

**Comment by RachelBraunLF** [comment]
@mollydb - circling back on the feedback you provided above. 
> 
> * The top of the left-hand bar has a quick link to the Code of Conduct, which is at https://lfprojects.org/policies/code-of-conduct/ 

- This has now been updated to reflect the correct Code of Conduct link, which is embedded LF community events page. 

> * Embedded in the LF community events page is an events specific code of conduct: https://events.linuxfoundation.org/about/code-of-conduct/

- This is the correct CoC link. 

> * Emily Ruf is mentioned on page: https://wiki.lfnetworking.org/display/LN/LFN+Community+Events
> 

- Emily Ruf is the event manager for this event, and should be considered one of the primary persons to contact in case of a CoC concern, however as outlined on the site, any member of the event staff can be contacted via the email address provided, or also on Slack. Angela Brown is also mentioned within the CoC, as she can also be contacted should a CoC issue arise. All inquiries will be addressed immediately by any of these channels. 


Please let me know if you have any questions on the above, and thank you!

**Comment by bistaastha** [comment]
Hi @mollydb !

Are you done with your review?

**Comment by RachelBraunLF** [comment]
Thank you all for the reivew. We accept the badge.

**Comment by bistaastha** [comment]
Hi @RachelBraunLF . I just generated that badge to check how far along the review was, percentage-wise. This review seems to be almost complete, but the badge generated was not supposed to be an indication for this review ending.

Sorry about the confusion.

**Comment by Dhruv-Sachdev1313** [comment]
@bistaastha  This comment got deleted while I was updating the checkboxes somehow, Can we do something about it?

**Comment by bistaastha** [comment]
@Dhruv-Sachdev1313 Your review looks to be complete. Do you have anything else to add?

**Comment by Dhruv-Sachdev1313** [comment]
@bistaastha I have checked it based on the above discussion, and yes I am done with this one.

**Comment by bistaastha** [comment]
Great! I'll go ahead and generate the final badge for this review. @RachelBraunLF Please confirm that you accept it :)

**Comment by RachelBraunLF** [comment]
Thank you, I accept the badge.

**Comment by bistaastha** [comment]
I'll be closing this application now. @djmitche , @mollydb and @Dhruv-Sachdev1313 Thanks for your feedback and reviews.
