### ISSUE TITLE
[Virtual Event] DPDK Summit North America

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#85]
# Virtual Event Submission

## Requirements

- Event Name: DPDK Summit North America
- Link to the Event Website: https://events.linuxfoundation.org/dpdk-summit-north-america/
- Provide verification that you are an event organizer: Event & Meeting Planner at The Linux Foundation - rbraun@linuxfoundation.org 

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.) -No all-man programs or panels
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - A: https://events.linuxfoundation.org/dpdk-summit-north-america/attend/diversity-inclusion/
  - `A` We collect feedback and ideas from the community via email, linked on the Diversity & Inclusion webpage, found here: https://events.linuxfoundation.org/dpdk-summit-north-america/attend/diversity-inclusion/  We encourage all participants (attendees or speakers) to email us with ideas on how we can create a more inclusive event. We will also include an open text question on the post-event survey for participants to provide their feedback on how we can improve and/or share any ideas they have with us related to D&I practices. 
  

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - A: https://events.linuxfoundation.org/dpdk-summit-north-america/attend/diversity-inclusion/
  - `A` We collect feedback and ideas from the community via email, linked on the Diversity & Inclusion webpage, found here: https://events.linuxfoundation.org/dpdk-summit-north-america/attend/diversity-inclusion/  We encourage all participants (attendees or speakers) to email us with ideas on how we can create a more inclusive event. We will also include an open text question on the post-event survey for participants to provide their feedback on how we can improve and/or share any ideas they have with us related to D&I practices. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform. All registrants are required to agree to follow the Code of Conduct before their registration is processed. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/dpdk-summit-north-america/attend/code-of-conduct/ 

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` NA - DPDK Summit NA is a free event. No barriers to entry. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`

**Comment by RachelBraunLF** [comment]
Hello! As an FYI - I just realized that the questions asked on the application here: https://chaoss.community/diversity-and-inclusion-badging/ do not map out correctly to the Markdown text (I think that's what it's called.)
For example - on the application, the question is "Provide an example of the Speaker Feedback page if available, however, it displays as "Provide the link for the page related to Speaker Demographics if available." The same goes for Attendee Demographics.

**Comment by germonprez** [comment]
Hi @RachelBraunLF. Thanks for catching this. We can get this updated today. Sorry for the mix up :) 

I think it should universally say: Provide the link for the page related to Speaker Demographics if available

@bistaastha and @ElizabethN what are your thoughts on this?

**Comment by ElizabethN** [comment]
@bistaastha @germonprez I think we are trying to ask all three things:

1. Detail the process for measuring Speaker Demographics.
2. Provide the link for the page related to Speaker Demographics if available.
3. Provide an example of the Speaker Feedback page if available.

It looks like on the application we only ask 1 and 3. Should we add that to the Speaker and Attendee demographics sections in the application? I *think* that's what we are trying to say here. Maybe?

**Comment by RachelBraunLF** [comment]
@ElizabethN - I added the answer to collecting feedback from speakers and attendees, since I knew the question was asked on the application, but was not included on the text that carries over to GitHub. That's why you don't see the question - I just added the answer, not the question. Sorry if that made this more confusing!

**Comment by bistaastha** [comment]
I'll go ahead and assign the reviewers for this Event.

**Comment by spotz** [comment]
Thanks Rachel this looks good and thanks for reporting the issues you found. 

@bistaastha This is good on my end

**Comment by Gemarodri** [comment]
Thank you @RachelBraunLF for the application, I have done the review and it looks great!

**Comment by bistaastha** [comment]
@RachelBraunLF Let us know if you accept the result :)

**Comment by bistaastha** [comment]
Congratulations on getting a badge for DPDK Summit North America!

I will go ahead and close this Application.

@Gemarodri and @spotz , thanks a lot for your reviews :)
