### ISSUE TITLE
[Virtual Event] Cloud Foundry Summit 2021

### ISSUE THREAD

**Issue by debgiles** [badging/event-diversity-and-inclusion#86]
# Virtual Event Submission

## Requirements

- Event Name: Cloud Foundry Summit 2021
- Link to the Event Website: https://www.cloudfoundry.org/events/summit/cfsummit2021/
- Provide verification that you are an event organizer: https://www.cloudfoundry.org/leadership/

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.) -No all-man programs or panels
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` Post Event Survey Question: Diversity and Inclusion are vital to the future of the Cloud Foundry community and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` Post Event Survey Question: Diversity and Inclusion are vital to the future of the Cloud Foundry community and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - the Code of Conduct is posted on the virtual event platform.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://www.cloudfoundry.org/events/summit/cfsummit2021/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 2, diversity and need-based scholarships
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Scholarships are awarded based on a combination of need and impact. Selection will be made by an assembled group of reviewers who will assess each applicant’s request. All application information will be kept confidential.  Applicants must be from a traditionally underrepresented and/or marginalized group in the technology and/or open source communities including, but not limited to: persons identifying as LGBTQ, women, persons of color, and/or persons with disabilities; and be unable to attend without some financial assistance.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://docs.google.com/forms/d/e/1FAIpQLSfJ27fBsm4HAxSz5ugozWfNhbgHRqPHjmPV0YbmgoTVr6BfpQ/viewform

**Comment by germonprez** [comment]
Hi @debgiles thanks for the application! This is wonderful :) 

I was going through the registration and was trying to see if you are asking registrants to accept the code of conduct upon registration. I could have completely missed it! :)

**Comment by debgiles** [comment]
Hi @germonprez - Thanks for reviewing our application!

Yes, we do require attendees to accept it during registration, under the Terms & Condition section.  I've attached a screenshot for reference.
<img width="896" alt="Screen Shot 2021-06-01 at 1 53 04 PM" src="https://user-images.githubusercontent.com/39927820/120375980-f8595900-c2e0-11eb-946d-21c3a0ccc4ea.png">

**Comment by germonprez** [comment]
Thanks! Would it be possible to change to check box to: 

I agree to the Cloud Foundry Summit 2021 Code of Conduct

?

**Comment by debgiles** [comment]
Hi @germonprez - Our registration team has made this update.
![Screen Shot 2021-06-03 at 11 47 13 AM](https://user-images.githubusercontent.com/39927820/120681925-83615d00-c461-11eb-93e3-1ba788c55ef4.png)

**Comment by germonprez** [comment]
This is great! Thanks @debgiles 

Thanks for all of your work and good luck with the event!!

**Comment by tetris4** [comment]
@bistaastha sorry for missing this one, I was afk on vacations. I'm back now, so if need be I can help. Thanks.

**Comment by djmitche** [comment]
I was also away for the long weekend -- sorry!  I'll get to work now.

**Comment by djmitche** [comment]
That was pretty easy -- this looks great!

**Comment by debgiles** [comment]
Let me know if you need anything else from us for this.  Thanks!

**Comment by Nebrethar** [comment]
Hi @debgiles! I appreciate your application and I'm really sorry it's been so long since this review began. I'm glad to help finish up the process. 

Thanks, @germonprez and @djmitche! It looks like our reviewers have finished, so I am going to generate a badge. I'll need confirmation from you whether you accept the badge, as a text reply.

I'm really glad you reached out!

**Comment by debgiles** [comment]
No problem @Nebrethar.  I appreciate you reviewing our event and all the efforts you're putting forward to help increase D&I at events!

I accept the badge.

**Comment by Nebrethar** [comment]
Thank you @debgiles !!! You should see the Cloud Foundry Summit in our readme shortly. Thank you and congratulations!
