### ISSUE TITLE
[Virtual Event] PX4 Developer Summit 2021

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#88]
# Virtual Event Submission

## Requirements

- Event Name: PX4 Developer Summit 2021
- Link to the Event Website: https://events.linuxfoundation.org/px4-developer-summit/
- Provide verification that you are an event organizer: Rachel Braun - Event & Meeting Planner, Linux Foundation

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.) -No all-man programs or panels
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` N/A - We collect feedback and ideas from the community via email, linked on the Diversity & Inclusion webpage, found here: https://events.linuxfoundation.org/dpdk-summit-north-america/attend/diversity-inclusion/  We encourage all participants (attendees or speakers) to email us with ideas on how we can create a more inclusive event. We will also include an open text question on the post-event survey for participants to provide their feedback on how we can improve and/or share any ideas they have with us related to D&I practices. 

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: -Gender identity -Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/px4-developer-summit/attend/diversity-inclusion/ - We encourage all participants (attendees or speakers) to email us with ideas on how we can create a more inclusive event. We will also include an open text question on the post-event survey for participants to provide their feedback on how we can improve and/or share any ideas they have with us related to D&I practices. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes - it is currently posted on the event website, and will be included on the virtual event platform on the homepage. 
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/px4-developer-summit/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` The number of diversity scholarships is not yet determined and will depend on overall applications received and pending sponsorship dollars for additional scholarships.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Scholarships are awarded based on a combination of need and impact. Selections will be made by an assembled group of reviewers who will assess each applicant’s request.   Scholarships are intended to support traditionally underrepresented and/or marginalized persons in technology and/or open source communities, including but not limited to persons identifying as LGBT, women, persons of color, and/or persons with disabilities.   Applicants must complete the application form (linked on the website) and answer key questions as follows:  Are you attending the event on behalf of a company? If so, can you receive funding from the company or organization to attend. Which underrepresented and/or marginalized group do you belong to?  Briefly describe the ways in which you are involved in the technology and/or open source community. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/px4-developer-summit/attend/scholarships/ and https://docs.google.com/forms/d/e/1FAIpQLSdtuWJYveFlO4Z4N8Fo5Wp0vrd68DjhCosAYzGeBmzy2bor7w/viewform

**Comment by Nebrethar** [comment]
Hi @RachelBraunLF and thank you for your application for a CHAOSS DEI Badge. I'm glad you're here!

**Comment by RachelBraunLF** [comment]
Thanks @Nebrethar! Looking forward to the review.

**Comment by Nebrethar** [comment]
Pinging @xiaoya-Esther for your review. Let me know if you need anything from me 🎉

**Comment by xiaoya-Esther** [comment]
Sorry @RachelBraunLF @Nebrethar, I overlooked the notification. 

The event is great, I completed my review 🎉 🎊

**Comment by Nebrethar** [comment]
@RachelBraunLF Thanks again for your submission. I will go ahead and generate the badge, and please let me know if you accept the result in a comment on this issue. 😁

**Comment by RachelBraunLF** [comment]
Thanks @Nebrethar - I accept the result!

**Comment by Nebrethar** [comment]
Thank you @RachelBraunLF , I will go ahead and add it to the list. You appear to have this process down! :)

We are going to make our release cycle public today. I'm glad to say we will have more metrics and questions soon!
