### ISSUE TITLE
[Virtual Event] Open Mainframe Summit 2021

### ISSUE THREAD

**Issue by Naomi-Wash** [badging/event-diversity-and-inclusion#89]
# Virtual Event Submission

## Requirements

- Event Name: Open Mainframe Summit 2021
- Link to the Event Website: https://events.linuxfoundation.org/open-mainframe-summit/
- Provide verification that you are an event organizer: I, Naomi Washington, work on the Linux Foundation events team.

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` On the Call for Proposals, we include multiple questions to ensure our speakers are diverse. The language is as follows: The Linux Foundation is committed to a diverse and inclusive community. The following question is asked in an effort to track our progress in increasing diversity at events and will remain confidential.  What gender does the primary speaker identify with?*  Is the primary speaker a person of color? Which racial/ethnic background(s) does the primary speaker identify with? (check all that apply) Aside from gender, if the co-speaker identifies with an underrepresented minority group in technology, please indicate that group below (ie race/ethnicity, dis/ability, LGBTQ etc). For panels, more than 2 speakers, we also don't allow panels with only men.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` You have to submit to the CFP to view those questions: https://linuxfoundation.smapply.io/prog/open_mainframe_summit_2021/

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` On the registration form, we have a list of language and questions that measure attendee demographics. Language and questions are as follows: Do you have a dis/ability that we should be mindful of as we try to accommodate everyone for this event? We want to encourage greater diversity within the open source community, and demographic information helps us achieve that goal. It is collected solely for the purpose of compiling, analyzing and disclosing aggregate statistics regarding diversity of attendance at our events, to help track progress towards meeting our commitment to diversity initiatives.  Consent to provide demographic information for the purpose listed above is optional and purely voluntary, and is provided by selecting an option from the drop-down for the corresponding category. Demographic information is considered confidential and private. It will not be shared with others as part of your registration details, nor will it be used to subject you to adverse treatment. It will be used only in aggregate form for reporting attendance totals. Do you identify as a person of color? What gender do you identify with? How old are you?
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` You have to register for the event to view those questions: https://www.cvent.com/d/hjqr53/4W?ct=50221cf5-5496-4c34-9ec0-3b52b1bf1204 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` It will be included on the event virtual platform and we include a link to it on all attendee communications.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/open-mainframe-summit/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 1
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Applicants must be from a traditionally underrepresented and/or marginalized group in the technology and/or open source communities who are unable to attend without some financial assistance. including, but not limited to: persons identifying as LGBTQIA, women, persons of color, and/or persons with dis/abilities. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A` https://events.linuxfoundation.org/open-mainframe-summit/attend/scholarships/

**Comment by Nebrethar** [comment]
Thank you @Naomi-Wash for your application 😁 Please let me know @Nebrethar if you have any questions from here on out. I will go ahead and assign two reviewers to this application.

**Comment by Nebrethar** [comment]
Whoops. I made a mistake in assigning reviewers. I am going to change Neofytos to Ruth

**Comment by Ruth-ikegah** [comment]
Hi @Naomi-Wash! Thanks for applying for a badge with us! Thanks for providing enough information in your application. I enjoyed reviewing it. I have a suggestion as regards Speaker and attendee demographics. If you can have a page that shows past stats for speakers and attendees, it will be awesome. Here's an example: https://events.linuxfoundation.org/hyperledger-global-forum/attend/diversity-inclusion/#event-demographics ( psst..We also badged Hyperledger too!)

Let me know your thoughts!

@Nebrethar done with my review!

**Comment by Anita-ihuman** [comment]
Hello @Naomi-Wash, Thank you for applying for a D&I badge with us.
Just as Ruth pointed, it would be great to have the speaker and attendee demographic reports on the website as well.
Good luck with your event.

@Nebrethar, I am done with my review.

**Comment by Nebrethar** [comment]
Thank you @Ruth-ikegah and @Anita-ihuman for your thoughtful reviews :)

Thank you again for applying @Naomi-Wash 🎉 I am going to generate a badge. I will need you to confirm whether you accept the badge on behalf of your event. Leaving a comment on this GitHub issue would suffice :)

**Comment by Naomi-Wash** [comment]
Hello Matt,

I accept this badge on behalf of the Open Mainframe Summit 2021 event.

Thank you all for your reviews.

Best,
-Naomi


*Naomi Washington*
LF Events
T: 1.913.426.3148 (Time Zone: Central)
E: ***@***.***
The Linux Foundation <https://www.linuxfoundation.org/>

**Comment by Nebrethar** [comment]
Thanks Naomi. Congratulations! You'll see the badge posted on the repository's readme soon. You are also welcome to post the gold badge on materials related to the event. 

You can find your badge images here, and the bot will post some markdown links.

SVG: https://svgur.com/s/TX5

PNG:
![image](https://user-images.githubusercontent.com/34951354/106024237-31609300-608d-11eb-9bae-7bd8af48a27c.png)
