### ISSUE TITLE
Open Source Leeds Meetup

### ISSUE THREAD

**Issue by clairecocks** [badging/event-diversity-and-inclusion#95]
I'm organising an event for our new 'Open Source Leeds' meetup next month and I'm wondering if we will qualify for a badge.

It will be a small event (30 people max) held after work hours. Therefore, a couple of criteria, such as diversity access tickets and family friendliness don't seem to apply.

Is it worth me applying for a badge even though I can't tick those boxes?

Any help and advice gratefully received.

Here's a link to the event: https://www.meetup.com/Open-Source-Leeds/events/279586280/

**Comment by germonprez** [comment]
Hi @clairecocks and thanks for reaching out! We'd certainly welcome you and the event to go through the process. It's meant to be developmental and help you through ways that could better center DEI within the event. 

To your point, if the event is free, providing diversity access tickets may not be applicable in this case. And that's okay! 

For family friendliness, there may be things that you could consider to improve family friendliness. For example, would it be okay if parents brought a kid? Could there be a pre-designated mother's room? 

Again, the hope is that the badging process can help in improving DEI related issues associated with the event. 

I hope this helps!

@Nebrethar do you have additional comments?

**Comment by Nebrethar** [comment]
Closing this issue because the following issue was closed. I really appreciate you for taking the time to apply. It worked out!
