### ISSUE TITLE
[In-Person Event] Open Source Leeds Meetup

### ISSUE THREAD

**Issue by clairecocks** [badging/event-diversity-and-inclusion#96]
# In-Person Event Submission

## Requirements

- Event Name: Open Source Leeds Meetup
- Link to the Event Website: https://www.meetup.com/Open-Source-Leeds/events/279586280/
- Provide verification that you are an event organizer: Yes

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` We are tracking this with a simple spreadsheet, measuring the number of female and BAME speakers over each year
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` This is asked for over email and logged in a spreadsheet

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Attendees are asked to 'check in' using iPads, completing a short survey upon arrival which includes questions about ethnic background and gender. This information is stored in a spreadsheet.
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` Attendees will be sent a survey post-event including the following questions: Did you feel welcome at the event?  (thumbs up/thumbs down) If you came to network with your peers, how easy did you find it to do this? Very easy; Easy; Average; Not easy; Really difficult. Did the icebreaker help? Yes, very much; Yes, somewhat; Meh…; It felt a bit awkward; I hated it! What suggestions do you have to improve D&I at our meetup? (open answer)

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://www.meetup.com/Open-Source-Leeds/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` Not applicable as this is a free event
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` No
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` The event is live-streamed to improve accessibility for all. We also have the following notice on the event website: "We don't want anyone to feel excluded from attending our events. If you have any special requirements, please let us know in advance by contacting Claire Cocks (ccocks@scottlogic.com)."
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://www.meetup.com/Open-Source-Leeds/events/279586280/

**Comment by spotz** [comment]
Claire - Do you have a link to the Code of Conduct? I can't find a link to it on the Meetup page. Also will you be collecting and publishing Diversity information for the virtual attendees as well?

**Comment by clairecocks** [comment]
The code of conduct can be found under the main meetup page under 'what we're about': https://www.meetup.com/Open-Source-Leeds/

We have a tight character limit on the event page so we don't have space. However, I could see if we could post a link to it?

To create as little friction as possible for those registering to attend the live stream, we will collect diversity information as part of the post-event survey. We can also use this event as a platform to announce what we're doing wrt D&I and why we're doing it so that they understand why we're asking for this information and are expecting it. That way, in the future we can start to ask for this at the point of registration.

We will publish diversity information on an annual basis.

**Comment by germonprez** [comment]
Thanks for the submission @clairecocks!

On these points, I have a few suggestions that I hope can help :) 
1) For the Code of Conduct, I'd recommend including a contact to which violations could be reported. 
2) For the Code of Conduct, I'd recommend including an incidence response process 

For both of these, the LF provides a nice template: https://events.linuxfoundation.org/about/code-of-conduct/

Also, the link that you provided (https://www.meetup.com/Open-Source-Leeds/) is not the event link so finding the Code of Conduct was not on the event web site. I like your suggestion to include a link on the event page that points to the Code of Conduct that you provided. 

Thanks for the clarity on the demographics and inclusion process. Just asking but I suspect that the post-event survey is sent to both attendees and speakers. Will you be able to differentiate responses based on either being an attendee or a speaker?

**Comment by clairecocks** [comment]
Hi, thanks for all of the suggestions.

I have now implemented these on the main meetup page: https://www.meetup.com/Open-Source-Leeds/ and have provided a link to the code of conduct from the event page.

**Comment by clairecocks** [comment]
Sorry... sent it too quickly :-) To answer your other question, we will be able to differentiate responses from the attendees and the speakers and will record these separately.

**Comment by germonprez** [comment]
Thanks! This is really looking great. Two additional things: 

1) When you are doing the post-conference DEI-related survey, a few questions that could be helpful are those that are coming from a soon-to-be release CHAOSS metric on Inclusive Experience at an Event: 

Ask attendees and speakers Survey with Likert Scale [1-5] (Or Emoji Scale): 
- I feel included at the event 
- I feel uniquely valued by the event staff 
- I had chances for my voice to be heard in sessions I plan to come back to this event

Interview or open questions for attendees and speakers: 
- Have you experienced anything during the event that made you feel unwelcome or unincluded? 
- Did you observe something that could make someone else feel unwelcome and unincluded? 
- Could you provide specific examples to help event organizers mitigate this in the future? 
- What is something that organizers of this event could improve on in the future regarding inclusivity at the event?

2) When people register for the event, are they required to accept the Code of Conduct? It could be a simple yes/no question. 

Thanks again!!

**Comment by clairecocks** [comment]
1. Thank you for that! I have started work on our post-event survey and for the first time we are adding questions related to DEI. I was really struggling to find the right ones so this is really helpful. I will definitely include some of these.

2. We can't customise the registration fields on Meetup. However, we would be happy to add a disclaimer to the event page saying "by registering to attend this event you are agreeing to abide by the code of conduct".

**Comment by germonprez** [comment]
This would be great for point #2. If you could include that text, that would cover this for me :) 

Could you let me know when you've done this and I'll check that part off. Thanks!

**Comment by clairecocks** [comment]
Done! https://www.meetup.com/Open-Source-Leeds/events/279586280/

**Comment by germonprez** [comment]
Thanks so much for the work @clairecocks! @Nebrethar I think I'm done with my review.

**Comment by clairecocks** [comment]
Thank you @germonprez and @spotz!

**Comment by spotz** [comment]
Thanks @clairecocks for submitting and all the changes! @Nebrethar I'm done as well

**Comment by clairecocks** [comment]
Hi all. Can you advise what the next step is please? I'm new to this so I'm not really sure what the badge looks like or when we get it. :-) 

I'm assuming it's a logo that we can display on our event page?

**Comment by Nebrethar** [comment]
Hi @clairecocks and thanks for asking! Our next step is to provide you with a badge.

Since we mentioned in the previous issue #95 that Diversity Access Tickets and Family Friendliness won't be counted for this event and since the metrics are not used here, I will not count them for the badge generation. With that in mind, here is your badge level:

![Assigned badge: gold](https://img.shields.io/badge/D%26I-Gold-yellow?style=flat-square&labelColor=583586&&link=https://github.com/badging/event-diversity-and-inclusion/issues/96/&logo=data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDI1MCAyNTAiPgo8cGF0aCBmaWxsPSIjMUM5QkQ2IiBkPSJNOTcuMSw0OS4zYzE4LTYuNywzNy44LTYuOCw1NS45LTAuMmwxNy41LTMwLjJjLTI5LTEyLjMtNjEuOC0xMi4yLTkwLjgsMC4zTDk3LjEsNDkuM3oiLz4KPHBhdGggZmlsbD0iIzZBQzdCOSIgZD0iTTE5NC42LDMyLjhMMTc3LjIsNjNjMTQuOCwxMi4zLDI0LjcsMjkuNSwyNy45LDQ4LjVoMzQuOUMyMzYuMiw4MC4yLDIxOS45LDUxLjcsMTk0LjYsMzIuOHoiLz4KPHBhdGggZmlsbD0iI0JGOUNDOSIgZD0iTTIwNC45LDEzOS40Yy03LjksNDMuOS00OS45LDczLTkzLjgsNjUuMWMtMTMuOC0yLjUtMjYuOC04LjYtMzcuNS0xNy42bC0yNi44LDIyLjQKCWM0Ni42LDQzLjQsMTE5LjUsNDAuOSwxNjIuOS01LjdjMTYuNS0xNy43LDI3LTQwLjIsMzAuMS02NC4ySDIwNC45eiIvPgo8cGF0aCBmaWxsPSIjRDYxRDVGIiBkPSJNNTUuNiwxNjUuNkMzNS45LDEzMS44LDQzLjMsODguOCw3My4xLDYzLjVMNTUuNywzMy4yQzcuNSw2OS44LTQuMiwxMzcuNCwyOC44LDE4OEw1NS42LDE2NS42eiIvPgo8L3N2Zz4K)
Review percentage: 100

Number of reviewers: 2

**I will need your confirmation on whether you accept the badge, and that is the last step.** Then I can add you to the readme and provide you with some hi-res versions of your badge.

**Comment by clairecocks** [comment]
We accept. And thanks again!

**Comment by Nebrethar** [comment]
Congratulations!! Usually, badges are good for a whole event cycle. In this case, re-apply in about a year. We will be two badging versions ahead by then! 😁 You can find your badge images here, with markdown links below:

SVG: https://svgur.com/s/TX5

PNG:
![image](https://user-images.githubusercontent.com/34951354/106024237-31609300-608d-11eb-9bae-7bd8af48a27c.png)

I will also add you to the readme now. Thanks again!!
