### ISSUE TITLE
[In-Person Event] Open Source Summit 2021

### ISSUE THREAD

**Issue by Nebrethar** [badging/event-diversity-and-inclusion#98]
# In-Person Event Submission

## Requirements

- Event Name: Open Source Summit 2021
- Link to the Event Website: https://events.linuxfoundation.org/open-source-summit-north-america/
- Provide verification that you are an event organizer: Yes, Event Manager 

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` On the Call for Proposals, we include multiple questions to ensure our speakers are diverse. The language is as follows: The Linux Foundation is committed to a diverse and inclusive community. The following questions are asked in an effort to track our progress in increasing diversity at events and will remain confidential. What gender does the primary speaker identify with?* Is the primary speaker a person of color? Which racial/ethnic background(s) does the primary speaker identify with? (check all that apply) Aside from gender, if the co-speaker identifies with an underrepresented minority group in technology, please indicate that group below (ie race/ethnicity, disability, LGBTQ etc). We also ask these same questions to co-speakers. For panels (more than 2 speakers), we do not allow panels with only men. On both the website and CFP form, we note that we do not accept all-male panels. Within the form, the submitter also has to verify that a diverse panel was submitted, and that it isn’t all men. We also encourage speakers to take the Inclusive Speaker Orientation Course, which was created In collaboration with the National Center for Women in Technology (NCWIT), to teach the speaker about inclusion, diversity, and unconscious bias.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` We send out a post-event survey to all speakers where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event.

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` We ask several questions in the registration process in order to compile attendee demographics, and to better cater to our attendees onsite to ensure they can enjoy the event to the fullest: Do you have a disability that we should be mindful of as we try to accommodate everyone for this event? Please specify dietary needs (if any). If you have a dietary need that isn’t listed, email us at events@linuxfoundation.org and we will make every reasonable effort to accommodate your need(s). Do you identify as a person of color? What gender do you identify with? How old are you? (Please note, none of these questions are required, they are optional for attendees to fill out) 
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` We send out a post-event survey to all attendees where we ask the following question: “Diversity and Inclusion are vital to the future of the linux ecosystem and it is imperative to us that everyone in the community that wants to participate feels welcome to do so. Please share any feedback or ideas regarding Diversity and Inclusion initiatives to help us improve future events.” We also encourage all attendees to share any ideas with us during the event, and have the contact information for the SVP & GM of Events as well as the specific Event Manager made easily accessible should anyone want to share their feedback prior, during, or after the event. 

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes, we have the code of conduct printed onsite and at all off-site venues. We have the code of conduct linked in all event emails, as well as on the onsite Diversity & Inclusion resources flyer. This flyer has all DEI related resources, as well as event team members they can contact should they need anything onsite.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/open-source-summit-north-america/attend/code-of-conduct/

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We offer 2 types of scholarships for this event, Diversity Registration Scholarships and Need-Based Registration Scholarships. There is no limit to the number of diversity or need-based registration scholarships that we offer for this event. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Diversity Registration Scholarships - Applicants must be from a traditionally underrepresented and/or marginalized group in the technology and/or open source communities who are unable to attend without some financial assistance. Including, but not limited to: persons identifying as LGBTQIA+, women, persons of color, and/or persons with disabilities. Need-based Registration Scholarships - Individuals who apply should be active members of the open source community who are unable to attend for financial reasons and are unable to get funding from their companies.
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  https://events.linuxfoundation.org/open-source-summit-north-america/attend/scholarships/#scholarships

## Family Friendliness

- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Historically, we offer childcare at every Linux Foundation event, and offer programming specific to underprivileged children with our Kid’s Day event. Unfortunately, this year due to COVID-19 restrictions and health and safety concerns, we are not offering childcare. We plan to resume offering this at events as soon as possible. We do have a list of local providers should anyone need help sourcing care. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` We offer our attendees a private nursing room that they can access throughout the event, gender neutral restrooms, pronoun stickers, and have ADA accessible transportation provided to any offsite venues.
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`  https://events.linuxfoundation.org/open-source-summit-north-america/attend/diversity-inclusion/

**Comment by Nebrethar** [comment]
Hi @spotz and @KafayahL!!

I submitted this event on behalf of @creyjons who was experiencing some technical trouble with their application. Let me know if anything seems "off" about it.

Otherwise, have fun! This one needs to be a rather quick review.

**Comment by spotz** [comment]
@Nebrethar Done, helps I'd been through the speaker and registration process, as well as been on the site quite a bit lately.:) One weirdness was that while I was doing the review things seemed to lock up and I wasn't able too check things until I refreshed the page might have been on my side.

**Comment by KafayahL** [comment]
Missing Findability for the Family Friendliness, otherwise I'm done.

**Comment by Nebrethar** [comment]
Thanks @spotz @KafayahL for your thoughtful reviews. Congratulations @creyjons on the Gold badge! I am going to go ahead and generate the badge, I'll need your call on whether you accept it.

**Comment by creyjons** [comment]
Thank you @Nebrethar for the help with the form and to @spotz and @KafayahL for the quick review.  Happy to accept the badge!

**Comment by Nebrethar** [comment]
Sounds great! I will add you to the list, and @creyjons after the issue is closed I will provide some badges for you to use on your event pages :)

**Comment by Nebrethar** [comment]
Congratulations!! You will be in the list of badged events in about 5 minutes. You can find your badge images here, with markdown links below:

SVG: https://svgur.com/s/TX5

PNG:
![image](https://user-images.githubusercontent.com/34951354/106024237-31609300-608d-11eb-9bae-7bd8af48a27c.png)
